"""Materi Minna no Nihongo 1 — Bab 2 s/d 9."""

from seed_data.dsl import BUNPO, CHAPTER, KAIWA, KANJI, KOTOBA, QB, QB_ID, QS

BAB2 = CHAPTER(
    2, "これは 辞書ですか。", "Apakah ini kamus?",
    bunpo=[
        BUNPO(
            "b2-1", "これ・それ・あれ — Kata Tunjuk Benda",
            "[Kata Tunjuk] は [Kata Benda] です",
            [
                "これ = ini (benda DEKAT pembicara)",
                "それ = itu (benda dekat LAWAN bicara)",
                "あれ = itu (benda JAUH dari keduanya)",
            ],
            "Bahasa Jepang membedakan jarak benda dalam tiga tingkat, bukan dua seperti Bahasa "
            "Indonesia. これ untuk benda di dekat pembicara, それ untuk benda di dekat lawan bicara, "
            "dan あれ untuk benda yang jauh dari keduanya. Ketiganya berdiri sendiri sebagai kata "
            "benda, jadi langsung diikuti partikel は.",
            [
                ("これ は 辞書|じしょ です。", "Ini kamus."),
                ("それ は 本|ほん です。", "Itu buku (dekat Anda)."),
                ("あれ は 車|くるま です。", "Itu mobil (di sana)."),
            ],
        ),
        BUNPO(
            "b2-2", "この・その・あの — Kata Tunjuk + Kata Benda",
            "[この/その/あの] [Kata Benda] は ~ です",
            [
                "この/その/あの TIDAK bisa berdiri sendiri",
                "wajib diikuti [Kata Benda]",
                "bandingkan: これは本です ↔ この本は…",
            ],
            "Berbeda dengan これ・それ・あれ yang berdiri sendiri, この・その・あの harus menempel "
            "pada kata benda. Jadi これは 本です (“ini buku”) tetapi この 本は わたしのです "
            "(“buku ini milik saya”). Kesalahan umum pemula adalah menulis これ 本, yang salah.",
            [
                ("この 本|ほん は わたし の です。", "Buku ini milik saya."),
                ("その かばん は ミラーさん の です。", "Tas itu milik Pak Miller."),
                ("あの 人|ひと は 先生|せんせい です。", "Orang itu guru."),
            ],
        ),
        BUNPO(
            "b2-3", "そうです / ちがいます — Jawaban Ya & Bukan",
            "はい、そうです。／ いいえ、ちがいます。",
            [
                "はい、そうです = ya, benar",
                "いいえ、ちがいます = bukan, salah",
                "dipakai menjawab pertanyaan berpola [KB]ですか",
            ],
            "Untuk menjawab pertanyaan konfirmasi, jawaban pendek yang paling alami adalah "
            "はい、そうです atau いいえ、ちがいます. ちがいます lebih halus dan umum dipakai daripada "
            "mengulang seluruh kalimat negatif. Bisa juga dijawab dengan mengulang kata bendanya: "
            "いいえ、辞書じゃありません。",
            [
                ("これ は テレホンカード です か。", "Apakah ini kartu telepon? — Ya, benar."),
                ("いいえ、 ちがいます。", "Bukan, salah."),
            ],
        ),
        BUNPO(
            "b2-4", "N1 の N2 & 〜の (Pengganti Kata Benda)",
            "[Kata Benda 1] の [Kata Benda 2] ／ [Kata Benda] の",
            [
                "の = [Partikel] penghubung milik/kategori",
                "の di akhir = pengganti kata benda yang sudah jelas",
                "何|なん の 〜 = 〜 tentang apa / jenis apa",
            ],
            "Selain menyatakan milik, の di akhir kalimat bisa menggantikan kata benda yang sudah "
            "disebut agar tidak berulang: この 本は わたしの です berarti “buku ini milik saya” "
            "(の menggantikan 本). Untuk menanyakan jenis/topik, gunakan 何の: これは 何の 本ですか "
            "(“ini buku tentang apa?”).",
            [
                ("これ は 車|くるま の 雑誌|ざっし です。", "Ini majalah mobil."),
                ("この かさ は わたし の です。", "Payung ini milik saya."),
                ("これ は 何|なん の 本|ほん です か。", "Ini buku tentang apa?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k2-1", "これ", "これ", "kore", "ini (benda dekat pembicara)", "Kata Tunjuk",
               ("これ は 辞書|じしょ です。", "Ini kamus.")),
        KOTOBA("k2-2", "それ", "それ", "sore", "itu (benda dekat lawan bicara)", "Kata Tunjuk",
               ("それ は 本|ほん です。", "Itu buku.")),
        KOTOBA("k2-3", "あれ", "あれ", "are", "itu (benda jauh dari keduanya)", "Kata Tunjuk",
               ("あれ は 会社|かいしゃ の 車|くるま です。", "Itu mobil perusahaan.")),
        KOTOBA("k2-4", "この", "この", "kono", "ini ~ (+ kata benda)", "Kata Tunjuk",
               ("この 本|ほん は わたし の です。", "Buku ini milik saya.")),
        KOTOBA("k2-5", "その", "その", "sono", "itu ~ (+ kata benda)", "Kata Tunjuk",
               ("その かばん は だれ の です か。", "Tas itu milik siapa?")),
        KOTOBA("k2-6", "あの", "あの", "ano", "itu ~ di sana (+ kata benda)", "Kata Tunjuk",
               ("あの 人|ひと は 山田|やまだ さん です。", "Orang itu Pak Yamada.")),
        KOTOBA("k2-7", "辞書", "じしょ", "jisho", "kamus", "Kata Benda",
               ("これ は 日本語|にほんご の 辞書|じしょ です。", "Ini kamus bahasa Jepang.")),
        KOTOBA("k2-8", "本", "ほん", "hon", "buku", "Kata Benda",
               ("その 本|ほん は わたし の です。", "Buku itu milik saya.")),
        KOTOBA("k2-9", "雑誌", "ざっし", "zasshi", "majalah", "Kata Benda",
               ("これ は 車|くるま の 雑誌|ざっし です。", "Ini majalah mobil.")),
        KOTOBA("k2-10", "新聞", "しんぶん", "shinbun", "surat kabar", "Kata Benda",
               ("あれ は 日本|にほん の 新聞|しんぶん です。", "Itu surat kabar Jepang.")),
        KOTOBA("k2-11", "ノート", "ノート", "nōto", "buku catatan", "Kata Benda",
               ("これ は わたし の ノート です。", "Ini buku catatan saya.")),
        KOTOBA("k2-12", "鉛筆", "えんぴつ", "enpitsu", "pensil", "Kata Benda",
               ("その 鉛筆|えんぴつ は だれ の です か。", "Pensil itu milik siapa?")),
        KOTOBA("k2-13", "かばん", "かばん", "kaban", "tas", "Kata Benda",
               ("この かばん は ミラーさん の です。", "Tas ini milik Pak Miller.")),
        KOTOBA("k2-14", "かぎ", "かぎ", "kagi", "kunci", "Kata Benda",
               ("これ は 車|くるま の かぎ です。", "Ini kunci mobil.")),
        KOTOBA("k2-15", "傘", "かさ", "kasa", "payung", "Kata Benda",
               ("あの 傘|かさ は わたし の じゃありません。", "Payung itu bukan milik saya.")),
        KOTOBA("k2-16", "そうです", "そうです", "sō desu", "benar; begitu", "Ungkapan",
               ("はい、 そうです。", "Ya, benar.")),
        KOTOBA("k2-17", "ちがいます", "ちがいます", "chigaimasu", "bukan; salah", "Ungkapan",
               ("いいえ、 ちがいます。", "Bukan, salah.")),
        KOTOBA("k2-18", "何", "なん", "nan", "apa", "Kata Tanya",
               ("これ は 何|なん です か。", "Ini apa?")),
    ],
    kanji=[
        KANJI("j2-1", "何", "カ", "なに・なん", "apa", 7,
              [("何", "なに", "apa"), ("何人", "なんにん", "berapa orang")]),
        KANJI("j2-2", "書", "ショ", "か(く)", "tulis; buku", 10,
              [("辞書", "じしょ", "kamus"), ("書店", "しょてん", "toko buku")]),
        KANJI("j2-3", "新", "シン", "あたら(しい)", "baru", 13,
              [("新聞", "しんぶん", "surat kabar"), ("新年", "しんねん", "tahun baru")]),
        KANJI("j2-4", "聞", "ブン・モン", "き(く)", "dengar; tanya", 14,
              [("新聞", "しんぶん", "surat kabar"), ("聞く", "きく", "mendengar")]),
        KANJI("j2-5", "語", "ゴ", "かた(る)", "bahasa; berkata", 14,
              [("日本語", "にほんご", "bahasa Jepang"), ("英語", "えいご", "bahasa Inggris")]),
    ],
    kaiwa=KAIWA(
        "これは 何ですか — Ini Apa?",
        "Pak Yamada menghampiri meja Pak Miller dan menanyakan beberapa barang di atasnya.",
        [
            ("山田", "Yamada", "ミラーさん、 これ は 何|なん です か。", "Pak Miller, ini apa?"),
            ("ミラー", "Mirā", "それ は 日本語|にほんご の 辞書|じしょ です。", "Itu kamus bahasa Jepang."),
            ("山田", "Yamada", "この 辞書|じしょ は ミラーさん の です か。", "Kamus ini milik Pak Miller?"),
            ("ミラー", "Mirā", "はい、 そうです。 わたし の です。", "Ya, benar. Milik saya."),
            ("山田", "Yamada", "あれ も ミラーさん の 本|ほん です か。", "Apakah itu juga buku Pak Miller?"),
            ("ミラー", "Mirā", "いいえ、 ちがいます。 あれ は 山田|やまだ さん の 雑誌|ざっし です。",
             "Bukan, salah. Itu majalah Pak Yamada."),
        ],
    ),
    quiz_bunpo=[
        QB("qb2-1", "＿＿ は 辞書|じしょ です。", ["これ", "この", "ここ", "だれ"], 0,
           "これ は 辞書|じしょ です。", "これ", "[Kata Tunjuk] は [Kata Benda] です",
           "これ berdiri sendiri sebagai kata benda sehingga bisa langsung diikuti は. この tidak bisa "
           "berdiri sendiri — harus diikuti kata benda seperti この 辞書."),
        QB("qb2-2", "＿＿ 本|ほん は わたし の です。", ["この", "これ", "それ", "何"], 0,
           "この 本|ほん は わたし の です。", "この", "[この/その/あの] [Kata Benda]",
           "Karena diikuti kata benda 本, yang dipakai adalah この. これ 本 adalah bentuk yang salah."),
        QB("qb2-3", "これ は 車|くるま ＿＿ 雑誌|ざっし です。", ["の", "は", "も", "か"], 0,
           "これ は 車|くるま の 雑誌|ざっし です。", "の", "[Kata Benda 1] の [Kata Benda 2]",
           "の menghubungkan dua kata benda: 車の 雑誌 = majalah (tentang) mobil."),
        QB_ID("qb2-4", "“Bukan, salah.”", ["はい、そうです。", "いいえ、ちがいます。", "はい、おねがいします。", "いいえ、けっこうです。"], 1,
              "いいえ、 ちがいます。", "ちがいます", "いいえ、ちがいます。",
              "ちがいます berarti “bukan/salah”, jawaban standar untuk menyangkal pertanyaan konfirmasi."),
        QB("qb2-5", "あの かさ は だれ ＿＿ です か。", ["の", "は", "が", "も"], 0,
           "あの かさ は だれ の です か。", "の", "だれ の [Kata Benda] / だれ の です",
           "だれの berarti “milik siapa”. の di akhir menggantikan kata benda yang sudah jelas (かさ)."),
    ],
    quiz_susun=[
        QS("qs2-1", "Ini kamus bahasa Jepang.", "これ は 日本語|にほんご の 辞書|じしょ です", "それ あれ"),
        QS("qs2-2", "Buku ini milik saya.", "この 本|ほん は わたし の です", "これ じゃありません"),
        QS("qs2-3", "Tas itu milik siapa?", "その かばん は だれ の です か", "わたし この"),
        QS("qs2-4", "Itu bukan surat kabar Jepang.", "あれ は 日本|にほん の 新聞|しんぶん じゃありません", "です も"),
    ],
)

BAB3 = CHAPTER(
    3, "ここは 食堂です。", "Di sini kantin.",
    bunpo=[
        BUNPO(
            "b3-1", "ここ・そこ・あそこ — Kata Tunjuk Tempat",
            "[ここ/そこ/あそこ] は [Kata Benda tempat] です",
            [
                "ここ = di sini (dekat pembicara)",
                "そこ = di situ (dekat lawan bicara)",
                "あそこ = di sana (jauh dari keduanya)",
                "どこ = [Kata Tanya] di mana",
            ],
            "Pola jarak tiga tingkat yang sama seperti これ・それ・あれ, tetapi untuk TEMPAT. "
            "Bentuk sopannya adalah こちら・そちら・あちら・どちら, yang juga bisa berarti arah. "
            "Untuk menanyakan lokasi, gunakan 〜は どこですか.",
            [
                ("ここ は 食堂|しょくどう です。", "Di sini kantin."),
                ("お手洗い|おてあらい は そこ です。", "Toiletnya di situ."),
                ("事務所|じむしょ は どこ です か。", "Di mana kantornya?"),
            ],
        ),
        BUNPO(
            "b3-2", "N は [Tempat] です — Menyatakan Lokasi",
            "[Kata Benda] は [Tempat] です",
            [
                "[Kata Benda] = benda/orang yang dicari",
                "[Tempat] = lokasinya",
                "pola tanya: 〜は どこ です か",
            ],
            "Untuk menyebutkan di mana sesuatu berada pada tahap dasar ini, cukup gunakan "
            "[Benda]は [Tempat]です. Pola dengan あります/います yang lebih rinci baru dipelajari "
            "di Bab 10. Untuk menanyakan asal atau negara, dipakai 〜は どこ の 〜ですか.",
            [
                ("エレベーター は あそこ です。", "Liftnya di sana."),
                ("山田|やまだ さん は 事務所|じむしょ です。", "Pak Yamada ada di kantor."),
                ("この 車|くるま は どこ の 車|くるま です か。", "Mobil ini buatan mana?"),
            ],
        ),
        BUNPO(
            "b3-3", "いくらですか — Menanyakan Harga",
            "[Kata Benda] は いくら です か",
            [
                "いくら = [Kata Tanya] berapa (harga)",
                "〜円|えん = satuan yen",
                "jawaban: 〜円です",
            ],
            "いくら khusus untuk menanyakan harga. Angka dalam yen memakai satuan 円: 100円 "
            "(ひゃくえん), 1000円 (せんえん), 10000円 (いちまんえん). Perhatikan bahwa Bahasa Jepang "
            "menghitung dalam satuan 万 (10.000), sehingga 30.000 dibaca 三万 (さんまん).",
            [
                ("これ は いくら です か。", "Ini berapa harganya?"),
                ("その 傘|かさ は 1500円|せんごひゃくえん です。", "Payung itu 1.500 yen."),
            ],
        ),
        BUNPO(
            "b3-4", "こちら・そちら・あちら — Bentuk Sopan & Arah",
            "[こちら/そちら/あちら/どちら] です",
            [
                "こちら = sini (sopan) / arah ini",
                "どちら = di mana (sopan) / yang mana",
                "dipakai saat berbicara dengan tamu atau atasan",
            ],
            "Bentuk こちら・そちら・あちら・どちら adalah versi lebih sopan dari ここ・そこ・あそこ・どこ "
            "dan sekaligus menunjukkan arah. Dalam situasi layanan pelanggan atau saat menghadapi "
            "atasan, bentuk inilah yang dipakai: エレベーターは こちらです (“liftnya di sebelah sini”).",
            [
                ("エレベーター は こちら です。", "Liftnya di sebelah sini."),
                ("お国|おくに は どちら です か。", "Anda berasal dari negara mana?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k3-1", "ここ", "ここ", "koko", "di sini", "Kata Tunjuk",
               ("ここ は 食堂|しょくどう です。", "Di sini kantin.")),
        KOTOBA("k3-2", "そこ", "そこ", "soko", "di situ", "Kata Tunjuk",
               ("お手洗い|おてあらい は そこ です。", "Toiletnya di situ.")),
        KOTOBA("k3-3", "あそこ", "あそこ", "asoko", "di sana", "Kata Tunjuk",
               ("エレベーター は あそこ です。", "Liftnya di sana.")),
        KOTOBA("k3-4", "どこ", "どこ", "doko", "di mana", "Kata Tanya",
               ("事務所|じむしょ は どこ です か。", "Di mana kantornya?")),
        KOTOBA("k3-5", "こちら", "こちら", "kochira", "sini (sopan); arah ini", "Kata Tunjuk",
               ("エレベーター は こちら です。", "Liftnya di sebelah sini.")),
        KOTOBA("k3-6", "どちら", "どちら", "dochira", "di mana (sopan); yang mana", "Kata Tanya",
               ("お国|おくに は どちら です か。", "Anda dari negara mana?")),
        KOTOBA("k3-7", "教室", "きょうしつ", "kyōshitsu", "ruang kelas", "Kata Benda",
               ("教室|きょうしつ は 2階|にかい です。", "Ruang kelas di lantai 2.")),
        KOTOBA("k3-8", "食堂", "しょくどう", "shokudō", "kantin; kedai makan", "Kata Benda",
               ("食堂|しょくどう は どこ です か。", "Di mana kantinnya?")),
        KOTOBA("k3-9", "事務所", "じむしょ", "jimusho", "kantor", "Kata Benda",
               ("山田|やまだ さん は 事務所|じむしょ です。", "Pak Yamada di kantor.")),
        KOTOBA("k3-10", "会議室", "かいぎしつ", "kaigishitsu", "ruang rapat", "Kata Benda",
               ("会議室|かいぎしつ は あそこ です。", "Ruang rapat di sana.")),
        KOTOBA("k3-11", "お手洗い", "おてあらい", "otearai", "toilet", "Kata Benda",
               ("お手洗い|おてあらい は そこ です。", "Toiletnya di situ.")),
        KOTOBA("k3-12", "階", "かい", "kai", "lantai (ke-)", "Satuan",
               ("事務所|じむしょ は 3階|さんがい です。", "Kantornya di lantai 3.")),
        KOTOBA("k3-13", "いくら", "いくら", "ikura", "berapa (harga)", "Kata Tanya",
               ("これ は いくら です か。", "Ini berapa harganya?")),
        KOTOBA("k3-14", "円", "えん", "en", "yen (mata uang Jepang)", "Satuan",
               ("その 本|ほん は 2000円|にせんえん です。", "Buku itu 2.000 yen.")),
        KOTOBA("k3-15", "国", "くに", "kuni", "negara", "Kata Benda",
               ("お国|おくに は どちら です か。", "Anda dari negara mana?")),
        KOTOBA("k3-16", "会社", "かいしゃ", "kaisha", "perusahaan", "Kata Benda",
               ("会社|かいしゃ は 東京|とうきょう です。", "Perusahaannya di Tokyo.")),
        KOTOBA("k3-17", "売り場", "うりば", "uriba", "counter penjualan", "Kata Benda",
               ("かばん の 売り場|うりば は 5階|ごかい です。", "Counter tas di lantai 5.")),
        KOTOBA("k3-18", "すみません", "すみません", "sumimasen", "permisi; maaf", "Ungkapan",
               ("すみません、 食堂|しょくどう は どこ です か。", "Permisi, di mana kantinnya?")),
    ],
    kanji=[
        KANJI("j3-1", "上", "ジョウ", "うえ・あ(がる)", "atas; naik", 3,
              [("上", "うえ", "atas"), ("上手", "じょうず", "pandai")]),
        KANJI("j3-2", "下", "カ・ゲ", "した・さ(がる)", "bawah; turun", 3,
              [("下", "した", "bawah"), ("地下", "ちか", "bawah tanah")]),
        KANJI("j3-3", "中", "チュウ", "なか", "tengah; dalam", 4,
              [("中", "なか", "dalam"), ("中国", "ちゅうごく", "Tiongkok")]),
        KANJI("j3-4", "国", "コク", "くに", "negara", 8,
              [("国", "くに", "negara"), ("外国", "がいこく", "luar negeri")]),
        KANJI("j3-5", "円", "エン", "まる(い)", "yen; bulat", 4,
              [("百円", "ひゃくえん", "seratus yen"), ("円い", "まるい", "bulat")]),
    ],
    kaiwa=KAIWA(
        "これを ください — Tolong Berikan Ini",
        "Nona Marie Schmidt bertanya kepada petugas toko serba ada tentang lokasi counter dan harga.",
        [
            ("シュミット", "Shumitto", "すみません。 ワイン の 売り場|うりば は どこ です か。",
             "Permisi. Di mana counter wine?"),
            ("店員", "Ten'in", "地下|ちか 1階|いっかい で ございます。", "Ada di lantai 1 bawah tanah."),
            ("シュミット", "Shumitto", "ありがとう。", "Terima kasih."),
            ("店員", "Ten'in", "いらっしゃいませ。", "Selamat datang."),
            ("シュミット", "Shumitto", "この ワイン は いくら です か。", "Wine ini berapa harganya?"),
            ("店員", "Ten'in", "2500円|にせんごひゃくえん です。", "2.500 yen."),
            ("シュミット", "Shumitto", "じゃ、 これ を ください。", "Baik, tolong berikan ini."),
        ],
    ),
    quiz_bunpo=[
        QB("qb3-1", "＿＿ は 食堂|しょくどう です。", ["ここ", "この", "これ", "どこ"], 0,
           "ここ は 食堂|しょくどう です。", "ここ", "[ここ/そこ/あそこ] は [Tempat] です",
           "ここ menunjuk TEMPAT di dekat pembicara. これ menunjuk benda, dan この harus diikuti kata benda."),
        QB("qb3-2", "事務所|じむしょ は ＿＿ です か。", ["どこ", "どれ", "いくら", "だれ"], 0,
           "事務所|じむしょ は どこ です か。", "どこ", "[Kata Benda] は どこ です か",
           "どこ = “di mana”, kata tanya untuk lokasi. いくら untuk harga, だれ untuk orang."),
        QB("qb3-3", "この 傘|かさ は ＿＿ です か。", ["いくら", "どこ", "だれ", "なん"], 0,
           "この 傘|かさ は いくら です か。", "いくら", "[Kata Benda] は いくら です か",
           "いくら khusus menanyakan harga. Jawabannya berupa angka + 円."),
        QB("qb3-4", "お国|おくに は ＿＿ です か。", ["どちら", "どこの", "いくら", "なに"], 0,
           "お国|おくに は どちら です か。", "どちら", "お国 は どちら です か",
           "どちら adalah bentuk sopan dari どこ, dipakai saat menanyakan asal seseorang dengan hormat."),
    ],
    quiz_susun=[
        QS("qs3-1", "Di mana kantinnya?", "食堂|しょくどう は どこ です か", "ここ いくら"),
        QS("qs3-2", "Ruang rapat di sana.", "会議室|かいぎしつ は あそこ です", "どこ か"),
        QS("qs3-3", "Wine ini berapa harganya?", "この ワイン は いくら です か", "これ どこ"),
        QS("qs3-4", "Counter tas di lantai 5.", "かばん の 売り場|うりば は 5階|ごかい です", "どこ は"),
    ],
)

BAB4 = CHAPTER(
    4, "今 何時ですか。", "Sekarang jam berapa?",
    bunpo=[
        BUNPO(
            "b4-1", "今 〜時〜分です — Menyatakan Waktu",
            "今|いま [angka]時|じ [angka]分|ふん です",
            [
                "〜時 = jam (pukul)",
                "〜分 = menit",
                "何時|なんじ = [Kata Tanya] jam berapa",
                "半|はん = setengah (tiga puluh menit)",
            ],
            "Waktu dinyatakan dengan 〜時 untuk jam dan 〜分 untuk menit. Beberapa bacaan tidak "
            "beraturan dan wajib dihafal: 4時 = よじ (bukan よんじ), 7時 = しちじ, 9時 = くじ. "
            "Untuk menit: 1分 = いっぷん, 3分 = さんぷん, 6分 = ろっぷん, 8分 = はっぷん, "
            "10分 = じゅっぷん. Setengah jam dinyatakan dengan 半.",
            [
                ("今|いま 9時|くじ 10分|じゅっぷん です。", "Sekarang jam 9 lewat 10 menit."),
                ("今|いま 何時|なんじ です か。", "Sekarang jam berapa?"),
                ("今|いま 4時|よじ 半|はん です。", "Sekarang jam setengah 5 (4.30)."),
            ],
        ),
        BUNPO(
            "b4-2", "Kata Kerja ます — Bentuk Sopan Sekarang & Akan Datang",
            "[Kata Kerja bentuk ます] / ません / ました / ませんでした",
            [
                "〜ます = bentuk sopan (sekarang/akan datang)",
                "〜ません = negatif sopan",
                "〜ました = bentuk lampau",
                "〜ませんでした = lampau negatif",
            ],
            "Kata kerja Bahasa Jepang tidak berubah menurut orang (saya/dia/mereka) — hanya menurut "
            "waktu dan positif/negatif. Bentuk ます sekaligus mencakup kebiasaan dan masa depan: "
            "毎日 働きます (“saya bekerja setiap hari”) maupun あした 働きます (“besok saya bekerja”). "
            "Konteks waktu yang menentukan maknanya.",
            [
                ("わたし は 毎日|まいにち 6時|ろくじ に 起|お きます。", "Saya bangun jam 6 setiap hari."),
                ("あした 働|はたら きません。", "Besok saya tidak bekerja."),
                ("きのう 勉強|べんきょう しました。", "Kemarin saya belajar."),
            ],
        ),
        BUNPO(
            "b4-3", "Partikel に — Titik Waktu",
            "[Waktu titik] に [Kata Kerja]",
            [
                "に dipakai untuk waktu yang BISA ditunjuk angka: 7時に, 月曜日に",
                "TIDAK dipakai pada: きょう, あした, きのう, 毎日|まいにち",
                "bulan & tanggal memakai に, tetapi 今週|こんしゅう tidak",
            ],
            "Partikel に menandai titik waktu terjadinya perbuatan, dan hanya dipakai pada kata waktu "
            "yang spesifik seperti jam, hari, tanggal, atau bulan. Kata waktu relatif seperti きょう, "
            "あした, きのう, 毎日, dan 今 TIDAK memakai に — ini kesalahan paling umum pemula.",
            [
                ("わたし は 7時|しちじ に 起|お きます。", "Saya bangun jam 7."),
                ("月曜日|げつようび に 働|はたら きます。", "Saya bekerja pada hari Senin."),
                ("あした 休|やす みます。", "Besok saya istirahat."),
            ],
        ),
        BUNPO(
            "b4-4", "〜から 〜まで — Dari … Sampai …",
            "[Titik awal] から [Titik akhir] まで",
            [
                "から = [Partikel] dari (waktu/tempat)",
                "まで = [Partikel] sampai (waktu/tempat)",
                "bisa dipakai salah satu saja",
            ],
            "から menandai titik awal dan まで titik akhir, baik untuk waktu maupun tempat. Keduanya "
            "boleh dipakai bersama atau terpisah. Jika mengikuti kata benda dan diikuti です, pola "
            "ini menjadi kalimat nominal: 銀行は 9時から 3時までです.",
            [
                ("銀行|ぎんこう は 9時|くじ から 3時|さんじ まで です。", "Bank buka dari jam 9 sampai jam 3."),
                ("わたし は 9時|くじ から 5時|ごじ まで 働|はたら きます。", "Saya bekerja dari jam 9 sampai jam 5."),
                ("大阪|おおさか から 東京|とうきょう まで 行|い きます。", "Saya pergi dari Osaka sampai Tokyo."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k4-1", "今", "いま", "ima", "sekarang", "Kata Benda Waktu",
               ("今|いま 何時|なんじ です か。", "Sekarang jam berapa?")),
        KOTOBA("k4-2", "何時", "なんじ", "nanji", "jam berapa", "Kata Tanya",
               ("会議|かいぎ は 何時|なんじ から です か。", "Rapat mulai jam berapa?")),
        KOTOBA("k4-3", "半", "はん", "han", "setengah (30 menit)", "Satuan",
               ("今|いま 8時|はちじ 半|はん です。", "Sekarang jam setengah 9.")),
        KOTOBA("k4-4", "午前", "ごぜん", "gozen", "pagi; a.m.", "Kata Benda Waktu",
               ("午前|ごぜん 9時|くじ に 始|はじ まります。", "Mulai jam 9 pagi.")),
        KOTOBA("k4-5", "午後", "ごご", "gogo", "siang-sore; p.m.", "Kata Benda Waktu",
               ("午後|ごご 3時|さんじ まで 働|はたら きます。", "Saya bekerja sampai jam 3 siang.")),
        KOTOBA("k4-6", "起きます", "おきます", "okimasu", "bangun (dari tidur)", "Kata Kerja",
               ("毎日|まいにち 6時|ろくじ に 起|お きます。", "Saya bangun jam 6 setiap hari.")),
        KOTOBA("k4-7", "寝ます", "ねます", "nemasu", "tidur", "Kata Kerja",
               ("11時|じゅういちじ に 寝|ね ます。", "Saya tidur jam 11.")),
        KOTOBA("k4-8", "働きます", "はたらきます", "hatarakimasu", "bekerja", "Kata Kerja",
               ("9時|くじ から 5時|ごじ まで 働|はたら きます。", "Saya bekerja jam 9 sampai 5.")),
        KOTOBA("k4-9", "休みます", "やすみます", "yasumimasu", "istirahat; libur", "Kata Kerja",
               ("日曜日|にちようび は 休|やす みます。", "Hari Minggu saya libur.")),
        KOTOBA("k4-10", "勉強します", "べんきょうします", "benkyō shimasu", "belajar", "Kata Kerja",
               ("毎日|まいにち 日本語|にほんご を 勉強|べんきょう します。", "Saya belajar bahasa Jepang setiap hari.")),
        KOTOBA("k4-11", "終わります", "おわります", "owarimasu", "berakhir; selesai", "Kata Kerja",
               ("授業|じゅぎょう は 3時|さんじ に 終|お わります。", "Pelajaran selesai jam 3.")),
        KOTOBA("k4-12", "銀行", "ぎんこう", "ginkō", "bank", "Kata Benda",
               ("銀行|ぎんこう は 9時|くじ から です。", "Bank buka dari jam 9.")),
        KOTOBA("k4-13", "郵便局", "ゆうびんきょく", "yūbinkyoku", "kantor pos", "Kata Benda",
               ("郵便局|ゆうびんきょく は 5時|ごじ まで です。", "Kantor pos sampai jam 5.")),
        KOTOBA("k4-14", "毎日", "まいにち", "mainichi", "setiap hari", "Kata Benda Waktu",
               ("毎日|まいにち 勉強|べんきょう します。", "Saya belajar setiap hari.")),
        KOTOBA("k4-15", "月曜日", "げつようび", "getsuyōbi", "hari Senin", "Kata Benda Waktu",
               ("月曜日|げつようび に 働|はたら きます。", "Saya bekerja hari Senin.")),
        KOTOBA("k4-16", "日曜日", "にちようび", "nichiyōbi", "hari Minggu", "Kata Benda Waktu",
               ("日曜日|にちようび は 休|やす みます。", "Hari Minggu saya libur.")),
        KOTOBA("k4-17", "から", "から", "kara", "dari", "Partikel",
               ("9時|くじ から 働|はたら きます。", "Saya bekerja dari jam 9.")),
        KOTOBA("k4-18", "まで", "まで", "made", "sampai", "Partikel",
               ("5時|ごじ まで 働|はたら きます。", "Saya bekerja sampai jam 5.")),
    ],
    kanji=[
        KANJI("j4-1", "時", "ジ", "とき", "waktu; jam", 10,
              [("何時", "なんじ", "jam berapa"), ("時間", "じかん", "waktu; jam")]),
        KANJI("j4-2", "分", "フン・ブン", "わ(かる)", "menit; membagi", 4,
              [("十分", "じゅっぷん", "sepuluh menit"), ("分かります", "わかります", "mengerti")]),
        KANJI("j4-3", "午", "ゴ", "—", "tengah hari", 4,
              [("午前", "ごぜん", "pagi"), ("午後", "ごご", "siang-sore")]),
        KANJI("j4-4", "毎", "マイ", "—", "setiap", 6,
              [("毎日", "まいにち", "setiap hari"), ("毎朝", "まいあさ", "setiap pagi")]),
        KANJI("j4-5", "休", "キュウ", "やす(む)", "istirahat", 6,
              [("休みます", "やすみます", "istirahat"), ("休日", "きゅうじつ", "hari libur")]),
        KANJI("j4-6", "働", "ドウ", "はたら(く)", "bekerja", 13,
              [("働きます", "はたらきます", "bekerja"), ("労働", "ろうどう", "kerja; buruh")]),
    ],
    kaiwa=KAIWA(
        "そちらは 何時までですか — Sampai Jam Berapa?",
        "Pak Miller menelepon museum untuk menanyakan jam buka dan hari libur.",
        [
            ("ミラー", "Mirā", "すみません。 そちら は 何時|なんじ から 何時|なんじ まで です か。",
             "Permisi. Di sana buka dari jam berapa sampai jam berapa?"),
            ("係|かかり", "Kakari", "9時|くじ から 4時|よじ まで です。", "Dari jam 9 sampai jam 4."),
            ("ミラー", "Mirā", "休み|やすみ は 何曜日|なんようび です か。", "Hari liburnya hari apa?"),
            ("係|かかり", "Kakari", "月曜日|げつようび です。", "Hari Senin."),
            ("ミラー", "Mirā", "分|わ かりました。 ありがとう ございました。", "Saya mengerti. Terima kasih banyak."),
        ],
    ),
    quiz_bunpo=[
        QB("qb4-1", "わたし は 7時|しちじ ＿＿ 起|お きます。", ["に", "で", "を", "から"], 0,
           "わたし は 7時|しちじ に 起|お きます。", "に", "[Waktu titik] に [Kata Kerja]",
           "Partikel に menandai titik waktu spesifik seperti jam. Perhatikan: あした dan 毎日 TIDAK memakai に."),
        QB("qb4-2", "銀行|ぎんこう は 9時|くじ から 3時|さんじ ＿＿ です。", ["まで", "に", "も", "の"], 0,
           "銀行|ぎんこう は 9時|くじ から 3時|さんじ まで です。", "まで", "[Awal] から [Akhir] まで",
           "から menandai titik awal, まで titik akhir. Pasangan から〜まで sering dipakai bersama."),
        QB_ID("qb4-3", "“Besok saya tidak bekerja.”",
              ["あした 働きます。", "あした 働きません。", "あした 働きました。", "あしたに 働きません。"], 1,
              "あした 働|はたら きません。", "働きません", "[Kata Kerja] ません",
              "〜ません adalah bentuk negatif sopan. Selain itu あした tidak memakai partikel に."),
        QB("qb4-4", "きのう 日本語|にほんご を 勉強|べんきょう ＿＿。",
           ["しました", "します", "しません", "しましょう"], 0,
           "きのう 日本語|にほんご を 勉強|べんきょう しました。", "しました", "[Kata Kerja] ました",
           "きのう (kemarin) menuntut bentuk lampau, yaitu 〜ました."),
        QB("qb4-5", "今|いま ＿＿ です か。", ["何時", "いくら", "どこ", "だれ"], 0,
           "今|いま 何時|なんじ です か。", "何時", "今 何時 です か",
           "何時 (なんじ) menanyakan jam. Perhatikan bacaan tidak beraturan: 4時=よじ, 7時=しちじ, 9時=くじ."),
    ],
    quiz_susun=[
        QS("qs4-1", "Saya bangun jam 6 setiap hari.", "毎日|まいにち 6時|ろくじ に 起|お きます", "まで を"),
        QS("qs4-2", "Bank buka dari jam 9 sampai jam 3.", "銀行|ぎんこう は 9時|くじ から 3時|さんじ まで です", "に も"),
        QS("qs4-3", "Hari Minggu saya libur.", "日曜日|にちようび は 休|やす みます", "に から"),
        QS("qs4-4", "Kemarin saya tidak bekerja.", "きのう 働|はたら きませんでした", "に ます"),
    ],
)

BAB5 = CHAPTER(
    5, "わたしは 京都へ 行きます。", "Saya pergi ke Kyoto.",
    bunpo=[
        BUNPO(
            "b5-1", "N へ 行きます/来ます/帰ります — Arah Perpindahan",
            "[Tempat] へ 行|い きます / 来|き ます / 帰|かえ ります",
            [
                "へ = [Partikel] arah tujuan, dibaca “e” (bukan “he”)",
                "行きます = pergi, 来ます = datang, 帰ります = pulang",
                "どこへ = ke mana; どこへも 行きません = tidak pergi ke mana pun",
            ],
            "Partikel へ menandai arah tujuan perpindahan dan hanya dipakai dengan kata kerja gerak "
            "seperti 行きます, 来ます, dan 帰ります. Perhatikan bahwa へ di sini dibaca “e”. Untuk "
            "menyatakan tidak pergi ke mana pun, dipakai どこへも + kata kerja negatif.",
            [
                ("わたし は 京都|きょうと へ 行|い きます。", "Saya pergi ke Kyoto."),
                ("来年|らいねん 国|くに へ 帰|かえ ります。", "Tahun depan saya pulang ke negara saya."),
                ("どこ へ も 行|い きません。", "Saya tidak pergi ke mana pun."),
            ],
        ),
        BUNPO(
            "b5-2", "N で 行きます — Alat Transportasi",
            "[Alat transportasi] で 行|い きます",
            [
                "で = [Partikel] dengan/memakai (alat)",
                "何|なに で = dengan apa (naik apa)",
                "歩いて|あるいて = jalan kaki — TIDAK memakai で",
            ],
            "Partikel で menandai sarana atau alat yang dipakai. Untuk transportasi: 電車で "
            "(dengan kereta), バスで (dengan bus), 飛行機で (dengan pesawat). Pengecualian penting: "
            "“jalan kaki” dinyatakan dengan 歩いて dan TIDAK boleh memakai で.",
            [
                ("電車|でんしゃ で 行|い きます。", "Saya pergi dengan kereta."),
                ("何|なに で 会社|かいしゃ へ 行|い きます か。", "Anda pergi ke kantor dengan apa?"),
                ("歩|ある いて 帰|かえ ります。", "Saya pulang jalan kaki."),
            ],
        ),
        BUNPO(
            "b5-3", "N と 行きます — Bersama Siapa",
            "[Orang] と [Kata Kerja]",
            [
                "と = [Partikel] bersama (dengan orang)",
                "だれ と = dengan siapa",
                "一人|ひとり で = sendirian — memakai で, bukan と",
            ],
            "と menandai orang yang menyertai perbuatan. Untuk menyatakan melakukan sesuatu "
            "sendirian, digunakan 一人で (bukan 一人と). Kata tanya yang sesuai adalah だれと "
            "(“dengan siapa”).",
            [
                ("家族|かぞく と 日本|にほん へ 来|き ました。", "Saya datang ke Jepang bersama keluarga."),
                ("だれ と 行|い きます か。", "Anda pergi dengan siapa?"),
                ("一人|ひとり で 行|い きます。", "Saya pergi sendirian."),
            ],
        ),
        BUNPO(
            "b5-4", "いつ — Menanyakan Waktu Tak Tentu",
            "いつ [Kata Kerja] か",
            [
                "いつ = [Kata Tanya] kapan",
                "いつ TIDAK diikuti partikel に",
                "jawaban bisa berupa tanggal, hari, atau kata waktu",
            ],
            "いつ menanyakan waktu secara umum dan tidak pernah diikuti partikel に. Untuk menjawab, "
            "gunakan kata waktu yang spesifik — dan ingat aturan Bab 4: jam/hari/tanggal memakai に, "
            "sedangkan きょう・あした・来週 tidak.",
            [
                ("いつ 日本|にほん へ 来|き ました か。", "Kapan Anda datang ke Jepang?"),
                ("3月|さんがつ 25日|にじゅうごにち に 来|き ました。", "Saya datang pada 25 Maret."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k5-1", "行きます", "いきます", "ikimasu", "pergi", "Kata Kerja",
               ("京都|きょうと へ 行|い きます。", "Saya pergi ke Kyoto.")),
        KOTOBA("k5-2", "来ます", "きます", "kimasu", "datang", "Kata Kerja",
               ("日本|にほん へ 来|き ました。", "Saya datang ke Jepang.")),
        KOTOBA("k5-3", "帰ります", "かえります", "kaerimasu", "pulang", "Kata Kerja",
               ("うち へ 帰|かえ ります。", "Saya pulang ke rumah.")),
        KOTOBA("k5-4", "電車", "でんしゃ", "densha", "kereta listrik", "Kata Benda",
               ("電車|でんしゃ で 行|い きます。", "Saya pergi dengan kereta.")),
        KOTOBA("k5-5", "バス", "バス", "basu", "bus", "Kata Benda",
               ("バス で 会社|かいしゃ へ 行|い きます。", "Saya pergi ke kantor dengan bus.")),
        KOTOBA("k5-6", "飛行機", "ひこうき", "hikōki", "pesawat terbang", "Kata Benda",
               ("飛行機|ひこうき で 国|くに へ 帰|かえ ります。", "Saya pulang ke negara saya dengan pesawat.")),
        KOTOBA("k5-7", "自転車", "じてんしゃ", "jitensha", "sepeda", "Kata Benda",
               ("自転車|じてんしゃ で 行|い きます。", "Saya pergi dengan sepeda.")),
        KOTOBA("k5-8", "歩いて", "あるいて", "aruite", "jalan kaki", "Ungkapan",
               ("歩|ある いて 帰|かえ ります。", "Saya pulang jalan kaki.")),
        KOTOBA("k5-9", "人", "ひと", "hito", "orang", "Kata Benda",
               ("あの 人|ひと は 友達|ともだち です。", "Orang itu teman saya.")),
        KOTOBA("k5-10", "友達", "ともだち", "tomodachi", "teman", "Kata Benda",
               ("友達|ともだち と 行|い きます。", "Saya pergi dengan teman.")),
        KOTOBA("k5-11", "家族", "かぞく", "kazoku", "keluarga", "Kata Benda",
               ("家族|かぞく と 来|き ました。", "Saya datang bersama keluarga.")),
        KOTOBA("k5-12", "一人で", "ひとりで", "hitori de", "sendirian", "Ungkapan",
               ("一人|ひとり で 行|い きます。", "Saya pergi sendirian.")),
        KOTOBA("k5-13", "いつ", "いつ", "itsu", "kapan", "Kata Tanya",
               ("いつ 日本|にほん へ 来|き ました か。", "Kapan Anda datang ke Jepang?")),
        KOTOBA("k5-14", "来週", "らいしゅう", "raishū", "minggu depan", "Kata Benda Waktu",
               ("来週|らいしゅう 大阪|おおさか へ 行|い きます。", "Minggu depan saya pergi ke Osaka.")),
        KOTOBA("k5-15", "来年", "らいねん", "rainen", "tahun depan", "Kata Benda Waktu",
               ("来年|らいねん 国|くに へ 帰|かえ ります。", "Tahun depan saya pulang ke negara saya.")),
        KOTOBA("k5-16", "誕生日", "たんじょうび", "tanjōbi", "hari ulang tahun", "Kata Benda",
               ("誕生日|たんじょうび は 5月|ごがつ 3日|みっか です。", "Ulang tahun saya 3 Mei.")),
        KOTOBA("k5-17", "駅", "えき", "eki", "stasiun", "Kata Benda",
               ("駅|えき へ 歩|ある いて 行|い きます。", "Saya pergi ke stasiun jalan kaki.")),
        KOTOBA("k5-18", "うち", "うち", "uchi", "rumah (saya)", "Kata Benda",
               ("うち へ 帰|かえ ります。", "Saya pulang ke rumah.")),
    ],
    kanji=[
        KANJI("j5-1", "行", "コウ", "い(く)・おこな(う)", "pergi; melaksanakan", 6,
              [("行きます", "いきます", "pergi"), ("旅行", "りょこう", "perjalanan")]),
        KANJI("j5-2", "来", "ライ", "く(る)", "datang", 7,
              [("来ます", "きます", "datang"), ("来年", "らいねん", "tahun depan")]),
        KANJI("j5-3", "帰", "キ", "かえ(る)", "pulang; kembali", 10,
              [("帰ります", "かえります", "pulang"), ("帰国", "きこく", "pulang ke negara asal")]),
        KANJI("j5-4", "電", "デン", "—", "listrik", 13,
              [("電車", "でんしゃ", "kereta listrik"), ("電話", "でんわ", "telepon")]),
        KANJI("j5-5", "車", "シャ", "くるま", "kendaraan; mobil", 7,
              [("電車", "でんしゃ", "kereta listrik"), ("自動車", "じどうしゃ", "mobil")]),
        KANJI("j5-6", "駅", "エキ", "—", "stasiun", 14,
              [("駅", "えき", "stasiun"), ("駅前", "えきまえ", "depan stasiun")]),
    ],
    kaiwa=KAIWA(
        "この 電車は 甲子園へ 行きますか — Apakah Kereta Ini ke Koshien?",
        "Nona Karina bertanya kepada seorang wanita di stasiun tentang kereta menuju stadion Koshien.",
        [
            ("カリナ", "Karina", "すみません。 甲子園|こうしえん まで いくら です か。",
             "Permisi. Sampai Koshien berapa (ongkosnya)?"),
            ("女|おんな の 人|ひと", "Onna no hito", "350円|さんびゃくごじゅうえん です。", "350 yen."),
            ("カリナ", "Karina", "この 電車|でんしゃ は 甲子園|こうしえん へ 行|い きます か。",
             "Apakah kereta ini pergi ke Koshien?"),
            ("女|おんな の 人|ひと", "Onna no hito", "いいえ。 次|つぎ の 「普通|ふつう」 です よ。",
             "Tidak. Yang berikutnya, kereta “lokal”."),
            ("カリナ", "Karina", "そう です か。 どうも ありがとう。", "Oh begitu. Terima kasih banyak."),
        ],
    ),
    quiz_bunpo=[
        QB("qb5-1", "わたし は 京都|きょうと ＿＿ 行|い きます。", ["へ", "で", "と", "を"], 0,
           "わたし は 京都|きょうと へ 行|い きます。", "へ", "[Tempat] へ 行きます",
           "へ menandai arah tujuan dan dibaca “e”. Partikel で untuk alat, と untuk orang yang menyertai."),
        QB("qb5-2", "電車|でんしゃ ＿＿ 会社|かいしゃ へ 行|い きます。", ["で", "へ", "と", "に"], 0,
           "電車|でんしゃ で 会社|かいしゃ へ 行|い きます。", "で", "[Alat transportasi] で 行きます",
           "で menandai sarana/alat. Ingat pengecualian: 歩いて (jalan kaki) tidak memakai で."),
        QB("qb5-3", "家族|かぞく ＿＿ 日本|にほん へ 来|き ました。", ["と", "で", "へ", "も"], 0,
           "家族|かぞく と 日本|にほん へ 来|き ました。", "と", "[Orang] と [Kata Kerja]",
           "と menandai orang yang menyertai. Untuk sendirian dipakai 一人で, memakai で bukan と."),
        QB("qb5-4", "＿＿ 日本|にほん へ 来|き ました か。", ["いつ", "どこ", "いくら", "なに"], 0,
           "いつ 日本|にほん へ 来|き ました か。", "いつ", "いつ [Kata Kerja] か",
           "いつ menanyakan waktu dan tidak pernah diikuti partikel に."),
        QB_ID("qb5-5", "“Saya tidak pergi ke mana pun.”",
              ["どこへ 行きます。", "どこへも 行きません。", "どこも 行きます。", "どこへ 行きません。"], 1,
              "どこ へ も 行|い きません。", "も", "どこへも [Kata Kerja negatif]",
              "Pola どこへも + kata kerja negatif berarti “tidak ke mana pun”. Partikel も menegaskan cakupan penuh."),
    ],
    quiz_susun=[
        QS("qs5-1", "Saya pergi ke Kyoto dengan kereta.", "電車|でんしゃ で 京都|きょうと へ 行|い きます", "と に"),
        QS("qs5-2", "Saya datang ke Jepang bersama keluarga.", "家族|かぞく と 日本|にほん へ 来|き ました", "で へ"),
        QS("qs5-3", "Tahun depan saya pulang ke negara saya.", "来年|らいねん 国|くに へ 帰|かえ ります", "に で"),
        QS("qs5-4", "Kapan Anda datang ke Jepang?", "いつ 日本|にほん へ 来|き ました か", "に どこ"),
    ],
)

BAB6 = CHAPTER(
    6, "わたしは 本を 読みます。", "Saya membaca buku.",
    bunpo=[
        BUNPO(
            "b6-1", "N を V — Objek Langsung",
            "[Kata Benda objek] を [Kata Kerja]",
            [
                "を = [Partikel] penanda objek, dibaca “o” (bukan “wo”)",
                "何|なに を = apa (sebagai objek)",
                "[Kata Kerja] = kata kerja transitif: 読みます, 食べます, 飲みます",
            ],
            "Partikel を menandai objek langsung yang dikenai perbuatan. Urutan kalimat Bahasa Jepang "
            "adalah Subjek–Objek–Kata Kerja, berbeda dengan Bahasa Indonesia yang Subjek–Kata Kerja–"
            "Objek. Jadi “saya membaca buku” menjadi わたしは 本を 読みます (saya + buku + membaca).",
            [
                ("わたし は 本|ほん を 読|よ みます。", "Saya membaca buku."),
                ("毎朝|まいあさ パン を 食|た べます。", "Setiap pagi saya makan roti."),
                ("何|なに を 飲|の みます か。", "Anda mau minum apa?"),
            ],
        ),
        BUNPO(
            "b6-2", "N で V — Tempat Berlangsungnya Perbuatan",
            "[Tempat] で [Kata Kerja]",
            [
                "で = [Partikel] di (tempat AKTIVITAS berlangsung)",
                "bedakan dari に yang menandai keberadaan (Bab 10)",
                "どこ で = di mana",
            ],
            "Partikel で menandai tempat terjadinya suatu aktivitas: 食堂で 昼ごはんを 食べます "
            "(“saya makan siang di kantin”). Ini berbeda dari partikel に yang menandai keberadaan "
            "atau titik tujuan. Aktivitas → で, keberadaan → に.",
            [
                ("食堂|しょくどう で 昼|ひる ごはん を 食|た べます。", "Saya makan siang di kantin."),
                ("図書館|としょかん で 勉強|べんきょう します。", "Saya belajar di perpustakaan."),
                ("どこ で 新聞|しんぶん を 買|か います か。", "Anda membeli surat kabar di mana?"),
            ],
        ),
        BUNPO(
            "b6-3", "〜ませんか — Mengajak dengan Halus",
            "[Kata Kerja] ませんか",
            [
                "〜ませんか = maukah Anda …? (ajakan sopan)",
                "bentuknya negatif, tetapi maknanya AJAKAN",
                "jawaban setuju: はい、〜ましょう / いいですね",
            ],
            "Meski bentuknya negatif, 〜ませんか adalah undangan sopan yang sangat umum, mirip "
            "“maukah Anda …?”. Menolak dilakukan secara halus, misalnya すみません、ちょっと… tanpa "
            "menyebutkan alasan lengkap — ini dianggap lebih sopan dalam budaya Jepang.",
            [
                ("いっしょ に 昼|ひる ごはん を 食|た べません か。", "Maukah Anda makan siang bersama?"),
                ("はい、 食|た べましょう。", "Ya, mari kita makan."),
            ],
        ),
        BUNPO(
            "b6-4", "〜ましょう — Mari Kita",
            "[Kata Kerja] ましょう",
            [
                "〜ましょう = mari (mengusulkan bersama)",
                "dipakai juga untuk menyetujui ajakan 〜ませんか",
                "〜ましょうか = maukah saya … (menawarkan bantuan)",
            ],
            "〜ましょう mengusulkan agar pembicara dan lawan bicara melakukan sesuatu bersama, atau "
            "menyatakan persetujuan atas ajakan sebelumnya. Bentuk 〜ましょうか dipakai saat menawarkan "
            "bantuan kepada orang lain.",
            [
                ("ちょっと 休|やす みましょう。", "Mari kita istirahat sedikit."),
                ("10時|じゅうじ に 行|い きましょう。", "Mari kita pergi jam 10."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k6-1", "食べます", "たべます", "tabemasu", "makan", "Kata Kerja",
               ("パン を 食|た べます。", "Saya makan roti.")),
        KOTOBA("k6-2", "飲みます", "のみます", "nomimasu", "minum", "Kata Kerja",
               ("お茶|おちゃ を 飲|の みます。", "Saya minum teh.")),
        KOTOBA("k6-3", "読みます", "よみます", "yomimasu", "membaca", "Kata Kerja",
               ("新聞|しんぶん を 読|よ みます。", "Saya membaca surat kabar.")),
        KOTOBA("k6-4", "書きます", "かきます", "kakimasu", "menulis", "Kata Kerja",
               ("手紙|てがみ を 書|か きます。", "Saya menulis surat.")),
        KOTOBA("k6-5", "買います", "かいます", "kaimasu", "membeli", "Kata Kerja",
               ("店|みせ で 本|ほん を 買|か います。", "Saya membeli buku di toko.")),
        KOTOBA("k6-6", "見ます", "みます", "mimasu", "melihat; menonton", "Kata Kerja",
               ("映画|えいが を 見|み ます。", "Saya menonton film.")),
        KOTOBA("k6-7", "聞きます", "ききます", "kikimasu", "mendengar", "Kata Kerja",
               ("音楽|おんがく を 聞|き きます。", "Saya mendengarkan musik.")),
        KOTOBA("k6-8", "します", "します", "shimasu", "melakukan", "Kata Kerja",
               ("テニス を します。", "Saya bermain tenis.")),
        KOTOBA("k6-9", "ごはん", "ごはん", "gohan", "nasi; makanan", "Kata Benda",
               ("朝|あさ ごはん を 食|た べます。", "Saya makan sarapan.")),
        KOTOBA("k6-10", "パン", "パン", "pan", "roti", "Kata Benda",
               ("毎朝|まいあさ パン を 食|た べます。", "Setiap pagi saya makan roti.")),
        KOTOBA("k6-11", "水", "みず", "mizu", "air", "Kata Benda",
               ("水|みず を 飲|の みます。", "Saya minum air.")),
        KOTOBA("k6-12", "お茶", "おちゃ", "ocha", "teh Jepang", "Kata Benda",
               ("お茶|おちゃ を 飲|の みません か。", "Maukah Anda minum teh?")),
        KOTOBA("k6-13", "手紙", "てがみ", "tegami", "surat", "Kata Benda",
               ("友達|ともだち に 手紙|てがみ を 書|か きます。", "Saya menulis surat kepada teman.")),
        KOTOBA("k6-14", "映画", "えいが", "eiga", "film", "Kata Benda",
               ("いっしょ に 映画|えいが を 見|み ません か。", "Maukah menonton film bersama?")),
        KOTOBA("k6-15", "図書館", "としょかん", "toshokan", "perpustakaan", "Kata Benda",
               ("図書館|としょかん で 勉強|べんきょう します。", "Saya belajar di perpustakaan.")),
        KOTOBA("k6-16", "店", "みせ", "mise", "toko", "Kata Benda",
               ("あの 店|みせ で 買|か います。", "Saya membeli di toko itu.")),
        KOTOBA("k6-17", "いっしょに", "いっしょに", "issho ni", "bersama-sama", "Ungkapan",
               ("いっしょ に 行|い きましょう。", "Mari kita pergi bersama.")),
        KOTOBA("k6-18", "何", "なに", "nani", "apa", "Kata Tanya",
               ("何|なに を 食|た べます か。", "Anda mau makan apa?")),
    ],
    kanji=[
        KANJI("j6-1", "食", "ショク", "た(べる)", "makan", 9,
              [("食べます", "たべます", "makan"), ("食堂", "しょくどう", "kantin")]),
        KANJI("j6-2", "飲", "イン", "の(む)", "minum", 12,
              [("飲みます", "のみます", "minum"), ("飲食", "いんしょく", "makan-minum")]),
        KANJI("j6-3", "読", "ドク", "よ(む)", "baca", 14,
              [("読みます", "よみます", "membaca"), ("読書", "どくしょ", "membaca buku")]),
        KANJI("j6-4", "見", "ケン", "み(る)", "lihat", 7,
              [("見ます", "みます", "melihat"), ("見学", "けんがく", "studi wisata")]),
        KANJI("j6-5", "買", "バイ", "か(う)", "beli", 12,
              [("買います", "かいます", "membeli"), ("売買", "ばいばい", "jual beli")]),
        KANJI("j6-6", "水", "スイ", "みず", "air", 4,
              [("水", "みず", "air"), ("水曜日", "すいようび", "hari Rabu")]),
    ],
    kaiwa=KAIWA(
        "いっしょに 行きませんか — Maukah Pergi Bersama?",
        "Pak Miller mengajak Nona Sato pergi menonton bunga sakura pada hari Sabtu.",
        [
            ("ミラー", "Mirā", "佐藤|さとう さん、 いっしょ に 花見|はなみ を しません か。",
             "Nona Sato, maukah Anda ikut melihat bunga sakura?"),
            ("佐藤", "Satō", "いい です ね。", "Wah, bagus sekali."),
            ("ミラー", "Mirā", "土曜日|どようび は どう です か。", "Bagaimana kalau hari Sabtu?"),
            ("佐藤", "Satō", "土曜日|どようび です ね。 いい です よ。", "Hari Sabtu ya. Baik, boleh."),
            ("ミラー", "Mirā", "じゃ、 10時|じゅうじ に 大阪駅|おおさかえき で 会|あ いましょう。",
             "Kalau begitu, mari bertemu jam 10 di stasiun Osaka."),
            ("佐藤", "Satō", "分|わ かりました。 また 土曜日|どようび。", "Baik. Sampai Sabtu."),
        ],
    ),
    quiz_bunpo=[
        QB("qb6-1", "わたし は 本|ほん ＿＿ 読|よ みます。", ["を", "は", "で", "に"], 0,
           "わたし は 本|ほん を 読|よ みます。", "を", "[Kata Benda] を [Kata Kerja]",
           "を menandai objek langsung dan dibaca “o”. Urutannya Subjek–Objek–Kata Kerja."),
        QB("qb6-2", "食堂|しょくどう ＿＿ 昼|ひる ごはん を 食|た べます。", ["で", "に", "へ", "を"], 0,
           "食堂|しょくどう で 昼|ひる ごはん を 食|た べます。", "で", "[Tempat] で [Kata Kerja]",
           "で menandai tempat berlangsungnya aktivitas. Partikel に menandai keberadaan, bukan aktivitas."),
        QB_ID("qb6-3", "“Maukah Anda makan siang bersama?”",
              ["いっしょに 昼ごはんを 食べます。", "いっしょに 昼ごはんを 食べませんか。",
               "いっしょに 昼ごはんを 食べました。", "いっしょに 昼ごはんを 食べましょうか。"], 1,
              "いっしょ に 昼|ひる ごはん を 食|た べません か。", "食べませんか", "[Kata Kerja] ませんか",
              "〜ませんか bentuknya negatif tetapi maknanya ajakan sopan “maukah Anda …?”."),
        QB("qb6-4", "ちょっと 休|やす ＿＿。", ["みましょう", "みますか", "みません", "みました"], 0,
           "ちょっと 休|やす みましょう。", "みましょう", "[Kata Kerja] ましょう",
           "〜ましょう berarti “mari kita …”, mengusulkan perbuatan bersama."),
        QB("qb6-5", "＿＿ を 飲|の みます か。", ["何", "どこ", "いつ", "だれ"], 0,
           "何|なに を 飲|の みます か。", "何", "何 を [Kata Kerja] か",
           "何 (なに) dipakai sebagai objek pertanyaan dan diikuti partikel を."),
    ],
    quiz_susun=[
        QS("qs6-1", "Saya membaca surat kabar setiap hari.", "毎日|まいにち 新聞|しんぶん を 読|よ みます", "で に"),
        QS("qs6-2", "Saya belajar bahasa Jepang di perpustakaan.",
           "図書館|としょかん で 日本語|にほんご を 勉強|べんきょう します", "へ を"),
        QS("qs6-3", "Maukah Anda menonton film bersama?", "いっしょ に 映画|えいが を 見|み ません か", "ます で"),
        QS("qs6-4", "Mari kita pergi jam 10.", "10時|じゅうじ に 行|い きましょう", "で ません"),
    ],
)

BAB7 = CHAPTER(
    7, "わたしは 花子さんに 花を あげます。", "Saya memberi bunga kepada Nona Hanako.",
    bunpo=[
        BUNPO(
            "b7-1", "N で V — Alat & Cara",
            "[Alat/bahasa] で [Kata Kerja]",
            [
                "で = [Partikel] dengan/memakai (alat, bahasa)",
                "何|なに で = dengan apa",
                "bedakan dari で penanda tempat (Bab 6)",
            ],
            "Selain menandai tempat aktivitas, で juga menandai alat, bahan, atau bahasa yang "
            "digunakan: はしで 食べます (“makan dengan sumpit”), 日本語で 話します (“berbicara dalam "
            "bahasa Jepang”). Konteks kata bendanya yang membedakan kedua fungsi ini.",
            [
                ("はし で 食|た べます。", "Saya makan dengan sumpit."),
                ("日本語|にほんご で 手紙|てがみ を 書|か きます。", "Saya menulis surat dalam bahasa Jepang."),
                ("何|なに で 「ありがとう」 を 言|い います か。", "Anda mengucapkan “terima kasih” dengan apa (bahasa)?"),
            ],
        ),
        BUNPO(
            "b7-2", "N に あげます — Memberi kepada Seseorang",
            "[Orang] に [Benda] を あげます",
            [
                "に = [Partikel] penanda penerima",
                "あげます = memberi (dari pembicara ke orang lain)",
                "JANGAN dipakai untuk memberi kepada atasan — gunakan さしあげます",
            ],
            "あげます menyatakan perbuatan memberi dari pembicara (atau pihak pembicara) kepada orang "
            "lain. Penerimanya ditandai partikel に. Perlu diingat: あげます tidak digunakan untuk "
            "menyatakan memberi kepada diri sendiri — untuk itu dipakai くれます.",
            [
                ("わたし は 花子|はなこ さん に 花|はな を あげます。", "Saya memberi bunga kepada Nona Hanako."),
                ("友達|ともだち に 手紙|てがみ を 書|か きました。", "Saya menulis surat kepada teman."),
            ],
        ),
        BUNPO(
            "b7-3", "N に/から もらいます — Menerima dari Seseorang",
            "[Orang] に / から [Benda] を もらいます",
            [
                "もらいます = menerima",
                "に dan から dua-duanya bisa menandai pemberi",
                "dari institusi (perusahaan/sekolah) WAJIB memakai から",
            ],
            "もらいます menyatakan bahwa pembicara menerima sesuatu. Pemberinya bisa ditandai に "
            "maupun から dengan makna yang sama. Namun jika pemberinya adalah lembaga seperti "
            "perusahaan atau sekolah, hanya から yang dipakai: 会社から もらいました.",
            [
                ("山田|やまだ さん に 本|ほん を もらいました。", "Saya menerima buku dari Pak Yamada."),
                ("会社|かいしゃ から お金|おかね を もらいます。", "Saya menerima uang dari perusahaan."),
            ],
        ),
        BUNPO(
            "b7-4", "もう 〜ました — Sudah Melakukan",
            "もう [Kata Kerja] ました ／ まだ です",
            [
                "もう = sudah",
                "jawaban belum: いいえ、まだ です",
                "JANGAN jawab いいえ、まだ 〜ませんでした",
            ],
            "もう 〜ましたか menanyakan apakah suatu perbuatan sudah dilakukan. Jika sudah, dijawab "
            "はい、もう 〜ました. Jika belum, jawaban yang benar adalah いいえ、まだ です — bukan bentuk "
            "lampau negatif. Ini pola jawaban yang harus dihafal apa adanya.",
            [
                ("もう 昼|ひる ごはん を 食|た べました か。", "Apakah Anda sudah makan siang?"),
                ("いいえ、 まだ です。", "Belum."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k7-1", "あげます", "あげます", "agemasu", "memberi", "Kata Kerja",
               ("花子|はなこ さん に 花|はな を あげます。", "Saya memberi bunga kepada Nona Hanako.")),
        KOTOBA("k7-2", "もらいます", "もらいます", "moraimasu", "menerima", "Kata Kerja",
               ("友達|ともだち に 本|ほん を もらいました。", "Saya menerima buku dari teman.")),
        KOTOBA("k7-3", "貸します", "かします", "kashimasu", "meminjamkan", "Kata Kerja",
               ("ノート を 貸|か します。", "Saya meminjamkan buku catatan.")),
        KOTOBA("k7-4", "借ります", "かります", "karimasu", "meminjam", "Kata Kerja",
               ("図書館|としょかん で 本|ほん を 借|か ります。", "Saya meminjam buku di perpustakaan.")),
        KOTOBA("k7-5", "教えます", "おしえます", "oshiemasu", "mengajar", "Kata Kerja",
               ("日本語|にほんご を 教|おし えます。", "Saya mengajar bahasa Jepang.")),
        KOTOBA("k7-6", "習います", "ならいます", "naraimasu", "belajar (dari guru)", "Kata Kerja",
               ("先生|せんせい に 習|なら います。", "Saya belajar dari guru.")),
        KOTOBA("k7-7", "かけます", "かけます", "kakemasu", "menelepon; memasang", "Kata Kerja",
               ("電話|でんわ を かけます。", "Saya menelepon.")),
        KOTOBA("k7-8", "手", "て", "te", "tangan", "Kata Benda",
               ("手|て で 食|た べます。", "Saya makan dengan tangan.")),
        KOTOBA("k7-9", "はし", "はし", "hashi", "sumpit", "Kata Benda",
               ("はし で 食|た べます。", "Saya makan dengan sumpit.")),
        KOTOBA("k7-10", "スプーン", "スプーン", "supūn", "sendok", "Kata Benda",
               ("スプーン で 食|た べます。", "Saya makan dengan sendok.")),
        KOTOBA("k7-11", "花", "はな", "hana", "bunga", "Kata Benda",
               ("花|はな を あげます。", "Saya memberi bunga.")),
        KOTOBA("k7-12", "お金", "おかね", "okane", "uang", "Kata Benda",
               ("会社|かいしゃ から お金|おかね を もらいます。", "Saya menerima uang dari perusahaan.")),
        KOTOBA("k7-13", "電話", "でんわ", "denwa", "telepon", "Kata Benda",
               ("友達|ともだち に 電話|でんわ を かけます。", "Saya menelepon teman.")),
        KOTOBA("k7-14", "プレゼント", "プレゼント", "purezento", "hadiah", "Kata Benda",
               ("プレゼント を もらいました。", "Saya menerima hadiah.")),
        KOTOBA("k7-15", "もう", "もう", "mō", "sudah", "Kata Keterangan",
               ("もう 食|た べました。", "Saya sudah makan.")),
        KOTOBA("k7-16", "まだ", "まだ", "mada", "belum; masih", "Kata Keterangan",
               ("いいえ、 まだ です。", "Belum.")),
        KOTOBA("k7-17", "言います", "いいます", "iimasu", "berkata", "Kata Kerja",
               ("日本語|にほんご で 言|い います。", "Saya mengatakannya dalam bahasa Jepang.")),
        KOTOBA("k7-18", "切ります", "きります", "kirimasu", "memotong", "Kata Kerja",
               ("ナイフ で 切|き ります。", "Saya memotong dengan pisau.")),
    ],
    kanji=[
        KANJI("j7-1", "手", "シュ", "て", "tangan", 4,
              [("手", "て", "tangan"), ("上手", "じょうず", "pandai")]),
        KANJI("j7-2", "花", "カ", "はな", "bunga", 7,
              [("花", "はな", "bunga"), ("花見", "はなみ", "melihat bunga sakura")]),
        KANJI("j7-3", "金", "キン", "かね", "uang; emas", 8,
              [("お金", "おかね", "uang"), ("金曜日", "きんようび", "hari Jumat")]),
        KANJI("j7-4", "話", "ワ", "はな(す)", "bicara; cerita", 13,
              [("電話", "でんわ", "telepon"), ("話します", "はなします", "berbicara")]),
        KANJI("j7-5", "教", "キョウ", "おし(える)", "ajar", 11,
              [("教えます", "おしえます", "mengajar"), ("教室", "きょうしつ", "ruang kelas")]),
        KANJI("j7-6", "貸", "タイ", "か(す)", "pinjamkan", 12,
              [("貸します", "かします", "meminjamkan"), ("貸出", "かしだし", "peminjaman")]),
    ],
    kaiwa=KAIWA(
        "いらっしゃい — Silakan Masuk",
        "Pak Miller bertamu ke rumah keluarga Yamada dan memberikan hadiah kepada tuan rumah.",
        [
            ("山田", "Yamada", "いらっしゃい。 どうぞ お上|あ がり ください。", "Selamat datang. Silakan masuk."),
            ("ミラー", "Mirā", "失礼|しつれい します。 これ、 ワイン です が、 どうぞ。",
             "Maaf mengganggu. Ini wine, silakan diterima."),
            ("山田", "Yamada", "どうも ありがとう ございます。", "Terima kasih banyak."),
            ("ミラー", "Mirā", "この お菓子|おかし は だれ に もらいました か。", "Kue ini Anda terima dari siapa?"),
            ("山田", "Yamada", "国|くに の 友達|ともだち に もらいました。", "Saya menerimanya dari teman di kampung."),
            ("ミラー", "Mirā", "もう 食|た べました か。", "Sudah dimakan?"),
            ("山田", "Yamada", "いいえ、 まだ です。 いっしょ に 食|た べましょう。",
             "Belum. Mari kita makan bersama."),
        ],
    ),
    quiz_bunpo=[
        QB("qb7-1", "はし ＿＿ 食|た べます。", ["で", "を", "に", "と"], 0,
           "はし で 食|た べます。", "で", "[Alat] で [Kata Kerja]",
           "で menandai alat atau cara. Objek yang dimakan ditandai を, bukan で."),
        QB("qb7-2", "花子|はなこ さん ＿＿ 花|はな を あげます。", ["に", "を", "で", "から"], 0,
           "花子|はなこ さん に 花|はな を あげます。", "に", "[Orang] に [Benda] を あげます",
           "に menandai penerima. Bendanya ditandai を: 人に 物を あげます."),
        QB("qb7-3", "会社|かいしゃ ＿＿ お金|おかね を もらいます。", ["から", "に", "で", "を"], 0,
           "会社|かいしゃ から お金|おかね を もらいます。", "から", "[Lembaga] から もらいます",
           "Jika pemberinya berupa lembaga seperti perusahaan atau sekolah, WAJIB memakai から, bukan に."),
        QB_ID("qb7-4", "“Belum.” (jawaban atas もう 食べましたか)",
              ["いいえ、まだ 食べませんでした。", "いいえ、まだ です。", "いいえ、もう です。", "いいえ、食べます。"], 1,
              "いいえ、 まだ です。", "まだ", "もう 〜ましたか → いいえ、まだ です",
              "Jawaban “belum” yang benar adalah いいえ、まだ です — bukan bentuk lampau negatif."),
        QB("qb7-5", "日本語|にほんご ＿＿ 手紙|てがみ を 書|か きます。", ["で", "を", "に", "へ"], 0,
           "日本語|にほんご で 手紙|てがみ を 書|か きます。", "で", "[Bahasa] で [Kata Kerja]",
           "Bahasa yang digunakan ditandai partikel で: 日本語で 話します."),
    ],
    quiz_susun=[
        QS("qs7-1", "Saya memberi bunga kepada Nona Hanako.", "花子|はなこ さん に 花|はな を あげます", "から で"),
        QS("qs7-2", "Saya menerima buku dari Pak Yamada.", "山田|やまだ さん に 本|ほん を もらいました", "を へ"),
        QS("qs7-3", "Saya makan dengan sumpit.", "はし で 食|た べます", "を に"),
        QS("qs7-4", "Saya sudah menelepon teman.", "もう 友達|ともだち に 電話|でんわ を かけました", "まだ で"),
    ],
)

BAB8 = CHAPTER(
    8, "桜は きれいです。", "Bunga sakura itu indah.",
    bunpo=[
        BUNPO(
            "b8-1", "Kata Sifat-na — [な] Adjektiva",
            "[Kata Benda] は [Kata Sifat-na] です",
            [
                "[Kata Sifat-na] = きれい, 有名|ゆうめい, 親切|しんせつ, 元気|げんき, 便利|べんり",
                "negatif: 〜じゃありません",
                "saat menerangkan kata benda: [Kata Sifat-na] な + [Kata Benda]",
            ],
            "Kata sifat-na disebut demikian karena memerlukan な saat langsung menerangkan kata benda: "
            "きれいな 花 (“bunga yang indah”). Namun jika menjadi predikat, な tidak dipakai: この 花は "
            "きれいです. Bentuk negatifnya mengikuti pola kata benda, yaitu 〜じゃありません.",
            [
                ("桜|さくら は きれい です。", "Bunga sakura itu indah."),
                ("この 町|まち は 有名|ゆうめい じゃありません。", "Kota ini tidak terkenal."),
                ("山田|やまだ さん は 親切|しんせつ な 人|ひと です。", "Pak Yamada orang yang baik hati."),
            ],
        ),
        BUNPO(
            "b8-2", "Kata Sifat-i — [い] Adjektiva",
            "[Kata Benda] は [Kata Sifat-i] です",
            [
                "[Kata Sifat-i] selalu berakhiran い: 高|たか い, 新|あたら しい, おいしい",
                "negatif: い → 〜くない です",
                "menerangkan kata benda: langsung tanpa な",
                "PENGECUALIAN: いい → よくない です",
            ],
            "Kata sifat-i berubah bentuk pada akhiran い-nya sendiri. Untuk negatif, い diganti "
            "menjadi くないです: 高い → 高くないです. Saat menerangkan kata benda, dipasang langsung "
            "tanpa な: 新しい 車. Hafalkan pengecualian いい (baik) yang negatifnya よくないです.",
            [
                ("この 本|ほん は おもしろい です。", "Buku ini menarik."),
                ("その かばん は 高|たか くない です。", "Tas itu tidak mahal."),
                ("新|あたら しい 車|くるま を 買|か いました。", "Saya membeli mobil baru."),
            ],
        ),
        BUNPO(
            "b8-3", "〜は どうですか — Menanyakan Kesan",
            "[Kata Benda] は どう です か",
            [
                "どう = [Kata Tanya] bagaimana (kesan/pendapat)",
                "jawabannya berupa kata sifat",
                "どうでしたか = bagaimana (untuk masa lampau)",
            ],
            "どうですか menanyakan kesan atau pendapat tentang sesuatu, dan dijawab dengan kata sifat. "
            "Untuk pengalaman yang sudah lewat, digunakan どうでしたか. Pola ini sangat sering dipakai "
            "dalam percakapan sehari-hari.",
            [
                ("日本|にほん の 生活|せいかつ は どう です か。", "Bagaimana kehidupan di Jepang?"),
                ("とても 楽|たの しい です。", "Sangat menyenangkan."),
            ],
        ),
        BUNPO(
            "b8-4", "どんな N — Menanyakan Sifat/Jenis",
            "どんな [Kata Benda]",
            [
                "どんな = [Kata Tanya] yang bagaimana / jenis apa",
                "SELALU diikuti kata benda",
                "bedakan dari どう yang berdiri sendiri",
            ],
            "どんな menanyakan sifat atau jenis dari suatu kata benda dan wajib diikuti kata benda "
            "tersebut: どんな 町ですか (“kota yang bagaimana?”). Bandingkan dengan どう yang berdiri "
            "sendiri untuk menanyakan kesan secara umum.",
            [
                ("奈良|なら は どんな 町|まち です か。", "Nara itu kota yang bagaimana?"),
                ("古|ふる い 町|まち です。", "Kota yang tua (bersejarah)."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k8-1", "きれい", "きれい", "kirei", "indah; bersih", "Kata Sifat-na",
               ("桜|さくら は きれい です。", "Bunga sakura itu indah.")),
        KOTOBA("k8-2", "有名", "ゆうめい", "yūmei", "terkenal", "Kata Sifat-na",
               ("この 町|まち は 有名|ゆうめい です。", "Kota ini terkenal.")),
        KOTOBA("k8-3", "親切", "しんせつ", "shinsetsu", "baik hati; ramah", "Kata Sifat-na",
               ("親切|しんせつ な 人|ひと です。", "Dia orang yang baik hati.")),
        KOTOBA("k8-4", "元気", "げんき", "genki", "sehat; bersemangat", "Kata Sifat-na",
               ("お元気|おげんき です か。", "Apakah Anda sehat?")),
        KOTOBA("k8-5", "便利", "べんり", "benri", "praktis; mudah", "Kata Sifat-na",
               ("この 辞書|じしょ は 便利|べんり です。", "Kamus ini praktis.")),
        KOTOBA("k8-6", "静か", "しずか", "shizuka", "tenang; sepi", "Kata Sifat-na",
               ("この 町|まち は 静|しず か です。", "Kota ini tenang.")),
        KOTOBA("k8-7", "にぎやか", "にぎやか", "nigiyaka", "ramai", "Kata Sifat-na",
               ("大阪|おおさか は にぎやか です。", "Osaka ramai.")),
        KOTOBA("k8-8", "大きい", "おおきい", "ōkii", "besar", "Kata Sifat-i",
               ("大|おお きい かばん を 買|か いました。", "Saya membeli tas besar.")),
        KOTOBA("k8-9", "小さい", "ちいさい", "chiisai", "kecil", "Kata Sifat-i",
               ("この 部屋|へや は 小|ちい さい です。", "Kamar ini kecil.")),
        KOTOBA("k8-10", "新しい", "あたらしい", "atarashii", "baru", "Kata Sifat-i",
               ("新|あたら しい 車|くるま です。", "Ini mobil baru.")),
        KOTOBA("k8-11", "古い", "ふるい", "furui", "tua; lama (benda)", "Kata Sifat-i",
               ("古|ふる い 町|まち です。", "Ini kota tua.")),
        KOTOBA("k8-12", "高い", "たかい", "takai", "mahal; tinggi", "Kata Sifat-i",
               ("その かばん は 高|たか くない です。", "Tas itu tidak mahal.")),
        KOTOBA("k8-13", "安い", "やすい", "yasui", "murah", "Kata Sifat-i",
               ("この 店|みせ は 安|やす いです。", "Toko ini murah.")),
        KOTOBA("k8-14", "おもしろい", "おもしろい", "omoshiroi", "menarik", "Kata Sifat-i",
               ("この 本|ほん は おもしろい です。", "Buku ini menarik.")),
        KOTOBA("k8-15", "おいしい", "おいしい", "oishii", "lezat", "Kata Sifat-i",
               ("この ケーキ は おいしい です。", "Kue ini lezat.")),
        KOTOBA("k8-16", "難しい", "むずかしい", "muzukashii", "sulit", "Kata Sifat-i",
               ("漢字|かんじ は 難|むずか しい です。", "Kanji itu sulit.")),
        KOTOBA("k8-17", "どう", "どう", "dō", "bagaimana", "Kata Tanya",
               ("日本|にほん の 生活|せいかつ は どう です か。", "Bagaimana kehidupan di Jepang?")),
        KOTOBA("k8-18", "どんな", "どんな", "donna", "yang bagaimana", "Kata Tanya",
               ("奈良|なら は どんな 町|まち です か。", "Nara kota yang bagaimana?")),
    ],
    kanji=[
        KANJI("j8-1", "大", "ダイ・タイ", "おお(きい)", "besar", 3,
              [("大きい", "おおきい", "besar"), ("大学", "だいがく", "universitas")]),
        KANJI("j8-2", "小", "ショウ", "ちい(さい)・こ", "kecil", 3,
              [("小さい", "ちいさい", "kecil"), ("小学校", "しょうがっこう", "sekolah dasar")]),
        KANJI("j8-3", "高", "コウ", "たか(い)", "tinggi; mahal", 10,
              [("高い", "たかい", "mahal"), ("高校", "こうこう", "SMA")]),
        KANJI("j8-4", "安", "アン", "やす(い)", "murah; aman", 6,
              [("安い", "やすい", "murah"), ("安心", "あんしん", "tenang; lega")]),
        KANJI("j8-5", "古", "コ", "ふる(い)", "tua; lama", 5,
              [("古い", "ふるい", "lama"), ("中古", "ちゅうこ", "barang bekas")]),
        KANJI("j8-6", "元", "ゲン", "もと", "asal; dasar", 4,
              [("元気", "げんき", "sehat"), ("元日", "がんじつ", "hari tahun baru")]),
    ],
    kaiwa=KAIWA(
        "そろそろ 失礼します — Saya Permisi Dulu",
        "Pak Miller sedang bertamu di rumah Pak Yamada dan berpamitan setelah mengobrol.",
        [
            ("山田", "Yamada", "日本|にほん の 生活|せいかつ は どう です か。", "Bagaimana kehidupan di Jepang?"),
            ("ミラー", "Mirā", "毎日|まいにち 楽|たの しい です。 でも、 仕事|しごと は 忙|いそが しい です。",
             "Setiap hari menyenangkan. Tapi pekerjaannya sibuk."),
            ("山田", "Yamada", "日本語|にほんご の 勉強|べんきょう は どう です か。",
             "Bagaimana belajar bahasa Jepangnya?"),
            ("ミラー", "Mirā", "漢字|かんじ は 難|むずか しい です が、 とても おもしろい です。",
             "Kanji sulit, tetapi sangat menarik."),
            ("ミラー", "Mirā", "あ、 もう 5時|ごじ です ね。 そろそろ 失礼|しつれい します。",
             "Ah, sudah jam 5 ya. Saya permisi dulu."),
            ("山田", "Yamada", "また どうぞ いらっしゃって ください。", "Silakan datang lagi."),
        ],
    ),
    quiz_bunpo=[
        QB("qb8-1", "山田|やまだ さん は 親切|しんせつ ＿＿ 人|ひと です。", ["な", "い", "の", "で"], 0,
           "山田|やまだ さん は 親切|しんせつ な 人|ひと です。", "な", "[Kata Sifat-na] な [Kata Benda]",
           "Kata sifat-na memerlukan な saat langsung menerangkan kata benda. Sebagai predikat, な tidak dipakai."),
        QB("qb8-2", "その かばん は 高|たか ＿＿ です。", ["くない", "じゃない", "ないく", "くはない"], 0,
           "その かばん は 高|たか くない です。", "くない", "[Kata Sifat-i] → 〜くない です",
           "Kata sifat-i dinegasikan dengan mengganti い menjadi くない. じゃありません dipakai untuk kata sifat-na dan kata benda."),
        QB("qb8-3", "この 町|まち は 有名|ゆうめい ＿＿。", ["じゃありません", "くないです", "ないです", "でわない"], 0,
           "この 町|まち は 有名|ゆうめい じゃありません。", "じゃありません", "[Kata Sifat-na] じゃありません",
           "有名 adalah kata sifat-na, jadi bentuk negatifnya mengikuti pola kata benda: じゃありません."),
        QB("qb8-4", "奈良|なら は ＿＿ 町|まち です か。", ["どんな", "どう", "どこ", "どちら"], 0,
           "奈良|なら は どんな 町|まち です か。", "どんな", "どんな [Kata Benda]",
           "どんな wajib diikuti kata benda. どう berdiri sendiri untuk menanyakan kesan: 〜は どうですか."),
        QB("qb8-5", "新|あたら しい ＿＿ を 買|か いました。", ["車", "車な", "車の", "車い"], 0,
           "新|あたら しい 車|くるま を 買|か いました。", "新しい", "[Kata Sifat-i] + [Kata Benda]",
           "Kata sifat-i menempel langsung pada kata benda tanpa tambahan apa pun: 新しい 車."),
    ],
    quiz_susun=[
        QS("qs8-1", "Bunga sakura itu indah.", "桜|さくら は きれい です", "な くない"),
        QS("qs8-2", "Buku ini menarik.", "この 本|ほん は おもしろい です", "な じゃありません"),
        QS("qs8-3", "Pak Yamada orang yang baik hati.", "山田|やまだ さん は 親切|しんせつ な 人|ひと です", "い の"),
        QS("qs8-4", "Tas itu tidak mahal.", "その かばん は 高|たか くない です", "じゃありません な"),
    ],
)

BAB9 = CHAPTER(
    9, "わたしは 日本語が 分かります。", "Saya mengerti bahasa Jepang.",
    bunpo=[
        BUNPO(
            "b9-1", "N が 分かります/あります — Partikel が pada Objek Khusus",
            "[Kata Benda] が 分|わ かります / あります",
            [
                "が = [Partikel] penanda objek untuk kata kerja tertentu",
                "dipakai dengan: 分かります, あります, 好|す き, 嫌|きら い, 上手|じょうず, 下手|へた",
                "BUKAN を — ini kesalahan umum",
            ],
            "Sekelompok kata kerja dan kata sifat tertentu menandai objeknya dengan が, bukan を. "
            "Kelompok ini mencakup 分かります (mengerti), あります (punya), serta kata sifat 好き "
            "(suka), 嫌い (tidak suka), 上手 (pandai), dan 下手 (tidak pandai). Jadi yang benar adalah "
            "日本語が 分かります, bukan 日本語を 分かります.",
            [
                ("わたし は 日本語|にほんご が 分|わ かります。", "Saya mengerti bahasa Jepang."),
                ("時間|じかん が ありません。", "Saya tidak punya waktu."),
                ("英語|えいご が 少|すこ し 分|わ かります。", "Saya sedikit mengerti bahasa Inggris."),
            ],
        ),
        BUNPO(
            "b9-2", "N が 好きです/嫌いです — Suka & Tidak Suka",
            "[Kata Benda] が 好|す き です / 嫌|きら い です",
            [
                "好き = [Kata Sifat-na] suka",
                "嫌い = [Kata Sifat-na] tidak suka",
                "objeknya ditandai が",
                "penguat: とても (sangat), あまり + negatif (tidak begitu)",
            ],
            "好き dan 嫌い berbentuk kata sifat-na, sehingga negatifnya 好きじゃありません. Objek yang "
            "disukai ditandai が. Untuk menyatakan “tidak terlalu suka”, dipakai あまり 好きじゃありません "
            "— あまり selalu berpasangan dengan bentuk negatif.",
            [
                ("わたし は 音楽|おんがく が 好|す き です。", "Saya suka musik."),
                ("納豆|なっとう は あまり 好|す き じゃありません。", "Saya tidak begitu suka natto."),
            ],
        ),
        BUNPO(
            "b9-3", "〜から — Menyatakan Alasan",
            "[Alasan] から、 [Akibat] ／ どうして 〜か",
            [
                "から = [Partikel] karena (menyusul alasan)",
                "どうして = [Kata Tanya] mengapa",
                "jawaban singkat: 〜から です",
            ],
            "から di akhir klausa menyatakan alasan, dan diletakkan SETELAH alasan tersebut — kebalikan "
            "dari Bahasa Indonesia yang menaruh “karena” di depan. Untuk menanyakan alasan digunakan "
            "どうして, dan jawabannya bisa diringkas menjadi 〜からです.",
            [
                ("時間|じかん が ありません から、 新聞|しんぶん を 読|よ みません。",
                 "Karena tidak punya waktu, saya tidak membaca surat kabar."),
                ("どうして 早|はや く 帰|かえ ります か。", "Mengapa Anda pulang cepat?"),
                ("用事|ようじ が ある から です。", "Karena ada urusan."),
            ],
        ),
        BUNPO(
            "b9-4", "よく・だいたい・少し・あまり・全然 — Kata Keterangan Tingkat",
            "[Kata Keterangan] + [Kata Kerja/Kata Sifat]",
            [
                "よく = dengan baik / sering",
                "だいたい = kurang lebih; secara garis besar",
                "少|すこ し = sedikit",
                "あまり + negatif = tidak begitu",
                "全然|ぜんぜん + negatif = sama sekali tidak",
            ],
            "Kata keterangan tingkat mengubah kadar suatu pernyataan. Yang paling penting diingat: "
            "あまり dan 全然 WAJIB dipasangkan dengan bentuk negatif. Menulis 全然 分かります adalah "
            "kesalahan — yang benar 全然 分かりません (“sama sekali tidak mengerti”).",
            [
                ("日本語|にほんご が よく 分|わ かります。", "Saya mengerti bahasa Jepang dengan baik."),
                ("英語|えいご は 全然|ぜんぜん 分|わ かりません。", "Saya sama sekali tidak mengerti bahasa Inggris."),
                ("お酒|おさけ は あまり 飲|の みません。", "Saya tidak begitu minum sake."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k9-1", "分かります", "わかります", "wakarimasu", "mengerti", "Kata Kerja",
               ("日本語|にほんご が 分|わ かります。", "Saya mengerti bahasa Jepang.")),
        KOTOBA("k9-2", "あります", "あります", "arimasu", "ada; punya", "Kata Kerja",
               ("時間|じかん が ありません。", "Saya tidak punya waktu.")),
        KOTOBA("k9-3", "好き", "すき", "suki", "suka", "Kata Sifat-na",
               ("音楽|おんがく が 好|す き です。", "Saya suka musik.")),
        KOTOBA("k9-4", "嫌い", "きらい", "kirai", "tidak suka; benci", "Kata Sifat-na",
               ("納豆|なっとう が 嫌|きら い です。", "Saya tidak suka natto.")),
        KOTOBA("k9-5", "上手", "じょうず", "jōzu", "pandai; mahir", "Kata Sifat-na",
               ("料理|りょうり が 上手|じょうず です。", "Dia pandai memasak.")),
        KOTOBA("k9-6", "下手", "へた", "heta", "tidak pandai", "Kata Sifat-na",
               ("歌|うた が 下手|へた です。", "Saya tidak pandai menyanyi.")),
        KOTOBA("k9-7", "料理", "りょうり", "ryōri", "masakan", "Kata Benda",
               ("日本|にほん 料理|りょうり が 好|す き です。", "Saya suka masakan Jepang.")),
        KOTOBA("k9-8", "音楽", "おんがく", "ongaku", "musik", "Kata Benda",
               ("音楽|おんがく を 聞|き きます。", "Saya mendengarkan musik.")),
        KOTOBA("k9-9", "スポーツ", "スポーツ", "supōtsu", "olahraga", "Kata Benda",
               ("スポーツ が 好|す き です。", "Saya suka olahraga.")),
        KOTOBA("k9-10", "時間", "じかん", "jikan", "waktu", "Kata Benda",
               ("時間|じかん が あります か。", "Apakah Anda punya waktu?")),
        KOTOBA("k9-11", "お金", "おかね", "okane", "uang", "Kata Benda",
               ("お金|おかね が ありません。", "Saya tidak punya uang.")),
        KOTOBA("k9-12", "どうして", "どうして", "dōshite", "mengapa", "Kata Tanya",
               ("どうして 帰|かえ ります か。", "Mengapa Anda pulang?")),
        KOTOBA("k9-13", "から", "から", "kara", "karena", "Partikel",
               ("時間|じかん が ありません から、 行|い きません。", "Karena tidak punya waktu, saya tidak pergi.")),
        KOTOBA("k9-14", "よく", "よく", "yoku", "dengan baik; sering", "Kata Keterangan",
               ("よく 分|わ かります。", "Saya mengerti dengan baik.")),
        KOTOBA("k9-15", "少し", "すこし", "sukoshi", "sedikit", "Kata Keterangan",
               ("少|すこ し 分|わ かります。", "Saya sedikit mengerti.")),
        KOTOBA("k9-16", "あまり", "あまり", "amari", "tidak begitu (+ negatif)", "Kata Keterangan",
               ("あまり 好|す き じゃありません。", "Saya tidak begitu suka.")),
        KOTOBA("k9-17", "全然", "ぜんぜん", "zenzen", "sama sekali tidak (+ negatif)", "Kata Keterangan",
               ("全然|ぜんぜん 分|わ かりません。", "Saya sama sekali tidak mengerti.")),
        KOTOBA("k9-18", "残念", "ざんねん", "zannen", "sayang sekali", "Kata Sifat-na",
               ("残念|ざんねん です ね。", "Sayang sekali, ya.")),
    ],
    kanji=[
        KANJI("j9-1", "好", "コウ", "す(き)・この(む)", "suka", 6,
              [("好き", "すき", "suka"), ("友好", "ゆうこう", "persahabatan")]),
        KANJI("j9-2", "間", "カン・ケン", "あいだ", "antara; jeda", 12,
              [("時間", "じかん", "waktu"), ("人間", "にんげん", "manusia")]),
        KANJI("j9-3", "少", "ショウ", "すこ(し)・すく(ない)", "sedikit", 4,
              [("少し", "すこし", "sedikit"), ("少年", "しょうねん", "anak laki-laki")]),
        KANJI("j9-4", "音", "オン", "おと", "suara; bunyi", 9,
              [("音楽", "おんがく", "musik"), ("発音", "はつおん", "pelafalan")]),
        KANJI("j9-5", "楽", "ガク・ラク", "たの(しい)", "musik; senang", 13,
              [("音楽", "おんがく", "musik"), ("楽しい", "たのしい", "menyenangkan")]),
        KANJI("j9-6", "料", "リョウ", "—", "bahan; biaya", 10,
              [("料理", "りょうり", "masakan"), ("料金", "りょうきん", "tarif")]),
    ],
    kaiwa=KAIWA(
        "残念です — Sayang Sekali",
        "Nona Kimura menawari Pak Miller tiket konser, tetapi Pak Miller tidak bisa datang.",
        [
            ("木村", "Kimura", "ミラーさん、 コンサート の チケット が ありますが、 いっしょ に 行|い きません か。",
             "Pak Miller, saya punya tiket konser. Maukah pergi bersama?"),
            ("ミラー", "Mirā", "いい です ね。 いつ です か。", "Bagus sekali. Kapan?"),
            ("木村", "Kimura", "来週|らいしゅう の 金曜日|きんようび です。", "Jumat minggu depan."),
            ("ミラー", "Mirā", "金曜日|きんようび です か。 ちょっと…。 時間|じかん が ありません から。",
             "Hari Jumat ya. Wah, agak… Karena saya tidak punya waktu."),
            ("木村", "Kimura", "そう です か。 残念|ざんねん です ね。", "Oh begitu. Sayang sekali, ya."),
            ("ミラー", "Mirā", "すみません。 また 今度|こんど おねがいします。",
             "Maaf. Lain kali mohon diajak lagi."),
        ],
    ),
    quiz_bunpo=[
        QB("qb9-1", "わたし は 日本語|にほんご ＿＿ 分|わ かります。", ["が", "を", "は", "に"], 0,
           "わたし は 日本語|にほんご が 分|わ かります。", "が", "[Kata Benda] が 分かります",
           "分かります menandai objeknya dengan が, bukan を. Aturan sama berlaku untuk あります, 好き, 上手."),
        QB("qb9-2", "わたし は 音楽|おんがく ＿＿ 好|す き です。", ["が", "を", "で", "に"], 0,
           "わたし は 音楽|おんがく が 好|す き です。", "が", "[Kata Benda] が 好き です",
           "好き adalah kata sifat-na dan objek yang disukai ditandai が."),
        QB("qb9-3", "時間|じかん が ありません ＿＿、 行|い きません。", ["から", "ので", "でも", "が"], 0,
           "時間|じかん が ありません から、 行|い きません。", "から", "[Alasan] から、[Akibat]",
           "から diletakkan SETELAH alasan, berbeda dari “karena” dalam Bahasa Indonesia yang di depan."),
        QB("qb9-4", "英語|えいご は 全然|ぜんぜん ＿＿。", ["分かりません", "分かります", "分かりました", "分かる"], 0,
           "英語|えいご は 全然|ぜんぜん 分|わ かりません。", "全然", "全然 + [bentuk negatif]",
           "全然 dan あまり WAJIB dipasangkan dengan bentuk negatif. 全然 分かります adalah kalimat yang salah."),
        QB("qb9-5", "＿＿ 早|はや く 帰|かえ ります か。", ["どうして", "どんな", "どう", "どこ"], 0,
           "どうして 早|はや く 帰|かえ ります か。", "どうして", "どうして 〜か → 〜から です",
           "どうして menanyakan alasan, dan jawabannya diakhiri から です."),
    ],
    quiz_susun=[
        QS("qs9-1", "Saya mengerti bahasa Jepang sedikit.", "日本語|にほんご が 少|すこ し 分|わ かります", "を から"),
        QS("qs9-2", "Saya suka masakan Jepang.", "日本|にほん 料理|りょうり が 好|す き です", "を な"),
        QS("qs9-3", "Karena tidak punya waktu, saya tidak pergi.",
           "時間|じかん が ありません から 行|い きません", "を どうして"),
        QS("qs9-4", "Saya sama sekali tidak mengerti bahasa Inggris.", "英語|えいご は 全然|ぜんぜん 分|わ かりません", "よく ます"),
    ],
)

CHAPTERS = [BAB2, BAB3, BAB4, BAB5, BAB6, BAB7, BAB8, BAB9]
