"""Materi Minna no Nihongo 1 — Bab 18 s/d 25 (penutup buku 1)."""

from seed_data.dsl import BUNPO, CHAPTER, KAIWA, KANJI, KOTOBA, QB, QB_ID, QS

BAB18 = CHAPTER(
    18, "わたしは 漢字を 読む ことが できます。", "Saya bisa membaca kanji.",
    bunpo=[
        BUNPO(
            "b18-1", "Bentuk Kamus (Jisho-kei)",
            "[Kata Kerja bentuk ます] → bentuk kamus",
            [
                "Golongan I: 〜います → 〜う (買います → 買う)",
                "Golongan II: ます → る (食べます → 食べる)",
                "Golongan III: します → する ； 来ます → 来る",
                "bentuk kamus = bentuk yang tercantum di kamus",
            ],
            "Bentuk kamus adalah bentuk dasar kata kerja dan menjadi fondasi banyak pola lanjutan. "
            "Golongan I mengubah baris い sebelum ます menjadi baris う: 読みます → 読む, 書きます → 書く. "
            "Golongan II cukup mengganti ます dengan る.",
            [
                ("読|よ みます → 読|よ む", "membaca → bentuk kamus"),
                ("食|た べます → 食|た べる", "makan → bentuk kamus"),
                ("します → する", "melakukan → bentuk kamus"),
            ],
        ),
        BUNPO(
            "b18-2", "V ことが できます — Bisa Melakukan",
            "[Kata Kerja bentuk kamus] こと が できます",
            [
                "〜ことができます = bisa / mampu",
                "negatif: 〜ことが できません",
                "untuk kata benda: [Kata Benda] が できます",
            ],
            "Pola ini menyatakan kemampuan atau kemungkinan melakukan sesuatu. こと mengubah kata "
            "kerja menjadi kata benda, sehingga bisa diikuti が できます. Untuk kemampuan berupa kata "
            "benda (bahasa, keterampilan), cukup 日本語が できます.",
            [
                ("わたし は 漢字|かんじ を 読|よ む こと が できます。", "Saya bisa membaca kanji."),
                ("車|くるま を 運転|うんてん する こと が できます か。", "Apakah Anda bisa menyetir mobil?"),
                ("ピアノ を 弾|ひ く こと が できません。", "Saya tidak bisa bermain piano."),
            ],
        ),
        BUNPO(
            "b18-3", "V のが 好きです/上手です — Suka & Mahir Melakukan",
            "[Kata Kerja bentuk kamus] の が 好|す き です / 上手|じょうず です",
            [
                "の mengubah kata kerja menjadi kata benda",
                "dipakai dengan 好き, 嫌い, 上手, 下手",
                "objek keseluruhan ditandai が",
            ],
            "Sama seperti こと, partikel の bisa mengubah klausa kata kerja menjadi kata benda. Pola ini "
            "dipakai bersama kata sifat yang menuntut が seperti 好き dan 上手 (lihat Bab 9): "
            "歌を 歌うのが 好きです (“saya suka menyanyi”).",
            [
                ("わたし は 歌|うた を 歌|うた う の が 好|す き です。", "Saya suka menyanyi."),
                ("木村|きむら さん は 料理|りょうり を 作|つく る の が 上手|じょうず です。",
                 "Nona Kimura pandai memasak."),
            ],
        ),
        BUNPO(
            "b18-4", "N の まえに / V まえに — Sebelum",
            "[Kata Benda] の まえ に ／ [Kata Kerja bentuk kamus] まえ に",
            [
                "kata benda: 食事|しょくじ の まえ に",
                "kata kerja: 寝|ね る まえ に (SELALU bentuk kamus)",
                "durasi: 3年|さんねん まえ に (tanpa の)",
            ],
            "まえに berarti “sebelum”. Setelah kata benda dipakai の, sedangkan setelah kata kerja "
            "dipakai bentuk kamus — bukan bentuk lampau, meski peristiwanya sudah terjadi. Untuk "
            "durasi waktu, まえに dipakai tanpa の.",
            [
                ("寝|ね る まえ に、 本|ほん を 読|よ みます。", "Sebelum tidur, saya membaca buku."),
                ("食事|しょくじ の まえ に 手|て を 洗|あら います。", "Sebelum makan, saya mencuci tangan."),
                ("3年|さんねん まえ に 日本|にほん へ 来|き ました。", "Tiga tahun lalu saya datang ke Jepang."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k18-1", "できます", "できます", "dekimasu", "bisa; mampu", "Kata Kerja",
               ("日本語|にほんご が できます。", "Saya bisa bahasa Jepang.")),
        KOTOBA("k18-2", "運転します", "うんてんします", "unten shimasu", "menyetir", "Kata Kerja",
               ("車|くるま を 運転|うんてん する こと が できます。", "Saya bisa menyetir mobil.")),
        KOTOBA("k18-3", "歌います", "うたいます", "utaimasu", "menyanyi", "Kata Kerja",
               ("歌|うた を 歌|うた う の が 好|す き です。", "Saya suka menyanyi.")),
        KOTOBA("k18-4", "集めます", "あつめます", "atsumemasu", "mengumpulkan", "Kata Kerja",
               ("切手|きって を 集|あつ めて います。", "Saya mengumpulkan meterai.")),
        KOTOBA("k18-5", "捨てます", "すてます", "sutemasu", "membuang", "Kata Kerja",
               ("ごみ を 捨|す てて ください。", "Tolong buang sampahnya.")),
        KOTOBA("k18-6", "作ります", "つくります", "tsukurimasu", "membuat", "Kata Kerja",
               ("料理|りょうり を 作|つく る の が 上手|じょうず です。", "Dia pandai memasak.")),
        KOTOBA("k18-7", "弾きます", "ひきます", "hikimasu", "memainkan (alat petik/tekan)", "Kata Kerja",
               ("ピアノ を 弾|ひ きます。", "Saya bermain piano.")),
        KOTOBA("k18-8", "洗います", "あらいます", "araimasu", "mencuci", "Kata Kerja",
               ("手|て を 洗|あら います。", "Saya mencuci tangan.")),
        KOTOBA("k18-9", "予約", "よやく", "yoyaku", "reservasi", "Kata Benda",
               ("予約|よやく が 必要|ひつよう です。", "Perlu reservasi.")),
        KOTOBA("k18-10", "趣味", "しゅみ", "shumi", "hobi", "Kata Benda",
               ("趣味|しゅみ は 何|なん です か。", "Apa hobi Anda?")),
        KOTOBA("k18-11", "歌", "うた", "uta", "lagu; nyanyian", "Kata Benda",
               ("日本|にほん の 歌|うた が 好|す き です。", "Saya suka lagu Jepang.")),
        KOTOBA("k18-12", "ピアノ", "ピアノ", "piano", "piano", "Kata Benda",
               ("ピアノ を 弾|ひ く こと が できます。", "Saya bisa bermain piano.")),
        KOTOBA("k18-13", "インターネット", "インターネット", "intānetto", "internet", "Kata Benda",
               ("インターネット で 調|しら べます。", "Saya mencari di internet.")),
        KOTOBA("k18-14", "まえに", "まえに", "mae ni", "sebelum", "Ungkapan",
               ("寝|ね る まえ に 読|よ みます。", "Sebelum tidur saya membaca.")),
        KOTOBA("k18-15", "必要", "ひつよう", "hitsuyō", "perlu; diperlukan", "Kata Sifat-na",
               ("パスポート が 必要|ひつよう です。", "Paspor diperlukan.")),
        KOTOBA("k18-16", "特に", "とくに", "toku ni", "terutama", "Kata Keterangan",
               ("特|とく に 好|す き です。", "Terutama saya suka ini.")),
    ],
    kanji=[
        KANJI("j18-1", "作", "サク", "つく(る)", "buat", 7,
              [("作ります", "つくります", "membuat"), ("作文", "さくぶん", "karangan")]),
        KANJI("j18-2", "歌", "カ", "うた(う)", "lagu; nyanyi", 14,
              [("歌", "うた", "lagu"), ("歌手", "かしゅ", "penyanyi")]),
        KANJI("j18-3", "運", "ウン", "はこ(ぶ)", "angkut; nasib", 12,
              [("運転", "うんてん", "menyetir"), ("運動", "うんどう", "olahraga")]),
        KANJI("j18-4", "転", "テン", "ころ(がる)", "berputar; berubah", 11,
              [("運転", "うんてん", "menyetir"), ("自転車", "じてんしゃ", "sepeda")]),
        KANJI("j18-5", "洗", "セン", "あら(う)", "cuci", 9,
              [("洗います", "あらいます", "mencuci"), ("洗濯", "せんたく", "mencuci pakaian")]),
    ],
    kaiwa=KAIWA(
        "趣味は 何ですか — Apa Hobi Anda?",
        "Pak Yamada dan Pak Miller berbincang tentang hobi masing-masing di ruang istirahat.",
        [
            ("山田", "Yamada", "ミラーさん、 趣味|しゅみ は 何|なん です か。", "Pak Miller, apa hobi Anda?"),
            ("ミラー", "Mirā", "写真|しゃしん を 撮|と る の が 好|す き です。", "Saya suka memotret."),
            ("山田", "Yamada", "そう です か。 わたし は 古|ふる い 物|もの を 集|あつ めて います。",
             "Oh begitu. Saya mengumpulkan barang antik."),
            ("ミラー", "Mirā", "山田|やまだ さん は 馬|うま に 乗|の る こと が できます か。",
             "Pak Yamada bisa menunggang kuda?"),
            ("山田", "Yamada", "いいえ、 できません。 でも、 習|なら いたい です。",
             "Tidak bisa. Tapi saya ingin belajar."),
            ("ミラー", "Mirā", "日本|にほん へ 来|く る まえ に、 少|すこ し 習|なら いました。",
             "Sebelum datang ke Jepang, saya belajar sedikit."),
        ],
    ),
    quiz_bunpo=[
        QB("qb18-1", "わたし は 漢字|かんじ を 読|よ ＿＿ こと が できます。", ["む", "みます", "んで", "まない"], 0,
           "わたし は 漢字|かんじ を 読|よ む こと が できます。", "読む", "[bentuk kamus] こと が できます",
           "Pola ことができます menuntut bentuk kamus. 読みます → 読む."),
        QB("qb18-2", "歌|うた を 歌|うた う ＿＿ が 好|す き です。", ["の", "こと", "を", "は"], 0,
           "歌|うた を 歌|うた う の が 好|す き です。", "の", "[bentuk kamus] の が 好き です",
           "の mengubah klausa kata kerja menjadi kata benda sehingga bisa diikuti が 好きです."),
        QB("qb18-3", "寝|ね ＿＿ まえ に、 本|ほん を 読|よ みます。", ["る", "ます", "た", "ない"], 0,
           "寝|ね る まえ に、 本|ほん を 読|よ みます。", "寝る", "[bentuk kamus] まえ に",
           "まえに SELALU didahului bentuk kamus, meski peristiwanya sudah lampau."),
        QB("qb18-4", "食事|しょくじ ＿＿ まえ に 手|て を 洗|あら います。", ["の", "を", "は", "で"], 0,
           "食事|しょくじ の まえ に 手|て を 洗|あら います。", "の", "[Kata Benda] の まえ に",
           "Setelah kata benda, まえに memerlukan の. Setelah kata kerja dipakai bentuk kamus tanpa の."),
    ],
    quiz_susun=[
        QS("qs18-1", "Saya bisa membaca kanji.", "漢字|かんじ を 読|よ む こと が できます", "みます の"),
        QS("qs18-2", "Saya suka memotret.", "写真|しゃしん を 撮|と る の が 好|す き です", "こと を"),
        QS("qs18-3", "Sebelum tidur, saya membaca buku.", "寝|ね る まえ に 本|ほん を 読|よ みます", "の から"),
    ],
)

BAB19 = CHAPTER(
    19, "ダイエットは 明日から します。", "Diet saya mulai besok.",
    bunpo=[
        BUNPO(
            "b19-1", "Bentuk た (Ta-form)",
            "[Kata Kerja bentuk て] → bentuk た",
            [
                "aturannya SAMA seperti bentuk て, hanya て → た",
                "読んで → 読んだ ； 書いて → 書いた",
                "食べて → 食べた ； して → した",
            ],
            "Bentuk た dibentuk dengan mengganti て pada bentuk て menjadi た (dan で menjadi だ). "
            "Karena itu, menguasai bentuk て otomatis berarti menguasai bentuk た. Bentuk ini menjadi "
            "dasar pola pengalaman dan beberapa pola lanjutan.",
            [
                ("食|た べて → 食|た べた", "makan → bentuk ta"),
                ("読|よ んで → 読|よ んだ", "membaca → bentuk ta"),
            ],
        ),
        BUNPO(
            "b19-2", "V たことが あります — Pernah Melakukan",
            "[Kata Kerja bentuk た] こと が あります",
            [
                "〜たことがあります = pernah (pengalaman)",
                "negatif: 〜たことが ありません",
                "bedakan dari bentuk lampau biasa 〜ました",
            ],
            "Pola ini menyatakan PENGALAMAN pernah melakukan sesuatu, bukan sekadar peristiwa lampau. "
            "Karena itu tidak dipakai bersama keterangan waktu yang spesifik: “kemarin saya pernah "
            "makan sushi” adalah kalimat yang tidak wajar — cukup きのう すしを 食べました.",
            [
                ("わたし は 馬|うま に 乗|の った こと が あります。", "Saya pernah menunggang kuda."),
                ("すし を 食|た べた こと が ありません。", "Saya belum pernah makan sushi."),
            ],
        ),
        BUNPO(
            "b19-3", "V たり、V たり します — Melakukan Ini dan Itu",
            "[bentuk た] り、 [bentuk た] り します",
            [
                "〜たり〜たり = melakukan A, B, dan sebagainya",
                "menyebut beberapa contoh kegiatan",
                "diakhiri します / しました",
            ],
            "Pola 〜たり〜たり します menyebutkan beberapa contoh kegiatan tanpa menyatakan urutan, "
            "mirip fungsi や pada kata benda. Kala kalimat ditentukan oleh します/しました di akhir.",
            [
                ("日曜日|にちようび は 洗濯|せんたく したり、 掃除|そうじ したり します。",
                 "Hari Minggu saya mencuci, bersih-bersih, dan sebagainya."),
                ("京都|きょうと で 写真|しゃしん を 撮|と ったり、 買|か い物|もの したり しました。",
                 "Di Kyoto saya memotret, berbelanja, dan sebagainya."),
            ],
        ),
        BUNPO(
            "b19-4", "〜く/〜に/〜に なります — Menjadi",
            "[Kata Sifat-i] い→く ／ [Kata Sifat-na] に ／ [Kata Benda] に + なります",
            [
                "Kata Sifat-i: 寒|さむ い → 寒|さむ く なります",
                "Kata Sifat-na: きれい → きれい に なります",
                "Kata Benda: 医者|いしゃ → 医者|いしゃ に なります",
            ],
            "なります menyatakan perubahan keadaan. Bentuk penghubungnya berbeda menurut jenis kata: "
            "kata sifat-i mengubah い menjadi く, sedangkan kata sifat-na dan kata benda memakai に. "
            "Pengecualian: いい → よく なります.",
            [
                ("もう すぐ 寒|さむ く なります。", "Segera akan menjadi dingin."),
                ("部屋|へや が きれい に なりました。", "Kamarnya jadi bersih."),
                ("息子|むすこ は 医者|いしゃ に なりました。", "Anak saya menjadi dokter."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k19-1", "登ります", "のぼります", "noborimasu", "mendaki", "Kata Kerja",
               ("山|やま に 登|のぼ った こと が あります。", "Saya pernah mendaki gunung.")),
        KOTOBA("k19-2", "泊まります", "とまります", "tomarimasu", "menginap", "Kata Kerja",
               ("ホテル に 泊|と まりました。", "Saya menginap di hotel.")),
        KOTOBA("k19-3", "掃除します", "そうじします", "sōji shimasu", "bersih-bersih", "Kata Kerja",
               ("部屋|へや を 掃除|そうじ します。", "Saya membersihkan kamar.")),
        KOTOBA("k19-4", "洗濯します", "せんたくします", "sentaku shimasu", "mencuci pakaian", "Kata Kerja",
               ("洗濯|せんたく したり、 掃除|そうじ したり します。", "Saya mencuci, bersih-bersih, dsb.")),
        KOTOBA("k19-5", "練習します", "れんしゅうします", "renshū shimasu", "berlatih", "Kata Kerja",
               ("毎日|まいにち 練習|れんしゅう します。", "Saya berlatih setiap hari.")),
        KOTOBA("k19-6", "なります", "なります", "narimasu", "menjadi", "Kata Kerja",
               ("寒|さむ く なりました。", "Menjadi dingin.")),
        KOTOBA("k19-7", "ダイエット", "ダイエット", "daietto", "diet", "Kata Benda",
               ("ダイエット は 明日|あした から します。", "Diet saya mulai besok.")),
        KOTOBA("k19-8", "ゴルフ", "ゴルフ", "gorufu", "golf", "Kata Benda",
               ("ゴルフ を した こと が あります。", "Saya pernah bermain golf.")),
        KOTOBA("k19-9", "相撲", "すもう", "sumō", "sumo", "Kata Benda",
               ("相撲|すもう を 見|み た こと が あります。", "Saya pernah menonton sumo.")),
        KOTOBA("k19-10", "山", "やま", "yama", "gunung", "Kata Benda",
               ("山|やま に 登|のぼ ります。", "Saya mendaki gunung.")),
        KOTOBA("k19-11", "馬", "うま", "uma", "kuda", "Kata Benda",
               ("馬|うま に 乗|の った こと が あります。", "Saya pernah menunggang kuda.")),
        KOTOBA("k19-12", "息子", "むすこ", "musuko", "anak laki-laki", "Kata Benda",
               ("息子|むすこ は 医者|いしゃ に なりました。", "Anak saya menjadi dokter.")),
        KOTOBA("k19-13", "娘", "むすめ", "musume", "anak perempuan", "Kata Benda",
               ("娘|むすめ は 学生|がくせい に なりました。", "Anak perempuan saya menjadi mahasiswa.")),
        KOTOBA("k19-14", "そろそろ", "そろそろ", "sorosoro", "segera; sudah waktunya", "Kata Keterangan",
               ("そろそろ 帰|かえ ります。", "Sudah waktunya saya pulang.")),
        KOTOBA("k19-15", "もうすぐ", "もうすぐ", "mō sugu", "segera; sebentar lagi", "Kata Keterangan",
               ("もう すぐ 春|はる に なります。", "Sebentar lagi musim semi.")),
        KOTOBA("k19-16", "だんだん", "だんだん", "dandan", "sedikit demi sedikit", "Kata Keterangan",
               ("だんだん 暖|あたた かく なります。", "Sedikit demi sedikit menjadi hangat.")),
    ],
    kanji=[
        KANJI("j19-1", "山", "サン", "やま", "gunung", 3,
              [("山", "やま", "gunung"), ("富士山", "ふじさん", "Gunung Fuji")]),
        KANJI("j19-2", "登", "トウ", "のぼ(る)", "mendaki", 12,
              [("登ります", "のぼります", "mendaki"), ("登山", "とざん", "pendakian gunung")]),
        KANJI("j19-3", "練", "レン", "—", "latih", 14,
              [("練習", "れんしゅう", "latihan")]),
        KANJI("j19-4", "習", "シュウ", "なら(う)", "belajar; biasa", 11,
              [("練習", "れんしゅう", "latihan"), ("習います", "ならいます", "belajar")]),
        KANJI("j19-5", "馬", "バ", "うま", "kuda", 10,
              [("馬", "うま", "kuda"), ("競馬", "けいば", "pacuan kuda")]),
    ],
    kaiwa=KAIWA(
        "ダイエットは 明日から します — Diet Mulai Besok",
        "Nona Matsumoto dan suaminya berbincang tentang berat badan dan rencana diet.",
        [
            ("松本", "Matsumoto", "最近|さいきん、 少|すこ し 太|ふと く なりました。",
             "Belakangan ini saya jadi agak gemuk."),
            ("夫", "Otto", "運動|うんどう を した こと が あります か。", "Pernah berolahraga?"),
            ("松本", "Matsumoto", "前|まえ は よく テニス を したり、 泳|およ いだり しました。",
             "Dulu saya sering bermain tenis, berenang, dan sebagainya."),
            ("夫", "Otto", "また 始|はじ めましょう。", "Mari mulai lagi."),
            ("松本", "Matsumoto", "そう です ね。 じゃ、 ダイエット は 明日|あした から します。",
             "Betul, ya. Baik, diet saya mulai besok."),
            ("夫", "Otto", "明日|あした から です か。", "Mulai besok ya?"),
        ],
    ),
    quiz_bunpo=[
        QB("qb19-1", "わたし は 馬|うま に 乗|の ＿＿ こと が あります。", ["った", "ります", "って", "らない"], 0,
           "わたし は 馬|うま に 乗|の った こと が あります。", "乗った", "[bentuk た] こと が あります",
           "Pola pengalaman memakai bentuk た: 乗ります → 乗って → 乗った."),
        QB("qb19-2", "日曜日|にちようび は 洗濯|せんたく ＿＿、 掃除|そうじ したり します。",
           ["したり", "して", "します", "した"], 0,
           "日曜日|にちようび は 洗濯|せんたく したり、 掃除|そうじ したり します。", "したり",
           "[bentuk た] り、[bentuk た] り します",
           "Pola 〜たり〜たり menyebut beberapa contoh kegiatan, dan diakhiri します/しました."),
        QB("qb19-3", "もう すぐ 寒|さむ ＿＿ なります。", ["く", "に", "で", "い"], 0,
           "もう すぐ 寒|さむ く なります。", "寒く", "[Kata Sifat-i] い → く なります",
           "Kata sifat-i mengubah い menjadi く sebelum なります. Kata sifat-na dan kata benda memakai に."),
        QB("qb19-4", "息子|むすこ は 医者|いしゃ ＿＿ なりました。", ["に", "く", "で", "が"], 0,
           "息子|むすこ は 医者|いしゃ に なりました。", "医者に", "[Kata Benda] に なります",
           "Kata benda memakai partikel に sebelum なります."),
    ],
    quiz_susun=[
        QS("qs19-1", "Saya pernah mendaki Gunung Fuji.", "富士山|ふじさん に 登|のぼ った こと が あります", "ます の"),
        QS("qs19-2", "Saya belum pernah menonton sumo.", "相撲|すもう を 見|み た こと が ありません", "あります ました"),
        QS("qs19-3", "Sebentar lagi akan menjadi dingin.", "もう すぐ 寒|さむ く なります", "に い"),
    ],
)

BAB20 = CHAPTER(
    20, "夏休みは どう するの。", "Libur musim panas mau bagaimana?",
    bunpo=[
        BUNPO(
            "b20-1", "Bentuk Biasa (Futsūkei) — Kata Kerja",
            "[bentuk ます] ↔ [bentuk biasa]",
            [
                "行きます ↔ 行く ； 行きません ↔ 行かない",
                "行きました ↔ 行った ； 行きませんでした ↔ 行かなかった",
                "bentuk biasa dipakai dengan keluarga & teman dekat",
            ],
            "Bahasa Jepang membedakan gaya bicara sopan (ですます) dan biasa (futsūkei). Bentuk biasa "
            "dipakai dengan keluarga, teman dekat, atau bawahan, serta dalam catatan dan diary. "
            "Menggunakan bentuk biasa kepada atasan atau orang yang baru dikenal dianggap kasar.",
            [
                ("あした 京都|きょうと へ 行|い く。", "Besok (aku) pergi ke Kyoto."),
                ("きのう 映画|えいが を 見|み た。", "Kemarin (aku) menonton film."),
                ("たばこ を 吸|す わない。", "(Aku) tidak merokok."),
            ],
        ),
        BUNPO(
            "b20-2", "Bentuk Biasa — Kata Benda & Kata Sifat",
            "[Kata Benda/Kata Sifat-na] だ ／ [Kata Sifat-i] い",
            [
                "学生です ↔ 学生だ ； 学生じゃありません ↔ 学生じゃない",
                "きれいです ↔ きれいだ",
                "高いです ↔ 高い (い tetap, です dihapus)",
                "高かったです ↔ 高かった",
            ],
            "Kata benda dan kata sifat-na memakai だ sebagai bentuk biasa dari です, sedangkan kata "
            "sifat-i cukup menghapus です. Dalam percakapan santai, だ sering dihilangkan sama sekali, "
            "terutama oleh perempuan: これ、おいしい。",
            [
                ("これ は わたし の 本|ほん だ。", "Ini bukuku."),
                ("この ケーキ、 おいしい。", "Kue ini enak."),
                ("きのう は 暇|ひま じゃなかった。", "Kemarin (aku) tidak senggang."),
            ],
        ),
        BUNPO(
            "b20-3", "Percakapan Santai — Partikel yang Dihilangkan",
            "の？ ／ 〜よ ／ 〜ね ／ partikel を・が dihilangkan",
            [
                "pertanyaan santai memakai の？ (bukan か)",
                "partikel を dan が sering dihilangkan",
                "laki-laki cenderung memakai だ, perempuan lebih sering menghilangkannya",
            ],
            "Dalam percakapan santai, pertanyaan diakhiri intonasi naik atau partikel の, bukan か. "
            "Partikel を dan が sering dihilangkan: ごはん 食べる？ (“mau makan?”). Namun partikel に, "
            "へ, dan で umumnya tetap dipertahankan karena membawa informasi penting.",
            [
                ("夏休み|なつやすみ は どう する の。", "Libur musim panas mau bagaimana?"),
                ("ごはん、 食|た べる。", "Mau makan?"),
                ("あした 暇|ひま。", "Besok senggang?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k20-1", "いる", "いる", "iru", "ada (bentuk biasa dari います)", "Kata Kerja",
               ("うち に いる。", "(Aku) ada di rumah.")),
        KOTOBA("k20-2", "要る", "いる", "iru", "perlu; butuh", "Kata Kerja",
               ("お金|おかね が 要|い る。", "(Aku) butuh uang."), display="要る|いる"),
        KOTOBA("k20-3", "国", "くに", "kuni", "negara; kampung", "Kata Benda",
               ("国|くに へ 帰|かえ る の。", "Mau pulang ke kampung?")),
        KOTOBA("k20-4", "夏休み", "なつやすみ", "natsuyasumi", "libur musim panas", "Kata Benda",
               ("夏休み|なつやすみ は どう する の。", "Libur musim panas mau bagaimana?")),
        KOTOBA("k20-5", "相撲", "すもう", "sumō", "sumo", "Kata Benda",
               ("相撲|すもう 見|み る。", "Mau lihat sumo?")),
        KOTOBA("k20-6", "切符", "きっぷ", "kippu", "tiket", "Kata Benda",
               ("切符|きっぷ を 買|か った。", "(Aku) sudah beli tiket.")),
        KOTOBA("k20-7", "ちょっと", "ちょっと", "chotto", "sebentar; agak", "Kata Keterangan",
               ("ちょっと 待|ま って。", "Tunggu sebentar.")),
        KOTOBA("k20-8", "うん", "うん", "un", "ya (santai)", "Ungkapan",
               ("うん、 そう だ。", "Ya, begitu.")),
        KOTOBA("k20-9", "ううん", "ううん", "uun", "tidak (santai)", "Ungkapan",
               ("ううん、 違|ちが う。", "Tidak, bukan.")),
        KOTOBA("k20-10", "ほんとう", "ほんとう", "hontō", "benar; sungguh", "Kata Benda",
               ("ほんとう。 よかった ね。", "Benarkah? Baguslah.")),
        KOTOBA("k20-11", "大変", "たいへん", "taihen", "berat; hebat", "Kata Sifat-na",
               ("仕事|しごと が 大変|たいへん だ。", "Pekerjaannya berat.")),
        KOTOBA("k20-12", "きっと", "きっと", "kitto", "pasti", "Kata Keterangan",
               ("きっと 来|く る。", "(Dia) pasti datang.")),
    ],
    kanji=[
        KANJI("j20-1", "夏", "カ", "なつ", "musim panas", 10,
              [("夏", "なつ", "musim panas"), ("夏休み", "なつやすみ", "libur musim panas")]),
        KANJI("j20-2", "春", "シュン", "はる", "musim semi", 9,
              [("春", "はる", "musim semi"), ("春休み", "はるやすみ", "libur musim semi")]),
        KANJI("j20-3", "秋", "シュウ", "あき", "musim gugur", 9,
              [("秋", "あき", "musim gugur"), ("秋分", "しゅうぶん", "ekuinoks musim gugur")]),
        KANJI("j20-4", "冬", "トウ", "ふゆ", "musim dingin", 5,
              [("冬", "ふゆ", "musim dingin"), ("冬休み", "ふゆやすみ", "libur musim dingin")]),
        KANJI("j20-5", "切", "セツ", "き(る)", "potong; tiket", 4,
              [("切符", "きっぷ", "tiket"), ("大切", "たいせつ", "penting")]),
    ],
    kaiwa=KAIWA(
        "夏休みは どう するの — Libur Musim Panas Mau Bagaimana?",
        "Dua mahasiswa, Kobayashi dan Ogawa, berbincang santai dengan bentuk biasa tentang rencana libur.",
        [
            ("小林", "Kobayashi", "小川|おがわ さん、 夏休み|なつやすみ は どう する の。",
             "Ogawa, libur musim panas mau bagaimana?"),
            ("小川", "Ogawa", "国|くに へ 帰|かえ る。 小林|こばやし さん は。", "Aku pulang kampung. Kalau kamu?"),
            ("小林", "Kobayashi", "わたし は 相撲|すもう を 見|み に 行|い く。", "Aku mau pergi lihat sumo."),
            ("小川", "Ogawa", "ほんとう。 いい ね。 切符|きっぷ は もう 買|か った の。",
             "Benarkah? Bagus ya. Tiketnya sudah beli?"),
            ("小林", "Kobayashi", "うん、 買|か った。 いっしょ に 行|い かない。",
             "Ya, sudah beli. Nggak mau ikut?"),
            ("小川", "Ogawa", "ごめん。 飛行機|ひこうき の 予約|よやく が ある から、 ちょっと 無理|むり だ。",
             "Maaf. Karena sudah ada reservasi pesawat, agak nggak bisa."),
        ],
    ),
    quiz_bunpo=[
        QB_ID("qb20-1", "Bentuk biasa dari 行きません", ["行かない", "行くない", "行きない", "行かなかった"], 0,
              "たばこ を 吸|す わない。", "吸わない", "〜ません ↔ bentuk ない",
              "Bentuk biasa dari 〜ません adalah bentuk ない: 行きません → 行かない."),
        QB_ID("qb20-2", "Bentuk biasa dari 学生です", ["学生だ", "学生い", "学生です", "学生な"], 0,
              "これ は わたし の 本|ほん だ。", "だ", "[Kata Benda] です ↔ [Kata Benda] だ",
              "Kata benda dan kata sifat-na memakai だ sebagai bentuk biasa dari です."),
        QB_ID("qb20-3", "Bentuk biasa dari 高いです", ["高い", "高いだ", "高くだ", "高かった"], 0,
              "この ケーキ、 おいしい。", "おいしい", "[Kata Sifat-i] です ↔ [Kata Sifat-i]",
              "Kata sifat-i cukup menghapus です — TIDAK ditambah だ. 高いだ adalah bentuk yang salah."),
        QB("qb20-4", "夏休み|なつやすみ は どう する ＿＿。", ["の", "か", "だ", "ね"], 0,
           "夏休み|なつやすみ は どう する の。", "の", "[bentuk biasa] の？",
           "Dalam percakapan santai, pertanyaan diakhiri の, bukan か."),
    ],
    quiz_susun=[
        QS("qs20-1", "Besok (aku) pergi ke Kyoto. (bentuk biasa)", "あした 京都|きょうと へ 行|い く", "ます か"),
        QS("qs20-2", "Kemarin (aku) menonton film. (bentuk biasa)", "きのう 映画|えいが を 見|み た", "ました です"),
        QS("qs20-3", "Libur musim panas mau bagaimana?", "夏休み|なつやすみ は どう する の", "か ます"),
    ],
)

BAB21 = CHAPTER(
    21, "わたしも そう 思います。", "Saya juga berpikir demikian.",
    bunpo=[
        BUNPO(
            "b21-1", "〜と 思います — Menyatakan Pendapat",
            "[kalimat bentuk biasa] と 思|おも います",
            [
                "と = [Partikel] penanda kutipan isi pikiran",
                "isi pikiran WAJIB bentuk biasa",
                "menanyakan pendapat: 〜について どう 思いますか",
            ],
            "Untuk menyatakan pendapat, isi pikirannya diubah ke bentuk biasa lalu diikuti と思います. "
            "Perhatikan bahwa meski kalimat utuhnya sopan, klausa sebelum と harus bentuk biasa: "
            "日本は 物価が 高いと 思います.",
            [
                ("日本|にほん は 物価|ぶっか が 高|たか い と 思|おも います。",
                 "Saya pikir harga barang di Jepang mahal."),
                ("ミラーさん は 来|こ ない と 思|おも います。", "Saya pikir Pak Miller tidak akan datang."),
                ("この 映画|えいが に ついて どう 思|おも います か。", "Apa pendapat Anda tentang film ini?"),
            ],
        ),
        BUNPO(
            "b21-2", "〜と 言います — Mengutip Perkataan",
            "「kutipan」 と 言|い います ／ [bentuk biasa] と 言|い いました",
            [
                "kutipan langsung memakai 「 」",
                "kutipan tidak langsung memakai bentuk biasa",
                "waktu kutipan tidak langsung menyesuaikan konteks",
            ],
            "Ada dua cara mengutip: langsung dengan tanda 「 」 yang menyalin ucapan apa adanya, dan "
            "tidak langsung dengan bentuk biasa sebelum と. Pada kutipan tidak langsung, kalimat "
            "aslinya diubah ke bentuk biasa.",
            [
                ("ミラーさん は 「あした 休|やす みます」 と 言|い いました。",
                 "Pak Miller berkata, “Besok saya libur.”"),
                ("ミラーさん は あした 休|やす む と 言|い いました。", "Pak Miller berkata bahwa besok dia libur."),
            ],
        ),
        BUNPO(
            "b21-3", "〜でしょう — Dugaan & Konfirmasi",
            "[bentuk biasa] でしょう ／ 〜でしょう？",
            [
                "でしょう = kemungkinan/dugaan (“mungkin”)",
                "dengan intonasi naik = meminta konfirmasi",
                "penguat: たぶん 〜でしょう",
            ],
            "でしょう menyatakan dugaan pembicara, sering diperkuat dengan たぶん. Jika diucapkan "
            "dengan intonasi naik, fungsinya berubah menjadi meminta konfirmasi dari lawan bicara, "
            "mirip “kan?” dalam Bahasa Indonesia.",
            [
                ("あした は 雨|あめ でしょう。", "Besok mungkin hujan."),
                ("たぶん ミラーさん は 知|し らない でしょう。", "Mungkin Pak Miller tidak tahu."),
                ("あした 来|き ます でしょう。", "Besok Anda datang, kan?"),
            ],
        ),
        BUNPO(
            "b21-4", "N について — Mengenai",
            "[Kata Benda] に ついて [Kata Kerja]",
            [
                "について = mengenai; tentang",
                "dipakai dengan: 話します, 聞きます, 思います, 書きます",
            ],
            "について menandai topik pembicaraan atau penulisan: 経済について 話します (“berbicara "
            "tentang ekonomi”). Pola ini banyak dipakai dalam konteks formal seperti presentasi, "
            "laporan, dan diskusi.",
            [
                ("日本|にほん の 経済|けいざい に ついて 話|はな しました。", "Saya berbicara tentang ekonomi Jepang."),
                ("この 問題|もんだい に ついて どう 思|おも います か。", "Apa pendapat Anda tentang masalah ini?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k21-1", "思います", "おもいます", "omoimasu", "berpikir; berpendapat", "Kata Kerja",
               ("わたし も そう 思|おも います。", "Saya juga berpikir demikian.")),
        KOTOBA("k21-2", "言います", "いいます", "iimasu", "berkata", "Kata Kerja",
               ("あした 休|やす む と 言|い いました。", "Dia berkata besok libur.")),
        KOTOBA("k21-3", "役に立ちます", "やくにたちます", "yaku ni tachimasu", "berguna", "Kata Kerja",
               ("この 辞書|じしょ は 役|やく に 立|た ちます。", "Kamus ini berguna.")),
        KOTOBA("k21-4", "意見", "いけん", "iken", "pendapat", "Kata Benda",
               ("意見|いけん を 言|い って ください。", "Tolong sampaikan pendapat Anda.")),
        KOTOBA("k21-5", "会議", "かいぎ", "kaigi", "rapat", "Kata Benda",
               ("会議|かいぎ に ついて 話|はな します。", "Saya berbicara tentang rapat.")),
        KOTOBA("k21-6", "ニュース", "ニュース", "nyūsu", "berita", "Kata Benda",
               ("ニュース を 見|み ました か。", "Sudah lihat beritanya?")),
        KOTOBA("k21-7", "政治", "せいじ", "seiji", "politik", "Kata Benda",
               ("政治|せいじ に ついて 話|はな します。", "Saya berbicara tentang politik.")),
        KOTOBA("k21-8", "経済", "けいざい", "keizai", "ekonomi", "Kata Benda",
               ("日本|にほん の 経済|けいざい に ついて 話|はな しました。", "Saya bicara tentang ekonomi Jepang.")),
        KOTOBA("k21-9", "交通", "こうつう", "kōtsū", "lalu lintas; transportasi", "Kata Benda",
               ("交通|こうつう が 便利|べんり です。", "Transportasinya praktis.")),
        KOTOBA("k21-10", "物価", "ぶっか", "bukka", "harga barang", "Kata Benda",
               ("物価|ぶっか が 高|たか い と 思|おも います。", "Saya pikir harga barang mahal.")),
        KOTOBA("k21-11", "問題", "もんだい", "mondai", "masalah; soal", "Kata Benda",
               ("この 問題|もんだい に ついて どう 思|おも います か。", "Apa pendapat Anda tentang masalah ini?")),
        KOTOBA("k21-12", "たぶん", "たぶん", "tabun", "mungkin", "Kata Keterangan",
               ("たぶん 来|こ ない でしょう。", "Mungkin dia tidak datang.")),
        KOTOBA("k21-13", "きっと", "きっと", "kitto", "pasti", "Kata Keterangan",
               ("きっと 来|き ます。", "Dia pasti datang.")),
        KOTOBA("k21-14", "本当に", "ほんとうに", "hontō ni", "sungguh-sungguh", "Kata Keterangan",
               ("本当|ほんとう に おいしい です。", "Sungguh lezat.")),
        KOTOBA("k21-15", "について", "について", "ni tsuite", "mengenai; tentang", "Ungkapan",
               ("政治|せいじ に ついて 話|はな します。", "Saya berbicara tentang politik.")),
        KOTOBA("k21-16", "でしょう", "でしょう", "deshō", "mungkin; kan?", "Ungkapan",
               ("あした は 雨|あめ でしょう。", "Besok mungkin hujan.")),
    ],
    kanji=[
        KANJI("j21-1", "思", "シ", "おも(う)", "pikir", 9,
              [("思います", "おもいます", "berpikir"), ("思想", "しそう", "pemikiran")]),
        KANJI("j21-2", "言", "ゲン・ゴン", "い(う)・こと", "kata; berkata", 7,
              [("言います", "いいます", "berkata"), ("言語", "げんご", "bahasa")]),
        KANJI("j21-3", "問", "モン", "と(う)", "tanya; soal", 11,
              [("問題", "もんだい", "masalah"), ("質問", "しつもん", "pertanyaan")]),
        KANJI("j21-4", "題", "ダイ", "—", "tema; judul", 18,
              [("問題", "もんだい", "masalah"), ("宿題", "しゅくだい", "PR")]),
        KANJI("j21-5", "意", "イ", "—", "maksud; kehendak", 13,
              [("意見", "いけん", "pendapat"), ("意味", "いみ", "makna")]),
    ],
    kaiwa=KAIWA(
        "わたしも そう 思います — Saya Juga Berpikir Demikian",
        "Pak Miller dan Pak Yamada berdiskusi tentang berita kenaikan harga di ruang rapat.",
        [
            ("山田", "Yamada", "ミラーさん、 ニュース を 見|み ました か。", "Pak Miller, sudah lihat beritanya?"),
            ("ミラー", "Mirā", "いいえ、 見|み ていません。 何|なに か あった ん です か。",
             "Belum, saya belum lihat. Ada apa?"),
            ("山田", "Yamada", "また 物価|ぶっか が 上|あ がる と 言|い って いました。",
             "Katanya harga barang naik lagi."),
            ("ミラー", "Mirā", "そう です か。 日本|にほん は 物価|ぶっか が 高|たか い と 思|おも います。",
             "Oh begitu. Saya pikir harga barang di Jepang mahal."),
            ("山田", "Yamada", "わたし も そう 思|おも います。 でも、 交通|こうつう は 便利|べんり です ね。",
             "Saya juga berpikir demikian. Tapi transportasinya praktis ya."),
            ("ミラー", "Mirā", "はい。 たぶん 世界|せかい で いちばん 便利|べんり でしょう。",
             "Ya. Mungkin paling praktis di dunia."),
        ],
    ),
    quiz_bunpo=[
        QB("qb21-1", "日本|にほん は 物価|ぶっか が 高|たか い ＿＿ 思|おも います。", ["と", "を", "で", "が"], 0,
           "日本|にほん は 物価|ぶっか が 高|たか い と 思|おも います。", "と", "[bentuk biasa] と 思います",
           "と menandai isi pikiran, dan klausa sebelum と WAJIB bentuk biasa."),
        QB("qb21-2", "ミラーさん は 来|こ ＿＿ と 思|おも います。", ["ない", "ません", "なくて", "ないです"], 0,
           "ミラーさん は 来|こ ない と 思|おも います。", "来ない", "[bentuk biasa] と 思います",
           "Sebelum と harus bentuk biasa, jadi 来ません menjadi 来ない."),
        QB("qb21-3", "あした は 雨|あめ ＿＿。", ["でしょう", "でしょうか", "だろか", "ましょう"], 0,
           "あした は 雨|あめ でしょう。", "でしょう", "[bentuk biasa] でしょう",
           "でしょう menyatakan dugaan. Dengan intonasi naik, fungsinya meminta konfirmasi."),
        QB("qb21-4", "この 問題|もんだい ＿＿ どう 思|おも います か。", ["について", "にとって", "による", "にして"], 0,
           "この 問題|もんだい に ついて どう 思|おも います か。", "について", "[Kata Benda] に ついて",
           "について berarti “mengenai/tentang”, dipakai dengan 思います, 話します, 書きます."),
    ],
    quiz_susun=[
        QS("qs21-1", "Saya juga berpikir demikian.", "わたし も そう 思|おも います", "と を"),
        QS("qs21-2", "Saya pikir Pak Miller tidak akan datang.", "ミラーさん は 来|こ ない と 思|おも います", "ません でしょう"),
        QS("qs21-3", "Besok mungkin hujan.", "あした は 雨|あめ でしょう", "と ます"),
    ],
)

BAB22 = CHAPTER(
    22, "これは 玉ねぎを 切る 機械です。", "Ini mesin untuk memotong bawang.",
    bunpo=[
        BUNPO(
            "b22-1", "Klausa Penerang Kata Benda",
            "[klausa bentuk biasa] + [Kata Benda]",
            [
                "klausa penerang memakai BENTUK BIASA",
                "subjek di dalam klausa ditandai が (bukan は)",
                "diletakkan SEBELUM kata benda yang diterangkan",
            ],
            "Bahasa Jepang menerangkan kata benda dengan meletakkan klausa lengkap di depannya, "
            "berbeda dari Bahasa Indonesia yang memakai “yang” di belakang. Klausa penerang selalu "
            "bentuk biasa, dan subjek di dalamnya ditandai が, bukan は: ミラーさんが 作った ケーキ "
            "(“kue yang dibuat Pak Miller”).",
            [
                ("これ は 玉|たま ねぎ を 切|き る 機械|きかい です。", "Ini mesin untuk memotong bawang."),
                ("ミラーさん が 作|つく った ケーキ は おいしい です。", "Kue yang dibuat Pak Miller lezat."),
                ("わたし が 住|す んで いる 町|まち は 静|しず か です。", "Kota tempat saya tinggal itu tenang."),
            ],
        ),
        BUNPO(
            "b22-2", "Klausa Penerang dengan Kata Sifat & Kata Benda",
            "[Kata Sifat-i] ／ [Kata Sifat-na] な ／ [Kata Benda] の + [Kata Benda]",
            [
                "kata sifat-i langsung: 背|せ が 高|たか い 人|ひと",
                "kata sifat-na + な: 有名|ゆうめい な 人|ひと",
                "kata benda + の: 日本語|にほんご の 本|ほん",
            ],
            "Selain klausa kata kerja, kata benda juga bisa diterangkan oleh kata sifat maupun kata "
            "benda lain. Aturan penyambungnya sudah dipelajari sebelumnya: kata sifat-i langsung, "
            "kata sifat-na memakai な, dan kata benda memakai の.",
            [
                ("背|せ が 高|たか い 人|ひと は だれ です か。", "Siapa orang yang tinggi itu?"),
                ("あれ は 有名|ゆうめい な 建物|たてもの です。", "Itu bangunan yang terkenal."),
            ],
        ),
        BUNPO(
            "b22-3", "〜時間が ありません — Tidak Ada Waktu untuk",
            "[Kata Kerja bentuk kamus] 時間|じかん が ありません",
            [
                "pola khusus klausa penerang + 時間",
                "bentuk kamus + 時間 = waktu untuk …",
                "bisa juga: 〜お金|おかね が ありません",
            ],
            "Karena klausa bentuk biasa bisa menerangkan kata benda apa pun, pola ini menghasilkan "
            "ungkapan yang sangat berguna: 新聞を 読む 時間が ありません (“tidak ada waktu untuk "
            "membaca surat kabar”).",
            [
                ("新聞|しんぶん を 読|よ む 時間|じかん が ありません。", "Saya tidak punya waktu untuk membaca surat kabar."),
                ("旅行|りょこう する お金|おかね が ありません。", "Saya tidak punya uang untuk bepergian."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k22-1", "着ます", "きます", "kimasu", "memakai (pakaian atas)", "Kata Kerja",
               ("シャツ を 着|き ます。", "Saya memakai kemeja.")),
        KOTOBA("k22-2", "かぶります", "かぶります", "kaburimasu", "memakai (topi)", "Kata Kerja",
               ("帽子|ぼうし を かぶります。", "Saya memakai topi.")),
        KOTOBA("k22-3", "はきます", "はきます", "hakimasu", "memakai (bawahan/sepatu)", "Kata Kerja",
               ("靴|くつ を はきます。", "Saya memakai sepatu.")),
        KOTOBA("k22-4", "かけます", "かけます", "kakemasu", "memakai (kacamata)", "Kata Kerja",
               ("眼鏡|めがね を かけて います。", "Saya memakai kacamata.")),
        KOTOBA("k22-5", "機械", "きかい", "kikai", "mesin", "Kata Benda",
               ("これ は 切|き る 機械|きかい です。", "Ini mesin untuk memotong.")),
        KOTOBA("k22-6", "約束", "やくそく", "yakusoku", "janji", "Kata Benda",
               ("約束|やくそく が あります。", "Saya ada janji.")),
        KOTOBA("k22-7", "用事", "ようじ", "yōji", "urusan", "Kata Benda",
               ("用事|ようじ が ある から、 帰|かえ ります。", "Karena ada urusan, saya pulang.")),
        KOTOBA("k22-8", "眼鏡", "めがね", "megane", "kacamata", "Kata Benda",
               ("眼鏡|めがね を かけて いる 人|ひと です。", "Orang yang memakai kacamata.")),
        KOTOBA("k22-9", "帽子", "ぼうし", "bōshi", "topi", "Kata Benda",
               ("帽子|ぼうし を かぶって います。", "Dia memakai topi.")),
        KOTOBA("k22-10", "背", "せ", "se", "tinggi badan; punggung", "Kata Benda",
               ("背|せ が 高|たか い 人|ひと です。", "Orang yang tinggi.")),
        KOTOBA("k22-11", "髪", "かみ", "kami", "rambut", "Kata Benda",
               ("髪|かみ が 長|なが い 人|ひと です。", "Orang yang berambut panjang.")),
        KOTOBA("k22-12", "玉ねぎ", "たまねぎ", "tamanegi", "bawang bombay", "Kata Benda",
               ("玉|たま ねぎ を 切|き ります。", "Saya memotong bawang bombay.")),
        KOTOBA("k22-13", "アパート", "アパート", "apāto", "apartemen", "Kata Benda",
               ("わたし が 住|す んで いる アパート です。", "Ini apartemen tempat saya tinggal.")),
        KOTOBA("k22-14", "家賃", "やちん", "yachin", "biaya sewa", "Kata Benda",
               ("家賃|やちん は 8万円|はちまんえん です。", "Sewanya 80.000 yen.")),
    ],
    kanji=[
        KANJI("j22-1", "着", "チャク", "き(る)・つ(く)", "pakai; tiba", 12,
              [("着ます", "きます", "memakai"), ("到着", "とうちゃく", "kedatangan")]),
        KANJI("j22-2", "洋", "ヨウ", "—", "samudra; gaya Barat", 9,
              [("洋服", "ようふく", "pakaian Barat"), ("太平洋", "たいへいよう", "Samudra Pasifik")]),
        KANJI("j22-3", "服", "フク", "—", "pakaian", 8,
              [("洋服", "ようふく", "pakaian"), ("服装", "ふくそう", "penampilan pakaian")]),
        KANJI("j22-4", "約", "ヤク", "—", "janji; kira-kira", 9,
              [("約束", "やくそく", "janji"), ("予約", "よやく", "reservasi")]),
        KANJI("j22-5", "束", "ソク", "たば", "ikat; berkas", 7,
              [("約束", "やくそく", "janji"), ("花束", "はなたば", "buket bunga")]),
    ],
    kaiwa=KAIWA(
        "どんな アパートが いいですか — Apartemen Seperti Apa yang Bagus?",
        "Nona Wang mencari apartemen di agen properti dan menyebutkan kriteria yang diinginkan.",
        [
            ("店員", "Ten'in", "どんな アパート を お探|さが し です か。", "Anda mencari apartemen seperti apa?"),
            ("ワン", "Wan", "駅|えき の 近|ちか く に ある アパート が いい です。",
             "Apartemen yang berada di dekat stasiun bagus."),
            ("店員", "Ten'in", "こちら は どう です か。 駅|えき から 歩|ある いて 5分|ごふん です。",
             "Bagaimana yang ini? Lima menit jalan kaki dari stasiun."),
            ("ワン", "Wan", "部屋|へや が 明|あか るくて、 広|ひろ い アパート です ね。 家賃|やちん は いくら です か。",
             "Apartemen yang kamarnya terang dan luas ya. Sewanya berapa?"),
            ("店員", "Ten'in", "8万円|はちまんえん です。", "80.000 yen."),
            ("ワン", "Wan", "ちょっと 考|かんが える 時間|じかん が ほしい です。",
             "Saya ingin waktu untuk berpikir sedikit."),
        ],
    ),
    quiz_bunpo=[
        QB("qb22-1", "これ は 玉|たま ねぎ を 切|き ＿＿ 機械|きかい です。", ["る", "ります", "った", "って"], 0,
           "これ は 玉|たま ねぎ を 切|き る 機械|きかい です。", "切る", "[klausa bentuk biasa] + [Kata Benda]",
           "Klausa penerang kata benda memakai bentuk biasa — di sini bentuk kamus 切る."),
        QB("qb22-2", "ミラーさん ＿＿ 作|つく った ケーキ は おいしい です。", ["が", "は", "を", "の"], 0,
           "ミラーさん が 作|つく った ケーキ は おいしい です。", "が",
           "[Subjek] が [klausa] + [Kata Benda]",
           "Subjek DI DALAM klausa penerang ditandai が, bukan は. は hanya untuk topik kalimat utama."),
        QB("qb22-3", "新聞|しんぶん を 読|よ ＿＿ 時間|じかん が ありません。", ["む", "みます", "んだ", "んで"], 0,
           "新聞|しんぶん を 読|よ む 時間|じかん が ありません。", "読む", "[bentuk kamus] 時間 が ありません",
           "Bentuk kamus + 時間 berarti “waktu untuk melakukan …”."),
        QB("qb22-4", "あれ は 有名|ゆうめい ＿＿ 建物|たてもの です。", ["な", "の", "い", "で"], 0,
           "あれ は 有名|ゆうめい な 建物|たてもの です。", "な", "[Kata Sifat-na] な [Kata Benda]",
           "有名 adalah kata sifat-na sehingga memerlukan な saat menerangkan kata benda."),
    ],
    quiz_susun=[
        QS("qs22-1", "Ini mesin untuk memotong bawang bombay.",
           "これ は 玉|たま ねぎ を 切|き る 機械|きかい です", "った ります"),
        QS("qs22-2", "Kue yang dibuat Pak Miller lezat.",
           "ミラーさん が 作|つく った ケーキ は おいしい です", "は を"),
        QS("qs22-3", "Saya tidak punya waktu untuk membaca surat kabar.",
           "新聞|しんぶん を 読|よ む 時間|じかん が ありません", "んだ あります"),
    ],
)

BAB23 = CHAPTER(
    23, "どうやって 行くか 教えて ください。", "Tolong ajari cara perginya.",
    bunpo=[
        BUNPO(
            "b23-1", "V とき、〜 — Ketika",
            "[klausa bentuk biasa] とき、 [kalimat]",
            [
                "とき didahului BENTUK BIASA",
                "kata benda: [Kata Benda] の とき",
                "kata sifat-na: [Kata Sifat-na] な とき",
                "bentuk kamus とき = sebelum/saat akan; bentuk た とき = setelah",
            ],
            "とき berarti “ketika/saat”. Yang penting dipahami: pilihan bentuk kamus atau bentuk た "
            "menentukan urutan waktu. 国へ 帰るとき (“saat akan pulang”) berbeda dari 国へ 帰ったとき "
            "(“setelah sampai di negara asal”).",
            [
                ("図書館|としょかん を 使|つか う とき、 カード が 必要|ひつよう です。",
                 "Saat memakai perpustakaan, kartu diperlukan."),
                ("子供|こども の とき、 よく 川|かわ で 泳|およ ぎました。",
                 "Waktu kecil, saya sering berenang di sungai."),
                ("暇|ひま な とき、 映画|えいが を 見|み ます。", "Saat senggang, saya menonton film."),
            ],
        ),
        BUNPO(
            "b23-2", "V と、〜 — Jika/Apabila (Akibat Pasti)",
            "[Kata Kerja bentuk kamus] と、 [akibat]",
            [
                "と = jika (hasilnya SELALU sama)",
                "dipakai untuk mekanisme, aturan alam, petunjuk jalan",
                "akibatnya TIDAK boleh berupa keinginan/perintah",
            ],
            "Pola 〜と menyatakan hubungan sebab-akibat yang pasti dan berulang: このボタンを 押すと、"
            "ドアが 開きます (“jika tombol ini ditekan, pintu terbuka”). Karena menyatakan kepastian, "
            "klausa akibatnya tidak boleh berupa permintaan, ajakan, atau keinginan.",
            [
                ("この ボタン を 押|お す と、 ドア が 開|あ きます。",
                 "Jika tombol ini ditekan, pintunya terbuka."),
                ("右|みぎ へ 曲|ま がる と、 郵便局|ゆうびんきょく が あります。",
                 "Jika berbelok ke kanan, ada kantor pos."),
            ],
        ),
        BUNPO(
            "b23-3", "N が [Kata Sifat] — Menyebut Bagian/Ciri",
            "[Kata Benda besar] は [bagian] が [Kata Sifat] です",
            [
                "pola topik-ganda: は untuk keseluruhan, が untuk bagian",
                "contoh: 象|ぞう は 鼻|はな が 長|なが い です",
            ],
            "Bahasa Jepang sering memakai dua penanda dalam satu kalimat: は menandai topik "
            "keseluruhan dan が menandai bagian yang dijelaskan. Pola ini alami untuk mendeskripsikan "
            "ciri fisik atau sifat bagian dari sesuatu.",
            [
                ("この 町|まち は 交通|こうつう が 便利|べんり です。", "Kota ini transportasinya praktis."),
                ("あの 人|ひと は 髪|かみ が 長|なが い です。", "Orang itu rambutnya panjang."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k23-1", "回します", "まわします", "mawashimasu", "memutar", "Kata Kerja",
               ("つまみ を 回|まわ して ください。", "Tolong putar tombolnya.")),
        KOTOBA("k23-2", "引きます", "ひきます", "hikimasu", "menarik", "Kata Kerja",
               ("この ドア を 引|ひ きます。", "Saya menarik pintu ini.")),
        KOTOBA("k23-3", "変えます", "かえます", "kaemasu", "mengubah", "Kata Kerja",
               ("予定|よてい を 変|か えました。", "Saya mengubah jadwal.")),
        KOTOBA("k23-4", "触ります", "さわります", "sawarimasu", "menyentuh", "Kata Kerja",
               ("触|さわ らないで ください。", "Tolong jangan disentuh.")),
        KOTOBA("k23-5", "とき", "とき", "toki", "ketika; saat", "Kata Benda",
               ("子供|こども の とき、 よく 遊|あそ びました。", "Waktu kecil saya sering bermain.")),
        KOTOBA("k23-6", "つまみ", "つまみ", "tsumami", "tombol putar", "Kata Benda",
               ("つまみ を 右|みぎ へ 回|まわ します。", "Saya putar tombolnya ke kanan.")),
        KOTOBA("k23-7", "信号", "しんごう", "shingō", "lampu lalu lintas", "Kata Benda",
               ("信号|しんごう を 右|みぎ へ 曲|ま がります。", "Saya belok kanan di lampu lalu lintas.")),
        KOTOBA("k23-8", "交差点", "こうさてん", "kōsaten", "persimpangan", "Kata Benda",
               ("交差点|こうさてん を 渡|わた ります。", "Saya melewati persimpangan.")),
        KOTOBA("k23-9", "角", "かど", "kado", "sudut; tikungan", "Kata Benda",
               ("角|かど を 左|ひだり へ 曲|ま がります。", "Saya belok kiri di tikungan.")),
        KOTOBA("k23-10", "橋", "はし", "hashi", "jembatan", "Kata Benda",
               ("橋|はし を 渡|わた ります。", "Saya menyeberangi jembatan.")),
        KOTOBA("k23-11", "道", "みち", "michi", "jalan", "Kata Benda",
               ("この 道|みち を まっすぐ 行|い きます。", "Saya lurus mengikuti jalan ini.")),
        KOTOBA("k23-12", "まっすぐ", "まっすぐ", "massugu", "lurus", "Kata Keterangan",
               ("まっすぐ 行|い って ください。", "Tolong jalan lurus.")),
        KOTOBA("k23-13", "近く", "ちかく", "chikaku", "dekat", "Kata Benda",
               ("駅|えき の 近|ちか く に あります。", "Ada di dekat stasiun.")),
        KOTOBA("k23-14", "曲がります", "まがります", "magarimasu", "berbelok", "Kata Kerja",
               ("右|みぎ へ 曲|ま がる と、 銀行|ぎんこう が あります。", "Jika belok kanan, ada bank.")),
    ],
    kanji=[
        KANJI("j23-1", "道", "ドウ", "みち", "jalan", 12,
              [("道", "みち", "jalan"), ("道路", "どうろ", "jalan raya")]),
        KANJI("j23-2", "橋", "キョウ", "はし", "jembatan", 16,
              [("橋", "はし", "jembatan"), ("歩道橋", "ほどうきょう", "jembatan penyeberangan")]),
        KANJI("j23-3", "角", "カク", "かど・つの", "sudut; tanduk", 7,
              [("角", "かど", "tikungan"), ("三角", "さんかく", "segitiga")]),
        KANJI("j23-4", "交", "コウ", "まじ(わる)", "silang; bergaul", 6,
              [("交通", "こうつう", "lalu lintas"), ("交差点", "こうさてん", "persimpangan")]),
        KANJI("j23-5", "通", "ツウ", "とお(る)・かよ(う)", "lewat; bolak-balik", 10,
              [("交通", "こうつう", "lalu lintas"), ("通います", "かよいます", "bolak-balik")]),
    ],
    kaiwa=KAIWA(
        "どうやって 行くか 教えて ください — Tolong Ajari Cara Perginya",
        "Nona Karina menelepon untuk menanyakan jalan menuju museum seni.",
        [
            ("カリナ", "Karina", "すみません。 美術館|びじゅつかん へ 行|い きたい ん です が…。",
             "Permisi. Saya ingin pergi ke museum seni…"),
            ("係|かかり", "Kakari", "駅|えき を 出|で る と、 大|おお きい 道|みち が あります。",
             "Jika keluar dari stasiun, ada jalan besar."),
            ("カリナ", "Karina", "はい。", "Ya."),
            ("係|かかり", "Kakari", "その 道|みち を まっすぐ 行|い って、 2つ|ふたつ 目|め の 角|かど を 右|みぎ へ 曲|ま がって ください。",
             "Jalan lurus mengikuti jalan itu, lalu belok kanan di tikungan kedua."),
            ("係|かかり", "Kakari", "橋|はし を 渡|わた る と、 左|ひだり に 美術館|びじゅつかん が あります。",
             "Jika menyeberangi jembatan, di sebelah kiri ada museum seni."),
            ("カリナ", "Karina", "分|わ かりました。 どうも ありがとう ございました。",
             "Saya mengerti. Terima kasih banyak."),
        ],
    ),
    quiz_bunpo=[
        QB("qb23-1", "図書館|としょかん を 使|つか ＿＿ とき、 カード が 必要|ひつよう です。",
           ["う", "います", "って", "った"], 0,
           "図書館|としょかん を 使|つか う とき、 カード が 必要|ひつよう です。", "使う",
           "[bentuk biasa] とき、〜",
           "とき didahului bentuk biasa. Bentuk kamus menandai “saat akan/sedang”, bentuk た menandai “setelah”."),
        QB("qb23-2", "子供|こども ＿＿ とき、 よく 川|かわ で 泳|およ ぎました。", ["の", "な", "だ", "が"], 0,
           "子供|こども の とき、 よく 川|かわ で 泳|およ ぎました。", "子供の", "[Kata Benda] の とき",
           "Setelah kata benda, とき memerlukan の. Kata sifat-na memakai な."),
        QB("qb23-3", "この ボタン を 押|お す ＿＿、 ドア が 開|あ きます。", ["と", "たら", "ば", "なら"], 0,
           "この ボタン を 押|お す と、 ドア が 開|あ きます。", "と", "[bentuk kamus] と、[akibat pasti]",
           "〜と menyatakan akibat yang SELALU terjadi — cocok untuk mekanisme dan petunjuk jalan."),
        QB("qb23-4", "この 町|まち は 交通|こうつう ＿＿ 便利|べんり です。", ["が", "は", "を", "の"], 0,
           "この 町|まち は 交通|こうつう が 便利|べんり です。", "が", "[Keseluruhan] は [bagian] が 〜",
           "は menandai topik keseluruhan, が menandai bagian yang dijelaskan."),
    ],
    quiz_susun=[
        QS("qs23-1", "Saat memakai perpustakaan, kartu diperlukan.",
           "図書館|としょかん を 使|つか う とき カード が 必要|ひつよう です", "った の"),
        QS("qs23-2", "Jika tombol ini ditekan, pintunya terbuka.",
           "この ボタン を 押|お す と ドア が 開|あ きます", "たら とき"),
        QS("qs23-3", "Waktu kecil, saya sering berenang di sungai.",
           "子供|こども の とき よく 川|かわ で 泳|およ ぎました", "な と"),
    ],
)

BAB24 = CHAPTER(
    24, "手伝って くれますか。", "Bisakah Anda membantu saya?",
    bunpo=[
        BUNPO(
            "b24-1", "V てくれます — Orang Lain Melakukan untuk Saya",
            "[Orang] が [Kata Kerja bentuk て] くれます",
            [
                "〜てくれます = melakukan sesuatu UNTUK saya",
                "penerima manfaatnya adalah pembicara (tidak disebut)",
                "permintaan: 〜てくれませんか",
            ],
            "〜てくれます menyatakan bahwa orang lain melakukan sesuatu yang menguntungkan pembicara. "
            "Karena penerimanya sudah pasti pembicara, kata わたしに biasanya tidak disebut. Untuk "
            "meminta bantuan, dipakai 〜てくれませんか yang terasa lebih halus dari 〜てください.",
            [
                ("木村|きむら さん が 手伝|てつだ って くれました。", "Nona Kimura membantu saya."),
                ("ちょっと 手伝|てつだ って くれません か。", "Bisakah Anda membantu saya sedikit?"),
            ],
        ),
        BUNPO(
            "b24-2", "V てあげます — Saya Melakukan untuk Orang Lain",
            "[Orang] に [Kata Kerja bentuk て] あげます",
            [
                "〜てあげます = melakukan sesuatu untuk orang lain",
                "JANGAN dipakai kepada atasan (terasa merendahkan)",
                "kepada atasan: 〜ましょうか atau bentuk hormat",
            ],
            "〜てあげます menyatakan pembicara melakukan sesuatu untuk orang lain. Perlu kehati-hatian "
            "budaya: memakai pola ini kepada atasan terkesan menonjolkan kebaikan sendiri, sehingga "
            "lebih baik memakai 〜ましょうか saat menawarkan bantuan kepada atasan.",
            [
                ("わたし は 友達|ともだち に 本|ほん を 貸|か して あげました。",
                 "Saya meminjamkan buku kepada teman."),
                ("駅|えき まで 送|おく って あげます。", "Saya akan mengantar Anda sampai stasiun."),
            ],
        ),
        BUNPO(
            "b24-3", "V てもらいます — Saya Minta Dibantu",
            "[Orang] に [Kata Kerja bentuk て] もらいます",
            [
                "〜てもらいます = mendapat bantuan dari (atas permintaan saya)",
                "pemberinya ditandai に",
                "bedakan dari くれます yang inisiatifnya dari pemberi",
            ],
            "〜てもらいます menekankan bahwa pembicara menerima bantuan, biasanya karena pembicara "
            "memintanya. Bandingkan dengan 〜てくれます yang menekankan kebaikan si pemberi atas "
            "inisiatifnya sendiri.",
            [
                ("山田|やまだ さん に 日本語|にほんご を 教|おし えて もらいました。",
                 "Saya diajari bahasa Jepang oleh Pak Yamada."),
                ("友達|ともだち に 手伝|てつだ って もらいます。", "Saya minta dibantu oleh teman."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k24-1", "くれます", "くれます", "kuremasu", "memberi (kepada saya)", "Kata Kerja",
               ("木村|きむら さん が 手伝|てつだ って くれました。", "Nona Kimura membantu saya.")),
        KOTOBA("k24-2", "直します", "なおします", "naoshimasu", "memperbaiki", "Kata Kerja",
               ("自転車|じてんしゃ を 直|なお して くれました。", "Dia memperbaiki sepeda saya.")),
        KOTOBA("k24-3", "送ります", "おくります", "okurimasu", "mengirim; mengantar", "Kata Kerja",
               ("駅|えき まで 送|おく って あげます。", "Saya antar sampai stasiun.")),
        KOTOBA("k24-4", "連れて行きます", "つれていきます", "tsurete ikimasu", "membawa (orang) pergi", "Kata Kerja",
               ("子供|こども を 連|つ れて 行|い きます。", "Saya membawa anak saya pergi.")),
        KOTOBA("k24-5", "紹介します", "しょうかいします", "shōkai shimasu", "memperkenalkan", "Kata Kerja",
               ("友達|ともだち を 紹介|しょうかい して くれました。", "Dia memperkenalkan temannya kepada saya.")),
        KOTOBA("k24-6", "案内します", "あんないします", "annai shimasu", "memandu; menunjukkan", "Kata Kerja",
               ("町|まち を 案内|あんない して あげます。", "Saya akan memandu Anda di kota.")),
        KOTOBA("k24-7", "説明します", "せつめいします", "setsumei shimasu", "menjelaskan", "Kata Kerja",
               ("説明|せつめい して くれません か。", "Bisakah Anda menjelaskannya?")),
        KOTOBA("k24-8", "引っ越します", "ひっこします", "hikkoshimasu", "pindah rumah", "Kata Kerja",
               ("来月|らいげつ 引|ひ っ越|こ します。", "Bulan depan saya pindah rumah.")),
        KOTOBA("k24-9", "お祖父さん", "おじいさん", "ojiisan", "kakek", "Kata Benda",
               ("お祖父|おじい さん が 話|はな して くれました。", "Kakek bercerita kepada saya.")),
        KOTOBA("k24-10", "お祖母さん", "おばあさん", "obāsan", "nenek", "Kata Benda",
               ("お祖母|おばあ さん に 料理|りょうり を 教|おし えて もらいました。", "Saya diajari memasak oleh nenek.")),
        KOTOBA("k24-11", "自分", "じぶん", "jibun", "diri sendiri", "Kata Benda",
               ("自分|じぶん で します。", "Saya lakukan sendiri.")),
        KOTOBA("k24-12", "ごちそう", "ごちそう", "gochisō", "hidangan; jamuan", "Kata Benda",
               ("ごちそう を 作|つく って くれました。", "Dia membuatkan hidangan untuk saya.")),
        KOTOBA("k24-13", "地図", "ちず", "chizu", "peta", "Kata Benda",
               ("地図|ちず を かいて くれました。", "Dia menggambarkan peta untuk saya.")),
        KOTOBA("k24-14", "手伝います", "てつだいます", "tetsudaimasu", "membantu", "Kata Kerja",
               ("手伝|てつだ って くれません か。", "Bisakah Anda membantu?")),
    ],
    kanji=[
        KANJI("j24-1", "送", "ソウ", "おく(る)", "kirim; antar", 9,
              [("送ります", "おくります", "mengirim"), ("放送", "ほうそう", "siaran")]),
        KANJI("j24-2", "地", "チ・ジ", "—", "tanah; bumi", 6,
              [("地図", "ちず", "peta"), ("地下", "ちか", "bawah tanah")]),
        KANJI("j24-3", "図", "ズ・ト", "—", "gambar; diagram", 7,
              [("地図", "ちず", "peta"), ("図書館", "としょかん", "perpustakaan")]),
        KANJI("j24-4", "紹", "ショウ", "—", "memperkenalkan", 11,
              [("紹介", "しょうかい", "perkenalan")]),
        KANJI("j24-5", "説", "セツ", "と(く)", "menjelaskan; teori", 14,
              [("説明", "せつめい", "penjelasan"), ("小説", "しょうせつ", "novel")]),
    ],
    kaiwa=KAIWA(
        "手伝って くれますか — Bisakah Anda Membantu?",
        "Nona Karina meminta bantuan Pak Miller untuk pindah apartemen akhir pekan ini.",
        [
            ("カリナ", "Karina", "ミラーさん、 今週|こんしゅう の 日曜日|にちようび、 暇|ひま です か。",
             "Pak Miller, hari Minggu pekan ini senggang?"),
            ("ミラー", "Mirā", "はい、 暇|ひま です よ。", "Ya, senggang."),
            ("カリナ", "Karina", "実|じつ は 引|ひ っ越|こ しする ん です。 ちょっと 手伝|てつだ って くれません か。",
             "Sebenarnya saya mau pindah rumah. Bisakah Anda membantu sedikit?"),
            ("ミラー", "Mirā", "いい です よ。 車|くるま で 荷物|にもつ を 運|はこ んで あげます。",
             "Boleh. Saya akan angkut barangnya dengan mobil."),
            ("カリナ", "Karina", "ありがとう ございます。 ワンさん に も 手伝|てつだ って もらいます。",
             "Terima kasih banyak. Saya juga minta dibantu Nona Wang."),
            ("ミラー", "Mirā", "じゃ、 9時|くじ に 行|い きます。 地図|ちず を かいて くれません か。",
             "Baik, saya datang jam 9. Bisakah Anda gambarkan petanya?"),
        ],
    ),
    quiz_bunpo=[
        QB("qb24-1", "木村|きむら さん が 手伝|てつだ って ＿＿。", ["くれました", "あげました", "もらいました", "ました"], 0,
           "木村|きむら さん が 手伝|てつだ って くれました。", "くれました", "[Orang] が [bentuk て] くれます",
           "〜てくれます dipakai saat orang lain melakukan sesuatu UNTUK pembicara."),
        QB("qb24-2", "わたし は 友達|ともだち に 本|ほん を 貸|か して ＿＿。",
           ["あげました", "くれました", "もらいました", "ました"], 0,
           "わたし は 友達|ともだち に 本|ほん を 貸|か して あげました。", "あげました",
           "[Orang] に [bentuk て] あげます",
           "〜てあげます dipakai saat PEMBICARA melakukan sesuatu untuk orang lain."),
        QB("qb24-3", "山田|やまだ さん ＿＿ 日本語|にほんご を 教|おし えて もらいました。", ["に", "が", "を", "で"], 0,
           "山田|やまだ さん に 日本語|にほんご を 教|おし えて もらいました。", "に",
           "[Orang] に [bentuk て] もらいます",
           "Pada pola もらいます, orang yang memberi bantuan ditandai partikel に."),
        QB_ID("qb24-4", "“Bisakah Anda membantu saya sedikit?” (permintaan halus)",
              ["ちょっと 手伝って あげませんか。", "ちょっと 手伝って くれませんか。",
               "ちょっと 手伝って もらいます。", "ちょっと 手伝いましょうか。"], 1,
              "ちょっと 手伝|てつだ って くれません か。", "くれませんか", "[bentuk て] くれません か",
              "〜てくれませんか adalah permintaan bantuan yang lebih halus daripada 〜てください."),
    ],
    quiz_susun=[
        QS("qs24-1", "Nona Kimura membantu saya.", "木村|きむら さん が 手伝|てつだ って くれました", "あげました に"),
        QS("qs24-2", "Saya meminjamkan buku kepada teman.",
           "友達|ともだち に 本|ほん を 貸|か して あげました", "くれました が"),
        QS("qs24-3", "Saya diajari bahasa Jepang oleh Pak Yamada.",
           "山田|やまだ さん に 日本語|にほんご を 教|おし えて もらいました", "が くれました"),
    ],
)

BAB25 = CHAPTER(
    25, "もし 雨が 降ったら、 行きません。", "Kalau hujan, saya tidak pergi.",
    bunpo=[
        BUNPO(
            "b25-1", "V たら、〜 — Jika (Syarat)",
            "[bentuk た] ら、 [akibat]",
            [
                "〜たら = jika/kalau (syarat)",
                "dibentuk dari bentuk た + ら",
                "akibat BOLEH berupa keinginan, ajakan, atau permintaan",
                "sering diperkuat もし di awal",
            ],
            "〜たら menyatakan syarat dan lebih luwes daripada 〜と dari Bab 23: klausa akibatnya boleh "
            "berupa keinginan, permintaan, atau ajakan. Dibentuk dari bentuk た ditambah ら: 降った → "
            "降ったら. Kata もし di awal kalimat memperkuat nuansa pengandaian.",
            [
                ("もし 雨|あめ が 降|ふ ったら、 行|い きません。", "Kalau hujan, saya tidak pergi."),
                ("時間|じかん が あったら、 手伝|てつだ って ください。", "Kalau ada waktu, tolong bantu saya."),
                ("お金|おかね が あったら、 車|くるま を 買|か いたい です。",
                 "Kalau punya uang, saya ingin membeli mobil."),
            ],
        ),
        BUNPO(
            "b25-2", "Kata Sifat & Kata Benda + たら",
            "[Kata Sifat-i] かったら ／ [Kata Sifat-na/Kata Benda] だったら",
            [
                "安い → 安かったら",
                "暇 → 暇だったら",
                "学生 → 学生だったら",
            ],
            "Pola たら juga berlaku untuk kata sifat dan kata benda. Kata sifat-i mengubah い menjadi "
            "かったら, sedangkan kata sifat-na dan kata benda memakai だったら. Bentuknya mengikuti "
            "bentuk lampau biasa + ら.",
            [
                ("安|やす かったら、 買|か います。", "Kalau murah, saya beli."),
                ("暇|ひま だったら、 映画|えいが を 見|み ましょう。", "Kalau senggang, mari menonton film."),
            ],
        ),
        BUNPO(
            "b25-3", "V ても、〜 — Meskipun",
            "[bentuk て] も、 [kalimat]",
            [
                "〜ても = meskipun; walaupun",
                "kata sifat-i: 安|やす くても",
                "kata sifat-na/kata benda: 暇|ひま でも",
                "akibatnya bertentangan dengan harapan",
            ],
            "〜ても menyatakan bahwa hasilnya tetap sama meskipun syaratnya terpenuhi — makna "
            "berlawanan dengan たら. Bentuknya sama dengan bentuk て ditambah も: 雨が 降っても 行きます "
            "(“meskipun hujan, saya tetap pergi”).",
            [
                ("雨|あめ が 降|ふ っても、 行|い きます。", "Meskipun hujan, saya tetap pergi."),
                ("安|やす くても、 買|か いません。", "Meskipun murah, saya tidak beli."),
                ("日曜日|にちようび でも、 働|はたら きます。", "Meskipun hari Minggu, saya tetap bekerja."),
            ],
        ),
        BUNPO(
            "b25-4", "〜たら、どうしますか — Pengandaian & Saran",
            "もし [bentuk た] ら、 どう します か",
            [
                "menanyakan tindakan dalam situasi andai",
                "sering dipakai untuk memberi saran: 〜たら どうですか",
                "〜たらいいです = sebaiknya …",
            ],
            "Selain menyatakan syarat, pola たら dipakai untuk menanyakan atau menyarankan tindakan "
            "dalam situasi tertentu. 〜たら どうですか adalah cara halus memberi saran, mirip "
            "“bagaimana kalau …?” dalam Bahasa Indonesia.",
            [
                ("もし 1億円|いちおくえん あったら、 どう します か。",
                 "Kalau punya 100 juta yen, Anda mau melakukan apa?"),
                ("医者|いしゃ に 見|み せたら どう です か。", "Bagaimana kalau diperiksakan ke dokter?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k25-1", "もし", "もし", "moshi", "kalau; seandainya", "Kata Keterangan",
               ("もし 雨|あめ が 降|ふ ったら、 行|い きません。", "Kalau hujan, saya tidak pergi.")),
        KOTOBA("k25-2", "たら", "たら", "tara", "jika (akhiran syarat)", "Ungkapan",
               ("時間|じかん が あったら、 手伝|てつだ って ください。", "Kalau ada waktu, tolong bantu.")),
        KOTOBA("k25-3", "考えます", "かんがえます", "kangaemasu", "berpikir; mempertimbangkan", "Kata Kerja",
               ("よく 考|かんが えて ください。", "Tolong pikirkan dengan matang.")),
        KOTOBA("k25-4", "着きます", "つきます", "tsukimasu", "tiba", "Kata Kerja",
               ("駅|えき に 着|つ いたら、 電話|でんわ します。", "Kalau sudah tiba di stasiun, saya telepon.")),
        KOTOBA("k25-5", "辞めます", "やめます", "yamemasu", "berhenti (dari pekerjaan)", "Kata Kerja",
               ("会社|かいしゃ を 辞|や めます。", "Saya berhenti dari perusahaan.")),
        KOTOBA("k25-6", "続けます", "つづけます", "tsuzukemasu", "melanjutkan", "Kata Kerja",
               ("勉強|べんきょう を 続|つづ けます。", "Saya melanjutkan belajar.")),
        KOTOBA("k25-7", "億", "おく", "oku", "seratus juta", "Satuan",
               ("1億円|いちおくえん あったら、 どう します か。", "Kalau punya 100 juta yen, mau apa?")),
        KOTOBA("k25-8", "生活", "せいかつ", "seikatsu", "kehidupan", "Kata Benda",
                       ("日本|にほん の 生活|せいかつ は 楽|たの しい です。", "Kehidupan di Jepang menyenangkan.")),
        KOTOBA("k25-9", "文化", "ぶんか", "bunka", "budaya", "Kata Benda",
               ("日本|にほん の 文化|ぶんか に ついて 勉強|べんきょう します。", "Saya belajar tentang budaya Jepang.")),
        KOTOBA("k25-10", "社会", "しゃかい", "shakai", "masyarakat", "Kata Benda",
               ("社会|しゃかい の 問題|もんだい です。", "Ini masalah masyarakat.")),
        KOTOBA("k25-11", "気持ち", "きもち", "kimochi", "perasaan", "Kata Benda",
               ("気持|きも ち が いい です。", "Perasaannya nyaman.")),
        KOTOBA("k25-12", "思い出", "おもいで", "omoide", "kenangan", "Kata Benda",
               ("いい 思|おも い出|で に なりました。", "Menjadi kenangan yang indah.")),
        KOTOBA("k25-13", "一生懸命", "いっしょうけんめい", "isshōkenmei", "sekuat tenaga", "Kata Keterangan",
               ("一生懸命|いっしょうけんめい 働|はたら きます。", "Saya bekerja sekuat tenaga.")),
        KOTOBA("k25-14", "残ります", "のこります", "nokorimasu", "tinggal; tersisa", "Kata Kerja",
               ("日本|にほん に 残|のこ りたい です。", "Saya ingin tetap tinggal di Jepang.")),
    ],
    kanji=[
        KANJI("j25-1", "考", "コウ", "かんが(える)", "berpikir", 6,
              [("考えます", "かんがえます", "berpikir"), ("参考", "さんこう", "referensi")]),
        KANJI("j25-2", "文", "ブン", "ふみ", "tulisan; kalimat", 4,
              [("文化", "ぶんか", "budaya"), ("文章", "ぶんしょう", "karangan")]),
        KANJI("j25-3", "化", "カ", "—", "berubah menjadi", 4,
              [("文化", "ぶんか", "budaya"), ("変化", "へんか", "perubahan")]),
        KANJI("j25-4", "社", "シャ", "—", "masyarakat; perusahaan", 7,
              [("社会", "しゃかい", "masyarakat"), ("会社", "かいしゃ", "perusahaan")]),
        KANJI("j25-5", "生", "セイ", "い(きる)・う(まれる)", "hidup", 5,
              [("生活", "せいかつ", "kehidupan"), ("学生", "がくせい", "mahasiswa")]),
        KANJI("j25-6", "活", "カツ", "—", "hidup; aktif", 9,
              [("生活", "せいかつ", "kehidupan"), ("活動", "かつどう", "kegiatan")]),
    ],
    kaiwa=KAIWA(
        "いろいろ お世話に なりました — Terima Kasih atas Segala Bantuannya",
        "Pak Miller akan pindah tugas dan berpamitan kepada Pak Yamada serta rekan sekantor.",
        [
            ("ミラー", "Mirā", "山田|やまだ さん、 いろいろ お世話|おせわ に なりました。",
             "Pak Yamada, terima kasih atas segala bantuannya."),
            ("山田", "Yamada", "いいえ。 東京|とうきょう に 着|つ いたら、 電話|でんわ を ください。",
             "Tidak apa-apa. Kalau sudah tiba di Tokyo, tolong telepon saya."),
            ("ミラー", "Mirā", "はい。 ときどき 大阪|おおさか に 来|き ます から、 また 会|あ いましょう。",
             "Baik. Karena saya kadang datang ke Osaka, mari bertemu lagi."),
            ("山田", "Yamada", "ええ。 忙|いそが しくても、 ぜひ 連絡|れんらく して ください。",
             "Ya. Meskipun sibuk, tolong tetap hubungi saya."),
            ("ミラー", "Mirā", "日本|にほん の 生活|せいかつ は いい 思|おも い出|で に なりました。",
             "Kehidupan di Jepang menjadi kenangan yang indah."),
            ("山田", "Yamada", "お元気|おげんき で。 体|からだ に 気|き を つけて ください。",
             "Jaga kesehatan. Tolong hati-hati dengan kondisi tubuh Anda."),
        ],
    ),
    quiz_bunpo=[
        QB("qb25-1", "もし 雨|あめ が 降|ふ ＿＿、 行|い きません。", ["ったら", "ると", "って", "りたら"], 0,
           "もし 雨|あめ が 降|ふ ったら、 行|い きません。", "降ったら", "[bentuk た] ら、[akibat]",
           "〜たら dibentuk dari bentuk た + ら: 降ります → 降った → 降ったら."),
        QB("qb25-2", "安|やす ＿＿、 買|か います。", ["かったら", "いたら", "くたら", "いだったら"], 0,
           "安|やす かったら、 買|か います。", "安かったら", "[Kata Sifat-i] かったら",
           "Kata sifat-i mengubah い menjadi かったら. Kata sifat-na dan kata benda memakai だったら."),
        QB("qb25-3", "雨|あめ が 降|ふ ＿＿、 行|い きます。", ["っても", "ったら", "ると", "って"], 0,
           "雨|あめ が 降|ふ っても、 行|い きます。", "降っても", "[bentuk て] も、〜",
           "〜ても berarti “meskipun” — hasilnya tetap sama walau syaratnya terpenuhi."),
        QB("qb25-4", "暇|ひま ＿＿、 映画|えいが を 見|み ましょう。", ["だったら", "かったら", "たら", "のたら"], 0,
           "暇|ひま だったら、 映画|えいが を 見|み ましょう。", "暇だったら", "[Kata Sifat-na] だったら",
           "暇 adalah kata sifat-na sehingga memakai だったら, bukan かったら."),
        QB_ID("qb25-5", "“Bagaimana kalau diperiksakan ke dokter?” (memberi saran)",
              ["医者に 見せても いいですか。", "医者に 見せたら どうですか。",
               "医者に 見せなければ なりません。", "医者に 見せると いいです。"], 1,
              "医者|いしゃ に 見|み せたら どう です か。", "見せたら", "[bentuk た] ら どう です か",
              "〜たら どうですか adalah cara halus memberi saran."),
    ],
    quiz_susun=[
        QS("qs25-1", "Kalau hujan, saya tidak pergi.", "もし 雨|あめ が 降|ふ ったら 行|い きません", "っても ると"),
        QS("qs25-2", "Meskipun hujan, saya tetap pergi.", "雨|あめ が 降|ふ っても 行|い きます", "ったら と"),
        QS("qs25-3", "Kalau ada waktu, tolong bantu saya.",
           "時間|じかん が あったら 手伝|てつだ って ください", "あっても ある"),
    ],
)

CHAPTERS = [BAB18, BAB19, BAB20, BAB21, BAB22, BAB23, BAB24, BAB25]
