"""Materi Minna no Nihongo 1 — Bab 10 s/d 17."""

from seed_data.dsl import BUNPO, CHAPTER, KAIWA, KANJI, KOTOBA, QB, QB_ID, QS

BAB10 = CHAPTER(
    10, "あそこに 交番が あります。", "Di sana ada pos polisi.",
    bunpo=[
        BUNPO(
            "b10-1", "N が あります/います — Keberadaan",
            "[Tempat] に [Kata Benda] が あります / います",
            [
                "あります = ada (BENDA & tumbuhan)",
                "います = ada (MAKHLUK HIDUP: orang, hewan)",
                "に = [Partikel] penanda lokasi keberadaan",
                "が = [Partikel] penanda subjek yang ada",
            ],
            "Bahasa Jepang membedakan “ada” menurut jenis subjeknya: あります untuk benda mati dan "
            "tumbuhan, います untuk manusia dan hewan. Lokasinya ditandai partikel に dan subjeknya "
            "ditandai が. Perhatikan bahwa に di sini menandai KEBERADAAN, berbeda dari で yang "
            "menandai tempat aktivitas (Bab 6).",
            [
                ("あそこ に 交番|こうばん が あります。", "Di sana ada pos polisi."),
                ("部屋|へや に 猫|ねこ が います。", "Di kamar ada kucing."),
                ("庭|にわ に 木|き が あります。", "Di halaman ada pohon."),
            ],
        ),
        BUNPO(
            "b10-2", "N は [Tempat] に あります/います — Topik Dibalik",
            "[Kata Benda] は [Tempat] に あります / います",
            [
                "pola ini menjadikan bendanya sebagai TOPIK (は)",
                "dipakai saat menjawab “di mana X?”",
                "bandingkan: 〜に 〜が あります (memperkenalkan yang ada)",
            ],
            "Kedua pola ini sama-sama benar tetapi fokusnya berbeda. Pola 〜に 〜が あります "
            "memperkenalkan sesuatu yang baru (“di sana ada pos polisi”), sedangkan 〜は 〜に あります "
            "menjawab pertanyaan tentang benda yang sudah diketahui (“pos polisinya ada di sana”).",
            [
                ("交番|こうばん は あそこ に あります。", "Pos polisinya ada di sana."),
                ("山田|やまだ さん は 事務所|じむしょ に います。", "Pak Yamada ada di kantor."),
                ("かぎ は かばん の 中|なか に あります。", "Kuncinya ada di dalam tas."),
            ],
        ),
        BUNPO(
            "b10-3", "N1 の 上/下/前/後ろ/中/となり — Kata Penunjuk Posisi",
            "[Kata Benda] の [上/下/前/後ろ/中/となり/近く]",
            [
                "上|うえ = atas, 下|した = bawah",
                "前|まえ = depan, 後|うし ろ = belakang",
                "中|なか = dalam, となり = sebelah",
                "近|ちか く = dekat, 間|あいだ = antara",
            ],
            "Kata posisi dalam Bahasa Jepang berupa kata benda, sehingga harus dihubungkan dengan の: "
            "つくえの 上 (“atas meja”). Urutannya kebalikan dari Bahasa Indonesia. Untuk “antara A dan "
            "B” dipakai pola AとBの 間.",
            [
                ("つくえ の 上|うえ に 本|ほん が あります。", "Di atas meja ada buku."),
                ("銀行|ぎんこう の となり に 郵便局|ゆうびんきょく が あります。", "Di sebelah bank ada kantor pos."),
                ("いす の 下|した に 猫|ねこ が います。", "Di bawah kursi ada kucing."),
            ],
        ),
        BUNPO(
            "b10-4", "N や N — Penyebutan Sebagian",
            "[Kata Benda] や [Kata Benda] （など）",
            [
                "や = dan (menyebut SEBAGIAN contoh)",
                "と = dan (menyebut SELURUH daftar)",
                "など = dan lain-lain",
            ],
            "Perbedaan や dan と penting: と menyebut daftar lengkap (“hanya A dan B”), sedangkan や "
            "menyebut beberapa contoh dari daftar yang lebih panjang (“A, B, dan sebagainya”). "
            "Sering ditutup dengan など untuk menegaskan bahwa masih ada yang lain.",
            [
                ("箱|はこ の 中|なか に 手紙|てがみ や 写真|しゃしん が あります。",
                 "Di dalam kotak ada surat, foto, dan lain-lain."),
                ("教室|きょうしつ に 先生|せんせい と 学生|がくせい が います。",
                 "Di ruang kelas ada guru dan mahasiswa (hanya mereka)."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k10-1", "あります", "あります", "arimasu", "ada (benda)", "Kata Kerja",
               ("つくえ の 上|うえ に 本|ほん が あります。", "Di atas meja ada buku.")),
        KOTOBA("k10-2", "います", "います", "imasu", "ada (makhluk hidup)", "Kata Kerja",
               ("部屋|へや に 猫|ねこ が います。", "Di kamar ada kucing.")),
        KOTOBA("k10-3", "上", "うえ", "ue", "atas", "Kata Benda Posisi",
               ("つくえ の 上|うえ に あります。", "Ada di atas meja.")),
        KOTOBA("k10-4", "下", "した", "shita", "bawah", "Kata Benda Posisi",
               ("いす の 下|した に います。", "Ada di bawah kursi.")),
        KOTOBA("k10-5", "前", "まえ", "mae", "depan", "Kata Benda Posisi",
               ("駅|えき の 前|まえ に あります。", "Ada di depan stasiun.")),
        KOTOBA("k10-6", "後ろ", "うしろ", "ushiro", "belakang", "Kata Benda Posisi",
               ("建物|たてもの の 後|うし ろ に あります。", "Ada di belakang gedung.")),
        KOTOBA("k10-7", "中", "なか", "naka", "dalam", "Kata Benda Posisi",
               ("かばん の 中|なか に あります。", "Ada di dalam tas.")),
        KOTOBA("k10-8", "となり", "となり", "tonari", "sebelah", "Kata Benda Posisi",
               ("銀行|ぎんこう の となり に あります。", "Ada di sebelah bank.")),
        KOTOBA("k10-9", "近く", "ちかく", "chikaku", "dekat", "Kata Benda Posisi",
               ("駅|えき の 近|ちか く に あります。", "Ada di dekat stasiun.")),
        KOTOBA("k10-10", "交番", "こうばん", "kōban", "pos polisi", "Kata Benda",
               ("あそこ に 交番|こうばん が あります。", "Di sana ada pos polisi.")),
        KOTOBA("k10-11", "建物", "たてもの", "tatemono", "bangunan", "Kata Benda",
               ("大|おお きい 建物|たてもの が あります。", "Ada bangunan besar.")),
        KOTOBA("k10-12", "部屋", "へや", "heya", "kamar", "Kata Benda",
               ("部屋|へや に だれ が います か。", "Di kamar ada siapa?")),
        KOTOBA("k10-13", "猫", "ねこ", "neko", "kucing", "Kata Benda",
               ("いす の 下|した に 猫|ねこ が います。", "Di bawah kursi ada kucing.")),
        KOTOBA("k10-14", "犬", "いぬ", "inu", "anjing", "Kata Benda",
               ("庭|にわ に 犬|いぬ が います。", "Di halaman ada anjing.")),
        KOTOBA("k10-15", "木", "き", "ki", "pohon; kayu", "Kata Benda",
               ("庭|にわ に 木|き が あります。", "Di halaman ada pohon.")),
        KOTOBA("k10-16", "写真", "しゃしん", "shashin", "foto", "Kata Benda",
               ("箱|はこ の 中|なか に 写真|しゃしん が あります。", "Di dalam kotak ada foto.")),
        KOTOBA("k10-17", "や", "や", "ya", "dan (sebagian)", "Partikel",
               ("手紙|てがみ や 写真|しゃしん が あります。", "Ada surat, foto, dan lain-lain.")),
        KOTOBA("k10-18", "いろいろ", "いろいろ", "iroiro", "beragam", "Kata Sifat-na",
               ("いろいろ な 人|ひと が います。", "Ada beragam orang.")),
    ],
    kanji=[
        KANJI("j10-1", "前", "ゼン", "まえ", "depan; sebelum", 9,
              [("前", "まえ", "depan"), ("午前", "ごぜん", "pagi")]),
        KANJI("j10-2", "後", "ゴ・コウ", "あと・うし(ろ)", "belakang; sesudah", 9,
              [("後ろ", "うしろ", "belakang"), ("午後", "ごご", "siang-sore")]),
        KANJI("j10-3", "右", "ウ・ユウ", "みぎ", "kanan", 5,
              [("右", "みぎ", "kanan"), ("左右", "さゆう", "kanan-kiri")]),
        KANJI("j10-4", "左", "サ", "ひだり", "kiri", 5,
              [("左", "ひだり", "kiri"), ("左手", "ひだりて", "tangan kiri")]),
        KANJI("j10-5", "近", "キン", "ちか(い)", "dekat", 7,
              [("近く", "ちかく", "dekat"), ("最近", "さいきん", "belakangan ini")]),
    ],
    kaiwa=KAIWA(
        "ソースは ありませんか — Apakah Ada Saus?",
        "Nona Wang dan Nona Watt berbincang di supermarket mencari saus khas negara asal.",
        [
            ("ワン", "Wan", "すみません。 チリソース は ありません か。", "Permisi. Apakah ada saus cabai?"),
            ("店員", "Ten'in", "はい。 あちら の 右|みぎ に あります。", "Ada. Di sebelah kanan sana."),
            ("ワン", "Wan", "ありがとう ございます。 それから、 みそ は どこ です か。",
             "Terima kasih. Kemudian, miso di mana?"),
            ("店員", "Ten'in", "みそ は 冷蔵庫|れいぞうこ の 中|なか に あります。", "Miso ada di dalam kulkas."),
            ("ワン", "Wan", "分|わ かりました。 どうも。", "Saya mengerti. Terima kasih."),
        ],
    ),
    quiz_bunpo=[
        QB("qb10-1", "部屋|へや に 猫|ねこ が ＿＿。", ["います", "あります", "です", "いです"], 0,
           "部屋|へや に 猫|ねこ が います。", "います", "[Tempat] に [Makhluk hidup] が います",
           "います untuk makhluk hidup (orang & hewan), あります untuk benda mati dan tumbuhan."),
        QB("qb10-2", "つくえ の 上|うえ に 本|ほん が ＿＿。", ["あります", "います", "です", "ます"], 0,
           "つくえ の 上|うえ に 本|ほん が あります。", "あります", "[Tempat] に [Benda] が あります",
           "本 adalah benda mati sehingga memakai あります."),
        QB("qb10-3", "銀行|ぎんこう ＿＿ となり に 郵便局|ゆうびんきょく が あります。", ["の", "に", "で", "は"], 0,
           "銀行|ぎんこう の となり に 郵便局|ゆうびんきょく が あります。", "の", "[Kata Benda] の [Posisi]",
           "Kata posisi seperti となり berupa kata benda, jadi dihubungkan dengan の."),
        QB("qb10-4", "箱|はこ の 中|なか に 手紙|てがみ ＿＿ 写真|しゃしん が あります。", ["や", "と", "も", "に"], 0,
           "箱|はこ の 中|なか に 手紙|てがみ や 写真|しゃしん が あります。", "や", "[N] や [N]（など）",
           "や menyebut sebagian contoh (“dan lain-lain”), sedangkan と menyebut daftar yang lengkap."),
    ],
    quiz_susun=[
        QS("qs10-1", "Di sana ada pos polisi.", "あそこ に 交番|こうばん が あります", "います の"),
        QS("qs10-2", "Di bawah kursi ada kucing.", "いす の 下|した に 猫|ねこ が います", "あります を"),
        QS("qs10-3", "Kuncinya ada di dalam tas.", "かぎ は かばん の 中|なか に あります", "います が"),
    ],
)

BAB11 = CHAPTER(
    11, "会議室に いすが 7つ あります。", "Di ruang rapat ada 7 kursi.",
    bunpo=[
        BUNPO(
            "b11-1", "Kata Bilangan 〜つ — Penghitung Benda Umum",
            "[Kata Benda] を [angka]つ [Kata Kerja]",
            [
                "1つ|ひとつ, 2つ|ふたつ, 3つ|みっつ, 4つ|よっつ, 5つ|いつつ",
                "6つ|むっつ, 7つ|ななつ, 8つ|やっつ, 9つ|ここのつ, 10|とお",
                "dari 11 ke atas memakai angka biasa + 個|こ",
            ],
            "Penghitung 〜つ dipakai untuk benda umum yang tidak punya penghitung khusus (buah, kue, "
            "kursi, dan sebagainya). Bacaannya tidak beraturan dan wajib dihafal dari ひとつ sampai "
            "とお. Kata bilangan diletakkan setelah objek + を, atau setelah が pada pola keberadaan.",
            [
                ("りんご を 3|みっ つ 買|か いました。", "Saya membeli 3 buah apel."),
                ("会議室|かいぎしつ に いす が 7|なな つ あります。", "Di ruang rapat ada 7 kursi."),
            ],
        ),
        BUNPO(
            "b11-2", "Penghitung Khusus — 人・台・枚・冊・本",
            "[Kata Benda] が [angka][penghitung] あります/います",
            [
                "〜人|にん = orang (1人|ひとり, 2人|ふたり, 3人|さんにん)",
                "〜台|だい = mesin, mobil, elektronik",
                "〜枚|まい = benda tipis (kertas, kaus, tiket)",
                "〜冊|さつ = buku, majalah",
                "〜本|ほん = benda panjang (pulpen, botol)",
            ],
            "Bahasa Jepang punya penghitung berbeda menurut bentuk atau jenis benda. Perhatikan "
            "bacaan tidak beraturan: 1人 = ひとり, 2人 = ふたり, 1本 = いっぽん, 3本 = さんぼん, "
            "1枚 = いちまい, 1冊 = いっさつ. Memilih penghitung yang tepat adalah bagian penting dari "
            "kefasihan.",
            [
                ("外国人|がいこくじん の 学生|がくせい が 2人|ふたり います。", "Ada 2 mahasiswa asing."),
                ("車|くるま が 3台|さんだい あります。", "Ada 3 mobil."),
                ("切手|きって を 5枚|ごまい ください。", "Tolong berikan 5 lembar meterai."),
            ],
        ),
        BUNPO(
            "b11-3", "〜に 〜回 — Frekuensi dalam Periode",
            "[Periode] に [angka]回|かい [Kata Kerja]",
            [
                "〜回|かい = kali (frekuensi)",
                "periode + に: 1週間|いっしゅうかん に, 1か月|いっかげつ に",
                "pola: 1週間に 2回 = dua kali seminggu",
            ],
            "Untuk menyatakan frekuensi, periode waktunya diberi partikel に lalu diikuti jumlah kali. "
            "Urutannya periode dulu, frekuensi kemudian: 1週間に 2回 映画を 見ます (“saya menonton "
            "film dua kali seminggu”).",
            [
                ("1か月|いっかげつ に 2回|にかい 映画|えいが を 見|み ます。", "Saya menonton film 2 kali sebulan."),
                ("1年|いちねん に 1回|いっかい 国|くに へ 帰|かえ ります。", "Saya pulang ke negara saya setahun sekali."),
            ],
        ),
        BUNPO(
            "b11-4", "〜ぐらい・〜だけ・どのくらい",
            "[Jumlah] ぐらい / だけ ／ どのくらい",
            [
                "ぐらい = kira-kira (jumlah/waktu)",
                "だけ = hanya",
                "どのくらい = berapa lama / berapa banyak",
            ],
            "ぐらい (juga くらい) menyatakan perkiraan dan diletakkan setelah jumlahnya: 30分ぐらい "
            "(“kira-kira 30 menit”). だけ berarti “hanya” dan juga diletakkan setelah jumlah. Untuk "
            "menanyakan durasi atau kuantitas secara umum digunakan どのくらい.",
            [
                ("駅|えき まで 30分|さんじゅっぷん ぐらい かかります。", "Sampai stasiun memakan waktu kira-kira 30 menit."),
                ("1つ|ひとつ だけ 買|か いました。", "Saya hanya membeli satu."),
                ("どのくらい 日本|にほん に います か。", "Berapa lama Anda tinggal di Jepang?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k11-1", "一つ", "ひとつ", "hitotsu", "satu buah", "Kata Bilangan",
               ("りんご を 一つ|ひとつ ください。", "Tolong satu apel.")),
        KOTOBA("k11-2", "二つ", "ふたつ", "futatsu", "dua buah", "Kata Bilangan",
               ("ケーキ を 二つ|ふたつ 買|か いました。", "Saya membeli dua kue.")),
        KOTOBA("k11-3", "一人", "ひとり", "hitori", "satu orang", "Kata Bilangan",
               ("学生|がくせい が 一人|ひとり います。", "Ada satu mahasiswa.")),
        KOTOBA("k11-4", "二人", "ふたり", "futari", "dua orang", "Kata Bilangan",
               ("子供|こども が 二人|ふたり います。", "Saya punya dua anak.")),
        KOTOBA("k11-5", "台", "だい", "dai", "penghitung mesin/mobil", "Satuan",
               ("車|くるま が 3台|さんだい あります。", "Ada 3 mobil.")),
        KOTOBA("k11-6", "枚", "まい", "mai", "penghitung benda tipis", "Satuan",
               ("切手|きって を 5枚|ごまい ください。", "Tolong 5 lembar meterai.")),
        KOTOBA("k11-7", "冊", "さつ", "satsu", "penghitung buku", "Satuan",
               ("本|ほん を 2冊|にさつ 借|か りました。", "Saya meminjam 2 buku.")),
        KOTOBA("k11-8", "回", "かい", "kai", "kali (frekuensi)", "Satuan",
               ("1か月|いっかげつ に 2回|にかい 行|い きます。", "Saya pergi 2 kali sebulan.")),
        KOTOBA("k11-9", "ぐらい", "ぐらい", "gurai", "kira-kira", "Kata Keterangan",
               ("30分|さんじゅっぷん ぐらい かかります。", "Memakan waktu kira-kira 30 menit.")),
        KOTOBA("k11-10", "だけ", "だけ", "dake", "hanya", "Partikel",
               ("一つ|ひとつ だけ 買|か いました。", "Saya hanya membeli satu.")),
        KOTOBA("k11-11", "どのくらい", "どのくらい", "dono kurai", "berapa lama", "Kata Tanya",
               ("どのくらい かかります か。", "Berapa lama waktunya?")),
        KOTOBA("k11-12", "かかります", "かかります", "kakarimasu", "memerlukan (waktu/biaya)", "Kata Kerja",
               ("1時間|いちじかん かかります。", "Memerlukan 1 jam.")),
        KOTOBA("k11-13", "切手", "きって", "kitte", "meterai; stempel pos", "Kata Benda",
               ("切手|きって を 買|か います。", "Saya membeli meterai.")),
        KOTOBA("k11-14", "封筒", "ふうとう", "fūtō", "amplop", "Kata Benda",
               ("封筒|ふうとう を 3枚|さんまい ください。", "Tolong 3 lembar amplop.")),
        KOTOBA("k11-15", "子供", "こども", "kodomo", "anak", "Kata Benda",
               ("子供|こども が 二人|ふたり います。", "Saya punya dua anak.")),
        KOTOBA("k11-16", "外国人", "がいこくじん", "gaikokujin", "orang asing", "Kata Benda",
               ("外国人|がいこくじん の 学生|がくせい が います。", "Ada mahasiswa asing.")),
        KOTOBA("k11-17", "兄弟", "きょうだい", "kyōdai", "saudara", "Kata Benda",
               ("兄弟|きょうだい が 何人|なんにん います か。", "Anda punya berapa saudara?")),
        KOTOBA("k11-18", "週間", "しゅうかん", "shūkan", "pekan; minggu (durasi)", "Satuan",
               ("1週間|いっしゅうかん に 2回|にかい です。", "Dua kali sepekan.")),
    ],
    kanji=[
        KANJI("j11-1", "人", "ジン・ニン", "ひと", "orang", 2,
              [("二人", "ふたり", "dua orang"), ("外国人", "がいこくじん", "orang asing")]),
        KANJI("j11-2", "回", "カイ", "まわ(る)", "kali; berputar", 6,
              [("一回", "いっかい", "satu kali"), ("回ります", "まわります", "berputar")]),
        KANJI("j11-3", "台", "ダイ", "—", "penghitung mesin; panggung", 5,
              [("一台", "いちだい", "satu unit"), ("台風", "たいふう", "taifun")]),
        KANJI("j11-4", "週", "シュウ", "—", "pekan", 11,
              [("今週", "こんしゅう", "pekan ini"), ("週間", "しゅうかん", "pekan (durasi)")]),
        KANJI("j11-5", "子", "シ", "こ", "anak", 3,
              [("子供", "こども", "anak"), ("女子", "じょし", "perempuan")]),
    ],
    kaiwa=KAIWA(
        "これ、お願いします — Tolong Ini",
        "Nona Karina mengirim paket di kantor pos dan menanyakan biaya serta lama pengiriman.",
        [
            ("カリナ", "Karina", "すみません。 これ、 オーストラリア まで お願|ねが いします。",
             "Permisi. Tolong kirim ini sampai Australia."),
            ("局員", "Kyokuin", "はい。 航空便|こうくうびん です か、 船便|ふなびん です か。",
             "Baik. Lewat pos udara atau kapal laut?"),
            ("カリナ", "Karina", "航空便|こうくうびん で いくら です か。", "Dengan pos udara berapa?"),
            ("局員", "Kyokuin", "7600円|ななせんろっぴゃくえん です。", "7.600 yen."),
            ("カリナ", "Karina", "どのくらい かかります か。", "Berapa lama waktunya?"),
            ("局員", "Kyokuin", "1週間|いっしゅうかん ぐらい です。", "Kira-kira satu pekan."),
            ("カリナ", "Karina", "じゃ、 それ を お願|ねが いします。 それから、 切手|きって を 5枚|ごまい ください。",
             "Baik, tolong yang itu. Lalu, tolong 5 lembar meterai."),
        ],
    ),
    quiz_bunpo=[
        QB("qb11-1", "りんご を ＿＿ 買|か いました。", ["三つ", "三枚", "三人", "三台"], 0,
           "りんご を 三つ|みっつ 買|か いました。", "三つ", "[Kata Benda] を [angka]つ [Kata Kerja]",
           "Buah memakai penghitung umum 〜つ. 枚 untuk benda tipis, 台 untuk mesin, 人 untuk orang."),
        QB("qb11-2", "学生|がくせい が ＿＿ います。", ["二人", "二つ", "二枚", "二台"], 0,
           "学生|がくせい が 二人|ふたり います。", "二人", "[Orang] が [angka]人 います",
           "Orang dihitung dengan 〜人. Hafalkan bacaan tidak beraturan: 1人=ひとり, 2人=ふたり."),
        QB("qb11-3", "車|くるま が 3 ＿＿ あります。", ["台", "枚", "つ", "冊"], 0,
           "車|くるま が 3台|さんだい あります。", "台", "[Mesin/mobil] が [angka]台 あります",
           "Mobil dan mesin dihitung dengan 〜台."),
        QB("qb11-4", "1か月|いっかげつ ＿＿ 2回|にかい 映画|えいが を 見|み ます。", ["に", "で", "は", "を"], 0,
           "1か月|いっかげつ に 2回|にかい 映画|えいが を 見|み ます。", "に", "[Periode] に [angka]回",
           "Periode waktunya diberi partikel に lalu diikuti frekuensi: 1か月に 2回."),
    ],
    quiz_susun=[
        QS("qs11-1", "Di ruang rapat ada 7 kursi.", "会議室|かいぎしつ に いす が 7|なな つ あります", "います 人"),
        QS("qs11-2", "Tolong berikan 5 lembar meterai.", "切手|きって を 5枚|ごまい ください", "つ 台"),
        QS("qs11-3", "Sampai stasiun kira-kira 30 menit.", "駅|えき まで 30分|さんじゅっぷん ぐらい かかります", "だけ に"),
    ],
)

BAB12 = CHAPTER(
    12, "きのうは 雨でした。", "Kemarin hujan.",
    bunpo=[
        BUNPO(
            "b12-1", "Bentuk Lampau Kata Benda & Kata Sifat-na",
            "[Kata Benda / Kata Sifat-na] でした / じゃありませんでした",
            [
                "〜でした = bentuk lampau sopan",
                "〜じゃありませんでした = lampau negatif",
                "berlaku untuk kata benda DAN kata sifat-na",
            ],
            "Kata benda dan kata sifat-na membentuk lampau dengan mengubah です menjadi でした, dan "
            "negatif lampaunya じゃありませんでした. Pola ini identik untuk keduanya karena kata "
            "sifat-na berperilaku seperti kata benda.",
            [
                ("きのう は 雨|あめ でした。", "Kemarin hujan."),
                ("旅行|りょこう は 楽|たの しかった です。", "Perjalanannya menyenangkan."),
                ("きのう は 暇|ひま じゃありませんでした。", "Kemarin saya tidak sempat (tidak senggang)."),
            ],
        ),
        BUNPO(
            "b12-2", "Bentuk Lampau Kata Sifat-i",
            "[Kata Sifat-i] い → かった です / くなかった です",
            [
                "高い → 高かった です (mahal → dulu mahal)",
                "negatif lampau: 高くなかった です",
                "PENGECUALIAN: いい → よかった です",
            ],
            "Kata sifat-i berubah pada akhirannya sendiri: い diganti menjadi かった untuk lampau, dan "
            "くなかった untuk lampau negatif. Perhatikan bahwa です tetap dipertahankan di belakang "
            "sebagai penanda sopan. Hafalkan pengecualian いい → よかったです.",
            [
                ("試験|しけん は 難|むずか しかった です。", "Ujiannya sulit."),
                ("天気|てんき は よくなかった です。", "Cuacanya tidak bagus."),
                ("料理|りょうり は おいしかった です。", "Masakannya lezat."),
            ],
        ),
        BUNPO(
            "b12-3", "N1 より N2 のほうが 〜 — Perbandingan Dua Hal",
            "[N1] より [N2] の ほう が [Kata Sifat] です",
            [
                "より = dibandingkan dengan",
                "〜のほうが = yang lebih …",
                "pertanyaan: N1と N2と どちらが 〜ですか",
            ],
            "Untuk membandingkan dua hal, pihak yang kalah ditandai より dan pihak yang lebih ditandai "
            "のほうが. Pertanyaan perbandingan memakai pola AとBと どちらが 〜ですか, dan jawabannya "
            "〜のほうが 〜です.",
            [
                ("電車|でんしゃ より バス の ほう が 安|やす い です。", "Bus lebih murah daripada kereta."),
                ("大阪|おおさか と 東京|とうきょう と どちら が にぎやか です か。",
                 "Antara Osaka dan Tokyo, mana yang lebih ramai?"),
            ],
        ),
        BUNPO(
            "b12-4", "N の中で 〜が いちばん 〜 — Paling",
            "[Kelompok] の 中|なか で [N] が いちばん [Kata Sifat] です",
            [
                "いちばん = paling",
                "の中で = di antara (kelompok)",
                "pertanyaan: 何|なに が いちばん 〜ですか",
            ],
            "いちばん menyatakan tingkat superlatif (“paling”). Kelompok pembandingnya dinyatakan "
            "dengan 〜の中で. Untuk kategori waktu atau tempat, kata tanyanya menyesuaikan: いつが, "
            "どこが, だれが いちばん 〜ですか.",
            [
                ("日本|にほん 料理|りょうり の 中|なか で すし が いちばん 好|す き です。",
                 "Di antara masakan Jepang, saya paling suka sushi."),
                ("1年|いちねん で いつ が いちばん 寒|さむ い です か。", "Dalam setahun, kapan yang paling dingin?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k12-1", "雨", "あめ", "ame", "hujan", "Kata Benda",
               ("きのう は 雨|あめ でした。", "Kemarin hujan.")),
        KOTOBA("k12-2", "雪", "ゆき", "yuki", "salju", "Kata Benda",
               ("北海道|ほっかいどう は 雪|ゆき が 多|おお い です。", "Di Hokkaido banyak salju.")),
        KOTOBA("k12-3", "天気", "てんき", "tenki", "cuaca", "Kata Benda",
               ("天気|てんき は よかった です。", "Cuacanya bagus.")),
        KOTOBA("k12-4", "旅行", "りょこう", "ryokō", "perjalanan; tamasya", "Kata Benda",
               ("旅行|りょこう は 楽|たの しかった です。", "Perjalanannya menyenangkan.")),
        KOTOBA("k12-5", "試験", "しけん", "shiken", "ujian", "Kata Benda",
               ("試験|しけん は 難|むずか しかった です。", "Ujiannya sulit.")),
        KOTOBA("k12-6", "楽しい", "たのしい", "tanoshii", "menyenangkan", "Kata Sifat-i",
               ("とても 楽|たの しかった です。", "Sangat menyenangkan.")),
        KOTOBA("k12-7", "暑い", "あつい", "atsui", "panas (udara)", "Kata Sifat-i",
               ("夏|なつ は 暑|あつ い です。", "Musim panas itu panas.")),
        KOTOBA("k12-8", "寒い", "さむい", "samui", "dingin (udara)", "Kata Sifat-i",
               ("冬|ふゆ は 寒|さむ い です。", "Musim dingin itu dingin.")),
        KOTOBA("k12-9", "忙しい", "いそがしい", "isogashii", "sibuk", "Kata Sifat-i",
               ("先週|せんしゅう は 忙|いそが しかった です。", "Pekan lalu saya sibuk.")),
        KOTOBA("k12-10", "暇", "ひま", "hima", "senggang; punya waktu", "Kata Sifat-na",
               ("あした は 暇|ひま です。", "Besok saya senggang.")),
        KOTOBA("k12-11", "より", "より", "yori", "dibandingkan dengan", "Partikel",
               ("バス より 電車|でんしゃ の ほう が 速|はや い です。", "Kereta lebih cepat daripada bus.")),
        KOTOBA("k12-12", "いちばん", "いちばん", "ichiban", "paling", "Kata Keterangan",
               ("すし が いちばん 好|す き です。", "Saya paling suka sushi.")),
        KOTOBA("k12-13", "ほう", "ほう", "hō", "sisi; pihak", "Kata Benda",
               ("こちら の ほう が いい です。", "Yang ini lebih baik.")),
        KOTOBA("k12-14", "夏", "なつ", "natsu", "musim panas", "Kata Benda",
               ("夏|なつ は 暑|あつ い です。", "Musim panas itu panas.")),
        KOTOBA("k12-15", "冬", "ふゆ", "fuyu", "musim dingin", "Kata Benda",
               ("冬|ふゆ は 寒|さむ い です。", "Musim dingin itu dingin.")),
        KOTOBA("k12-16", "季節", "きせつ", "kisetsu", "musim", "Kata Benda",
               ("どの 季節|きせつ が いちばん 好|す き です か。", "Musim mana yang paling Anda sukai?")),
        KOTOBA("k12-17", "祭り", "まつり", "matsuri", "festival", "Kata Benda",
               ("祭|まつ り は にぎやか でした。", "Festivalnya ramai.")),
        KOTOBA("k12-18", "どちら", "どちら", "dochira", "yang mana (dari dua)", "Kata Tanya",
               ("どちら が 安|やす い です か。", "Mana yang lebih murah?")),
    ],
    kanji=[
        KANJI("j12-1", "雨", "ウ", "あめ", "hujan", 8,
              [("雨", "あめ", "hujan"), ("大雨", "おおあめ", "hujan lebat")]),
        KANJI("j12-2", "天", "テン", "—", "langit", 4,
              [("天気", "てんき", "cuaca"), ("天国", "てんごく", "surga")]),
        KANJI("j12-3", "気", "キ", "—", "udara; perasaan", 6,
              [("天気", "てんき", "cuaca"), ("元気", "げんき", "sehat")]),
        KANJI("j12-4", "暑", "ショ", "あつ(い)", "panas (udara)", 12,
              [("暑い", "あつい", "panas"), ("暑中", "しょちゅう", "puncak musim panas")]),
        KANJI("j12-5", "寒", "カン", "さむ(い)", "dingin", 12,
              [("寒い", "さむい", "dingin"), ("寒気", "かんき", "hawa dingin")]),
        KANJI("j12-6", "旅", "リョ", "たび", "perjalanan", 10,
              [("旅行", "りょこう", "perjalanan"), ("旅館", "りょかん", "penginapan Jepang")]),
    ],
    kaiwa=KAIWA(
        "祇園祭は どうでしたか — Bagaimana Festival Gion?",
        "Nona Kimura bertanya kepada Pak Miller yang baru pulang dari festival Gion di Kyoto.",
        [
            ("木村", "Kimura", "ミラーさん、 祇園祭|ぎおんまつり は どう でした か。",
             "Pak Miller, bagaimana Festival Gion?"),
            ("ミラー", "Mirā", "とても おもしろかった です。", "Sangat menarik."),
            ("木村", "Kimura", "人|ひと が 多|おお かった です か。", "Orangnya banyak?"),
            ("ミラー", "Mirā", "はい、 とても にぎやか でした。 でも、 暑|あつ かった です。",
             "Ya, sangat ramai. Tapi panas sekali."),
            ("木村", "Kimura", "写真|しゃしん を 撮|と りました か。", "Anda mengambil foto?"),
            ("ミラー", "Mirā", "はい。 日本|にほん の 祭|まつ り の 中|なか で これ が いちばん 有名|ゆうめい です ね。",
             "Ya. Di antara festival Jepang, ini yang paling terkenal ya."),
        ],
    ),
    quiz_bunpo=[
        QB("qb12-1", "きのう は 雨|あめ ＿＿。", ["でした", "かったです", "でわない", "です"], 0,
           "きのう は 雨|あめ でした。", "でした", "[Kata Benda] でした",
           "Kata benda membentuk lampau dengan でした. かったです hanya untuk kata sifat-i."),
        QB("qb12-2", "試験|しけん は 難|むずか ＿＿ です。", ["しかった", "しいでした", "しくない", "しいかった"], 0,
           "試験|しけん は 難|むずか しかった です。", "しかった", "[Kata Sifat-i] い → かった です",
           "Kata sifat-i membentuk lampau dengan mengubah い menjadi かった: 難しい → 難しかったです."),
        QB("qb12-3", "電車|でんしゃ ＿＿ バス の ほう が 安|やす い です。", ["より", "から", "ほど", "まで"], 0,
           "電車|でんしゃ より バス の ほう が 安|やす い です。", "より", "[N1] より [N2] の ほう が 〜",
           "より menandai pihak pembanding yang “kalah”, dan のほうが menandai pihak yang lebih."),
        QB_ID("qb12-4", "“Cuacanya tidak bagus.” (bentuk lampau dari いい)",
              ["天気は いくなかったです。", "天気は よくなかったです。",
               "天気は いいじゃありませんでした。", "天気は よかったです。"], 1,
              "天気|てんき は よくなかった です。", "よくなかった", "いい → よかった / よくなかった です",
              "いい adalah pengecualian: lampaunya よかったです dan lampau negatifnya よくなかったです."),
        QB("qb12-5", "日本|にほん 料理|りょうり の 中|なか で すし が ＿＿ 好|す き です。",
           ["いちばん", "より", "ほう", "もっと"], 0,
           "日本|にほん 料理|りょうり の 中|なか で すし が いちばん 好|す き です。", "いちばん",
           "[Kelompok] の 中 で [N] が いちばん 〜",
           "いちばん menyatakan “paling”, dan kelompok pembandingnya ditandai 〜の中で."),
    ],
    quiz_susun=[
        QS("qs12-1", "Kemarin hujan.", "きのう は 雨|あめ でした", "です かった"),
        QS("qs12-2", "Ujiannya sulit.", "試験|しけん は 難|むずか しかった です", "でした じゃありません"),
        QS("qs12-3", "Bus lebih murah daripada kereta.", "電車|でんしゃ より バス の ほう が 安|やす い です", "いちばん から"),
    ],
)

BAB13 = CHAPTER(
    13, "わたしは 車が ほしいです。", "Saya ingin punya mobil.",
    bunpo=[
        BUNPO(
            "b13-1", "N が ほしいです — Menginginkan Benda",
            "[Kata Benda] が ほしい です",
            [
                "ほしい = [Kata Sifat-i] ingin punya",
                "objeknya ditandai が, bukan を",
                "negatif: ほしくない です",
                "TIDAK dipakai untuk keinginan orang ketiga secara langsung",
            ],
            "ほしい adalah kata sifat-i yang menyatakan keinginan memiliki suatu benda, dan objeknya "
            "ditandai が. Karena berupa kata sifat-i, negatifnya ほしくないです. Perlu diingat: pola ini "
            "hanya untuk menyatakan keinginan diri sendiri atau menanyakan keinginan lawan bicara.",
            [
                ("わたし は 車|くるま が ほしい です。", "Saya ingin punya mobil."),
                ("今|いま 何|なに が いちばん ほしい です か。", "Sekarang apa yang paling Anda inginkan?"),
                ("お金|おかね は ほしくない です。", "Saya tidak ingin uang."),
            ],
        ),
        BUNPO(
            "b13-2", "V たいです — Ingin Melakukan",
            "[Kata Kerja bentuk ます tanpa ます] + たい です",
            [
                "食べます → 食べたい です",
                "objek boleh ditandai を ATAU が",
                "negatif: 〜たくない です",
                "berperilaku seperti [Kata Sifat-i]",
            ],
            "Bentuk 〜たい dibuat dengan menghapus ます lalu menambahkan たい: 行きます → 行きたい. "
            "Hasilnya berperilaku sebagai kata sifat-i, sehingga lampaunya 〜たかったです dan negatifnya "
            "〜たくないです. Objeknya boleh ditandai を maupun が.",
            [
                ("わたし は 日本|にほん へ 行|い きたい です。", "Saya ingin pergi ke Jepang."),
                ("すし を 食|た べたい です。", "Saya ingin makan sushi."),
                ("今日|きょう は 何|なに も したくない です。", "Hari ini saya tidak ingin melakukan apa pun."),
            ],
        ),
        BUNPO(
            "b13-3", "N へ V に 行きます — Tujuan Perpindahan",
            "[Tempat] へ [Kata Kerja bentuk ます tanpa ます / Kata Benda] に 行|い きます",
            [
                "に di sini = untuk (tujuan/maksud)",
                "kata kerja: 買います → 買い に 行きます",
                "kata benda aktivitas: 買い物|かいもの に 行きます",
            ],
            "Untuk menyatakan pergi DENGAN TUJUAN melakukan sesuatu, dipakai pola [tempat]へ "
            "[kata kerja tanpa ます]に 行きます: デパートへ かばんを 買いに 行きます. Kata benda "
            "aktivitas seperti 買い物, 食事, 勉強 langsung diikuti に.",
            [
                ("デパート へ かばん を 買|か い に 行|い きます。", "Saya pergi ke department store untuk membeli tas."),
                ("日本|にほん へ 日本語|にほんご を 勉強|べんきょう し に 来|き ました。",
                 "Saya datang ke Jepang untuk belajar bahasa Jepang."),
                ("神戸|こうべ へ 食事|しょくじ に 行|い きます。", "Saya pergi ke Kobe untuk makan."),
            ],
        ),
        BUNPO(
            "b13-4", "どこか・何か — Kata Tanya + か",
            "どこ か / 何|なに か / だれ か",
            [
                "どこか = di suatu tempat / ke suatu tempat",
                "何か = sesuatu",
                "だれか = seseorang",
                "partikel を/へ sering DIHILANGKAN setelahnya",
            ],
            "Menambahkan か pada kata tanya mengubahnya menjadi bentuk tak tentu: どこか (“suatu "
            "tempat”), 何か (“sesuatu”), だれか (“seseorang”). Pada pola ini partikel を dan へ umumnya "
            "dihilangkan: 何か 食べたいです (bukan 何かを 食べたいです).",
            [
                ("何|なに か 飲|の みたい です。", "Saya ingin minum sesuatu."),
                ("どこ か へ 行|い きたい です。", "Saya ingin pergi ke suatu tempat."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k13-1", "ほしい", "ほしい", "hoshii", "ingin punya", "Kata Sifat-i",
               ("車|くるま が ほしい です。", "Saya ingin punya mobil.")),
        KOTOBA("k13-2", "疲れます", "つかれます", "tsukaremasu", "lelah", "Kata Kerja",
               ("とても 疲|つか れました。", "Saya sangat lelah.")),
        KOTOBA("k13-3", "結婚します", "けっこんします", "kekkon shimasu", "menikah", "Kata Kerja",
               ("来年|らいねん 結婚|けっこん します。", "Tahun depan saya menikah.")),
        KOTOBA("k13-4", "買い物", "かいもの", "kaimono", "berbelanja", "Kata Benda",
               ("買|か い物|もの に 行|い きます。", "Saya pergi berbelanja.")),
        KOTOBA("k13-5", "食事", "しょくじ", "shokuji", "makan; santap", "Kata Benda",
               ("食事|しょくじ に 行|い きましょう。", "Mari pergi makan.")),
        KOTOBA("k13-6", "散歩", "さんぽ", "sanpo", "jalan-jalan santai", "Kata Benda",
               ("公園|こうえん を 散歩|さんぽ します。", "Saya jalan-jalan di taman.")),
        KOTOBA("k13-7", "温泉", "おんせん", "onsen", "pemandian air panas", "Kata Benda",
               ("温泉|おんせん へ 行|い きたい です。", "Saya ingin pergi ke onsen.")),
        KOTOBA("k13-8", "海", "うみ", "umi", "laut", "Kata Benda",
               ("海|うみ で 泳|およ ぎたい です。", "Saya ingin berenang di laut.")),
        KOTOBA("k13-9", "泳ぎます", "およぎます", "oyogimasu", "berenang", "Kata Kerja",
               ("海|うみ で 泳|およ ぎます。", "Saya berenang di laut.")),
        KOTOBA("k13-10", "降ります", "ふります", "furimasu", "turun (hujan/salju)", "Kata Kerja",
               ("雨|あめ が 降|ふ ります。", "Hujan turun.")),
        KOTOBA("k13-11", "公園", "こうえん", "kōen", "taman", "Kata Benda",
               ("公園|こうえん へ 行|い きます。", "Saya pergi ke taman.")),
        KOTOBA("k13-12", "何か", "なにか", "nanika", "sesuatu", "Kata Ganti",
               ("何|なに か 食|た べたい です。", "Saya ingin makan sesuatu.")),
        KOTOBA("k13-13", "どこか", "どこか", "dokoka", "suatu tempat", "Kata Ganti",
               ("どこ か へ 行|い きたい です。", "Saya ingin pergi ke suatu tempat.")),
        KOTOBA("k13-14", "疲れた", "つかれた", "tsukareta", "lelah (bentuk biasa)", "Ungkapan",
               ("ああ、 疲|つか れた。", "Aduh, lelah.")),
        KOTOBA("k13-15", "そば", "そば", "soba", "mi soba", "Kata Benda",
               ("そば を 食|た べたい です。", "Saya ingin makan soba.")),
        KOTOBA("k13-16", "美術館", "びじゅつかん", "bijutsukan", "museum seni", "Kata Benda",
               ("美術館|びじゅつかん へ 行|い きました。", "Saya pergi ke museum seni.")),
        KOTOBA("k13-17", "キャンプ", "キャンプ", "kyanpu", "kemah", "Kata Benda",
               ("キャンプ に 行|い きたい です。", "Saya ingin pergi berkemah.")),
        KOTOBA("k13-18", "ぜひ", "ぜひ", "zehi", "sangat berharap; pasti", "Kata Keterangan",
               ("ぜひ 行|い きたい です。", "Saya sangat ingin pergi.")),
    ],
    kanji=[
        KANJI("j13-1", "海", "カイ", "うみ", "laut", 9,
              [("海", "うみ", "laut"), ("海外", "かいがい", "luar negeri")]),
        KANJI("j13-2", "物", "ブツ・モツ", "もの", "benda", 8,
              [("買い物", "かいもの", "berbelanja"), ("食べ物", "たべもの", "makanan")]),
        KANJI("j13-3", "事", "ジ", "こと", "hal; urusan", 8,
              [("食事", "しょくじ", "makan"), ("仕事", "しごと", "pekerjaan")]),
        KANJI("j13-4", "公", "コウ", "—", "umum; publik", 4,
              [("公園", "こうえん", "taman"), ("公開", "こうかい", "pembukaan untuk umum")]),
        KANJI("j13-5", "園", "エン", "—", "taman; kebun", 13,
              [("公園", "こうえん", "taman"), ("動物園", "どうぶつえん", "kebun binatang")]),
    ],
    kaiwa=KAIWA(
        "別々に お願いします — Tolong Dipisah",
        "Pak Miller dan Nona Sato memesan makan siang di restoran dan meminta bon dipisah.",
        [
            ("店員", "Ten'in", "いらっしゃいませ。 何|なに に なさいます か。",
             "Selamat datang. Anda ingin pesan apa?"),
            ("ミラー", "Mirā", "すみません。 わたし は 天ぷら|てんぷら 定食|ていしょく が ほしい です。",
             "Permisi. Saya ingin set makan tempura."),
            ("佐藤", "Satō", "わたし は そば を 食|た べたい です。", "Saya ingin makan soba."),
            ("店員", "Ten'in", "はい、 かしこまりました。", "Baik, mengerti."),
            ("ミラー", "Mirā", "すみません、 お勘定|おかんじょう を お願|ねが いします。",
             "Permisi, tolong bonnya."),
            ("店員", "Ten'in", "ご一緒|ごいっしょ です か。", "Dijadikan satu?"),
            ("ミラー", "Mirā", "いいえ、 別々|べつべつ に お願|ねが いします。", "Tidak, tolong dipisah."),
        ],
    ),
    quiz_bunpo=[
        QB("qb13-1", "わたし は 車|くるま ＿＿ ほしい です。", ["が", "を", "は", "に"], 0,
           "わたし は 車|くるま が ほしい です。", "が", "[Kata Benda] が ほしい です",
           "ほしい adalah kata sifat-i dan objek yang diinginkan ditandai が, bukan を."),
        QB("qb13-2", "わたし は 日本|にほん へ 行|い ＿＿ です。", ["きたい", "きます", "くたい", "きた"], 0,
           "わたし は 日本|にほん へ 行|い きたい です。", "きたい", "[V-ます tanpa ます] たい です",
           "Bentuk たい dibuat dengan menghapus ます lalu menambah たい: 行きます → 行きたい."),
        QB("qb13-3", "デパート へ かばん を 買|か い ＿＿ 行|い きます。", ["に", "へ", "で", "を"], 0,
           "デパート へ かばん を 買|か い に 行|い きます。", "に", "[V-ます tanpa ます] に 行きます",
           "に di sini menandai maksud/tujuan perbuatan, bukan waktu atau lokasi."),
        QB("qb13-4", "＿＿ 飲|の みたい です。", ["何か", "何を", "何が", "何も"], 0,
           "何|なに か 飲|の みたい です。", "何", "[Kata Tanya] + か",
           "何か berarti “sesuatu”, dan partikel を biasanya dihilangkan setelahnya."),
    ],
    quiz_susun=[
        QS("qs13-1", "Saya ingin punya mobil baru.", "新|あたら しい 車|くるま が ほしい です", "を たい"),
        QS("qs13-2", "Saya ingin makan sushi.", "すし を 食|た べたい です", "が ほしい"),
        QS("qs13-3", "Saya pergi ke department store untuk membeli tas.",
           "デパート へ かばん を 買|か い に 行|い きます", "で たい"),
    ],
)

BAB14 = CHAPTER(
    14, "ちょっと 待って ください。", "Tolong tunggu sebentar.",
    bunpo=[
        BUNPO(
            "b14-1", "Bentuk て (Te-form) — Perubahan Kata Kerja",
            "[Kata Kerja golongan I/II/III] → bentuk て",
            [
                "Golongan I: い/ち/り → って ； み/び/に → んで ； き → いて ； ぎ → いで ； し → して",
                "Golongan II: ます → て (食べます → 食べて)",
                "Golongan III: します → して ； 来ます → 来て",
                "PENGECUALIAN: 行きます → 行って (bukan 行いて)",
            ],
            "Bentuk て adalah kunci menuju banyak pola lanjutan, sehingga perubahannya wajib dikuasai. "
            "Kata kerja golongan I berubah menurut suku kata terakhir sebelum ます. Golongan II cukup "
            "mengganti ます dengan て. Hafalkan pengecualian penting: 行きます menjadi 行って.",
            [
                ("待|ま ちます → 待|ま って", "menunggu → bentuk te"),
                ("読|よ みます → 読|よ んで", "membaca → bentuk te"),
                ("食|た べます → 食|た べて", "makan → bentuk te"),
            ],
        ),
        BUNPO(
            "b14-2", "V てください — Permintaan Sopan",
            "[Kata Kerja bentuk て] ください",
            [
                "〜てください = tolong lakukan …",
                "bukan perintah kasar, tetapi permintaan sopan",
                "untuk menawarkan sesuatu juga dipakai: どうぞ 〜てください",
            ],
            "〜てください adalah cara standar meminta orang lain melakukan sesuatu dengan sopan. "
            "Meski sopan, pola ini tetap bernuansa instruksi, sehingga saat meminta tolong kepada "
            "atasan sering dilembutkan lagi menjadi 〜ていただけませんか (dipelajari kemudian).",
            [
                ("ちょっと 待|ま って ください。", "Tolong tunggu sebentar."),
                ("もう 一度|いちど 言|い って ください。", "Tolong katakan sekali lagi."),
                ("住所|じゅうしょ を 書|か いて ください。", "Tolong tuliskan alamatnya."),
            ],
        ),
        BUNPO(
            "b14-3", "V ています — Sedang Berlangsung",
            "[Kata Kerja bentuk て] います",
            [
                "〜ています = sedang melakukan (progresif)",
                "negatif: 〜ていません",
                "juga menyatakan keadaan yang berlanjut",
            ],
            "〜ています menyatakan perbuatan yang sedang berlangsung saat ini: 今 雨が 降っています "
            "(“sekarang sedang hujan”). Dengan kata kerja tertentu, pola ini juga menyatakan keadaan "
            "yang bertahan, misalnya 結婚しています (“sudah/sedang berstatus menikah”).",
            [
                ("今|いま 雨|あめ が 降|ふ って います。", "Sekarang sedang hujan."),
                ("ミラーさん は 電話|でんわ を かけて います。", "Pak Miller sedang menelepon."),
                ("今|いま 何|なに を して います か。", "Sekarang Anda sedang melakukan apa?"),
            ],
        ),
        BUNPO(
            "b14-4", "V ましょうか — Menawarkan Bantuan",
            "[Kata Kerja] ましょう か",
            [
                "〜ましょうか = maukah saya … (menawarkan bantuan)",
                "bedakan dari 〜ましょう (mari KITA)",
                "jawaban: はい、お願いします / いいえ、大丈夫です",
            ],
            "〜ましょうか dipakai saat pembicara MENAWARKAN diri melakukan sesuatu untuk orang lain: "
            "手伝いましょうか (“maukah saya bantu?”). Ini berbeda dari 〜ましょう yang mengajak "
            "melakukan sesuatu bersama-sama.",
            [
                ("手伝|てつだ いましょう か。", "Maukah saya bantu?"),
                ("エアコン を つけましょう か。", "Perlu saya nyalakan AC-nya?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k14-1", "待ちます", "まちます", "machimasu", "menunggu", "Kata Kerja",
               ("ちょっと 待|ま って ください。", "Tolong tunggu sebentar.")),
        KOTOBA("k14-2", "急ぎます", "いそぎます", "isogimasu", "bergegas", "Kata Kerja",
               ("急|いそ いで ください。", "Tolong cepat.")),
        KOTOBA("k14-3", "止めます", "とめます", "tomemasu", "menghentikan; memarkir", "Kata Kerja",
               ("ここ に 止|と めて ください。", "Tolong berhenti di sini.")),
        KOTOBA("k14-4", "曲がります", "まがります", "magarimasu", "berbelok", "Kata Kerja",
               ("右|みぎ へ 曲|ま がって ください。", "Tolong belok ke kanan.")),
        KOTOBA("k14-5", "貸します", "かします", "kashimasu", "meminjamkan", "Kata Kerja",
               ("ペン を 貸|か して ください。", "Tolong pinjamkan pulpen.")),
        KOTOBA("k14-6", "手伝います", "てつだいます", "tetsudaimasu", "membantu", "Kata Kerja",
               ("手伝|てつだ いましょう か。", "Maukah saya bantu?")),
        KOTOBA("k14-7", "つけます", "つけます", "tsukemasu", "menyalakan", "Kata Kerja",
               ("エアコン を つけて ください。", "Tolong nyalakan AC.")),
        KOTOBA("k14-8", "消します", "けします", "keshimasu", "mematikan; menghapus", "Kata Kerja",
               ("電気|でんき を 消|け して ください。", "Tolong matikan lampu.")),
        KOTOBA("k14-9", "開けます", "あけます", "akemasu", "membuka", "Kata Kerja",
               ("窓|まど を 開|あ けて ください。", "Tolong buka jendela.")),
        KOTOBA("k14-10", "閉めます", "しめます", "shimemasu", "menutup", "Kata Kerja",
               ("ドア を 閉|し めて ください。", "Tolong tutup pintu.")),
        KOTOBA("k14-11", "住所", "じゅうしょ", "jūsho", "alamat", "Kata Benda",
               ("住所|じゅうしょ を 書|か いて ください。", "Tolong tuliskan alamat.")),
        KOTOBA("k14-12", "名前", "なまえ", "namae", "nama", "Kata Benda",
               ("名前|なまえ を 教|おし えて ください。", "Tolong beri tahu nama Anda.")),
        KOTOBA("k14-13", "電気", "でんき", "denki", "lampu; listrik", "Kata Benda",
               ("電気|でんき を つけて ください。", "Tolong nyalakan lampu.")),
        KOTOBA("k14-14", "窓", "まど", "mado", "jendela", "Kata Benda",
               ("窓|まど を 開|あ けて ください。", "Tolong buka jendela.")),
        KOTOBA("k14-15", "信号", "しんごう", "shingō", "lampu lalu lintas", "Kata Benda",
               ("あの 信号|しんごう を 右|みぎ へ。", "Ke kanan di lampu lalu lintas itu.")),
        KOTOBA("k14-16", "もう一度", "もういちど", "mō ichido", "sekali lagi", "Ungkapan",
               ("もう 一度|いちど 言|い って ください。", "Tolong katakan sekali lagi.")),
        KOTOBA("k14-17", "ゆっくり", "ゆっくり", "yukkuri", "pelan-pelan", "Kata Keterangan",
               ("ゆっくり 話|はな して ください。", "Tolong bicara pelan-pelan.")),
        KOTOBA("k14-18", "大丈夫", "だいじょうぶ", "daijōbu", "tidak masalah", "Kata Sifat-na",
               ("大丈夫|だいじょうぶ です。", "Tidak masalah.")),
    ],
    kanji=[
        KANJI("j14-1", "待", "タイ", "ま(つ)", "menunggu", 9,
              [("待ちます", "まちます", "menunggu"), ("期待", "きたい", "harapan")]),
        KANJI("j14-2", "名", "メイ", "な", "nama", 6,
              [("名前", "なまえ", "nama"), ("有名", "ゆうめい", "terkenal")]),
        KANJI("j14-3", "住", "ジュウ", "す(む)", "tinggal", 7,
              [("住所", "じゅうしょ", "alamat"), ("住みます", "すみます", "tinggal")]),
        KANJI("j14-4", "開", "カイ", "あ(ける)・ひら(く)", "buka", 12,
              [("開けます", "あけます", "membuka"), ("開始", "かいし", "permulaan")]),
        KANJI("j14-5", "閉", "ヘイ", "し(める)・と(じる)", "tutup", 11,
              [("閉めます", "しめます", "menutup"), ("閉店", "へいてん", "tutup toko")]),
    ],
    kaiwa=KAIWA(
        "みどり町まで お願いします — Tolong ke Midori-cho",
        "Pak Karl Schmidt naik taksi dan memberi petunjuk arah kepada pengemudi.",
        [
            ("シュミット", "Shumitto", "すみません。 みどり町|ちょう まで お願|ねが いします。",
             "Permisi. Tolong ke Midori-cho."),
            ("運転手", "Untenshu", "はい。", "Baik."),
            ("シュミット", "Shumitto", "すみません、 少|すこ し 急|いそ いで ください。",
             "Permisi, tolong sedikit cepat."),
            ("運転手", "Untenshu", "分|わ かりました。", "Mengerti."),
            ("シュミット", "Shumitto", "あの 信号|しんごう を 右|みぎ へ 曲|ま がって ください。",
             "Tolong belok ke kanan di lampu lalu lintas itu."),
            ("シュミット", "Shumitto", "ここ で 止|と めて ください。", "Tolong berhenti di sini."),
            ("運転手", "Untenshu", "1800円|せんはっぴゃくえん です。", "1.800 yen."),
        ],
    ),
    quiz_bunpo=[
        QB("qb14-1", "ちょっと 待|ま ＿＿ ください。", ["って", "ちて", "んで", "いて"], 0,
           "ちょっと 待|ま って ください。", "って", "[Kata Kerja bentuk て] ください",
           "待ちます berakhiran ち, sehingga bentuk て-nya 待って (aturan い/ち/り → って)."),
        QB("qb14-2", "住所|じゅうしょ を 書|か ＿＿ ください。", ["いて", "って", "んで", "きて"], 0,
           "住所|じゅうしょ を 書|か いて ください。", "いて", "き → いて",
           "書きます berakhiran き sehingga menjadi 書いて. Ingat pengecualian 行きます → 行って."),
        QB("qb14-3", "今|いま 雨|あめ が 降|ふ って ＿＿。", ["います", "あります", "です", "ました"], 0,
           "今|いま 雨|あめ が 降|ふ って います。", "います", "[bentuk て] います",
           "〜ています menyatakan perbuatan yang sedang berlangsung."),
        QB_ID("qb14-4", "“Maukah saya bantu?” (menawarkan diri)",
              ["手伝いましょう。", "手伝いましょうか。", "手伝ってください。", "手伝いませんか。"], 1,
              "手伝|てつだ いましょう か。", "ましょうか", "[Kata Kerja] ましょう か",
              "〜ましょうか menawarkan bantuan dari pembicara. 〜ましょう berarti “mari KITA”, dan 〜てください adalah permintaan."),
        QB("qb14-5", "読|よ みます の bentuk て adalah ＿＿。", ["読んで", "読みて", "読いて", "読って"], 0,
           "本|ほん を 読|よ んで ください。", "読んで", "み/び/に → んで",
           "読みます berakhiran み sehingga bentuk て-nya 読んで."),
    ],
    quiz_susun=[
        QS("qs14-1", "Tolong tunggu sebentar.", "ちょっと 待|ま って ください", "います ましょう"),
        QS("qs14-2", "Sekarang sedang hujan.", "今|いま 雨|あめ が 降|ふ って います", "ください ました"),
        QS("qs14-3", "Tolong belok ke kanan di lampu lalu lintas itu.",
           "あの 信号|しんごう を 右|みぎ へ 曲|ま がって ください", "います から"),
    ],
)

BAB15 = CHAPTER(
    15, "写真を 撮っても いいですか。", "Bolehkah saya memotret?",
    bunpo=[
        BUNPO(
            "b15-1", "V てもいいですか — Meminta Izin",
            "[Kata Kerja bentuk て] も いい です か",
            [
                "〜てもいいですか = bolehkah saya …?",
                "izin diberikan: はい、いいですよ / どうぞ",
                "izin ditolak: すみません、ちょっと…",
            ],
            "Pola 〜てもいいですか dipakai untuk meminta izin melakukan sesuatu. Saat menolak, budaya "
            "Jepang lebih memilih ungkapan tidak langsung seperti すみません、ちょっと… daripada "
            "menolak tegas, karena penolakan langsung dianggap kurang sopan.",
            [
                ("写真|しゃしん を 撮|と って も いい です か。", "Bolehkah saya memotret?"),
                ("ここ で たばこ を 吸|す って も いい です か。", "Bolehkah saya merokok di sini?"),
                ("はい、 いい です よ。", "Ya, boleh."),
            ],
        ),
        BUNPO(
            "b15-2", "V ては いけません — Larangan",
            "[Kata Kerja bentuk て] は いけません",
            [
                "〜てはいけません = tidak boleh …",
                "bersifat larangan tegas (aturan, rambu)",
                "lebih halus: 〜ないでください (Bab 17)",
            ],
            "〜てはいけません menyatakan larangan yang tegas dan sering muncul pada aturan tempat umum "
            "atau rambu. Untuk melarang secara lebih lembut dalam percakapan sehari-hari, digunakan "
            "〜ないでください yang dipelajari di Bab 17.",
            [
                ("ここ で 写真|しゃしん を 撮|と って は いけません。", "Tidak boleh memotret di sini."),
                ("この 部屋|へや に 入|はい って は いけません。", "Tidak boleh masuk ke ruangan ini."),
            ],
        ),
        BUNPO(
            "b15-3", "V ています — Keadaan & Pekerjaan",
            "[Kata Kerja bentuk て] います",
            [
                "menyatakan keadaan yang BERTAHAN, bukan hanya progresif",
                "結婚しています = sudah berkeluarga",
                "住んでいます = bertempat tinggal",
                "持っています = memiliki",
            ],
            "Selain menyatakan perbuatan yang sedang berlangsung, 〜ています juga menyatakan keadaan "
            "yang bertahan lama. Untuk kata kerja seperti 住みます, 結婚します, 知ります, dan 持ちます, "
            "bentuk ini justru bermakna kondisi saat ini — bukan aksi sesaat.",
            [
                ("わたし は 大阪|おおさか に 住|す んで います。", "Saya tinggal di Osaka."),
                ("兄|あに は 銀行|ぎんこう で 働|はたら いて います。", "Kakak saya bekerja di bank."),
                ("車|くるま を 持|も って います。", "Saya punya mobil."),
            ],
        ),
        BUNPO(
            "b15-4", "N を 知っています/知りません",
            "[Kata Benda] を 知|し って います / 知|し りません",
            [
                "知っています = tahu (kondisi mengetahui)",
                "negatifnya BUKAN 知っていません, tetapi 知りません",
                "bedakan dari 分かります (mengerti/memahami)",
            ],
            "知っています berarti “tahu” sebagai informasi yang sudah dimiliki, dan bentuk negatifnya "
            "tidak beraturan: 知りません. Ini berbeda dari 分かります yang berarti memahami sesuatu. "
            "Menulis 知っていません dianggap salah.",
            [
                ("ミラーさん の 住所|じゅうしょ を 知|し って います か。", "Apakah Anda tahu alamat Pak Miller?"),
                ("いいえ、 知|し りません。", "Tidak, saya tidak tahu."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k15-1", "撮ります", "とります", "torimasu", "memotret; mengambil (foto)", "Kata Kerja",
               ("写真|しゃしん を 撮|と ります。", "Saya memotret.")),
        KOTOBA("k15-2", "吸います", "すいます", "suimasu", "merokok; menghirup", "Kata Kerja",
               ("たばこ を 吸|す います。", "Saya merokok.")),
        KOTOBA("k15-3", "入ります", "はいります", "hairimasu", "masuk", "Kata Kerja",
               ("部屋|へや に 入|はい ります。", "Saya masuk ke kamar.")),
        KOTOBA("k15-4", "住みます", "すみます", "sumimasu", "tinggal; berdiam", "Kata Kerja",
               ("大阪|おおさか に 住|す んで います。", "Saya tinggal di Osaka.")),
        KOTOBA("k15-5", "知ります", "しります", "shirimasu", "tahu", "Kata Kerja",
               ("住所|じゅうしょ を 知|し って います。", "Saya tahu alamatnya.")),
        KOTOBA("k15-6", "持ちます", "もちます", "mochimasu", "memegang; memiliki", "Kata Kerja",
               ("車|くるま を 持|も って います。", "Saya punya mobil.")),
        KOTOBA("k15-7", "使います", "つかいます", "tsukaimasu", "memakai", "Kata Kerja",
               ("この ペン を 使|つか って も いい です か。", "Bolehkah saya pakai pulpen ini?")),
        KOTOBA("k15-8", "座ります", "すわります", "suwarimasu", "duduk", "Kata Kerja",
               ("ここ に 座|すわ って も いい です か。", "Bolehkah saya duduk di sini?")),
        KOTOBA("k15-9", "たばこ", "たばこ", "tabako", "rokok", "Kata Benda",
               ("たばこ を 吸|す って は いけません。", "Tidak boleh merokok.")),
        KOTOBA("k15-10", "独身", "どくしん", "dokushin", "belum menikah", "Kata Benda",
               ("わたし は 独身|どくしん です。", "Saya belum menikah.")),
        KOTOBA("k15-11", "兄", "あに", "ani", "kakak laki-laki (sendiri)", "Kata Benda",
               ("兄|あに は 銀行|ぎんこう で 働|はたら いて います。", "Kakak saya bekerja di bank.")),
        KOTOBA("k15-12", "姉", "あね", "ane", "kakak perempuan (sendiri)", "Kata Benda",
               ("姉|あね は 結婚|けっこん して います。", "Kakak perempuan saya sudah menikah.")),
        KOTOBA("k15-13", "両親", "りょうしん", "ryōshin", "orang tua", "Kata Benda",
               ("両親|りょうしん は 国|くに に 住|す んで います。", "Orang tua saya tinggal di kampung.")),
        KOTOBA("k15-14", "資料", "しりょう", "shiryō", "dokumen; bahan", "Kata Benda",
               ("資料|しりょう を 見|み て も いい です か。", "Bolehkah saya lihat dokumennya?")),
        KOTOBA("k15-15", "カタログ", "カタログ", "katarogu", "katalog", "Kata Benda",
               ("カタログ を もらって も いい です か。", "Bolehkah saya minta katalognya?")),
        KOTOBA("k15-16", "工場", "こうじょう", "kōjō", "pabrik", "Kata Benda",
               ("工場|こうじょう で 働|はたら いて います。", "Saya bekerja di pabrik.")),
        KOTOBA("k15-17", "研究", "けんきゅう", "kenkyū", "penelitian", "Kata Benda",
               ("日本語|にほんご を 研究|けんきゅう して います。", "Saya meneliti bahasa Jepang.")),
        KOTOBA("k15-18", "ちょっと", "ちょっと", "chotto", "sebentar; agak (penolakan halus)", "Kata Keterangan",
               ("すみません、 ちょっと…。", "Maaf, agak… (menolak halus).")),
    ],
    kanji=[
        KANJI("j15-1", "住", "ジュウ", "す(む)", "tinggal", 7,
              [("住んでいます", "すんでいます", "tinggal"), ("住所", "じゅうしょ", "alamat")]),
        KANJI("j15-2", "知", "チ", "し(る)", "tahu", 8,
              [("知っています", "しっています", "tahu"), ("知識", "ちしき", "pengetahuan")]),
        KANJI("j15-3", "持", "ジ", "も(つ)", "pegang; punya", 9,
              [("持ちます", "もちます", "memegang"), ("所持", "しょじ", "kepemilikan")]),
        KANJI("j15-4", "使", "シ", "つか(う)", "pakai", 8,
              [("使います", "つかいます", "memakai"), ("使用", "しよう", "penggunaan")]),
        KANJI("j15-5", "写", "シャ", "うつ(す)", "memotret; menyalin", 5,
              [("写真", "しゃしん", "foto"), ("写します", "うつします", "menyalin")]),
        KANJI("j15-6", "真", "シン", "ま", "sungguh; benar", 10,
              [("写真", "しゃしん", "foto"), ("真面目", "まじめ", "serius; rajin")]),
    ],
    kaiwa=KAIWA(
        "ご家族は — Bagaimana Keluarga Anda?",
        "Nona Kimura dan Pak Miller saling bertanya tentang keluarga masing-masing.",
        [
            ("木村", "Kimura", "ミラーさん、 ご家族|ごかぞく は どこ に 住|す んで います か。",
             "Pak Miller, keluarga Anda tinggal di mana?"),
            ("ミラー", "Mirā", "両親|りょうしん は ニューヨーク に 住|す んで います。",
             "Orang tua saya tinggal di New York."),
            ("木村", "Kimura", "ご兄弟|ごきょうだい は？", "Bagaimana saudara Anda?"),
            ("ミラー", "Mirā", "姉|あね が 一人|ひとり います。 銀行|ぎんこう で 働|はたら いて います。",
             "Saya punya satu kakak perempuan. Dia bekerja di bank."),
            ("木村", "Kimura", "結婚|けっこん して います か。", "Apakah dia sudah menikah?"),
            ("ミラー", "Mirā", "はい。 子供|こども が 二人|ふたり います。", "Ya. Dia punya dua anak."),
            ("ミラー", "Mirā", "あ、 写真|しゃしん が あります。 見|み て も いい です か。",
             "Ah, ada fotonya. Bolehkah saya lihat?"),
        ],
    ),
    quiz_bunpo=[
        QB("qb15-1", "写真|しゃしん を 撮|と って ＿＿ いい です か。", ["も", "は", "が", "に"], 0,
           "写真|しゃしん を 撮|と って も いい です か。", "も", "[bentuk て] も いい です か",
           "Pola izin adalah 〜てもいいですか. Partikel も adalah bagian tetap dari pola ini."),
        QB("qb15-2", "ここ で たばこ を 吸|す って ＿＿ いけません。", ["は", "も", "が", "に"], 0,
           "ここ で たばこ を 吸|す って は いけません。", "は", "[bentuk て] は いけません",
           "Pola larangan adalah 〜てはいけません, memakai partikel は — bukan も."),
        QB("qb15-3", "わたし は 大阪|おおさか に 住|す ＿＿ います。", ["んで", "みて", "んだ", "んて"], 0,
           "わたし は 大阪|おおさか に 住|す んで います。", "んで", "[bentuk て] います (keadaan)",
           "住みます → 住んで (aturan み → んで). 住んでいます menyatakan keadaan bertempat tinggal."),
        QB_ID("qb15-4", "“Tidak, saya tidak tahu.” (jawaban atas 知っていますか)",
              ["いいえ、知っていません。", "いいえ、知りません。", "いいえ、分かりません。", "いいえ、知らないです。"], 1,
              "いいえ、 知|し りません。", "知りません", "知っています ↔ 知りません",
              "Bentuk negatif dari 知っています tidak beraturan: 知りません. 知っていません dianggap salah."),
    ],
    quiz_susun=[
        QS("qs15-1", "Bolehkah saya memotret?", "写真|しゃしん を 撮|と って も いい です か", "は いけません"),
        QS("qs15-2", "Tidak boleh merokok di sini.", "ここ で たばこ を 吸|す って は いけません", "も いい"),
        QS("qs15-3", "Saya tinggal di Osaka.", "わたし は 大阪|おおさか に 住|す んで います", "で ください"),
    ],
)

BAB16 = CHAPTER(
    16, "どうやって 行きますか。", "Bagaimana cara perginya?",
    bunpo=[
        BUNPO(
            "b16-1", "V て、V て、〜 — Merangkai Urutan Perbuatan",
            "[Kata Kerja bentuk て]、 [Kata Kerja bentuk て]、 [Kata Kerja akhir]",
            [
                "bentuk て merangkai beberapa perbuatan berurutan",
                "KALA (waktu) ditentukan oleh kata kerja TERAKHIR",
                "hanya kata kerja terakhir yang berubah bentuk lampau",
            ],
            "Untuk merangkai beberapa perbuatan dalam satu kalimat, kata kerja selain yang terakhir "
            "diubah ke bentuk て. Yang penting: hanya kata kerja TERAKHIR yang menentukan kala "
            "kalimat. Jadi “saya bangun, makan, lalu pergi” menjadi 起きて、ごはんを 食べて、行きました.",
            [
                ("朝|あさ 起|お きて、 ごはん を 食|た べて、 会社|かいしゃ へ 行|い きます。",
                 "Pagi saya bangun, makan, lalu pergi ke kantor."),
                ("きのう は 勉強|べんきょう して、 寝|ね ました。", "Kemarin saya belajar, lalu tidur."),
            ],
        ),
        BUNPO(
            "b16-2", "V てから — Setelah Melakukan",
            "[Kata Kerja bentuk て] から、 [kalimat]",
            [
                "〜てから = setelah …",
                "menegaskan urutan waktu",
                "jangan tertukar dengan から “karena” (Bab 9)",
            ],
            "〜てから menegaskan bahwa perbuatan kedua dilakukan setelah perbuatan pertama selesai. "
            "Perhatikan bahwa から di sini berbeda fungsi dari から penanda alasan di Bab 9 — yang "
            "membedakan adalah bentuk kata sebelumnya (bentuk て vs kalimat lengkap).",
            [
                ("仕事|しごと が 終|お わって から、 映画|えいが を 見|み ます。",
                 "Setelah pekerjaan selesai, saya menonton film."),
                ("国|くに へ 帰|かえ って から、 会社|かいしゃ を つくりたい です。",
                 "Setelah pulang ke negara saya, saya ingin membuat perusahaan."),
            ],
        ),
        BUNPO(
            "b16-3", "Kata Sifat Penghubung — 〜くて / 〜で",
            "[Kata Sifat-i] い→くて ／ [Kata Sifat-na/Kata Benda] で",
            [
                "Kata Sifat-i: 安い → 安くて",
                "Kata Sifat-na: きれい → きれいで",
                "Kata Benda: 学生 → 学生で",
                "PENGECUALIAN: いい → よくて",
            ],
            "Untuk menyambung dua sifat dalam satu kalimat, kata sifat-i berubah menjadi 〜くて dan "
            "kata sifat-na serta kata benda memakai で. Sifat-sifat yang disambung sebaiknya senada "
            "(sama-sama positif atau negatif); untuk kontras digunakan が (“tetapi”).",
            [
                ("この 部屋|へや は 広|ひろ くて、 明|あか るい です。", "Kamar ini luas dan terang."),
                ("大阪|おおさか は にぎやか で、 おもしろい 町|まち です。", "Osaka kota yang ramai dan menarik."),
            ],
        ),
        BUNPO(
            "b16-4", "どうやって・どの N — Cara & Pilihan",
            "どうやって [Kata Kerja] か ／ どの [Kata Benda]",
            [
                "どうやって = bagaimana caranya",
                "どの + [Kata Benda] = yang mana (dari 3 atau lebih)",
                "どれ berdiri sendiri, どの harus diikuti kata benda",
            ],
            "どうやって menanyakan cara atau metode melakukan sesuatu, dan jawabannya biasanya "
            "berupa rangkaian bentuk て. Untuk memilih dari tiga atau lebih pilihan, どの dipakai "
            "dengan kata benda, sedangkan どれ berdiri sendiri.",
            [
                ("大学|だいがく まで どうやって 行|い きます か。", "Bagaimana cara pergi ke universitas?"),
                ("駅|えき で 25番|にじゅうごばん の バス に 乗|の って、 大学前|だいがくまえ で 降|お りて ください。",
                 "Naik bus nomor 25 di stasiun, lalu turun di Daigakumae."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k16-1", "乗ります", "のります", "norimasu", "naik (kendaraan)", "Kata Kerja",
               ("バス に 乗|の ります。", "Saya naik bus.")),
        KOTOBA("k16-2", "降ります", "おります", "orimasu", "turun (kendaraan)", "Kata Kerja",
               ("駅|えき で 降|お ります。", "Saya turun di stasiun.")),
        KOTOBA("k16-3", "乗り換えます", "のりかえます", "norikaemasu", "berganti kendaraan", "Kata Kerja",
               ("大阪|おおさか で 乗|の り換|か えます。", "Saya berganti kereta di Osaka.")),
        KOTOBA("k16-4", "浴びます", "あびます", "abimasu", "mandi (siram)", "Kata Kerja",
               ("シャワー を 浴|あ びます。", "Saya mandi (shower).")),
        KOTOBA("k16-5", "入れます", "いれます", "iremasu", "memasukkan", "Kata Kerja",
               ("お金|おかね を 入|い れて ください。", "Tolong masukkan uangnya.")),
        KOTOBA("k16-6", "押します", "おします", "oshimasu", "menekan", "Kata Kerja",
               ("ボタン を 押|お します。", "Saya menekan tombol.")),
        KOTOBA("k16-7", "若い", "わかい", "wakai", "muda", "Kata Sifat-i",
               ("若|わか くて、 元気|げんき です。", "Muda dan bersemangat.")),
        KOTOBA("k16-8", "長い", "ながい", "nagai", "panjang", "Kata Sifat-i",
               ("髪|かみ が 長|なが くて、 きれい です。", "Rambutnya panjang dan indah.")),
        KOTOBA("k16-9", "短い", "みじかい", "mijikai", "pendek", "Kata Sifat-i",
               ("短|みじか くて 便利|べんり です。", "Pendek dan praktis.")),
        KOTOBA("k16-10", "広い", "ひろい", "hiroi", "luas", "Kata Sifat-i",
               ("この 部屋|へや は 広|ひろ い です。", "Kamar ini luas.")),
        KOTOBA("k16-11", "狭い", "せまい", "semai", "sempit", "Kata Sifat-i",
               ("部屋|へや が 狭|せま いです。", "Kamarnya sempit.")),
        KOTOBA("k16-12", "明るい", "あかるい", "akarui", "terang", "Kata Sifat-i",
               ("明|あか るくて、 きれい です。", "Terang dan bersih.")),
        KOTOBA("k16-13", "暗い", "くらい", "kurai", "gelap", "Kata Sifat-i",
               ("部屋|へや が 暗|くら い です。", "Kamarnya gelap.")),
        KOTOBA("k16-14", "どうやって", "どうやって", "dō yatte", "bagaimana caranya", "Kata Tanya",
               ("どうやって 行|い きます か。", "Bagaimana cara perginya?")),
        KOTOBA("k16-15", "どの", "どの", "dono", "yang mana", "Kata Tanya",
               ("どの バス に 乗|の ります か。", "Naik bus yang mana?")),
        KOTOBA("k16-16", "番", "ばん", "ban", "nomor (urutan)", "Satuan",
               ("25番|にじゅうごばん の バス です。", "Bus nomor 25.")),
        KOTOBA("k16-17", "それから", "それから", "sorekara", "lalu; setelah itu", "Kata Penghubung",
               ("それから、 バス に 乗|の ります。", "Setelah itu, saya naik bus.")),
        KOTOBA("k16-18", "髪", "かみ", "kami", "rambut", "Kata Benda",
               ("髪|かみ が 長|なが い です。", "Rambutnya panjang.")),
    ],
    kanji=[
        KANJI("j16-1", "乗", "ジョウ", "の(る)", "naik; menumpang", 9,
              [("乗ります", "のります", "naik"), ("乗車", "じょうしゃ", "menaiki kendaraan")]),
        KANJI("j16-2", "降", "コウ", "お(りる)・ふ(る)", "turun", 10,
              [("降ります", "おります", "turun"), ("降雨", "こうう", "curah hujan")]),
        KANJI("j16-3", "長", "チョウ", "なが(い)", "panjang; kepala", 8,
              [("長い", "ながい", "panjang"), ("社長", "しゃちょう", "direktur")]),
        KANJI("j16-4", "広", "コウ", "ひろ(い)", "luas", 5,
              [("広い", "ひろい", "luas"), ("広告", "こうこく", "iklan")]),
        KANJI("j16-5", "番", "バン", "—", "nomor; urutan", 12,
              [("一番", "いちばん", "paling; nomor satu"), ("番号", "ばんごう", "nomor")]),
    ],
    kaiwa=KAIWA(
        "どうやって 行きますか — Bagaimana Cara Perginya?",
        "Nona Karina menelepon kantor universitas untuk menanyakan cara menuju kampus.",
        [
            ("カリナ", "Karina", "すみません。 大学|だいがく まで どうやって 行|い きます か。",
             "Permisi. Bagaimana cara pergi ke universitas?"),
            ("係|かかり", "Kakari", "大阪駅|おおさかえき から 25番|にじゅうごばん の バス に 乗|の って ください。",
             "Silakan naik bus nomor 25 dari stasiun Osaka."),
            ("カリナ", "Karina", "それから どう します か。", "Setelah itu bagaimana?"),
            ("係|かかり", "Kakari", "大学前|だいがくまえ で 降|お りて ください。 3つ|みっつ 目|め です。",
             "Silakan turun di Daigakumae. Pemberhentian ketiga."),
            ("カリナ", "Karina", "どのくらい かかります か。", "Berapa lama waktunya?"),
            ("係|かかり", "Kakari", "30分|さんじゅっぷん ぐらい です。", "Kira-kira 30 menit."),
            ("カリナ", "Karina", "分|わ かりました。 ありがとう ございました。", "Saya mengerti. Terima kasih banyak."),
        ],
    ),
    quiz_bunpo=[
        QB("qb16-1", "朝|あさ 起|お ＿＿、 ごはん を 食|た べて、 会社|かいしゃ へ 行|い きます。",
           ["きて", "きます", "きた", "きって"], 0,
           "朝|あさ 起|お きて、 ごはん を 食|た べて、 会社|かいしゃ へ 行|い きます。", "起きて",
           "[bentuk て]、[bentuk て]、[Kata Kerja akhir]",
           "Saat merangkai perbuatan, semua kata kerja kecuali yang terakhir memakai bentuk て. Kala ditentukan kata kerja terakhir."),
        QB("qb16-2", "仕事|しごと が 終|お わって ＿＿、 映画|えいが を 見|み ます。", ["から", "ので", "まで", "けど"], 0,
           "仕事|しごと が 終|お わって から、 映画|えいが を 見|み ます。", "から", "[bentuk て] から",
           "〜てから berarti “setelah …”. Berbeda dari から penanda alasan yang mengikuti kalimat lengkap."),
        QB("qb16-3", "この 部屋|へや は 広|ひろ ＿＿、 明|あか るい です。", ["くて", "で", "て", "いで"], 0,
           "この 部屋|へや は 広|ひろ くて、 明|あか るい です。", "広くて", "[Kata Sifat-i] い → くて",
           "Kata sifat-i disambung dengan mengubah い menjadi くて. Kata sifat-na memakai で."),
        QB("qb16-4", "大阪|おおさか は にぎやか ＿＿、 おもしろい 町|まち です。", ["で", "くて", "て", "な"], 0,
           "大阪|おおさか は にぎやか で、 おもしろい 町|まち です。", "にぎやかで",
           "[Kata Sifat-na] で",
           "にぎやか adalah kata sifat-na sehingga disambung dengan で, bukan くて."),
        QB("qb16-5", "大学|だいがく まで ＿＿ 行|い きます か。", ["どうやって", "どう", "どの", "どこ"], 0,
           "大学|だいがく まで どうやって 行|い きます か。", "どうやって", "どうやって [Kata Kerja] か",
           "どうやって menanyakan CARA melakukan sesuatu, dijawab dengan rangkaian bentuk て."),
    ],
    quiz_susun=[
        QS("qs16-1", "Setelah pekerjaan selesai, saya menonton film.",
           "仕事|しごと が 終|お わって から 映画|えいが を 見|み ます", "ので まで"),
        QS("qs16-2", "Kamar ini luas dan terang.", "この 部屋|へや は 広|ひろ くて 明|あか るい です", "で な"),
        QS("qs16-3", "Naik bus nomor 25, lalu turun di Daigakumae.",
           "25番|にじゅうごばん の バス に 乗|の って 大学前|だいがくまえ で 降|お りて ください", "から います"),
    ],
)

BAB17 = CHAPTER(
    17, "どう したんですか。", "Ada apa? / Kenapa?",
    bunpo=[
        BUNPO(
            "b17-1", "Bentuk ない (Nai-form)",
            "[Kata Kerja] → bentuk ない",
            [
                "Golongan I: 〜ます → 〜あ-baris + ない (書きます → 書かない)",
                "Golongan II: ます → ない (食べます → 食べない)",
                "Golongan III: します → しない ； 来ます → 来ない",
                "PENGECUALIAN: あります → ない",
            ],
            "Bentuk ない adalah bentuk negatif biasa (kamus) dan menjadi dasar beberapa pola penting. "
            "Untuk golongan I, suku kata sebelum ます dipindah ke baris あ lalu ditambah ない: "
            "書きます → 書かない, 飲みます → 飲まない. Perhatikan pengecualian あります yang menjadi ない.",
            [
                ("吸|す います → 吸|す わない", "merokok → bentuk nai"),
                ("食|た べます → 食|た べない", "makan → bentuk nai"),
                ("来|き ます → 来|こ ない", "datang → bentuk nai"),
            ],
        ),
        BUNPO(
            "b17-2", "V ないでください — Larangan Halus",
            "[Kata Kerja bentuk ない] で ください",
            [
                "〜ないでください = tolong jangan …",
                "lebih halus daripada 〜てはいけません",
                "dipakai sehari-hari antar rekan",
            ],
            "〜ないでください adalah permintaan agar seseorang tidak melakukan sesuatu, dan terasa "
            "jauh lebih lembut daripada larangan tegas 〜てはいけません. Pola ini yang umum dipakai "
            "dalam percakapan sehari-hari.",
            [
                ("ここ で たばこ を 吸|す わないで ください。", "Tolong jangan merokok di sini."),
                ("心配|しんぱい しないで ください。", "Tolong jangan khawatir."),
            ],
        ),
        BUNPO(
            "b17-3", "V なければなりません — Harus",
            "[Kata Kerja bentuk ない tanpa ない] + なければ なりません",
            [
                "〜なければなりません = harus (kewajiban)",
                "飲みます → 飲まなければ なりません",
                "bentuk percakapan: 〜なきゃ",
                "nuansanya: tidak ada pilihan lain",
            ],
            "Pola ini menyatakan kewajiban yang tidak bisa dihindari. Dibentuk dari bentuk ない dengan "
            "menghapus ない lalu menambahkan なければなりません. Dalam percakapan santai sering "
            "disingkat menjadi 〜なきゃ.",
            [
                ("薬|くすり を 飲|の まなければ なりません。", "Saya harus minum obat."),
                ("あした 会社|かいしゃ へ 行|い かなければ なりません。", "Besok saya harus pergi ke kantor."),
            ],
        ),
        BUNPO(
            "b17-4", "V なくてもいいです — Tidak Perlu",
            "[Kata Kerja bentuk ない tanpa い] + くても いい です",
            [
                "〜なくてもいいです = tidak perlu …",
                "飲みます → 飲まなくても いい です",
                "kebalikan dari 〜なければなりません",
            ],
            "〜なくてもいいです menyatakan bahwa sesuatu tidak wajib dilakukan. Dibentuk dari bentuk "
            "ない dengan mengganti い menjadi くてもいいです. Pola ini adalah pasangan kontras dari "
            "〜なければなりません.",
            [
                ("あした 来|こ なくても いい です。", "Besok Anda tidak perlu datang."),
                ("お金|おかね を 払|はら わなくても いい です。", "Anda tidak perlu membayar."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k17-1", "覚えます", "おぼえます", "oboemasu", "menghafal; mengingat", "Kata Kerja",
               ("漢字|かんじ を 覚|おぼ えなければ なりません。", "Saya harus menghafal kanji.")),
        KOTOBA("k17-2", "忘れます", "わすれます", "wasuremasu", "lupa", "Kata Kerja",
               ("忘|わす れないで ください。", "Tolong jangan lupa.")),
        KOTOBA("k17-3", "払います", "はらいます", "haraimasu", "membayar", "Kata Kerja",
               ("お金|おかね を 払|はら わなくても いい です。", "Anda tidak perlu membayar.")),
        KOTOBA("k17-4", "心配します", "しんぱいします", "shinpai shimasu", "khawatir", "Kata Kerja",
               ("心配|しんぱい しないで ください。", "Tolong jangan khawatir.")),
        KOTOBA("k17-5", "脱ぎます", "ぬぎます", "nugimasu", "melepas (pakaian/sepatu)", "Kata Kerja",
               ("靴|くつ を 脱|ぬ いで ください。", "Tolong lepas sepatu.")),
        KOTOBA("k17-6", "持って行きます", "もっていきます", "motte ikimasu", "membawa pergi", "Kata Kerja",
               ("持|も って 行|い かなければ なりません。", "Saya harus membawanya.")),
        KOTOBA("k17-7", "薬", "くすり", "kusuri", "obat", "Kata Benda",
               ("薬|くすり を 飲|の みます。", "Saya minum obat.")),
        KOTOBA("k17-8", "病院", "びょういん", "byōin", "rumah sakit", "Kata Benda",
               ("病院|びょういん へ 行|い かなければ なりません。", "Saya harus pergi ke rumah sakit.")),
        KOTOBA("k17-9", "医者", "いしゃ", "isha", "dokter", "Kata Benda",
               ("医者|いしゃ に 見|み せます。", "Saya periksa ke dokter.")),
        KOTOBA("k17-10", "熱", "ねつ", "netsu", "demam", "Kata Benda",
               ("熱|ねつ が あります。", "Saya demam.")),
        KOTOBA("k17-11", "風邪", "かぜ", "kaze", "masuk angin; flu", "Kata Benda",
               ("風邪|かぜ を ひきました。", "Saya masuk angin.")),
        KOTOBA("k17-12", "元気", "げんき", "genki", "sehat", "Kata Sifat-na",
               ("お元気|おげんき です か。", "Apakah Anda sehat?")),
        KOTOBA("k17-13", "無理", "むり", "muri", "berlebihan; memaksakan", "Kata Sifat-na",
               ("無理|むり を しないで ください。", "Tolong jangan memaksakan diri.")),
        KOTOBA("k17-14", "パスポート", "パスポート", "pasupōto", "paspor", "Kata Benda",
               ("パスポート を 持|も って 来|き なければ なりません。", "Anda harus membawa paspor.")),
        KOTOBA("k17-15", "宿題", "しゅくだい", "shukudai", "pekerjaan rumah", "Kata Benda",
               ("宿題|しゅくだい を しなければ なりません。", "Saya harus mengerjakan PR.")),
        KOTOBA("k17-16", "大切", "たいせつ", "taisetsu", "penting; berharga", "Kata Sifat-na",
               ("大切|たいせつ な 物|もの です。", "Ini benda yang penting.")),
        KOTOBA("k17-17", "ゆっくり", "ゆっくり", "yukkuri", "santai; pelan", "Kata Keterangan",
               ("ゆっくり 休|やす んで ください。", "Tolong beristirahat dengan tenang.")),
        KOTOBA("k17-18", "どうしたんですか", "どうしたんですか", "dō shita n desu ka", "ada apa?", "Ungkapan",
               ("どう した ん です か。", "Ada apa?")),
    ],
    kanji=[
        KANJI("j17-1", "医", "イ", "—", "kedokteran", 7,
              [("医者", "いしゃ", "dokter"), ("医学", "いがく", "ilmu kedokteran")]),
        KANJI("j17-2", "者", "シャ", "もの", "orang (pelaku)", 8,
              [("医者", "いしゃ", "dokter"), ("学者", "がくしゃ", "ilmuwan")]),
        KANJI("j17-3", "病", "ビョウ", "や(む)", "sakit; penyakit", 10,
              [("病院", "びょういん", "rumah sakit"), ("病気", "びょうき", "penyakit")]),
        KANJI("j17-4", "院", "イン", "—", "lembaga; institusi", 10,
              [("病院", "びょういん", "rumah sakit"), ("大学院", "だいがくいん", "pascasarjana")]),
        KANJI("j17-5", "薬", "ヤク", "くすり", "obat", 16,
              [("薬", "くすり", "obat"), ("薬局", "やっきょく", "apotek")]),
        KANJI("j17-6", "切", "セツ", "き(る)", "potong; penting", 4,
              [("大切", "たいせつ", "penting"), ("切ります", "きります", "memotong")]),
    ],
    kaiwa=KAIWA(
        "どう しましたか — Ada Keluhan Apa?",
        "Nona Matsumoto memeriksakan diri ke dokter karena merasa tidak sehat.",
        [
            ("医者", "Isha", "どう しました か。", "Ada keluhan apa?"),
            ("松本", "Matsumoto", "きのう から 熱|ねつ が あって、 のど が 痛|いた い です。",
             "Sejak kemarin saya demam dan tenggorokan sakit."),
            ("医者", "Isha", "そう です か。 ちょっと 口|くち を 開|あ けて ください。",
             "Begitu ya. Tolong buka mulutnya sedikit."),
            ("医者", "Isha", "風邪|かぜ です ね。 2、3日|にさんにち ゆっくり 休|やす んで ください。",
             "Anda masuk angin. Silakan beristirahat dengan tenang dua-tiga hari."),
            ("松本", "Matsumoto", "あのう、 おふろ に 入|はい って も いい です か。",
             "Maaf, bolehkah saya berendam?"),
            ("医者", "Isha", "今日|きょう は 入|はい らないで ください。 それから、 この 薬|くすり を 飲|の まなければ なりません。",
             "Hari ini jangan berendam. Lalu, Anda harus minum obat ini."),
            ("松本", "Matsumoto", "分|わ かりました。 ありがとう ございました。", "Saya mengerti. Terima kasih banyak."),
        ],
    ),
    quiz_bunpo=[
        QB("qb17-1", "ここ で たばこ を 吸|す ＿＿ ください。", ["わないで", "いないで", "わなくて", "わない"], 0,
           "ここ で たばこ を 吸|す わないで ください。", "吸わないで", "[bentuk ない] で ください",
           "吸います (golongan I) → bentuk ない-nya 吸わない, sehingga larangannya 吸わないでください."),
        QB("qb17-2", "薬|くすり を 飲|の ＿＿ なりません。", ["まなければ", "みなければ", "まなくても", "んで"], 0,
           "薬|くすり を 飲|の まなければ なりません。", "飲まなければ", "[bentuk ない tanpa ない] なければ なりません",
           "飲みます → 飲まない → 飲まなければ なりません (“harus minum obat”)."),
        QB("qb17-3", "あした 来|こ ＿＿ いい です。", ["なくても", "ないでも", "なければ", "ないで"], 0,
           "あした 来|こ なくても いい です。", "来なくても", "[bentuk ない tanpa い] くても いい です",
           "来ます → 来ない → 来なくてもいいです (“tidak perlu datang”)."),
        QB_ID("qb17-4", "“Tolong jangan khawatir.”",
              ["心配しなければなりません。", "心配しないでください。", "心配してください。", "心配しなくてもいいです。"], 1,
              "心配|しんぱい しないで ください。", "しないで", "[bentuk ない] で ください",
              "します → しない → しないでください. Pola ini melarang dengan halus."),
    ],
    quiz_susun=[
        QS("qs17-1", "Tolong jangan merokok di sini.", "ここ で たばこ を 吸|す わないで ください", "ては いけません"),
        QS("qs17-2", "Saya harus minum obat.", "薬|くすり を 飲|の まなければ なりません", "なくても いい"),
        QS("qs17-3", "Besok Anda tidak perlu datang.", "あした 来|こ なくても いい です", "なければ なりません"),
    ],
)

CHAPTERS = [BAB10, BAB11, BAB12, BAB13, BAB14, BAB15, BAB16, BAB17]
