"""Materi Minna no Nihongo 2 — Bab 26 s/d 30 (pembuka buku 2)."""

from seed_data.dsl import BUNPO, CHAPTER, KAIWA, KANJI, KOTOBA, QB, QB_ID, QS

BAB26 = CHAPTER(
    26, "ごみは いつ 出したら いいですか。", "Kapan sebaiknya saya mengeluarkan sampah?",
    bunpo=[
        BUNPO(
            "b26-1", "〜んです — Menjelaskan Alasan / Keadaan",
            "[Bentuk Biasa] ん です",
            [
                "kata kerja: 行|い く → 行くんです",
                "kata sifat-i: 痛|いた い → 痛いんです",
                "kata sifat-na: 静|しず か → 静かなんです",
                "kata benda: 雨|あめ → 雨なんです",
                "んです = bentuk percakapan dari のです",
            ],
            "～んです dipakai saat pembicara menjelaskan alasan atau latar belakang suatu keadaan, "
            "atau menegaskan sesuatu kepada lawan bicara. Setelah kata sifat-na dan kata benda, "
            "bentuknya menjadi なんです. Dalam tulisan formal dipakai のです.",
            [
                ("頭|あたま が 痛|いた いん です。", "Kepala saya sakit (makanya…)."),
                ("あした 運動会|うんどうかい が あるん です。", "Besok ada lomba olahraga, lho."),
                ("この 町|まち は 静|しず か なん です。", "Kota ini tenang, lho."),
            ],
        ),
        BUNPO(
            "b26-2", "Kata Tanya + 〜んですか — Menanyakan Penjelasan",
            "[Kata Tanya] 〜ん です か",
            [
                "どう したんですか = ada apa / kenapa",
                "lebih alami daripada 〜ますか saat menanyakan alasan",
                "jawaban biasanya juga memakai 〜んです",
            ],
            "Untuk menanyakan penjelasan atas suatu keadaan, pertanyaan dibentuk dengan 〜んですか. "
            "Pertanyaan ini menunjukkan pembicara melihat suatu keadaan dan ingin tahu alasannya.",
            [
                ("どう したん です か。", "Ada apa? / Kenapa?"),
                ("いつ 日本|にほん へ 来|き たん です か。", "Kapan Anda datang ke Jepang?"),
                ("どこ で その 本|ほん を 買|か ったん です か。", "Di mana Anda membeli buku itu?"),
            ],
        ),
        BUNPO(
            "b26-3", "〜んですが、〜ていただけませんか — Permintaan Sopan",
            "[Bentuk Biasa] ん です が、 [Kata Kerja bentuk て] いただけません か",
            [
                "んですが = menjelaskan keadaan dulu sebelum meminta",
                "〜ていただけませんか = tingkat sopan tertinggi",
                "lebih halus daripada 〜てください / 〜てもらえませんか",
            ],
            "Sebelum mengajukan permintaan, orang Jepang biasanya menjelaskan dulu keadaannya dengan "
            "〜んですが, lalu menutup dengan 〜ていただけませんか. Susunan ini terdengar jauh lebih "
            "sopan daripada langsung meminta.",
            [
                ("ちょっと 相談|そうだん したいん です が、 時間|じかん を いただけません か。",
                 "Saya ingin berkonsultasi sebentar, bolehkah saya minta waktunya?"),
                ("使|つか い方|かた が 分|わ からないん です が、 教|おし えて いただけません か。",
                 "Saya tidak tahu cara memakainya, bisakah Anda mengajari saya?"),
                ("荷物|にもつ が 重|おも いん です が、 持|も って いただけません か。",
                 "Barang bawaan saya berat, bisakah Anda membawakannya?"),
            ],
        ),
        BUNPO(
            "b26-4", "〜んですが、〜たら いいですか — Meminta Petunjuk",
            "[Bentuk Biasa] ん です が、 [Kata Tanya] 〜たら いい です か",
            [
                "いつ 〜たらいいですか = kapan sebaiknya",
                "どう 〜たらいいですか = bagaimana sebaiknya",
                "〜たら = bentuk pengandaian (Bab 25)",
            ],
            "Pola ini dipakai untuk meminta petunjuk mengenai waktu atau cara yang sebaiknya dilakukan. "
            "Keadaan dijelaskan dulu dengan 〜んですが, lalu kata tanya diikuti bentuk 〜たらいいですか.",
            [
                ("ごみ を 出|だ したいん です が、 いつ 出|だ したら いい です か。",
                 "Saya mau mengeluarkan sampah, kapan sebaiknya dikeluarkan?"),
                ("市役所|しやくしょ へ 行|い きたいん です が、 どう 行|い ったら いい です か。",
                 "Saya mau ke balai kota, bagaimana sebaiknya perginya?"),
                ("この 漢字|かんじ が 読|よ めないん です が、 何|なん と 読|よ んだら いい です か。",
                 "Kanji ini tidak bisa saya baca, bagaimana membacanya?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k26-1", "診ます", "みます", "mimasu", "memeriksa (dokter)", "Kata Kerja",
               ("医者|いしゃ が 患者|かんじゃ を 診|み ます。", "Dokter memeriksa pasien.")),
        KOTOBA("k26-2", "探します", "さがします", "sagashimasu", "mencari", "Kata Kerja",
               ("落|お とした 財布|さいふ を 探|さが して います。", "Saya sedang mencari dompet yang jatuh.")),
        KOTOBA("k26-3", "遅れます", "おくれます", "okuremasu", "terlambat; ketinggalan", "Kata Kerja",
               ("電車|でんしゃ に 遅|おく れました。", "Saya ketinggalan kereta.")),
        KOTOBA("k26-4", "間に合います", "まにあいます", "maniaimasu", "sempat; tepat waktu", "Kata Kerja",
               ("会議|かいぎ に 間|ま に 合|あ いました。", "Saya sempat hadir rapat tepat waktu.")),
        KOTOBA("k26-5", "参加します", "さんかします", "sanka shimasu", "ikut serta", "Kata Kerja",
               ("運動会|うんどうかい に 参加|さんか します。", "Saya ikut lomba olahraga.")),
        KOTOBA("k26-6", "申し込みます", "もうしこみます", "mōshikomimasu", "mendaftar; mengajukan", "Kata Kerja",
               ("講座|こうざ に 申|もう し込|こ みました。", "Saya mendaftar kursus.")),
        KOTOBA("k26-7", "連絡します", "れんらくします", "renraku shimasu", "menghubungi", "Kata Kerja",
               ("あとで 連絡|れんらく します。", "Nanti saya hubungi.")),
        KOTOBA("k26-8", "燃えます", "もえます", "moemasu", "terbakar", "Kata Kerja",
               ("ごみ が 燃|も えます。", "Sampahnya terbakar.")),
        KOTOBA("k26-9", "片づきます", "かたづきます", "katazukimasu", "menjadi rapi", "Kata Kerja",
               ("部屋|へや が 片|かた づきました。", "Kamarnya sudah rapi.")),
        KOTOBA("k26-10", "ごみ", "ごみ", "gomi", "sampah", "Kata Benda",
               ("ごみ を 出|だ します。", "Mengeluarkan sampah.")),
        KOTOBA("k26-11", "燃えるごみ", "もえるごみ", "moeru gomi", "sampah yang bisa dibakar", "Kata Benda",
               ("燃|も えるごみ は 月水金|げっすいきん です。", "Sampah yang bisa dibakar (dikeluarkan) Senin, Rabu, Jumat.")),
        KOTOBA("k26-12", "置き場", "おきば", "okiba", "tempat menaruh", "Kata Benda",
               ("ごみ の 置|お き場|ば は あそこ です。", "Tempat sampahnya di sana.")),
        KOTOBA("k26-13", "横", "よこ", "yoko", "samping", "Kata Benda",
               ("駅|えき の 横|よこ に 銀行|ぎんこう が あります。", "Di samping stasiun ada bank.")),
        KOTOBA("k26-14", "瓶", "びん", "bin", "botol", "Kata Benda",
               ("瓶|びん は 燃|も えないごみ です。", "Botol termasuk sampah yang tidak bisa dibakar.")),
        KOTOBA("k26-15", "缶", "かん", "kan", "kaleng", "Kata Benda",
               ("缶|かん を 開|あ けます。", "Membuka kaleng.")),
        KOTOBA("k26-16", "お湯", "おゆ", "oyu", "air panas", "Kata Benda",
               ("お湯|おゆ が わきました。", "Air panasnya sudah mendidih.")),
        KOTOBA("k26-17", "都合がいい", "つごうがいい", "tsugō ga ii", "cocok (soal waktu)", "Ungkapan",
               ("あした は 都合|つごう が いい です。", "Besok cocok bagi saya.")),
        KOTOBA("k26-18", "直接", "ちょくせつ", "chokusetsu", "langsung", "Kata Keterangan",
               ("直接|ちょくせつ 会社|かいしゃ へ 行|い きます。", "Saya langsung pergi ke kantor.")),
    ],
    kanji=[
        KANJI("j26-1", "遅", "チ", "おく(れる)", "lambat; terlambat", 12,
              [("遅れます", "おくれます", "terlambat"), ("遅刻", "ちこく", "datang terlambat")]),
        KANJI("j26-2", "燃", "ネン", "も(える)", "bakar", 16,
              [("燃えるごみ", "もえるごみ", "sampah yang bisa dibakar"), ("燃料", "ねんりょう", "bahan bakar")]),
        KANJI("j26-3", "湯", "トウ", "ゆ", "air panas", 12,
              [("お湯", "おゆ", "air panas"), ("銭湯", "せんとう", "pemandian umum")]),
        KANJI("j26-4", "連", "レン", "つ(れる)", "hubung; bawa", 10,
              [("連絡", "れんらく", "kontak; menghubungi"), ("連れます", "つれます", "membawa (orang)")]),
        KANJI("j26-5", "怖", "フ", "こわ(い)", "takut", 8,
              [("怖い", "こわい", "menakutkan"), ("恐怖", "きょうふ", "ketakutan")]),
        KANJI("j26-6", "困", "コン", "こま(る)", "sulit; repot", 7,
              [("困ります", "こまります", "kerepotan"), ("困難", "こんなん", "kesulitan")]),
    ],
    kaiwa=KAIWA(
        "ごみの 出し方 — Cara Membuang Sampah",
        "Karina baru pindah ke apartemen dan bertanya kepada Ibu Yamada, tetangganya, tentang aturan membuang sampah.",
        [
            ("カリナ", "Karina", "すみません。 ごみ を 出|だ したいん です が、 いつ 出|だ したら いい です か。",
             "Permisi. Saya mau mengeluarkan sampah, kapan sebaiknya dikeluarkan?"),
            ("山田", "Yamada", "燃|も えるごみ は 月水金|げっすいきん の 朝|あさ 8時|はちじ まで です。",
             "Sampah yang bisa dibakar: hari Senin, Rabu, Jumat, sampai jam 8 pagi."),
            ("カリナ", "Karina", "置|お き場|ば は どこ なん です か。", "Di mana tempatnya?"),
            ("山田", "Yamada", "アパート の 横|よこ です。 ネット を かけて ください ね。",
             "Di samping apartemen. Tolong pasang jaringnya, ya."),
            ("カリナ", "Karina", "瓶|びん や 缶|かん は いつ 出|だ したら いい です か。",
             "Kapan sebaiknya botol dan kaleng dikeluarkan?"),
            ("山田", "Yamada", "金曜日|きんようび です。 何|なん か あったら、 連絡|れんらく して ください。",
             "Hari Jumat. Kalau ada apa-apa, hubungi saya, ya."),
            ("カリナ", "Karina", "わかりました。 ありがとう ございます。", "Baik. Terima kasih banyak."),
        ],
    ),
    quiz_bunpo=[
        QB("qb26-1", "頭|あたま が 痛|いた い＿＿ です。", ["ん", "のん", "こと", "はず"], 0,
           "頭|あたま が 痛|いた い ん です。", "痛いんです", "[Bentuk Biasa] ん です",
           "～んです dipakai untuk menjelaskan keadaan atau alasan. Setelah kata sifat-i langsung ditambah んです."),
        QB("qb26-2", "この 町|まち は 静|しず か ＿＿ です。", ["なん", "ん", "だん", "の"], 0,
           "この 町|まち は 静|しず か なん です。", "なんです", "[Kata Sifat-na / Kata Benda] なん です",
           "Setelah kata sifat-na dan kata benda, bentuknya なんです, bukan んです."),
        QB("qb26-3", "使|つか い方|かた が 分|わ からないん です が、 教|おし えて ＿＿ません か。",
           ["いただけ", "もらい", "くれ", "あげ"], 0,
           "使|つか い方|かた が 分|わ からないん です が、 教|おし えて いただけません か。", "いただけませんか",
           "[Kata Kerja bentuk て] いただけません か",
           "Bentuk permintaan paling sopan adalah ～ていただけませんか."),
        QB_ID("qb26-4", "“Permisi, kapan sebaiknya saya mengeluarkan sampah?”",
              ["すみません、 ごみ は いつ 出|だ したら いい です か。",
               "すみません、 ごみ は いつ 出|だ します か。",
               "すみません、 ごみ は いつ 出|だ すん です か。",
               "すみません、 ごみ は いつ 出|だ しましょう か。"], 0,
              "すみません、 ごみ は いつ 出|だ したら いい です か。", "出したらいいですか",
              "[Kata Tanya] 〜たら いい です か",
              "～たらいいですか dipakai untuk menanyakan waktu atau cara yang sebaiknya dilakukan."),
    ],
    quiz_susun=[
        QS("qs26-1", "Kapan sebaiknya saya mengeluarkan sampah?",
           "ごみ は いつ 出|だ したら いい です か", "毎日|まいにち も"),
        QS("qs26-2", "Sampah yang bisa dibakar dikeluarkan hari Senin, Rabu, dan Jumat.",
           "燃|も えるごみ は 月水金|げっすいきん に 出|だ します", "日曜日|にちようび だけ"),
        QS("qs26-3", "Saya tidak tahu cara memakainya, bisakah Anda mengajari saya?",
           "使|つか い方|かた が 分|わ からないん です が 教|おし えて いただけません か", "ください ほしい"),
    ],
)

BAB27 = CHAPTER(
    27, "窓から 富士山が 見えます。", "Dari jendela terlihat Gunung Fuji.",
    bunpo=[
        BUNPO(
            "b27-1", "Bentuk Kemungkinan (Potential) — Bisa Melakukan",
            "Gol I: 〜います → 〜えます ／ Gol II: ます → られます ／ Gol III: できます・来|こ られます",
            [
                "Golongan I: 書|か きます → 書けます (baris い → え)",
                "Golongan II: 食|た べます → 食べられます",
                "Golongan III: します → できます ； 来|き ます → 来|こ られます",
                "objek を berubah menjadi が: 漢字が 読めます",
            ],
            "Selain 〜ことができます (Bab 18), bahasa Jepang punya bentuk kemungkinan khusus. "
            "Golongan I mengubah vokal akhir i menjadi e (読みます → 読めます), Golongan II menambah "
            "られる setelah batang kata (食べます → 食べられます). Perhatikan perubahan partikel "
            "を menjadi が.",
            [
                ("わたし は 漢字|かんじ が 読|よ めます。", "Saya bisa membaca kanji."),
                ("一人|ひとり で 病院|びょういん へ 行|い けます。", "Saya bisa pergi ke rumah sakit sendiri."),
                ("この 温泉|おんせん に は 入|はい れます か。", "Bisakah kita masuk ke pemandian air panas ini?"),
            ],
        ),
        BUNPO(
            "b27-2", "見えます・聞こえます — Terlihat & Terdengar",
            "[Kata Benda] が 見|み えます ／ 聞|き こえます",
            [
                "見えます = terlihat (dengan sendirinya)",
                "聞こえます = terdengar (dengan sendirinya)",
                "berbeda dengan 見られます (bisa menonton) / 聞けます (bisa mendengarkan)",
            ],
            "見えます dan 聞こえます menyatakan sesuatu terlihat atau terdengar secara alami, tanpa "
            "usaha dari pembicara. Partikelnya selalu が. Bandingkan: 映画が 見られます (bisa menonton "
            "film = ada kesempatan), 山が 見えます (gunung terlihat).",
            [
                ("窓|まど から 富士山|ふじさん が 見|み えます。", "Dari jendela terlihat Gunung Fuji."),
                ("隣|となり の 部屋|へや から 声|こえ が 聞|き こえます。", "Dari kamar sebelah terdengar suara."),
                ("夜|よる は 波|なみ の 音|おと が 聞|き こえます。", "Pada malam hari terdengar suara ombak."),
            ],
        ),
        BUNPO(
            "b27-3", "N が できます — Selesai Dibangun / Terbentuk",
            "[Kata Benda] が できました",
            [
                "untuk gedung, jalan, fasilitas, toko",
                "berarti telah selesai dibangun / telah ada",
                "jangan disamakan dengan 〜ことができます (kemampuan)",
            ],
            "できます juga berarti “jadi / selesai dibangun / terbentuk” ketika subjeknya berupa "
            "bangunan atau fasilitas. Kalimat ini bercerita tentang perubahan di lingkungan sekitar.",
            [
                ("駅前|えきまえ に 大|おお きい スーパー が できました。",
                 "Di depan stasiun telah dibangun supermarket besar."),
                ("1994年|せんきゅうひゃくきゅうじゅうよねん に 関西空港|かんさいくうこう が できました。",
                 "Bandara Kansai selesai dibangun pada tahun 1994."),
                ("近|ちか く に 新|あたら しい マンション が できました。",
                 "Di dekat sini telah berdiri apartemen baru."),
            ],
        ),
        BUNPO(
            "b27-4", "N しか〜ません — Hanya ／ A は〜が、B は〜 — Kontras",
            "[Kata Benda] しか ～ません",
            [
                "しか WAJIB dipasangkan dengan bentuk negatif",
                "500円しか ありません = hanya ada 500 yen",
                "kontras: [A] は 〜が、 [B] は 〜",
            ],
            "しか berarti “hanya” dan selalu diikuti bentuk negatif — kebalikan dari だけ yang "
            "diikuti bentuk positif. Untuk membandingkan dua hal yang berbeda, pakai は〜が、は〜.",
            [
                ("財布|さいふ の 中|なか に 500円|ごひゃくえん しか ありません。",
                 "Di dompet hanya ada 500 yen."),
                ("日本語|にほんご の クラス は 月曜日|げつようび しか ありません。",
                 "Kelas bahasa Jepang hanya ada hari Senin."),
                ("肉|にく は 食|た べられます が、 魚|さかな は 食|た べられません。",
                 "Daging bisa saya makan, tetapi ikan tidak."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k27-1", "飼います", "かいます", "kaimasu", "memelihara (hewan)", "Kata Kerja",
               ("猫|ねこ を 飼|か って います。", "Saya memelihara kucing.")),
        KOTOBA("k27-2", "建てます", "たてます", "tatemasu", "membangun", "Kata Kerja",
               ("駅前|えきまえ に ビル を 建|た てて います。", "Mereka sedang membangun gedung di depan stasiun.")),
        KOTOBA("k27-3", "走ります", "はしります", "hashirimasu", "berlari; melaju", "Kata Kerja",
               ("道|みち を 走|はし ります。", "Berlari di jalan.")),
        KOTOBA("k27-4", "見えます", "みえます", "miemasu", "terlihat", "Kata Kerja",
               ("山|やま が 見|み えます。", "Gunungnya terlihat.")),
        KOTOBA("k27-5", "聞こえます", "きこえます", "kikoemasu", "terdengar", "Kata Kerja",
               ("音|おと が 聞|き こえます。", "Terdengar suara.")),
        KOTOBA("k27-6", "できます", "できます", "dekimasu", "selesai dibangun; terbentuk", "Kata Kerja",
               ("空港|くうこう が できました。", "Bandaranya telah selesai dibangun.")),
        KOTOBA("k27-7", "開きます", "ひらきます", "hirakimasu", "membuka; menyelenggarakan", "Kata Kerja",
               ("日本語|にほんご の 教室|きょうしつ を 開|ひら きました。", "Membuka kelas bahasa Jepang.")),
        KOTOBA("k27-8", "ペット", "ペット", "petto", "hewan peliharaan", "Kata Benda",
               ("ペット を 飼|か いたい です。", "Saya ingin memelihara hewan.")),
        KOTOBA("k27-9", "鳥", "とり", "tori", "burung", "Kata Benda",
               ("鳥|とり の 声|こえ が 聞|き こえます。", "Terdengar suara burung.")),
        KOTOBA("k27-10", "声", "こえ", "koe", "suara", "Kata Benda",
               ("大|おお きい 声|こえ で 話|はな さないで ください。", "Tolong jangan bicara dengan suara keras.")),
        KOTOBA("k27-11", "波", "なみ", "nami", "ombak", "Kata Benda",
               ("波|なみ の 音|おと が 聞|き こえます。", "Terdengar suara ombak.")),
        KOTOBA("k27-12", "花火", "はなび", "hanabi", "kembang api", "Kata Benda",
               ("夏|なつ に 花火|はなび が 見|み えます。", "Pada musim panas terlihat kembang api.")),
        KOTOBA("k27-13", "景色", "けしき", "keshiki", "pemandangan", "Kata Benda",
               ("ここ は 景色|けしき が きれい です。", "Pemandangan di sini indah.")),
        KOTOBA("k27-14", "昔", "むかし", "mukashi", "zaman dahulu", "Kata Benda",
               ("昔|むかし は ここ に 何|なに も ありません でした。", "Dahulu di sini tidak ada apa-apa.")),
        KOTOBA("k27-15", "自動販売機", "じどうはんばいき", "jidōhanbaiki", "mesin penjual otomatis", "Kata Benda",
               ("自動販売機|じどうはんばいき で 水|みず を 買|か いました。", "Saya membeli air di mesin penjual otomatis.")),
        KOTOBA("k27-16", "マンション", "マンション", "manshon", "apartemen", "Kata Benda",
               ("新|あたら しい マンション に 引|ひ っ越|こ しました。", "Saya pindah ke apartemen baru.")),
        KOTOBA("k27-17", "夢", "ゆめ", "yume", "mimpi; cita-cita", "Kata Benda",
               ("夢|ゆめ は 先生|せんせい に なる こと です。", "Cita-cita saya adalah menjadi guru.")),
        KOTOBA("k27-18", "いつか", "いつか", "itsuka", "suatu hari nanti", "Kata Keterangan",
               ("いつか 日本|にほん へ 行|い きたい です。", "Suatu hari nanti saya ingin pergi ke Jepang.")),
    ],
    kanji=[
        KANJI("j27-1", "飼", "シ", "か(う)", "pelihara", 13,
              [("飼います", "かいます", "memelihara"), ("飼い主", "かいぬし", "pemilik hewan")]),
        KANJI("j27-2", "建", "ケン", "た(てる)", "bangun", 9,
              [("建てます", "たてます", "membangun"), ("建物", "たてもの", "bangunan")]),
        KANJI("j27-3", "走", "ソウ", "はし(る)", "lari", 7,
              [("走ります", "はしります", "berlari"), ("走者", "そうしゃ", "pelari")]),
        KANJI("j27-4", "昔", "セキ", "むかし", "dahulu", 8,
              [("昔", "むかし", "zaman dahulu"), ("昔話", "むかしばなし", "cerita rakyat")]),
        KANJI("j27-5", "波", "ハ", "なみ", "ombak", 8,
              [("波", "なみ", "ombak"), ("電波", "でんぱ", "gelombang radio")]),
        KANJI("j27-6", "景", "ケイ", "—", "pemandangan", 12,
              [("景色", "けしき", "pemandangan"), ("背景", "はいけい", "latar belakang")]),
    ],
    kaiwa=KAIWA(
        "新しい アパート — Apartemen Baru",
        "Sari berkunjung ke apartemen baru Rina. Keduanya berbincang sambil melihat pemandangan dari jendela.",
        [
            ("サリ", "Sari", "わあ、 窓|まど から 海|うみ が 見|み えます ね。",
             "Wah, dari jendela terlihat laut, ya."),
            ("リナ", "Rina", "ええ。 夜|よる は 波|なみ の 音|おと が 聞|き こえます よ。",
             "Iya. Kalau malam terdengar suara ombak, lho."),
            ("サリ", "Sari", "ここ は ペット が 飼|か えます か。", "Di sini bisa memelihara hewan?"),
            ("リナ", "Rina", "犬|いぬ は 飼|か えません が、 鳥|とり は 飼|か えます。",
             "Anjing tidak boleh, tetapi burung boleh."),
            ("サリ", "Sari", "この 辺|へん に スーパー が できました ね。",
             "Di sekitar sini sudah ada supermarket, ya."),
            ("リナ", "Rina", "ええ、 先月|せんげつ できました。 とても 便利|べんり です。",
             "Iya, dibangun bulan lalu. Sangat praktis."),
        ],
    ),
    quiz_bunpo=[
        QB("qb27-1", "わたし は 泳|およ ＿＿。", ["げます", "ぎられます", "げるます", "べます"], 0,
           "わたし は 泳|およ げます。", "泳げます", "Gol I: baris い → baris え ＋ ます",
           "Golongan I mengubah bunyi い menjadi え: 泳ぎます → 泳げます."),
        QB("qb27-2", "ここ から 山|やま が ＿＿。", ["見えます", "見ます", "見られます", "見せます"], 0,
           "ここ から 山|やま が 見|み えます。", "見えます", "[Kata Benda] が 見えます",
           "見えます berarti terlihat dengan sendirinya; partikelnya が."),
        QB("qb27-3", "駅前|えきまえ に 新|あたら しい ビル が ＿＿。", ["できました", "しました", "ありました", "なりました"], 0,
           "駅前|えきまえ に 新|あたら しい ビル が できました。", "できました", "[Kata Benda] が できました",
           "できました untuk bangunan atau fasilitas berarti telah selesai dibangun / telah ada."),
        QB_ID("qb27-4", "“Di dompet hanya ada 500 yen.”",
              ["財布|さいふ に 500円|ごひゃくえん しか ありません。",
               "財布|さいふ に 500円|ごひゃくえん だけ ありません。",
               "財布|さいふ に 500円|ごひゃくえん しか あります。",
               "財布|さいふ に 500円|ごひゃくえん も ありません。"], 0,
              "財布|さいふ に 500円|ごひゃくえん しか ありません。", "しか〜ありません",
              "[Kata Benda] しか ～ません",
              "しか selalu dipasangkan dengan bentuk negatif dan berarti hanya."),
    ],
    quiz_susun=[
        QS("qs27-1", "Dari jendela terlihat Gunung Fuji.",
           "窓|まど から 富士山|ふじさん が 見|み えます", "聞|き こえます 海|うみ"),
        QS("qs27-2", "Saya bisa berbicara bahasa Jepang sedikit.",
           "わたし は 日本語|にほんご が 少|すこ し 話|はな せます", "読|よ めます たくさん"),
        QS("qs27-3", "Bulan lalu telah dibangun supermarket baru.",
           "先月|せんげつ 新|あたら しい スーパー が できました", "ありました 駅|えき"),
    ],
)

BAB28 = CHAPTER(
    28, "お茶を 飲みながら 話しましょう。", "Mari mengobrol sambil minum teh.",
    bunpo=[
        BUNPO(
            "b28-1", "V1 ながら V2 — Sambil Melakukan",
            "[Kata Kerja bentuk ます tanpa ます] ながら [Kata Kerja]",
            [
                "buang ます, sambungkan ながら: 飲|の みます → 飲みながら",
                "aksi UTAMA ada di kata kerja kedua",
                "subjek kedua aksi harus sama",
            ],
            "ながら menghubungkan dua aksi yang dilakukan bersamaan oleh orang yang sama. "
            "Aksi yang dianggap utama diletakkan di kata kerja sesudah ながら.",
            [
                ("音楽|おんがく を 聞|き きながら 勉強|べんきょう します。", "Saya belajar sambil mendengarkan musik."),
                ("お茶|ちゃ を 飲|の みながら 話|はな しましょう。", "Mari mengobrol sambil minum teh."),
                ("歩|ある きながら 写真|しゃしん を 撮|と りました。", "Saya memotret sambil berjalan."),
            ],
        ),
        BUNPO(
            "b28-2", "V ています — Kebiasaan & Pekerjaan Tetap",
            "[Kata Kerja bentuk て] います",
            [
                "aksi sedang berlangsung: 今|いま 食|た べて います",
                "kebiasaan rutin: 毎朝|まいあさ 走|はし って います",
                "pekerjaan tetap: 銀行|ぎんこう で 働|はたら いて います",
            ],
            "Selain menyatakan aksi yang sedang berlangsung, 〜ています juga menyatakan kebiasaan "
            "yang dilakukan berulang atau keadaan tetap seperti pekerjaan dan tempat kuliah. "
            "Lihat kata keterangan waktunya untuk menentukan makna.",
            [
                ("毎朝|まいあさ ジョギング して います。", "Saya rutin jogging setiap pagi."),
                ("兄|あに は 銀行|ぎんこう で 働|はたら いて います。", "Kakak saya bekerja di bank."),
                ("大学|だいがく に 通|かよ って います。", "Saya berkuliah (rutin ke universitas)."),
            ],
        ),
        BUNPO(
            "b28-3", "〜し、〜し — Mendaftar Alasan",
            "[Bentuk Biasa] し、 [Bentuk Biasa] し",
            [
                "mendaftar dua alasan atau lebih sekaligus",
                "kesan: bukan hanya itu, tapi juga…",
                "bisa untuk kata kerja, kata sifat, dan kata benda (〜だし)",
            ],
            "Partikel し dipakai untuk menyebutkan beberapa alasan atau keadaan sekaligus, dengan "
            "kesan “lagipula”. Untuk kata benda dan kata sifat-na, bentuknya 〜だし.",
            [
                ("この 店|みせ は 安|やす い し、 おいしい し、 大好|だいす き です。",
                 "Toko ini murah, enak pula, jadi saya sangat suka."),
                ("あの 先生|せんせい は 優|やさ しい し、 熱心|ねっしん だ し、 人気|にんき が あります。",
                 "Guru itu baik hati, penuh semangat pula, jadi populer."),
                ("雨|あめ だ し、 風|かぜ も 強|つよ い し、 家|いえ に います。",
                 "Hujan, anginnya juga kencang, jadi saya di rumah saja."),
            ],
        ),
        BUNPO(
            "b28-4", "N が します — Bau, Bunyi, Rasa",
            "[Kata Benda] が します",
            [
                "におい が します = tercium bau",
                "音|おと / 声|こえ が します = terdengar bunyi",
                "味|あじ / 感|かん じ が します = berasa / terasa",
            ],
            "Untuk hal yang ditangkap pancaindra (bau, bunyi, rasa, kesan), bahasa Jepang memakai "
            "pola [Kata Benda] が します, bukan あります.",
            [
                ("いい におい が します ね。", "Tercium bau harum, ya."),
                ("変|へん な 音|おと が します。", "Terdengar bunyi aneh."),
                ("この 料理|りょうり は レモン の 味|あじ が します。", "Masakan ini berasa lemon."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k28-1", "売れます", "うれます", "uremasu", "laku; terjual", "Kata Kerja",
               ("この 本|ほん は よく 売|う れます。", "Buku ini laku keras.")),
        KOTOBA("k28-2", "踊ります", "おどります", "odorimasu", "menari", "Kata Kerja",
               ("祭|まつ り で 踊|おど ります。", "Menari di festival.")),
        KOTOBA("k28-3", "かみます", "かみます", "kamimasu", "mengunyah; menggigit", "Kata Kerja",
               ("よく かんで 食|た べて ください。", "Tolong makan dengan dikunyah baik-baik.")),
        KOTOBA("k28-4", "選びます", "えらびます", "erabimasu", "memilih", "Kata Kerja",
               ("プレゼント を 選|えら びます。", "Memilih hadiah.")),
        KOTOBA("k28-5", "違います", "ちがいます", "chigaimasu", "berbeda; salah", "Kata Kerja",
               ("答|こた え が 違|ちが います。", "Jawabannya salah.")),
        KOTOBA("k28-6", "通います", "かよいます", "kayoimasu", "pulang-pergi; bersekolah", "Kata Kerja",
               ("大学|だいがく に 通|かよ って います。", "Saya berkuliah.")),
        KOTOBA("k28-7", "メモします", "メモします", "memo shimasu", "mencatat", "Kata Kerja",
               ("電話番号|でんわばんごう を メモ しました。", "Saya mencatat nomor teleponnya.")),
        KOTOBA("k28-8", "熱心", "ねっしん", "nesshin", "penuh semangat", "Kata Sifat-na",
               ("熱心|ねっしん に 勉強|べんきょう して います。", "Dia belajar dengan penuh semangat.")),
        KOTOBA("k28-9", "優しい", "やさしい", "yasashii", "baik hati; lembut", "Kata Sifat-i",
               ("優|やさ しい 先生|せんせい です。", "Guru yang baik hati.")),
        KOTOBA("k28-10", "ちょうどいい", "ちょうどいい", "chōdo ii", "pas; tepat", "Kata Sifat-i",
               ("この 靴|くつ は ちょうど いい です。", "Sepatu ini pas.")),
        KOTOBA("k28-11", "習慣", "しゅうかん", "shūkan", "kebiasaan; adat", "Kata Benda",
               ("日本|にほん の 習慣|しゅうかん を 勉強|べんきょう します。", "Saya mempelajari adat Jepang.")),
        KOTOBA("k28-12", "経験", "けいけん", "keiken", "pengalaman", "Kata Benda",
               ("いい 経験|けいけん に なりました。", "Itu menjadi pengalaman yang baik.")),
        KOTOBA("k28-13", "人気", "にんき", "ninki", "popularitas; populer", "Kata Benda",
               ("この 歌手|かしゅ は 人気|にんき が あります。", "Penyanyi ini populer.")),
        KOTOBA("k28-14", "値段", "ねだん", "nedan", "harga", "Kata Benda",
               ("値段|ねだん が 高|たか い です。", "Harganya mahal.")),
        KOTOBA("k28-15", "給料", "きゅうりょう", "kyūryō", "gaji", "Kata Benda",
               ("給料|きゅうりょう が 上|あ がりました。", "Gajinya naik.")),
        KOTOBA("k28-16", "番組", "ばんぐみ", "bangumi", "acara (TV/radio)", "Kata Benda",
               ("この 番組|ばんぐみ は おもしろい です。", "Acara ini menarik.")),
        KOTOBA("k28-17", "小説", "しょうせつ", "shōsetsu", "novel", "Kata Benda",
               ("小説|しょうせつ を 読|よ む の が 好|す き です。", "Saya suka membaca novel.")),
        KOTOBA("k28-18", "たいてい", "たいてい", "taitei", "biasanya; umumnya", "Kata Keterangan",
               ("たいてい 7時|しちじ に 起|お きます。", "Saya biasanya bangun jam 7.")),
    ],
    kanji=[
        KANJI("j28-1", "売", "バイ", "う(る)", "jual", 7,
              [("売れます", "うれます", "laku"), ("販売", "はんばい", "penjualan")]),
        KANJI("j28-2", "踊", "ヨウ", "おど(る)", "tari", 14,
              [("踊ります", "おどります", "menari"), ("盆踊り", "ぼんおどり", "tari Bon")]),
        KANJI("j28-3", "選", "セン", "えら(ぶ)", "pilih", 15,
              [("選びます", "えらびます", "memilih"), ("選挙", "せんきょ", "pemilihan umum")]),
        KANJI("j28-4", "違", "イ", "ちが(う)", "beda; salah", 13,
              [("違います", "ちがいます", "berbeda"), ("間違い", "まちがい", "kesalahan")]),
        KANJI("j28-5", "通", "ツウ", "かよ(う)", "lewat; pulang-pergi", 10,
              [("通います", "かよいます", "pulang-pergi"), ("通学", "つうがく", "pergi ke sekolah")]),
        KANJI("j28-6", "番", "バン", "—", "nomor; urutan", 12,
              [("番組", "ばんぐみ", "acara"), ("番号", "ばんごう", "nomor")]),
    ],
    kaiwa=KAIWA(
        "お弁当 — Bekal Makan Siang",
        "Istirahat makan siang di kantor. Tan dan Bu Kimura mengobrol sambil makan.",
        [
            ("タン", "Tan", "いい におい が します ね。 何|なん です か。",
             "Tercium bau harum, ya. Itu apa?"),
            ("木村", "Kimura", "カレー です。 よかったら、 食|た べながら 話|はな しません か。",
             "Kari. Kalau mau, ngobrol sambil makan, yuk?"),
            ("タン", "Tan", "いい です ね。 木村|きむら さん は 毎日|まいにち 弁当|べんとう を 作|つく って いるん です か。",
             "Boleh. Bu Kimura membuat bekal setiap hari?"),
            ("木村", "Kimura", "ええ。 安|やす い し、 体|からだ に いい し、 たいてい 作|つく ります。",
             "Iya. Murah, sehat pula, jadi biasanya saya buat sendiri."),
            ("タン", "Tan", "すごい です ね。 わたし は いつも コンビニ です。",
             "Hebat, ya. Saya selalu beli di minimarket."),
            ("木村", "Kimura", "今度|こんど いっしょ に 作|つく りましょう か。",
             "Lain kali kita buat bersama, ya?"),
        ],
    ),
    quiz_bunpo=[
        QB("qb28-1", "音楽|おんがく を 聞|き き ＿＿ 勉強|べんきょう します。", ["ながら", "なから", "あいだ", "まま"], 0,
           "音楽|おんがく を 聞|き きながら 勉強|べんきょう します。", "ながら", "[Vます tanpa ます] ながら",
           "ながら berarti sambil; aksi utama ada pada kata kerja sesudahnya."),
        QB("qb28-2", "この 店|みせ は 安|やす い ＿＿、 おいしい です。", ["し", "が", "ので", "から"], 0,
           "この 店|みせ は 安|やす い し、 おいしい です。", "し", "[Bentuk Biasa] し、 〜し",
           "し dipakai untuk mendaftar beberapa alasan sekaligus."),
        QB("qb28-3", "兄|あに は 銀行|ぎんこう で 働|はたら いて ＿＿。", ["います", "あります", "おきます", "しまいます"], 0,
           "兄|あに は 銀行|ぎんこう で 働|はたら いて います。", "働いています", "Vて います (pekerjaan tetap)",
           "〜ています di sini menyatakan pekerjaan tetap, bukan aksi yang sedang berlangsung."),
        QB_ID("qb28-4", "“Tercium bau harum dari dapur.”",
              ["台所|だいどころ から いい におい が します。",
               "台所|だいどころ で いい におい が あります。",
               "台所|だいどころ から いい におい が 見|み えます。",
               "台所|だいどころ から いい におい が 聞|き こえます。"], 0,
              "台所|だいどころ から いい におい が します。", "においが します", "[Kata Benda] が します",
              "Bau, bunyi, dan rasa memakai pola Nがします, bukan あります."),
    ],
    quiz_susun=[
        QS("qs28-1", "Saya belajar sambil mendengarkan musik.",
           "音楽|おんがく を 聞|き きながら 勉強|べんきょう します", "食|た べながら 寝|ね ます"),
        QS("qs28-2", "Guru itu baik hati dan juga penuh semangat.",
           "あの 先生|せんせい は 優|やさ しい し 熱心|ねっしん です", "まじめ でも"),
        QS("qs28-3", "Kakak saya bekerja di bank.",
           "兄|あに は 銀行|ぎんこう で 働|はたら いて います", "遊|あそ んで 会社|かいしゃ"),
    ],
)

BAB29 = CHAPTER(
    29, "傘を 電車に 忘れて しまいました。", "Saya terlanjur meninggalkan payung di kereta.",
    bunpo=[
        BUNPO(
            "b29-1", "Kata Kerja Intransitif + ています — Keadaan",
            "[Kata Benda] が [Kata Kerja Intransitif bentuk て] います",
            [
                "menyatakan KEADAAN hasil suatu perubahan",
                "pasangan 開|あ きます / 開|あ けます (terbuka / membuka)",
                "pasangan 閉|し まります / 閉|し めます (tertutup / menutup)",
                "pasangan つきます / つけます (menyala / menyalakan)",
                "pasangan 消|き えます / 消|け します (padam / mematikan)",
            ],
            "Kata kerja berpasangan: intransitif (terjadi sendiri) dan transitif (dilakukan seseorang). "
            "Intransitif + ています menyatakan keadaan yang terlihat sekarang: 窓が 開いています = "
            "jendelanya (sedang) terbuka. Partikelnya が, bukan を.",
            [
                ("ドア が 開|あ いて います。", "Pintunya terbuka."),
                ("窓|まど が 割|わ れて います。", "Jendelanya pecah."),
                ("電気|でんき が 消|き えて います。", "Lampunya padam."),
            ],
        ),
        BUNPO(
            "b29-2", "〜てしまいます — Selesai Sampai Tuntas",
            "[Kata Kerja bentuk て] しまいます",
            [
                "menyatakan aksi diselesaikan sampai habis",
                "bentuk percakapan: 〜ちゃいます / 〜じゃいます",
                "食|た べてしまいます → 食べちゃいます",
            ],
            "Salah satu makna 〜てしまいます adalah menyelesaikan sesuatu sampai tuntas. Dalam "
            "percakapan sehari-hari sering diringkas menjadi 〜ちゃいます.",
            [
                ("宿題|しゅくだい を 全部|ぜんぶ して しまいました。", "PR sudah saya kerjakan semua."),
                ("この 本|ほん は もう 読|よ んで しまいました。", "Buku ini sudah selesai saya baca."),
                ("ケーキ を 全部|ぜんぶ 食|た べて しまいました。", "Kuenya habis dimakan semua."),
            ],
        ),
        BUNPO(
            "b29-3", "〜てしまいます — Menyesal / Tidak Sengaja",
            "[Kata Kerja bentuk て] しまいます",
            [
                "menyatakan kejadian yang disesalkan",
                "atau kejadian yang terjadi tanpa sengaja",
                "sering dipakai saat meminta maaf atau melapor",
            ],
            "〜てしまいます juga menyatakan bahwa sesuatu terjadi di luar kehendak dan disesalkan. "
            "Pola inilah yang dipakai saat melaporkan barang hilang atau kesalahan.",
            [
                ("傘|かさ を 電車|でんしゃ に 忘|わす れて しまいました。",
                 "Saya terlanjur meninggalkan payung di kereta."),
                ("財布|さいふ を 落|お として しまいました。", "Dompet saya terjatuh (tidak sengaja)."),
                ("大切|たいせつ な コップ を 割|わ って しまいました。", "Gelas kesayangan saya terlanjur pecah."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k29-1", "開きます", "あきます", "akimasu", "terbuka", "Kata Kerja",
               ("ドア が 開|あ きました。", "Pintunya terbuka.")),
        KOTOBA("k29-2", "閉まります", "しまります", "shimarimasu", "tertutup", "Kata Kerja",
               ("店|みせ が 閉|し まりました。", "Tokonya sudah tutup.")),
        KOTOBA("k29-3", "つきます", "つきます", "tsukimasu", "menyala", "Kata Kerja",
               ("電気|でんき が つきました。", "Lampunya menyala.")),
        KOTOBA("k29-4", "消えます", "きえます", "kiemasu", "padam; hilang", "Kata Kerja",
               ("電気|でんき が 消|き えました。", "Lampunya padam.")),
        KOTOBA("k29-5", "込みます", "こみます", "komimasu", "padat; ramai", "Kata Kerja",
               ("道|みち が 込|こ んで います。", "Jalannya padat.")),
        KOTOBA("k29-6", "壊れます", "こわれます", "kowaremasu", "rusak", "Kata Kerja",
               ("椅子|いす が 壊|こわ れました。", "Kursinya rusak.")),
        KOTOBA("k29-7", "割れます", "われます", "waremasu", "pecah", "Kata Kerja",
               ("コップ が 割|わ れました。", "Gelasnya pecah.")),
        KOTOBA("k29-8", "折れます", "おれます", "oremasu", "patah", "Kata Kerja",
               ("木|き の 枝|えだ が 折|お れました。", "Dahan pohonnya patah.")),
        KOTOBA("k29-9", "破れます", "やぶれます", "yaburemasu", "sobek", "Kata Kerja",
               ("紙|かみ が 破|やぶ れました。", "Kertasnya sobek.")),
        KOTOBA("k29-10", "汚れます", "よごれます", "yogoremasu", "kotor", "Kata Kerja",
               ("服|ふく が 汚|よご れました。", "Bajunya kotor.")),
        KOTOBA("k29-11", "付きます", "つきます", "tsukimasu", "terpasang; melekat", "Kata Kerja",
               ("ポケット が 付|つ いて います。", "Ada sakunya (terpasang).")),
        KOTOBA("k29-12", "外れます", "はずれます", "hazuremasu", "terlepas", "Kata Kerja",
               ("ボタン が 外|はず れました。", "Kancingnya lepas.")),
        KOTOBA("k29-13", "落とします", "おとします", "otoshimasu", "menjatuhkan; kehilangan", "Kata Kerja",
               ("財布|さいふ を 落|お としました。", "Saya menjatuhkan dompet.")),
        KOTOBA("k29-14", "お皿", "おさら", "osara", "piring", "Kata Benda",
               ("お皿|おさら を 洗|あら います。", "Mencuci piring.")),
        KOTOBA("k29-15", "袋", "ふくろ", "fukuro", "kantong", "Kata Benda",
               ("袋|ふくろ が 破|やぶ れて います。", "Kantongnya sobek.")),
        KOTOBA("k29-16", "忘れ物", "わすれもの", "wasuremono", "barang ketinggalan", "Kata Benda",
               ("忘|わす れ物|もの を 届|とど けます。", "Melaporkan barang ketinggalan.")),
        KOTOBA("k29-17", "網棚", "あみだな", "amidana", "rak (di kereta)", "Kata Benda",
               ("網棚|あみだな に 荷物|にもつ を 置|お きます。", "Menaruh barang di rak.")),
        KOTOBA("k29-18", "確か", "たしか", "tashika", "kalau tidak salah", "Kata Keterangan",
               ("確|たし か、 あした は 休|やす み です。", "Kalau tidak salah, besok libur.")),
    ],
    kanji=[
        KANJI("j29-1", "閉", "ヘイ", "し(まる)", "tutup", 11,
              [("閉まります", "しまります", "tertutup"), ("開閉", "かいへい", "buka-tutup")]),
        KANJI("j29-2", "消", "ショウ", "き(える)", "padam; hapus", 10,
              [("消えます", "きえます", "padam"), ("消火", "しょうか", "pemadaman api")]),
        KANJI("j29-3", "壊", "カイ", "こわ(れる)", "rusak", 16,
              [("壊れます", "こわれます", "rusak"), ("破壊", "はかい", "kehancuran")]),
        KANJI("j29-4", "割", "カツ", "わ(れる)", "pecah; belah", 12,
              [("割れます", "われます", "pecah"), ("割合", "わりあい", "persentase")]),
        KANJI("j29-5", "破", "ハ", "やぶ(れる)", "sobek", 10,
              [("破れます", "やぶれます", "sobek"), ("破産", "はさん", "kebangkrutan")]),
        KANJI("j29-6", "汚", "オ", "よご(れる)", "kotor", 6,
              [("汚れます", "よごれます", "kotor"), ("汚水", "おすい", "air kotor")]),
    ],
    kaiwa=KAIWA(
        "忘れ物 — Barang Ketinggalan",
        "Sari menyadari payungnya tertinggal di kereta dan melapor ke petugas stasiun.",
        [
            ("サリ", "Sari", "すみません、 さっき の 電車|でんしゃ に 傘|かさ を 忘|わす れて しまったん です が…。",
             "Permisi, tadi saya terlanjur meninggalkan payung di kereta…"),
            ("駅員", "Ekiin", "どんな 傘|かさ です か。", "Payung yang seperti apa?"),
            ("サリ", "Sari", "赤|あか い 傘|かさ です。 網棚|あみだな の 上|うえ に 置|お いて おいたん です。",
             "Payung merah. Tadi saya taruh di atas rak."),
            ("駅員", "Ekiin", "少々|しょうしょう お待|ま ち ください。 …ああ、 確|たし か 届|とど いて います。 これ です か。",
             "Tunggu sebentar. …Ah, kalau tidak salah sudah dilaporkan. Apakah ini?"),
            ("サリ", "Sari", "ああ、 よかった。 それ です。", "Ah, syukurlah. Itu dia."),
            ("駅員", "Ekiin", "ここ に 名前|なまえ を 書|か いて ください。", "Tolong tulis nama Anda di sini."),
            ("サリ", "Sari", "はい。 ありがとう ございました。", "Baik. Terima kasih banyak."),
        ],
    ),
    quiz_bunpo=[
        QB("qb29-1", "窓|まど が 開|あ いて ＿＿。", ["います", "あります", "おきます", "しまいます"], 0,
           "窓|まど が 開|あ いて います。", "開いています", "[Kata Benda] が [Intransitifて] います",
           "開きます (あきます) adalah kata kerja intransitif, jadi keadaannya 開いています dengan partikel が."),
        QB("qb29-2", "傘|かさ を 電車|でんしゃ に 忘|わす れて ＿＿。", ["しまいました", "おきました", "ありました", "いきました"], 0,
           "傘|かさ を 電車|でんしゃ に 忘|わす れて しまいました。", "忘れてしまいました", "Vて しまいます (menyesal)",
           "〜てしまいました di sini menyatakan kejadian yang tidak disengaja dan disesalkan."),
        QB("qb29-3", "宿題|しゅくだい を 全部|ぜんぶ して ＿＿。 もう 遊|あそ べます。", ["しまいました", "いきました", "きました", "みました"], 0,
           "宿題|しゅくだい を 全部|ぜんぶ して しまいました。", "してしまいました", "Vて しまいます (tuntas)",
           "〜てしまいます juga berarti menyelesaikan sesuatu sampai tuntas."),
        QB_ID("qb29-4", "“Lampunya padam.”",
              ["電気|でんき が 消|き えて います。",
               "電気|でんき を 消|け して います。",
               "電気|でんき が ついて います。",
               "電気|でんき を 消|け しました。"], 0,
              "電気|でんき が 消|き えて います。", "消えています", "[Kata Benda] が [Intransitifて] います",
              "Padam dengan sendirinya: 消えています (intransitif). 消しています berarti sedang mematikannya."),
    ],
    quiz_susun=[
        QS("qs29-1", "Saya terlanjur menjatuhkan dompet.",
           "財布|さいふ を 落|お として しまいました", "忘|わす れて 傘|かさ"),
        QS("qs29-2", "Pintunya tertutup.",
           "ドア が 閉|し まって います", "開|あ いて 窓|まど"),
        QS("qs29-3", "Buku ini sudah selesai saya baca.",
           "この 本|ほん は もう 読|よ んで しまいました", "まだ 書|か いて"),
    ],
)

BAB30 = CHAPTER(
    30, "ポスターが 壁に はって あります。", "Posternya tertempel di dinding.",
    bunpo=[
        BUNPO(
            "b30-1", "〜てあります — Keadaan Hasil Tindakan",
            "[Kata Benda] が [Kata Kerja Transitif bentuk て] あります",
            [
                "memakai kata kerja TRANSITIF: 掛|か けます → 掛けてあります",
                "partikel を berubah menjadi が",
                "menyiratkan seseorang sengaja melakukannya",
            ],
            "〜てあります menyatakan keadaan yang ada sekarang sebagai hasil tindakan yang sengaja "
            "dilakukan seseorang. Bedakan dengan Bab 29: 窓が 開いています (keadaan netral) vs "
            "窓が 開けてあります (dibuka dengan sengaja, mis. untuk sirkulasi udara).",
            [
                ("壁|かべ に ポスター が はって あります。", "Di dinding tertempel poster."),
                ("机|つくえ の 上|うえ に 花瓶|かびん が 飾|かざ って あります。", "Di atas meja terpasang vas bunga."),
                ("予定表|よていひょう に 会議|かいぎ の 日|ひ が 書|か いて あります。", "Di jadwal tertulis tanggal rapat."),
            ],
        ),
        BUNPO(
            "b30-2", "〜ておきます — Melakukan Dulu sebagai Persiapan",
            "[Kata Kerja bentuk て] おきます",
            [
                "melakukan sesuatu LEBIH DULU untuk keperluan nanti",
                "bentuk percakapan: 〜ときます",
                "買|か っておきます → 買っときます",
            ],
            "〜ておきます berarti melakukan suatu tindakan lebih dulu sebagai persiapan untuk hal "
            "yang akan datang: membeli tiket sebelum berangkat, merapikan kamar sebelum tamu datang.",
            [
                ("客|きゃく が 来|く る まえ に、 部屋|へや を 片|かた 付|づ けて おきます。",
                 "Sebelum tamu datang, saya rapikan kamarnya dulu."),
                ("旅行|りょこう の まえ に 切符|きっぷ を 買|か って おきました。",
                 "Sebelum berangkat, saya sudah membeli tiketnya duluan."),
                ("あした 使|つか う 資料|しりょう を コピー して おきます。",
                 "Saya fotokopi dulu bahan yang akan dipakai besok."),
            ],
        ),
        BUNPO(
            "b30-3", "まだ〜ていません — Belum ／ 〜ておきます — Membiarkan",
            "まだ [Kata Kerja bentuk て] いません",
            [
                "まだ〜ていません = belum (sampai saat ini)",
                "jawaban negatif untuk もう〜ましたか",
                "〜ておく juga bisa berarti membiarkan apa adanya",
            ],
            "Untuk menjawab もう〜ましたか dengan “belum”, pakai まだ〜ていません — bukan "
            "まだ〜ません. Selain itu 〜ておきます juga berarti membiarkan keadaan tetap seperti itu: "
            "そのままに しておいて ください (biarkan saja).",
            [
                ("まだ 昼|ひる ごはん を 食|た べて いません。", "Saya belum makan siang."),
                ("会議|かいぎ の 資料|しりょう は まだ 配|くば って いません。", "Bahan rapat belum dibagikan."),
                ("窓|まど は そのまま に して おいて ください。", "Jendelanya dibiarkan saja begitu."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k30-1", "はります", "はります", "harimasu", "menempel", "Kata Kerja",
               ("壁|かべ に ポスター を はります。", "Menempel poster di dinding.")),
        KOTOBA("k30-2", "掛けます", "かけます", "kakemasu", "menggantung", "Kata Kerja",
               ("カレンダー を 掛|か けます。", "Menggantung kalender.")),
        KOTOBA("k30-3", "飾ります", "かざります", "kazarimasu", "menghias; memajang", "Kata Kerja",
               ("花瓶|かびん を 飾|かざ ります。", "Memajang vas bunga.")),
        KOTOBA("k30-4", "並べます", "ならべます", "narabemasu", "menyusun; mengatur", "Kata Kerja",
               ("椅子|いす を 並|なら べます。", "Menyusun kursi.")),
        KOTOBA("k30-5", "植えます", "うえます", "uemasu", "menanam", "Kata Kerja",
               ("庭|にわ に 木|き を 植|う えます。", "Menanam pohon di taman.")),
        KOTOBA("k30-6", "戻します", "もどします", "modoshimasu", "mengembalikan", "Kata Kerja",
               ("本|ほん を 元|もと の 所|ところ に 戻|もど します。", "Mengembalikan buku ke tempat semula.")),
        KOTOBA("k30-7", "片付けます", "かたづけます", "katazukemasu", "membereskan", "Kata Kerja",
               ("部屋|へや を 片|かた 付|づ けます。", "Membereskan kamar.")),
        KOTOBA("k30-8", "しまいます", "しまいます", "shimaimasu", "menyimpan", "Kata Kerja",
               ("道具|どうぐ を 引|ひ き出|だ し に しまいます。", "Menyimpan perkakas di laci.")),
        KOTOBA("k30-9", "決めます", "きめます", "kimemasu", "memutuskan", "Kata Kerja",
               ("会議|かいぎ の 日|ひ を 決|き めます。", "Menentukan tanggal rapat.")),
        KOTOBA("k30-10", "知らせます", "しらせます", "shirasemasu", "memberitahukan", "Kata Kerja",
               ("結果|けっか を 知|し らせます。", "Memberitahukan hasilnya.")),
        KOTOBA("k30-11", "相談します", "そうだんします", "sōdan shimasu", "berkonsultasi; berdiskusi", "Kata Kerja",
               ("先生|せんせい に 相談|そうだん します。", "Berkonsultasi dengan guru.")),
        KOTOBA("k30-12", "予習します", "よしゅうします", "yoshū shimasu", "mempersiapkan pelajaran", "Kata Kerja",
               ("明日|あした の 授業|じゅぎょう を 予習|よしゅう します。", "Mempersiapkan pelajaran besok.")),
        KOTOBA("k30-13", "復習します", "ふくしゅうします", "fukushū shimasu", "mengulang pelajaran", "Kata Kerja",
               ("文法|ぶんぽう を 復習|ふくしゅう します。", "Mengulang tata bahasa.")),
        KOTOBA("k30-14", "予定", "よてい", "yotei", "rencana; jadwal", "Kata Benda",
               ("週末|しゅうまつ の 予定|よてい は 何|なん です か。", "Apa rencana akhir pekan ini?")),
        KOTOBA("k30-15", "予定表", "よていひょう", "yoteihyō", "jadwal (tertulis)", "Kata Benda",
               ("予定表|よていひょう に 書|か いて おきます。", "Saya tuliskan dulu di jadwal.")),
        KOTOBA("k30-16", "花瓶", "かびん", "kabin", "vas bunga", "Kata Benda",
               ("花瓶|かびん に 花|はな を 入|い れます。", "Memasukkan bunga ke vas.")),
        KOTOBA("k30-17", "鏡", "かがみ", "kagami", "cermin", "Kata Benda",
               ("鏡|かがみ を 見|み ます。", "Bercermin.")),
        KOTOBA("k30-18", "隅", "すみ", "sumi", "sudut", "Kata Benda",
               ("部屋|へや の 隅|すみ に 本棚|ほんだな が あります。", "Di sudut ruangan ada rak buku.")),
    ],
    kanji=[
        KANJI("j30-1", "掛", "カイ", "か(ける)", "gantung", 11,
              [("掛けます", "かけます", "menggantung"), ("掛け算", "かけざん", "perkalian")]),
        KANJI("j30-2", "飾", "ショク", "かざ(る)", "hias", 13,
              [("飾ります", "かざります", "menghias"), ("装飾", "そうしょく", "dekorasi")]),
        KANJI("j30-3", "並", "ヘイ", "なら(べる)", "baris; susun", 8,
              [("並べます", "ならべます", "menyusun"), ("並木", "なみき", "deretan pohon")]),
        KANJI("j30-4", "植", "ショク", "う(える)", "tanam", 12,
              [("植えます", "うえます", "menanam"), ("植物", "しょくぶつ", "tumbuhan")]),
        KANJI("j30-5", "決", "ケツ", "き(める)", "putuskan", 7,
              [("決めます", "きめます", "memutuskan"), ("解決", "かいけつ", "penyelesaian")]),
        KANJI("j30-6", "鏡", "キョウ", "かがみ", "cermin", 19,
              [("鏡", "かがみ", "cermin"), ("眼鏡", "めがね", "kacamata")]),
    ],
    kaiwa=KAIWA(
        "パーティーの 準備 — Persiapan Pesta",
        "Bu Sato dan Wang menyiapkan ruangan untuk pesta perpisahan di kantor.",
        [
            ("佐藤", "Satō", "ポスター は 壁|かべ に はって あります か。",
             "Posternya sudah ditempel di dinding?"),
            ("ワン", "Wan", "はい、 玄関|げんかん の 前|まえ にも はって おきました。",
             "Sudah, saya tempel juga di depan pintu masuk."),
            ("佐藤", "Satō", "椅子|いす は まだ 並|なら べて いません ね。",
             "Kursinya belum disusun, ya."),
            ("ワン", "Wan", "すみません、 今|いま 並|なら べます。 花瓶|かびん は どこ に 飾|かざ りましょう か。",
             "Maaf, sekarang saya susun. Vas bunganya dipajang di mana?"),
            ("佐藤", "Satō", "部屋|へや の 真ん中|まんなか の テーブル の 上|うえ に お願|ねが いします。",
             "Di atas meja di tengah ruangan, ya."),
            ("ワン", "Wan", "わかりました。 終|お わったら、 全部|ぜんぶ 片|かた 付|づ けて おきます。",
             "Baik. Kalau sudah selesai, semuanya akan saya bereskan dulu."),
        ],
    ),
    quiz_bunpo=[
        QB("qb30-1", "壁|かべ に カレンダー が 掛|か けて ＿＿。", ["あります", "います", "おきます", "しまいます"], 0,
           "壁|かべ に カレンダー が 掛|か けて あります。", "掛けてあります", "[Kata Benda] が [Transitifて] あります",
           "てあります menyatakan keadaan hasil tindakan sengaja; partikel を berubah menjadi が."),
        QB("qb30-2", "客|きゃく が 来|く る まえ に、 部屋|へや を 片|かた 付|づ けて ＿＿。", ["おきます", "あります", "います", "なります"], 0,
           "客|きゃく が 来|く る まえ に、 部屋|へや を 片|かた 付|づ けて おきます。", "片付けておきます", "Vて おきます",
           "〜ておきます berarti melakukan lebih dulu sebagai persiapan."),
        QB("qb30-3", "昼|ひる ごはん は もう 食|た べました か。 — いいえ、 まだ 食|た べて ＿＿。", ["いません", "ありません", "おきません", "しまいません"], 0,
           "いいえ、 まだ 食|た べて いません。", "まだ〜ていません", "まだ Vて いません",
           "まだ〜ていません berarti belum sampai saat ini; jawaban standar untuk もう〜ましたか."),
        QB_ID("qb30-4", "“Di dinding tertempel poster.”",
              ["壁|かべ に ポスター が はって あります。",
               "壁|かべ に ポスター を はって います。",
               "壁|かべ の ポスター が はります。",
               "壁|かべ に ポスター が はります。"], 0,
              "壁|かべ に ポスター が はって あります。", "はってあります", "[Kata Benda] が Vて あります",
              "Menyatakan keadaan (sudah ditempel oleh seseorang), bukan aksi yang sedang berlangsung."),
    ],
    quiz_susun=[
        QS("qs30-1", "Sebelum tamu datang, saya rapikan kamarnya dulu.",
           "客|きゃく が 来|く る まえ に 部屋|へや を 片|かた 付|づ けて おきます", "寝|ね て しまいます"),
        QS("qs30-2", "Di atas meja terpasang vas bunga.",
           "机|つくえ の 上|うえ に 花瓶|かびん が 飾|かざ って あります", "置|お いて います 本|ほん"),
        QS("qs30-3", "Saya belum membeli tiketnya.",
           "まだ 切符|きっぷ を 買|か って いません", "もう 予約|よやく して"),
    ],
)

CHAPTERS = [BAB26, BAB27, BAB28, BAB29, BAB30]
