"""Materi Minna no Nihongo 2 — Bab 36 s/d 40."""

from seed_data.dsl import BUNPO, CHAPTER, KAIWA, KANJI, KOTOBA, QB, QB_ID, QS

BAB36 = CHAPTER(
    36, "日本語が 話せるように なりました。", "Akhirnya saya menjadi bisa berbahasa Jepang.",
    bunpo=[
        BUNPO(
            "b36-1", "〜ように — Supaya / Agar (Tujuan)",
            "[Bentuk kamus / ない形] ように、 〜",
            [
                "V1 biasanya kata kerja non-kehendak: 見えます, 聞こえます, 分かります, bentuk kemungkinan",
                "V2 adalah aksi yang disengaja untuk mencapai tujuan itu",
                "berbeda dengan 〜ために yang memakai kata kerja kehendak",
            ],
            "〜ように menyatakan tujuan ketika bagian depannya berupa keadaan yang tidak langsung "
            "dikendalikan (terlihat, bisa, mengerti). Untuk aksi yang memang dikehendaki "
            "(行く, 買う), tujuannya memakai 〜に 行く (Bab 13) atau 〜ために.",
            [
                ("よく 見|み える ように、 大|おお きい 字|じ で 書|か きました。",
                 "Saya menulis dengan huruf besar supaya mudah terlihat."),
                ("忘|わす れない ように、 メモ して おきます。", "Supaya tidak lupa, saya catat dulu."),
                ("みんな に 聞|き こえる ように、 大|おお きい 声|こえ で 話|はな しました。",
                 "Saya berbicara dengan suara keras supaya terdengar semua orang."),
            ],
        ),
        BUNPO(
            "b36-2", "〜ように なります — Menjadi Bisa / Menjadi Terbiasa",
            "[Bentuk kamus / ない形] ように なります",
            [
                "menyatakan perubahan keadaan atau kemampuan",
                "positif: 話|はな せる ように なりました (menjadi bisa)",
                "negatif: 食|た べない ように なりました (menjadi tidak makan lagi)",
            ],
            "Sama seperti 〜く なります untuk kata sifat, 〜ように なります menyatakan perubahan — "
            "tetapi untuk kata kerja: dari tidak bisa menjadi bisa, dari terbiasa menjadi tidak lagi.",
            [
                ("やっと 新聞|しんぶん が 読|よ める ように なりました。",
                 "Akhirnya saya menjadi bisa membaca surat kabar."),
                ("日本|にほん の 生活|せいかつ に 慣|な れる ように なりました。",
                 "Saya sudah menjadi terbiasa dengan kehidupan di Jepang."),
                ("最近|さいきん 甘|あま い もの を 食|た べない ように なりました。",
                 "Akhir-akhir ini saya menjadi tidak makan yang manis."),
            ],
        ),
        BUNPO(
            "b36-3", "〜ように しています ／ 〜ように してください",
            "[Bentuk kamus / ない形] ように しています",
            [
                "〜ように しています = membiasakan diri melakukan",
                "〜ように してください = tolong usahakan (permintaan tidak langsung)",
                "lebih halus daripada perintah langsung",
            ],
            "〜ように しています menyatakan kebiasaan yang diusahakan secara sadar. Dalam bentuk "
            "〜ように してください, polanya menjadi permintaan sopan agar seseorang membiasakan "
            "(atau menghindari) sesuatu.",
            [
                ("毎日|まいにち 運動|うんどう する ように して います。", "Saya membiasakan berolahraga setiap hari."),
                ("時間|じかん に 遅|おく れない ように してください。", "Tolong usahakan jangan terlambat."),
                ("寝|ね る まえ に 復習|ふくしゅう する ように して います。", "Saya membiasakan mengulang pelajaran sebelum tidur."),
            ],
        ),
        BUNPO(
            "b36-4", "〜とか 〜とか — Menyebut Contoh (Santai)",
            "[Kata Benda] とか [Kata Benda] とか",
            [
                "bentuk santai dari 〜や 〜など",
                "menyebut beberapa contoh, bukan daftar lengkap",
                "bisa juga untuk kata kerja: 読む とか 書く とか",
            ],
            "Dalam percakapan santai, contoh-contoh disebut dengan とか: 東京とか 大阪とか "
            "行きました (saya pergi ke Tokyo, Osaka, dan sebagainya).",
            [
                ("週末|しゅうまつ は 映画|えいが を 見|み る とか、 買|か い物|もの を する とか します。",
                 "Akhir pekan saya nonton film, belanja, dan sebagainya."),
                ("日本|にほん では 東京|とうきょう とか 大阪|おおさか とか へ 行|い きました。",
                 "Di Jepang saya pergi ke Tokyo, Osaka, dan lain-lain."),
                ("剣道|けんどう とか 柔道|じゅうどう とか、 武道|ぶどう が 好|す き です。",
                 "Saya suka beladiri seperti kendo, judo, dan sebagainya."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k36-1", "届きます", "とどきます", "todokimasu", "sampai; terkirim", "Kata Kerja",
               ("荷物|にもつ が 届|とど きました。", "Paketnya sudah sampai.")),
        KOTOBA("k36-2", "出ます", "でます", "demasu", "ikut serta (lomba)", "Kata Kerja",
               ("試合|しあい に 出|で ます。", "Ikut pertandingan.")),
        KOTOBA("k36-3", "打ちます", "うちます", "uchimasu", "mengetik", "Kata Kerja",
               ("パソコン で 書類|しょるい を 打|う ちます。", "Mengetik dokumen di komputer.")),
        KOTOBA("k36-4", "貯金します", "ちょきんします", "chokin shimasu", "menabung", "Kata Kerja",
               ("毎月|まいつき 少|すこ し ずつ 貯金|ちょきん して います。", "Saya menabung sedikit demi sedikit setiap bulan.")),
        KOTOBA("k36-5", "太ります", "ふとります", "futorimasu", "bertambah gemuk", "Kata Kerja",
               ("最近|さいきん 太|ふと りました。", "Akhir-akhir ini saya bertambah gemuk.")),
        KOTOBA("k36-6", "やせます", "やせます", "yasemasu", "menjadi kurus", "Kata Kerja",
               ("3キロ やせました。", "Saya turun 3 kilo.")),
        KOTOBA("k36-7", "過ぎます", "すぎます", "sugimasu", "lewat (waktu)", "Kata Kerja",
               ("7時|しちじ を 過|す ぎました。", "Sudah lewat jam 7.")),
        KOTOBA("k36-8", "慣れます", "なれます", "naremasu", "terbiasa", "Kata Kerja",
               ("習慣|しゅうかん に 慣|な れました。", "Sudah terbiasa dengan adatnya.")),
        KOTOBA("k36-9", "硬い", "かたい", "katai", "keras", "Kata Sifat-i",
               ("この パン は 硬|かた い です。", "Roti ini keras.")),
        KOTOBA("k36-10", "軟らかい", "やわらかい", "yawarakai", "lunak; lembut", "Kata Sifat-i",
               ("この 肉|にく は 軟|やわ らかい です。", "Daging ini empuk.")),
        KOTOBA("k36-11", "工場", "こうじょう", "kōjō", "pabrik", "Kata Benda",
               ("工場|こうじょう で 働|はたら いて います。", "Bekerja di pabrik.")),
        KOTOBA("k36-12", "剣道", "けんどう", "kendō", "kendo", "Kata Benda",
               ("剣道|けんどう を 習|なら って います。", "Saya belajar kendo.")),
        KOTOBA("k36-13", "毎週", "まいしゅう", "maishū", "setiap minggu", "Kata Keterangan",
               ("毎週|まいしゅう テニス を します。", "Main tenis setiap minggu.")),
        KOTOBA("k36-14", "やっと", "やっと", "yatto", "akhirnya", "Kata Keterangan",
               ("やっと できました。", "Akhirnya selesai juga.")),
        KOTOBA("k36-15", "かなり", "かなり", "kanari", "cukup (lumayan)", "Kata Keterangan",
               ("かなり 上手|じょうず に なりました。", "Sudah cukup mahir.")),
        KOTOBA("k36-16", "必ず", "かならず", "kanarazu", "pasti; tanpa gagal", "Kata Keterangan",
               ("必|かなら ず 行|い きます。", "Saya pasti datang.")),
        KOTOBA("k36-17", "絶対に", "ぜったいに", "zettaini", "sama sekali (tidak)", "Kata Keterangan",
               ("絶対|ぜったい に 遅|おく れません。", "Sama sekali tidak akan terlambat.")),
        KOTOBA("k36-18", "このごろ", "このごろ", "kono goro", "akhir-akhir ini", "Kata Keterangan",
               ("このごろ 忙|いそが しい です。", "Akhir-akhir ini saya sibuk.")),
    ],
    kanji=[
        KANJI("j36-1", "慣", "カン", "な(れる)", "biasa", 14,
              [("慣れます", "なれます", "terbiasa"), ("習慣", "しゅうかん", "kebiasaan")]),
        KANJI("j36-2", "硬", "コウ", "かた(い)", "keras", 12,
              [("硬い", "かたい", "keras"), ("硬貨", "こうか", "koin")]),
        KANJI("j36-3", "貯", "チョ", "—", "simpan", 12,
              [("貯金", "ちょきん", "tabungan"), ("貯蔵", "ちょぞう", "penyimpanan")]),
        KANJI("j36-4", "過", "カ", "す(ぎる)", "lewat; berlebih", 12,
              [("過ぎます", "すぎます", "lewat"), ("過去", "かこ", "masa lalu")]),
        KANJI("j36-5", "歴", "レキ", "—", "riwayat", 14,
              [("歴史", "れきし", "sejarah"), ("経歴", "けいれき", "riwayat (karier)")]),
        KANJI("j36-6", "宇", "ウ", "—", "angkasa", 6,
              [("宇宙", "うちゅう", "antariksa"), ("宇宙船", "うちゅうせん", "wahana antariksa")]),
    ],
    kaiwa=KAIWA(
        "日本語の 上達 — Kemajuan Bahasa Jepang",
        "Pak Yamada memuji kemajuan bahasa Jepang Miller dan bertanya cara belajarnya.",
        [
            ("山田", "Yamada", "ミラーさん、 日本語|にほんご が ずいぶん 上手|じょうず に なりました ね。",
             "Pak Miller, bahasa Jepang Anda sudah jauh lebih bagus, ya."),
            ("ミラー", "Mirā", "ありがとう ございます。 やっと 新聞|しんぶん が 読|よ める ように なりました。",
             "Terima kasih. Akhirnya saya menjadi bisa membaca surat kabar."),
            ("山田", "Yamada", "すごい です ね。 どう やって 勉強|べんきょう して いるん です か。",
             "Hebat, ya. Bagaimana cara Anda belajar?"),
            ("ミラー", "Mirā", "毎朝|まいあさ ラジオ を 聞|き く ように して います。 それから、 漢字|かんじ を 五|いつ つ ずつ 覚|おぼ えます。",
             "Saya membiasakan mendengar radio setiap pagi. Lalu, menghafal lima kanji setiap hari."),
            ("山田", "Yamada", "それは いい 習慣|しゅうかん です ね。", "Itu kebiasaan yang baik, ya."),
            ("ミラー", "Mirā", "でも、 忘|わす れない ように、 必|かなら ず 復習|ふくしゅう する ように して います。",
             "Tapi supaya tidak lupa, saya selalu berusaha mengulang pelajaran."),
        ],
    ),
    quiz_bunpo=[
        QB("qb36-1", "よく 見|み える ＿＿、 大|おお きい 字|じ で 書|か きました。", ["ように", "ために", "ことに", "ほうに"], 0,
           "よく 見|み える ように、 大|おお きい 字|じ で 書|か きました。", "見えるように",
           "[Bentuk kamus] ように (tujuan)",
           "Tujuan dengan kata kerja non-kehendak (見える) memakai ように, bukan ために."),
        QB("qb36-2", "やっと 自転車|じてんしゃ に 乗|の れる ように ＿＿。", ["なりました", "しました", "おきました", "ありました"], 0,
           "やっと 自転車|じてんしゃ に 乗|の れる ように なりました。", "ようになりました",
           "〜 ように なります",
           "〜ようになります menyatakan perubahan kemampuan: menjadi bisa."),
        QB("qb36-3", "時間|じかん に 遅|おく れない ＿＿ して ください。", ["ように", "ことに", "ものに", "わけに"], 0,
           "時間|じかん に 遅|おく れない ように して ください。", "ようにしてください",
           "〜 ように してください",
           "〜ようにしてください adalah permintaan sopan agar seseorang mengusahakan sesuatu."),
        QB_ID("qb36-4", "“Saya membiasakan diri berolahraga setiap hari.”",
              ["毎日|まいにち 運動|うんどう する ように して います。",
               "毎日|まいにち 運動|うんどう する ように なります。",
               "毎日|まいにち 運動|うんどう が する ように なりました。",
               "毎日|まいにち 運動|うんどう する ために います。"], 0,
              "毎日|まいにち 運動|うんどう する ように して います。", "ようにしています",
              "〜 ように しています",
              "Kebiasaan yang diusahakan dengan sadar memakai 〜ようにしています."),
    ],
    quiz_susun=[
        QS("qs36-1", "Akhirnya saya menjadi bisa membaca surat kabar.",
           "やっと 新聞|しんぶん が 読|よ める ように なりました", "まだ 書|か ける"),
        QS("qs36-2", "Saya menulis dengan huruf besar supaya mudah terlihat.",
           "見|み える ように 大|おお きい 字|じ で 書|か きました", "小|ちい さい 読|よ めない"),
        QS("qs36-3", "Saya menghafal lima kanji setiap hari.",
           "毎日|まいにち 漢字|かんじ を 五|いつ つ ずつ 覚|おぼ えます", "忘|わす れます 全部|ぜんぶ"),
    ],
)

BAB37 = CHAPTER(
    37, "泥棒に 財布を 取られました。", "Dompet saya dicuri pencuri.",
    bunpo=[
        BUNPO(
            "b37-1", "Bentuk Pasif (受身) — Pasif Langsung",
            "Gol I: あ段 ＋ れます ／ Gol II: られます ／ Gol III: されます・来|こ られます",
            [
                "Golongan I: 書|か きます → 書かれます",
                "Golongan II: 褒|ほ めます → 褒められます",
                "Golongan III: します → されます ； 来|き ます → 来|こ られます",
                "pelaku ditandai に: [Penderita] は [Pelaku] に V(ら)れます",
            ],
            "Bentuk pasif dipakai ketika sudut pandangnya adalah pihak yang TERKENA aksi, bukan "
            "pelakunya: 先生が わたしを 褒めました → わたしは 先生に 褒められました.",
            [
                ("わたし は 先生|せんせい に 褒|ほ められました。", "Saya dipuji oleh guru."),
                ("弟|おとうと は 母|はは に しかられました。", "Adik saya dimarahi ibu."),
                ("彼|かれ は みんな に 誘|さそ われました。", "Dia diajak oleh semua orang."),
            ],
        ),
        BUNPO(
            "b37-2", "Pasif “Kena Dampak” (間接受身)",
            "[Penderita] は [Pelaku] に [Milik] を V(ら)れます",
            [
                "menyatakan pembicara dirugikan / terganggu oleh aksi orang lain",
                "milik/bagian tubuh tetap memakai を: 財布|さいふ を 取られました",
                "fenomena: 雨|あめ に 降|ふ られました (kehujanan)",
            ],
            "Bahasa Jepang punya pasif khas yang menyatakan pembicara “kena getahnya”: barangnya "
            "dicuri, kakinya diinjak, kehujanan. Nuansanya selalu negatif atau merepotkan.",
            [
                ("泥棒|どろぼう に 財布|さいふ を 取|と られました。", "Dompet saya dicuri pencuri."),
                ("電車|でんしゃ の 中|なか で 足|あし を 踏|ふ まれました。", "Kaki saya terinjak di dalam kereta."),
                ("雨|あめ に 降|ふ られて、 ぬれて しまいました。", "Saya kehujanan dan basah kuyup."),
            ],
        ),
        BUNPO(
            "b37-3", "Pasif Objektif — Tanpa Pelaku",
            "[Kata Benda] が／は V(ら)れます",
            [
                "dipakai untuk berita, fakta, dan peristiwa umum",
                "pelaku tidak disebut atau tidak penting",
                "umum di bahasa tulisan dan berita",
            ],
            "Ketika pelaku tidak penting (atau tidak diketahui), kalimat pasif cukup menyebut "
            "peristiwanya saja. Pola ini banyak dipakai dalam berita dan laporan.",
            [
                ("この 橋|はし は 100年|ひゃくねん 前|まえ に 作|つく られました。", "Jembatan ini dibangun 100 tahun yang lalu."),
                ("オリンピック は 東京|とうきょう で 行|おこな われました。", "Olimpiade diselenggarakan di Tokyo."),
                ("この 車|くるま は 日本|にほん で 設計|せっけい されました。", "Mobil ini dirancang di Jepang."),
            ],
        ),
        BUNPO(
            "b37-4", "〜によって — Oleh (Penciptaan & Penemuan)",
            "[Karya] は [Pencipta] によって V(ら)れます",
            [
                "untuk karya: buku, lukisan, bangunan",
                "untuk penemuan: 発明|はつめい, 発見|はっけん",
                "bukan に tetapi によって",
            ],
            "Ketika membicarakan siapa pencipta suatu karya atau penemu suatu hal, pelakunya "
            "ditandai によって: この 小説は 紫式部によって 書かれました.",
            [
                ("「源氏物語|げんじものがたり」 は 紫式部|むらさきしきぶ によって 書|か かれました。",
                 "“Hikayat Genji” ditulis oleh Murasaki Shikibu."),
                ("電話|でんわ は グラハム・ベル によって 発明|はつめい されました。",
                 "Telepon ditemukan oleh Graham Bell."),
                ("この 寺|てら は 江戸時代|えどじだい に 建|た てられました。", "Kuil ini dibangun pada zaman Edo."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k37-1", "褒めます", "ほめます", "homemasu", "memuji", "Kata Kerja",
               ("先生|せんせい に 褒|ほ められました。", "Dipuji guru.")),
        KOTOBA("k37-2", "しかります", "しかります", "shikarimasu", "memarahi", "Kata Kerja",
               ("父|ちち に しかられました。", "Dimarahi ayah.")),
        KOTOBA("k37-3", "誘います", "さそいます", "sasoimasu", "mengajak", "Kata Kerja",
               ("友達|ともだち を 食事|しょくじ に 誘|さそ います。", "Mengajak teman makan.")),
        KOTOBA("k37-4", "起こします", "おこします", "okoshimasu", "membangunkan", "Kata Kerja",
               ("6時|ろくじ に 起|お こして ください。", "Tolong bangunkan saya jam 6.")),
        KOTOBA("k37-5", "招待します", "しょうたいします", "shōtai shimasu", "mengundang", "Kata Kerja",
               ("結婚式|けっこんしき に 招待|しょうたい されました。", "Saya diundang ke pesta pernikahan.")),
        KOTOBA("k37-6", "頼みます", "たのみます", "tanomimasu", "meminta tolong", "Kata Kerja",
               ("友達|ともだち に 引|ひ っ越|こ し を 頼|たの みました。", "Saya minta tolong teman untuk pindahan.")),
        KOTOBA("k37-7", "とります", "とります", "torimasu", "mencuri", "Kata Kerja",
               ("財布|さいふ を とられました。", "Dompet saya dicuri.")),
        KOTOBA("k37-8", "踏みます", "ふみます", "fumimasu", "menginjak", "Kata Kerja",
               ("足|あし を 踏|ふ まれました。", "Kaki saya terinjak.")),
        KOTOBA("k37-9", "壊します", "こわします", "kowashimasu", "merusak", "Kata Kerja",
               ("おもちゃ を 壊|こわ しました。", "Saya merusak mainannya.")),
        KOTOBA("k37-10", "汚します", "よごします", "yogoshimasu", "mengotori", "Kata Kerja",
               ("服|ふく を 汚|よご しました。", "Saya mengotori baju.")),
        KOTOBA("k37-11", "行います", "おこないます", "okonaimasu", "menyelenggarakan", "Kata Kerja",
               ("大会|たいかい が 行|おこな われます。", "Ajangnya akan diselenggarakan.")),
        KOTOBA("k37-12", "輸出します", "ゆしゅつします", "yushutsu shimasu", "mengekspor", "Kata Kerja",
               ("車|くるま を 輸出|ゆしゅつ します。", "Mengekspor mobil.")),
        KOTOBA("k37-13", "輸入します", "ゆにゅうします", "yunyū shimasu", "mengimpor", "Kata Kerja",
               ("石油|せきゆ を 輸入|ゆにゅう します。", "Mengimpor minyak bumi.")),
        KOTOBA("k37-14", "翻訳します", "ほんやくします", "hon'yaku shimasu", "menerjemahkan", "Kata Kerja",
               ("小説|しょうせつ を 翻訳|ほんやく します。", "Menerjemahkan novel.")),
        KOTOBA("k37-15", "発明します", "はつめいします", "hatsumei shimasu", "menemukan (ciptaan)", "Kata Kerja",
               ("新|あたら しい 機械|きかい を 発明|はつめい しました。", "Menemukan mesin baru.")),
        KOTOBA("k37-16", "発見します", "はっけんします", "hakken shimasu", "menemukan (sesuatu yang sudah ada)", "Kata Kerja",
               ("新|あたら しい 星|ほし が 発見|はっけん されました。", "Bintang baru ditemukan.")),
        KOTOBA("k37-17", "設計します", "せっけいします", "sekkei shimasu", "merancang", "Kata Kerja",
               ("ビル を 設計|せっけい します。", "Merancang gedung.")),
        KOTOBA("k37-18", "科学者", "かがくしゃ", "kagakusha", "ilmuwan", "Kata Benda",
               ("科学者|かがくしゃ に なりたい です。", "Saya ingin menjadi ilmuwan.")),
    ],
    kanji=[
        KANJI("j37-1", "褒", "ホウ", "ほ(める)", "puji", 15,
              [("褒めます", "ほめます", "memuji"), ("褒美", "ほうび", "hadiah")]),
        KANJI("j37-2", "誘", "ユウ", "さそ(う)", "ajak", 14,
              [("誘います", "さそいます", "mengajak"), ("誘惑", "ゆうわく", "godaan")]),
        KANJI("j37-3", "輸", "ユ", "—", "angkut; kirim", 16,
              [("輸出", "ゆしゅつ", "ekspor"), ("輸入", "ゆにゅう", "impor")]),
        KANJI("j37-4", "発", "ハツ", "—", "muncul; berangkat", 9,
              [("発明", "はつめい", "penemuan"), ("出発", "しゅっぱつ", "keberangkatan")]),
        KANJI("j37-5", "訳", "ヤク", "—", "terjemah", 11,
              [("翻訳", "ほんやく", "terjemahan"), ("通訳", "つうやく", "juru bahasa")]),
        KANJI("j37-6", "踏", "トウ", "ふ(む)", "injak", 15,
              [("踏みます", "ふみます", "menginjak"), ("踏切", "ふみきり", "perlintasan kereta")]),
    ],
    kaiwa=KAIWA(
        "朝の できごと — Kejadian Pagi Hari",
        "Wan bercerita kepada Pak Sato tentang pengalaman tidak menyenangkan di kereta pagi ini.",
        [
            ("佐藤", "Satō", "どう したん です か。 暗|くら い 顔|かお を して います ね。",
             "Kenapa? Wajah Anda kelihatan murung."),
            ("ワン", "Wan", "今朝|けさ 電車|でんしゃ の 中|なか で 足|あし を 踏|ふ まれました。 それに、 財布|さいふ を 取|と られそう に なりました。",
             "Pagi ini kaki saya terinjak di dalam kereta. Selain itu, dompet saya hampir dicuri."),
            ("佐藤", "Satō", "それは 大変|たいへん でした ね。", "Wah, kasihan sekali."),
            ("ワン", "Wan", "でも、 駅員|えきいん が 注意|ちゅうい して くれて、 犯人|はんにん は すぐ 捕|つか まえられました。",
             "Tapi petugas stasiun menegurnya, dan pelakunya langsung ditangkap."),
            ("佐藤", "Satō", "よかった です ね。 ところで、 その 本|ほん は 誰|だれ が 書|か いたん です か。",
             "Syukurlah. Ngomong-ngomong, buku itu ditulis siapa?"),
            ("ワン", "Wan", "紫式部|むらさきしきぶ によって 書|か かれました。 「源氏物語|げんじものがたり」 です。",
             "Ditulis oleh Murasaki Shikibu. “Hikayat Genji”."),
        ],
    ),
    quiz_bunpo=[
        QB("qb37-1", "わたし は 先生|せんせい に 褒|ほ め＿＿ました。", ["られ", "させ", "てもらい", "ていただき"], 0,
           "わたし は 先生|せんせい に 褒|ほ められました。", "褒められました", "Pasif: [Penderita] は [Pelaku] に V(ら)れます",
           "Golongan II membentuk pasif dengan られます: 褒めます → 褒められます."),
        QB("qb37-2", "泥棒|どろぼう に 財布|さいふ を 取|と ＿＿ました。", ["られ", "せ", "あげ", "くれ"], 0,
           "泥棒|どろぼう に 財布|さいふ を 取|と られました。", "取られました", "Pasif kena dampak: Nに Nを V(ら)れます",
           "Pasif “kena dampak”: milik yang terkena tetap memakai を, pelaku memakai に."),
        QB("qb37-3", "この 小説|しょうせつ は 紫式部|むらさきしきぶ ＿＿ 書|か かれました。", ["によって", "にとって", "について", "のために"], 0,
           "この 小説|しょうせつ は 紫式部|むらさきしきぶ によって 書|か かれました。", "によって",
           "[Karya] は [Pencipta] によって V(ら)れます",
           "Pencipta karya atau penemu ditandai によって, bukan に."),
        QB_ID("qb37-4", "“Kaki saya terinjak di dalam kereta.”",
              ["電車|でんしゃ の 中|なか で 足|あし を 踏|ふ まれました。",
               "電車|でんしゃ の 中|なか で 足|あし を 踏|ふ みました。",
               "電車|でんしゃ の 中|なか で 足|あし が 踏|ふ みました。",
               "電車|でんしゃ の 中|なか で 足|あし を 踏|ふ ませました。"], 0,
              "電車|でんしゃ の 中|なか で 足|あし を 踏|ふ まれました。", "踏まれました",
              "[Penderita] は [Milik] を V(ら)れます",
              "Kaki yang TERINJAK: pakai pasif 踏まれました; 踏みました berarti saya yang menginjak."),
    ],
    quiz_susun=[
        QS("qs37-1", "Saya dipuji oleh guru.",
           "わたし は 先生|せんせい に 褒|ほ められました", "しかられました 母|はは"),
        QS("qs37-2", "Dompet saya dicuri pencuri.",
           "泥棒|どろぼう に 財布|さいふ を 取|と られました", "拾|ひろ いました 警察|けいさつ"),
        QS("qs37-3", "Novel ini ditulis oleh Murasaki Shikibu.",
           "この 小説|しょうせつ は 紫式部|むらさきしきぶ によって 書|か かれました", "読|よ まれました 翻訳|ほんやく"),
    ],
)

BAB38 = CHAPTER(
    38, "星を 見るのは 楽しいです。", "Melihat bintang itu menyenangkan.",
    bunpo=[
        BUNPO(
            "b38-1", "〜のは ／ 〜のが ＋ Kata Sifat — Menilai Suatu Kegiatan",
            "[Kata Kerja bentuk kamus] のは ／ のが ＋ [Kata Sifat] です",
            [
                "のは: penilaian umum （泳|およ ぐのは 難|むずか しいです）",
                "のが: reaksi atas yang dilihat/dialami （歌|うた うのが 好|す きです）",
                "の mengubah kata kerja menjadi kata benda",
            ],
            "Untuk memberi penilaian pada suatu kegiatan, kata kerja dinominalkan dengan の. "
            "Pernyataan umum memakai のは; hal yang disukai, dikuasai, atau terlihat memakai のが.",
            [
                ("星|ほし を 見|み る のは 楽|たの しい です。", "Melihat bintang itu menyenangkan."),
                ("一人|ひとり で 暮|く らす のは 寂|さび しい です。", "Hidup sendiri itu sepi."),
                ("あの 人|ひと が 歌|うた う のが 上手|じょうず です。", "Orang itu pandai bernyanyi."),
            ],
        ),
        BUNPO(
            "b38-2", "〜のを 忘れました ／ 知っています",
            "[Kalimat bentuk biasa] の を 忘|わす れました ／ 知|し って います",
            [
                "ドア を 閉|し めるのを 忘れました = lupa menutup pintu",
                "彼|かれ が 来|く るのを 知っています = tahu bahwa dia akan datang",
                "klausa utuh dinominalkan dengan の lalu diikuti を",
            ],
            "Dengan 忘れます dan 知っています, seluruh peristiwa diubah menjadi kata benda dengan の "
            "lalu ditandai を. Perhatikan: subjek di dalam klausa ditandai が.",
            [
                ("ドア に かぎ を かける のを 忘|わす れました。", "Saya lupa mengunci pintu."),
                ("会議|かいぎ が 3時|さんじ に なった のを 知|し って います か。", "Apakah Anda tahu rapatnya pindah ke jam 3?"),
                ("彼|かれ が 結婚|けっこん した のを 知|し って います か。", "Apakah Anda tahu dia sudah menikah?"),
            ],
        ),
        BUNPO(
            "b38-3", "〜のは 〜です — Penegasan",
            "[Kalimat bentuk biasa] のは [Kata Benda] です",
            [
                "menegaskan bagian kalimat yang menjadi jawaban",
                "買|か ったのは 日本|にほん です = yang jadi tempat membeli adalah Jepang",
                "sering dipakai untuk koreksi atau penjelasan",
            ],
            "Susunan ini menegaskan satu unsur kalimat: bukan sekadar “saya membeli ini di Jepang”, "
            "tetapi “tempat saya membelinya adalah Jepang”.",
            [
                ("これ を 買|か った のは 日本|にほん です。", "Tempat saya membeli ini adalah di Jepang."),
                ("わたし が 生|う まれた のは 1988年|せんきゅうひゃくはちじゅうはちねん です。", "Tahun kelahiran saya adalah 1988."),
                ("一番|いちばん 好|す き な のは 秋|あき です。", "Yang paling saya sukai adalah musim gugur."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k38-1", "育てます", "そだてます", "sodatemasu", "membesarkan; memelihara", "Kata Kerja",
               ("子|こ ども を 育|そだ てます。", "Membesarkan anak.")),
        KOTOBA("k38-2", "運びます", "はこびます", "hakobimasu", "mengangkut", "Kata Kerja",
               ("荷物|にもつ を 運|はこ びます。", "Mengangkut barang.")),
        KOTOBA("k38-3", "亡くなります", "なくなります", "nakunarimasu", "meninggal dunia", "Kata Kerja",
               ("祖父|そふ が 亡|な くなりました。", "Kakek saya meninggal.")),
        KOTOBA("k38-4", "入院します", "にゅういんします", "nyūin shimasu", "dirawat di rumah sakit", "Kata Kerja",
               ("来週|らいしゅう 入院|にゅういん します。", "Minggu depan saya dirawat.")),
        KOTOBA("k38-5", "入れます", "いれます", "iremasu", "menyalakan (daya)", "Kata Kerja",
               ("電源|でんげん を 入|い れます。", "Menyalakan daya.")),
        KOTOBA("k38-6", "切ります", "きります", "kirimasu", "mematikan (daya)", "Kata Kerja",
               ("電源|でんげん を 切|き って ください。", "Tolong matikan dayanya.")),
        KOTOBA("k38-7", "掛けます", "かけます", "kakemasu", "mengunci", "Kata Kerja",
               ("かぎ を 掛|か ける のを 忘|わす れました。", "Saya lupa menguncinya.")),
        KOTOBA("k38-8", "気持ちがいい", "きもちがいい", "kimochi ga ii", "nyaman; enak rasanya", "Ungkapan",
               ("温泉|おんせん は 気持|きも ち が いい です。", "Pemandian air panas itu nyaman.")),
        KOTOBA("k38-9", "大きな", "おおきな", "ōkina", "besar", "Kata Sifat-na",
               ("大|おお きな 家|いえ に 住|す みたい です。", "Saya ingin tinggal di rumah besar.")),
        KOTOBA("k38-10", "小さな", "ちいさな", "chiisana", "kecil", "Kata Sifat-na",
               ("小|ちい さな 赤|あか ちゃん が 生|う まれました。", "Telah lahir bayi mungil.")),
        KOTOBA("k38-11", "赤ちゃん", "あかちゃん", "akachan", "bayi", "Kata Benda",
               ("赤|あか ちゃん が 泣|な いて います。", "Bayinya sedang menangis.")),
        KOTOBA("k38-12", "海岸", "かいがん", "kaigan", "pantai; pesisir", "Kata Benda",
               ("海岸|かいがん を 散歩|さんぽ します。", "Berjalan-jalan di pantai.")),
        KOTOBA("k38-13", "うそ", "うそ", "uso", "bohong", "Kata Benda",
               ("うそ を ついては いけません。", "Tidak boleh berbohong.")),
        KOTOBA("k38-14", "書類", "しょるい", "shorui", "dokumen", "Kata Benda",
               ("書類|しょるい を 整理|せいり します。", "Merapikan dokumen.")),
        KOTOBA("k38-15", "電源", "でんげん", "dengen", "saklar daya", "Kata Benda",
               ("電源|でんげん が 入|はい りません。", "Dayanya tidak menyala.")),
        KOTOBA("k38-16", "整理します", "せいりします", "seiri shimasu", "merapikan; menata", "Kata Kerja",
               ("机|つくえ の 上|うえ を 整理|せいり します。", "Merapikan atas meja.")),
        KOTOBA("k38-17", "双子", "ふたご", "futago", "kembar", "Kata Benda",
               ("双子|ふたご の 姉妹|しまい です。", "Mereka kakak-adik kembar.")),
        KOTOBA("k38-18", "似ています", "にています", "nite imasu", "mirip", "Kata Kerja",
               ("母|はは に 似|に て います。", "Mirip dengan ibunya.")),
    ],
    kanji=[
        KANJI("j38-1", "育", "イク", "そだ(てる)", "besarkan", 8,
              [("育てます", "そだてます", "membesarkan"), ("教育", "きょういく", "pendidikan")]),
        KANJI("j38-2", "研", "ケン", "—", "asah; teliti", 9,
              [("研究", "けんきゅう", "penelitian"), ("研究室", "けんきゅうしつ", "ruang riset")]),
        KANJI("j38-3", "整", "セイ", "—", "rapi; tata", 16,
              [("整理", "せいり", "merapikan"), ("整備", "せいび", "pemeliharaan")]),
        KANJI("j38-4", "押", "オウ", "お(す)", "tekan; dorong", 8,
              [("押します", "おします", "menekan"), ("押印", "おういん", "membubuhkan stempel")]),
        KANJI("j38-5", "似", "ジ", "に(る)", "mirip", 7,
              [("似ています", "にています", "mirip"), ("類似", "るいじ", "kemiripan")]),
        KANJI("j38-6", "格", "カク", "—", "status; kaidah", 10,
              [("性格", "せいかく", "watak"), ("合格", "ごうかく", "lulus")]),
    ],
    kaiwa=KAIWA(
        "趣味と 忘れ物 — Hobi dan Barang yang Terlupa",
        "Pak Yamada dan Miller mengobrol tentang hobi, lalu mengingatkan soal rapat besok.",
        [
            ("山田", "Yamada", "ミラーさん の 趣味|しゅみ は 何|なん です か。", "Apa hobi Anda, Pak Miller?"),
            ("ミラー", "Mirā", "写真|しゃしん を 撮|と る の が 好|す き です。 歩|ある きながら 撮|と る のは 楽|たの しい です。",
             "Saya suka memotret. Memotret sambil berjalan itu menyenangkan."),
            ("山田", "Yamada", "いい です ね。 ところで、 あした の 会議|かいぎ、 書類|しょるい を 持|も って 来|く る のを 忘|わす れないで ください ね。",
             "Bagus, ya. Omong-omong, jangan lupa membawa dokumen untuk rapat besok, ya."),
            ("ミラー", "Mirā", "あっ、 危|あぶ ない ところ でした。 教|おし えて くれて ありがとう ございます。",
             "Ah, hampir saja lupa. Terima kasih sudah mengingatkan."),
            ("山田", "Yamada", "会議|かいぎ が 3時|さんじ に 変|か わった のを 知|し って います か。",
             "Apakah Anda tahu rapatnya diubah ke jam 3?"),
            ("ミラー", "Mirā", "ええ。 始|はじ まる のは 3時|さんじ から です ね。", "Ya. Yang mulai jam 3, kan."),
        ],
    ),
    quiz_bunpo=[
        QB("qb38-1", "早|はや く 歩|ある く ＿＿ は 疲|つか れます。", ["の", "を", "に", "へ"], 0,
           "早|はや く 歩|ある く のは 疲|つか れます。", "歩くのは", "[Bentuk kamus] のは ＋ Kata Sifat",
           "Penilaian umum terhadap suatu kegiatan memakai のは."),
        QB("qb38-2", "あの 人|ひと が 歌|うた う ＿＿ が 上手|じょうず です。", ["の", "を", "に", "で"], 0,
           "あの 人|ひと が 歌|うた う のが 上手|じょうず です。", "歌うのが", "[Bentuk kamus] のが",
           "Hal yang dikuasai atau disukai dinominalkan dengan のが."),
        QB("qb38-3", "ドア に かぎ を かける ＿＿ を 忘|わす れました。", ["の", "と", "が", "に"], 0,
           "ドア に かぎ を かける のを 忘|わす れました。", "のを忘れました", "[Klausa] の を 忘れました",
           "Seluruh peristiwa dinominalkan dengan の lalu diikuti を: 〜のを忘れました."),
        QB_ID("qb38-4", "“Tahun kelahiran saya adalah 1988.” (dengan penegasan)",
              ["わたし が 生|う まれた のは 1988年|せんきゅうひゃくはちじゅうはちねん です。",
               "わたし は 1988年|せんきゅうひゃくはちじゅうはちねん に 生|う まれる のです。",
               "わたし が 1988年|せんきゅうひゃくはちじゅうはちねん を 生|う まれました。",
               "1988年|せんきゅうひゃくはちじゅうはちねん の わたし が 生|う まれました。"], 0,
              "わたし が 生|う まれた のは 1988年|せんきゅうひゃくはちじゅうはちねん です。", "生まれたのは",
              "[Klausa] のは 〜 です",
              "Pola 〜のは〜です menegaskan unsur jawaban: yang ditanyakan adalah tahunnya."),
    ],
    quiz_susun=[
        QS("qs38-1", "Melihat bintang itu menyenangkan.",
           "星|ほし を 見|み るのは 楽|たの しい です", "聞|き く 悲|かな しい"),
        QS("qs38-2", "Saya lupa mengunci pintu.",
           "ドア に かぎ を かける のを 忘|わす れました", "開|あ ける 覚|おぼ えました"),
        QS("qs38-3", "Apakah Anda tahu dia sudah menikah?",
           "彼|かれ が 結婚|けっこん した のを 知|し って います か", "離婚|りこん 見|み ました"),
    ],
)

BAB39 = CHAPTER(
    39, "ニュースを 聞いて、 びっくりしました。", "Mendengar beritanya, saya terkejut.",
    bunpo=[
        BUNPO(
            "b39-1", "〜て ／ 〜くて ／ 〜で — Sebab Perasaan & Keadaan",
            "Kata kerja: Vて ／ Sifat-i: 〜くて ／ Sifat-na・benda: 〜で",
            [
                "ニュース を 聞|き いて、 びっくり しました",
                "家族|かぞく に 会|あ えなくて、 寂|さび しい です",
                "仕事|しごと が 忙|いそが しくて、 疲|つか れました",
                "地震|じしん で ビル が 倒|たお れました (bencana: Nで)",
            ],
            "Bentuk て juga bisa menyatakan SEBAB, terutama ketika akibatnya berupa perasaan "
            "(びっくり, 安心, がっかり) atau keadaan yang tidak bisa dikendalikan. Untuk bencana "
            "alam dan kejadian, penyebabnya ditandai Nで.",
            [
                ("ニュース を 聞|き いて、 びっくり しました。", "Mendengar beritanya, saya terkejut."),
                ("家族|かぞく に 会|あ えなくて、 寂|さび しい です。", "Karena tidak bisa bertemu keluarga, saya sedih."),
                ("地震|じしん で ビル が 倒|たお れました。", "Gedungnya roboh karena gempa."),
            ],
        ),
        BUNPO(
            "b39-2", "〜ので — Alasan (Sopan)",
            "[Bentuk Biasa] ので ／ [Sifat-na・Kata Benda] な ので",
            [
                "lebih halus dan objektif daripada から",
                "cocok untuk alasan dan permintaan maaf formal",
                "静|しず か なので ／ 雨|あめ なので",
            ],
            "ので menyatakan alasan dengan nada yang lebih halus daripada から, sehingga aman "
            "dipakai di situasi formal, permintaan maaf, atau saat menyampaikan alasan kepada "
            "orang yang lebih tinggi.",
            [
                ("電車|でんしゃ が 遅|おく れた ので、 遅刻|ちこく しました。", "Karena kereta terlambat, saya terlambat datang."),
                ("頭|あたま が 痛|いた い ので、 早退|そうたい します。", "Karena kepala saya sakit, saya pulang lebih awal."),
                ("雨|あめ なので、 試合|しあい は 中止|ちゅうし です。", "Karena hujan, pertandingannya dibatalkan."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k39-1", "答えます", "こたえます", "kotaemasu", "menjawab", "Kata Kerja",
               ("質問|しつもん に 答|こた えます。", "Menjawab pertanyaan.")),
        KOTOBA("k39-2", "倒れます", "たおれます", "taoremasu", "roboh; jatuh", "Kata Kerja",
               ("木|き が 倒|たお れました。", "Pohonnya tumbang.")),
        KOTOBA("k39-3", "焼けます", "やけます", "yakemasu", "terbakar; matang", "Kata Kerja",
               ("パン が 焼|や けました。", "Rotinya sudah matang.")),
        KOTOBA("k39-4", "通ります", "とおります", "tōrimasu", "melewati", "Kata Kerja",
               ("家|いえ の 前|まえ を バス が 通|とお ります。", "Bus melewati depan rumah.")),
        KOTOBA("k39-5", "死にます", "しにます", "shinimasu", "meninggal", "Kata Kerja",
               ("飼|か って いた 犬|いぬ が 死|し にました。", "Anjing peliharaan saya mati.")),
        KOTOBA("k39-6", "びっくりします", "びっくりします", "bikkuri shimasu", "terkejut", "Kata Kerja",
               ("値段|ねだん を 聞|き いて びっくり しました。", "Mendengar harganya, saya terkejut.")),
        KOTOBA("k39-7", "がっかりします", "がっかりします", "gakkari shimasu", "kecewa", "Kata Kerja",
               ("試験|しけん の 結果|けっか に がっかり しました。", "Saya kecewa dengan hasil ujian.")),
        KOTOBA("k39-8", "安心します", "あんしんします", "anshin shimasu", "lega; tenang", "Kata Kerja",
               ("無事|ぶじ が 分|わ かって 安心|あんしん しました。", "Mengetahui semuanya selamat, saya lega.")),
        KOTOBA("k39-9", "遅刻します", "ちこくします", "chikoku shimasu", "datang terlambat", "Kata Kerja",
               ("電車|でんしゃ が 遅|おく れて、 遅刻|ちこく しました。", "Karena kereta terlambat, saya terlambat.")),
        KOTOBA("k39-10", "早退します", "そうたいします", "sōtai shimasu", "pulang lebih awal", "Kata Kerja",
               ("気分|きぶん が 悪|わる い ので、 早退|そうたい します。", "Karena badan tidak enak, saya pulang lebih awal.")),
        KOTOBA("k39-11", "離婚します", "りこんします", "rikon shimasu", "bercerai", "Kata Kerja",
               ("けんか が 多|おお くて、 離婚|りこん しました。", "Karena sering bertengkar, mereka bercerai.")),
        KOTOBA("k39-12", "複雑", "ふくざつ", "fukuzatsu", "rumit", "Kata Sifat-na",
               ("手続|てつづ き が 複雑|ふくざつ です。", "Prosedurnya rumit.")),
        KOTOBA("k39-13", "邪魔", "じゃま", "jama", "mengganggu", "Kata Sifat-na",
               ("大|おお きい 荷物|にもつ が 邪魔|じゃま です。", "Barang besarnya menghalangi.")),
        KOTOBA("k39-14", "汚い", "きたない", "kitanai", "kotor", "Kata Sifat-i",
               ("部屋|へや が 汚|きたな い です。", "Kamarnya kotor.")),
        KOTOBA("k39-15", "うれしい", "うれしい", "ureshii", "senang; bahagia", "Kata Sifat-i",
               ("合格|ごうかく して うれしい です。", "Saya senang karena lulus.")),
        KOTOBA("k39-16", "悲しい", "かなしい", "kanashii", "sedih", "Kata Sifat-i",
               ("別|わか れが 悲|かな しい です。", "Perpisahan itu menyedihkan.")),
        KOTOBA("k39-17", "恥ずかしい", "はずかしい", "hazukashii", "malu", "Kata Sifat-i",
               ("みんな の 前|まえ で 転|ころ んで 恥|は ずかしかった です。", "Saya malu jatuh di depan semua orang.")),
        KOTOBA("k39-18", "地震", "じしん", "jishin", "gempa bumi", "Kata Benda",
               ("地震|じしん で ビル が 倒|たお れました。", "Gedung roboh karena gempa.")),
    ],
    kanji=[
        KANJI("j39-1", "答", "トウ", "こた(える)", "jawab", 12,
              [("答えます", "こたえます", "menjawab"), ("回答", "かいとう", "jawaban")]),
        KANJI("j39-2", "倒", "トウ", "たお(れる)", "roboh", 10,
              [("倒れます", "たおれます", "roboh"), ("倒産", "とうさん", "kebangkrutan")]),
        KANJI("j39-3", "焼", "ショウ", "や(ける)", "bakar; panggang", 12,
              [("焼けます", "やけます", "terbakar; matang"), ("夕焼け", "ゆうやけ", "langit senja kemerahan")]),
        KANJI("j39-4", "悲", "ヒ", "かな(しい)", "sedih", 12,
              [("悲しい", "かなしい", "sedih"), ("悲劇", "ひげき", "tragedi")]),
        KANJI("j39-5", "恥", "チ", "は(ずかしい)", "malu", 10,
              [("恥ずかしい", "はずかしい", "memalukan"), ("恥知らず", "はじしらず", "tak tahu malu")]),
        KANJI("j39-6", "震", "シン", "ふる(える)", "getar", 15,
              [("地震", "じしん", "gempa"), ("震えます", "ふるえます", "gemetar")]),
    ],
    kaiwa=KAIWA(
        "地震の あとで — Setelah Gempa",
        "Wan khawatir setelah mendengar berita gempa dan tidak bisa menghubungi keluarganya.",
        [
            ("佐藤", "Satō", "ニュース を 聞|き いて、 びっくり しました。 大|おお きな 地震|じしん が あった そう です よ。",
             "Saya terkejut mendengar beritanya. Kabarnya ada gempa besar."),
            ("ワン", "Wan", "えっ、 本当|ほんとう です か。 家族|かぞく に 連絡|れんらく が つかなくて、 心配|しんぱい です。",
             "Hah, benarkah? Saya tidak bisa menghubungi keluarga, jadi khawatir."),
            ("佐藤", "Satō", "電話|でんわ が 混|こ んで いる ので、 しばらく 待|ま った ほうが いい です よ。",
             "Karena sambungan telepon sedang padat, sebaiknya tunggu sebentar."),
            ("ワン", "Wan", "…あ、 連絡|れんらく が つきました。 皆|みな 無事|ぶじ だそう です。 安心|あんしん しました。",
             "…Ah, sudah tersambung. Katanya semuanya selamat. Saya lega."),
            ("佐藤", "Satō", "よかった です ね。 今朝|けさ は 事故|じこ で 電車|でんしゃ が 遅|おく れて、 遅刻|ちこく しそう に なりました よ。",
             "Syukurlah. Pagi ini kereta terlambat karena kecelakaan, saya hampir terlambat."),
            ("ワン", "Wan", "災害|さいがい の 日|ひ は 大変|たいへん です ね。", "Hari bencana memang repot, ya."),
        ],
    ),
    quiz_bunpo=[
        QB("qb39-1", "ニュース を 聞|き い＿＿、 びっくり しました。", ["て", "のに", "ば", "たら"], 0,
           "ニュース を 聞|き いて、 びっくり しました。", "聞いて", "Vて (sebab perasaan)",
           "Bentuk て menyatakan sebab ketika akibatnya perasaan seperti びっくりしました."),
        QB("qb39-2", "電車|でんしゃ が 遅|おく れた ＿＿、 遅刻|ちこく しました。", ["ので", "のに", "ても", "ばかり"], 0,
           "電車|でんしゃ が 遅|おく れた ので、 遅刻|ちこく しました。", "遅れたので", "[Bentuk Biasa] ので",
           "ので adalah cara sopan menyatakan alasan, lebih halus daripada から."),
        QB("qb39-3", "地震|じしん ＿＿ ビル が 倒|たお れました。", ["で", "に", "を", "が"], 0,
           "地震|じしん で ビル が 倒|たお れました。", "地震で", "[Kata Benda] で (sebab)",
           "Penyebab berupa bencana atau kejadian ditandai で: 地震で, 事故で, 火事で."),
        QB_ID("qb39-4", "“Karena tidak bisa bertemu keluarga, saya sedih.”",
              ["家族|かぞく に 会|あ えなくて、 寂|さび しい です。",
               "家族|かぞく に 会|あ えて、 寂|さび しい です。",
               "家族|かぞく に 会|あ えば、 寂|さび しい です。",
               "家族|かぞく に 会|あ うので、 寂|さび しい です。"], 0,
              "家族|かぞく に 会|あ えなくて、 寂|さび しい です。", "会えなくて", "〜なくて (sebab perasaan)",
              "Bentuk nai-nya adalah 〜なくて: tidak bisa bertemu → sedih."),
    ],
    quiz_susun=[
        QS("qs39-1", "Mendengar beritanya, saya terkejut.",
           "ニュース を 聞|き いて びっくり しました", "読|よ んで がっかり"),
        QS("qs39-2", "Karena kereta terlambat, saya terlambat datang.",
           "電車|でんしゃ が 遅|おく れた ので 遅刻|ちこく しました", "早退|そうたい 事故|じこ"),
        QS("qs39-3", "Gedungnya roboh karena gempa.",
           "地震|じしん で ビル が 倒|たお れました", "火事|かじ 焼|や けました"),
    ],
)

BAB40 = CHAPTER(
    40, "答えが 正しいかどうか 確かめます。", "Saya memastikan apakah jawabannya benar.",
    bunpo=[
        BUNPO(
            "b40-1", "Kata Tanya ＋ か — Pertanyaan Tersisip",
            "[Kata Tanya ＋ bentuk biasa] か ＋ 知|し っています ／ 教|おし えて ください",
            [
                "何時|なんじ に 始|はじ まるか 知っていますか",
                "predikat di dalam klausa memakai BENTUK BIASA",
                "dipakai dengan 知っています, 分かります, 教えてください",
            ],
            "Untuk menyisipkan pertanyaan ke dalam kalimat lain, bagian tanyanya diakhiri か dan "
            "memakai bentuk biasa: 会議は 何時に 始まりますか → 何時に 始まるか 知っていますか.",
            [
                ("会議|かいぎ が 何時|なんじ に 始|はじ まる か、 知|し って います か。",
                 "Apakah Anda tahu jam berapa rapat dimulai?"),
                ("これ が いくら か、 教|おし えて ください。", "Tolong beri tahu berapa harganya."),
                ("彼|かれ が どこ に 住|す んで いる か、 分|わ かりません。", "Saya tidak tahu di mana dia tinggal."),
            ],
        ),
        BUNPO(
            "b40-2", "〜か どうか — Apakah … atau Tidak",
            "[Bentuk Biasa] か どうか",
            [
                "untuk pertanyaan ya/tidak yang disisipkan",
                "来|く るかどうか 分かりません",
                "sering dipakai dengan 確かめます, 聞きます, 分かりません",
            ],
            "Kalau pertanyaan yang disisipkan tidak memakai kata tanya (ya/tidak), polanya "
            "menjadi 〜かどうか: 答えが 正しいかどうか 確かめます (memastikan benar atau tidak).",
            [
                ("答|こた え が 正|ただ しい か どうか、 確|たし かめます。", "Saya memastikan apakah jawabannya benar."),
                ("あした 晴|は れる か どうか、 分|わ かりません。", "Saya tidak tahu apakah besok akan cerah."),
                ("ミラーさん が 来|く る か どうか、 聞|き いて みます。", "Saya akan coba tanyakan apakah Miller datang."),
            ],
        ),
        BUNPO(
            "b40-3", "〜て みます — Mencoba Melakukan",
            "[Kata Kerja bentuk て] みます",
            [
                "mencoba sesuatu untuk melihat hasilnya",
                "この 靴|くつ を 履|は いて みます = mencoba memakai sepatu ini",
                "〜て みて ください = silakan coba",
            ],
            "〜てみます menyatakan mencoba melakukan sesuatu untuk mengetahui bagaimana hasil atau "
            "rasanya: mencoba makan, mencoba memakai, mencoba bertanya.",
            [
                ("一度|いちど やって みます。", "Saya akan mencobanya sekali."),
                ("この 靴|くつ を 履|は いて みても いい です か。", "Bolehkah saya mencoba sepatu ini?"),
                ("日本|にほん の 着物|きもの を 着|き て みたい です。", "Saya ingin mencoba memakai kimono Jepang."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k40-1", "数えます", "かぞえます", "kazoemasu", "menghitung", "Kata Kerja",
               ("お金|かね を 数|かぞ えます。", "Menghitung uang.")),
        KOTOBA("k40-2", "測ります", "はかります", "hakarimasu", "mengukur", "Kata Kerja",
               ("長|なが さ を 測|はか ります。", "Mengukur panjangnya.")),
        KOTOBA("k40-3", "量ります", "はかります", "hakarimasu", "menimbang", "Kata Kerja",
               ("重|おも さ を 量|はか ります。", "Menimbang beratnya.")),
        KOTOBA("k40-4", "確かめます", "たしかめます", "tashikamemasu", "memastikan", "Kata Kerja",
               ("時間|じかん を 確|たし かめます。", "Memastikan waktunya.")),
        KOTOBA("k40-5", "合います", "あいます", "aimasu", "cocok; pas", "Kata Kerja",
               ("サイズ が 合|あ います。", "Ukurannya pas.")),
        KOTOBA("k40-6", "出発します", "しゅっぱつします", "shuppatsu shimasu", "berangkat", "Kata Kerja",
               ("8時|はちじ の 飛行機|ひこうき で 出発|しゅっぱつ します。", "Berangkat dengan pesawat jam 8.")),
        KOTOBA("k40-7", "到着します", "とうちゃくします", "tōchaku shimasu", "tiba", "Kata Kerja",
               ("何時|なんじ に 到着|とうちゃく する か 教|おし えて ください。", "Tolong beri tahu jam berapa tibanya.")),
        KOTOBA("k40-8", "酔います", "よいます", "yoimasu", "mabuk", "Kata Kerja",
               ("お酒|さけ に 酔|よ いました。", "Saya mabuk.")),
        KOTOBA("k40-9", "危険", "きけん", "kiken", "berbahaya", "Kata Sifat-na",
               ("ここ で 泳|およ ぐ の は 危険|きけん です。", "Berbahaya berenang di sini.")),
        KOTOBA("k40-10", "忘年会", "ぼうねんかい", "bōnenkai", "pesta akhir tahun", "Kata Benda",
               ("忘年会|ぼうねんかい に 出|で ます か。", "Apakah Anda ikut pesta akhir tahun?")),
        KOTOBA("k40-11", "新年会", "しんねんかい", "shinnenkai", "pesta tahun baru", "Kata Benda",
               ("新年会|しんねんかい は 1月|いちがつ です。", "Pesta tahun barunya bulan Januari.")),
        KOTOBA("k40-12", "二次会", "にじかい", "nijikai", "pesta lanjutan", "Kata Benda",
               ("二次会|にじかい に 行|い きません か。", "Ikut pesta lanjutan, tidak?")),
        KOTOBA("k40-13", "表", "おもて", "omote", "sisi depan", "Kata Benda",
               ("表|おもて に 名前|なまえ を 書|か いて ください。", "Tolong tulis nama di sisi depan.")),
        KOTOBA("k40-14", "裏", "うら", "ura", "sisi belakang", "Kata Benda",
               ("裏|うら も 読|よ んで ください。", "Tolong baca juga sisi belakangnya.")),
        KOTOBA("k40-15", "返事", "へんじ", "henji", "balasan", "Kata Benda",
               ("早|はや く 返事|へんじ を ください。", "Tolong cepat dibalas.")),
        KOTOBA("k40-16", "申し込み", "もうしこみ", "mōshikomi", "pendaftaran", "Kata Benda",
               ("申|もう し込|こ み は もう 済|す みました か。", "Apakah pendaftarannya sudah selesai?")),
        KOTOBA("k40-17", "成績", "せいせき", "seiseki", "nilai; prestasi", "Kata Benda",
               ("成績|せいせき が 上|あ がりました。", "Nilainya naik.")),
        KOTOBA("k40-18", "様子", "ようす", "yōsu", "keadaan; situasi", "Kata Benda",
               ("様子|ようす を 見|み に 行|い きます。", "Saya pergi melihat keadaannya.")),
    ],
    kanji=[
        KANJI("j40-1", "数", "スウ", "かぞ(える)", "hitung; angka", 13,
              [("数えます", "かぞえます", "menghitung"), ("数学", "すうがく", "matematika")]),
        KANJI("j40-2", "測", "ソク", "はか(る)", "ukur", 12,
              [("測ります", "はかります", "mengukur"), ("測定", "そくてい", "pengukuran")]),
        KANJI("j40-3", "確", "カク", "たし(かめる)", "pasti", 15,
              [("確かめます", "たしかめます", "memastikan"), ("確認", "かくにん", "konfirmasi")]),
        KANJI("j40-4", "到", "トウ", "—", "tiba", 8,
              [("到着", "とうちゃく", "tiba"), ("到底", "とうてい", "sama sekali (tidak)")]),
        KANJI("j40-5", "酔", "スイ", "よ(う)", "mabuk", 15,
              [("酔います", "よいます", "mabuk"), ("麻酔", "ますい", "pembiusan")]),
        KANJI("j40-6", "危", "キ", "あぶ(ない)", "bahaya", 6,
              [("危険", "きけん", "berbahaya"), ("危ない", "あぶない", "berbahaya")]),
    ],
    kaiwa=KAIWA(
        "靴屋さんで — Di Toko Sepatu",
        "Seorang pelanggan mencoba sepatu di toko dan bertanya soal ukuran.",
        [
            ("客", "Kaku", "すみません、 この 靴|くつ、 履|は いて みても いい です か。",
             "Permisi, bolehkah saya mencoba sepatu ini?"),
            ("店員", "Tenin", "はい、 どうぞ。 サイズ が 合|あ う か どうか、 確|たし かめて ください。",
             "Silakan. Tolong pastikan apakah ukurannya pas."),
            ("客", "Kaku", "少|すこ し 小|ちい さい です ね。 もう 一|ひと つ 大|おお きい の は あります か。",
             "Agak kecil, ya. Apakah ada yang satu ukuran lebih besar?"),
            ("店員", "Tenin", "ある か どうか 確|たし かめます ので、 少々|しょうしょう お待|ま ち ください。 …ごめんなさい、 これ が 最後|さいご です。",
             "Saya periksa dulu apakah ada, mohon tunggu sebentar. …Maaf, ini stok terakhir."),
            ("客", "Kaku", "そう です か。 じゃ、 いつ 入|はい って 来|く る か、 分|わ かります か。",
             "Oh begitu. Kalau begitu, tahukah Anda kapan stoknya datang?"),
            ("店員", "Tenin", "来週|らいしゅう の 予定|よてい です。 届|とど いたら、 ご連絡|れんらく します。",
             "Dijadwalkan minggu depan. Kalau sudah sampai, akan kami kabari."),
        ],
    ),
    quiz_bunpo=[
        QB("qb40-1", "会議|かいぎ が 何時|なんじ に 始|はじ まる ＿＿ 知|し って います か。", ["か", "かどうか", "のを", "こと"], 0,
           "会議|かいぎ が 何時|なんじ に 始|はじ まる か 知|し って います か。", "始まるか", "[Kata Tanya ＋ bentuk biasa] か",
           "Pertanyaan ber-kata tanya yang disisipkan diakhiri か (tanpa どうか)."),
        QB("qb40-2", "答|こた え が 正|ただ しい ＿＿ 確|たし かめます。", ["かどうか", "かな", "ので", "ば"], 0,
           "答|こた え が 正|ただ しい か どうか 確|たし かめます。", "かどうか", "[Bentuk Biasa] か どうか",
           "Pertanyaan ya/tidak yang disisipkan memakai 〜かどうか."),
        QB("qb40-3", "一度|いちど やって ＿＿ ください。", ["みて", "おいて", "しまって", "いて"], 0,
           "一度|いちど やって みて ください。", "やってみて", "[Bentuk て] みます",
           "〜てみます berarti mencoba melakukan untuk melihat hasilnya."),
        QB_ID("qb40-4", "“Apakah Anda tahu jam berapa keretanya berangkat?”",
              ["電車|でんしゃ が いつ 出発|しゅっぱつ する か 知|し って います か。",
               "電車|でんしゃ が 出発|しゅっぱつ する かどうか 知|し って います か。",
               "電車|でんしゃ が 出発|しゅっぱつ する のを 知|し って います か。",
               "電車|でんしゃ が いつ 出発|しゅっぱつ します か 知|し って います。"], 0,
              "電車|でんしゃ が いつ 出発|しゅっぱつ する か 知|し って います か。", "いつ 出発するか",
              "[Kata Tanya ＋ bentuk biasa] か",
              "Pertanyaan “jam berapa” disisipkan dengan か; かどうか dipakai untuk ya/tidak."),
    ],
    quiz_susun=[
        QS("qs40-1", "Saya memastikan apakah jawabannya benar.",
           "答|こた え が 正|ただ しいか どうか 確|たし かめます", "間違|まちが い 数|かぞ えます"),
        QS("qs40-2", "Apakah Anda tahu jam berapa rapat dimulai?",
           "会議|かいぎ が 何時|なんじ に 始|はじ まるか 知|し って います か", "終|お わる 忘|わす れました"),
        QS("qs40-3", "Bolehkah saya mencoba sepatu ini?",
           "この 靴|くつ を 履|は いて みても いい です か", "買|か って 履|は きます"),
    ],
)

CHAPTERS = [BAB36, BAB37, BAB38, BAB39, BAB40]
