"""Materi Minna no Nihongo 2 — Bab 31 s/d 35."""

from seed_data.dsl import BUNPO, CHAPTER, KAIWA, KANJI, KOTOBA, QB, QB_ID, QS

BAB31 = CHAPTER(
    31, "大学院に 進もうと 思っています。", "Saya berniat melanjutkan ke pascasarjana.",
    bunpo=[
        BUNPO(
            "b31-1", "Bentuk Volitional (意向形) — Mari / Akan",
            "Gol I: 〜います → 〜おう ／ Gol II: ます → よう ／ Gol III: しよう・来|こ よう",
            [
                "Golongan I: 読|よ みます → 読もう (baris い → お ＋ う)",
                "Golongan II: 食|た べます → 食べよう",
                "Golongan III: します → しよう ； 来|き ます → 来|こ よう",
                "dipakai untuk ajakan dan tekad pribadi",
            ],
            "Bentuk volitional menyatakan ajakan (“mari”) atau tekad pembicara (“akan”). "
            "Bentuk sopannya adalah 〜ましょう yang sudah dipelajari di Bab 5.",
            [
                ("あした は 早|はや く 起|お きよう。", "Besok saya akan bangun pagi."),
                ("みんな で 歌|うた を 歌|うた おう。", "Mari kita bernyanyi bersama."),
                ("疲|つか れた から、 少|すこ し 休|やす もう。", "Karena lelah, ayo istirahat sebentar."),
            ],
        ),
        BUNPO(
            "b31-2", "意向形 ＋ と 思います / と 思っています — Niat",
            "[Bentuk Volitional] と 思|おも います ／ と 思|おも って います",
            [
                "〜と 思います = niat yang muncul saat berbicara",
                "〜と 思っています = niat yang sudah dipertimbangkan lama",
                "bisa juga untuk niat orang ketiga",
            ],
            "Untuk menyatakan niat atau rencana, bentuk volitional diikuti と 思います. "
            "Jika rencana itu sudah dipikirkan sejak lama, pakai と 思っています — nuansanya "
            "lebih matang dan mantap.",
            [
                ("大学院|だいがくいん に 進|すす もう と 思|おも って います。",
                 "Saya berniat melanjutkan ke pascasarjana."),
                ("来年|らいねん 国|くに へ 帰|かえ ろう と 思|おも います。", "Tahun depan saya berniat pulang ke tanah air."),
                ("弟|おとうと は 医者|いしゃ に なろう と 思|おも って います。", "Adik saya bercita-cita menjadi dokter."),
            ],
        ),
        BUNPO(
            "b31-3", "つもりです ／ 予定です — Rencana & Jadwal",
            "[Bentuk kamus / ない形] つもり です ／ [Kata Benda] の ／ [Bentuk kamus] 予定|よてい です",
            [
                "つもりです = niat pribadi (positif: 行くつもり / negatif: 行かないつもり)",
                "予定です = jadwal yang sudah ditetapkan (rapat, kereta, acara)",
                "つもり TIDAK dipakai untuk jadwal resmi orang lain",
            ],
            "つもりです menyatakan niat si pembicara sendiri, sedangkan 予定です menyatakan jadwal "
            "yang sudah pasti, misalnya jadwal rapat atau keberangkatan kereta.",
            [
                ("卒業|そつぎょう したら、 国|くに で 働|はたら く つもり です。",
                 "Setelah lulus, saya berniat bekerja di tanah air."),
                ("もう タバコ は 吸|す わない つもり です。", "Saya berniat tidak merokok lagi."),
                ("会議|かいぎ は 3時|さんじ に 始|はじ まる 予定|よてい です。", "Rapat dijadwalkan mulai jam 3."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k31-1", "始まります", "はじまります", "hajimarimasu", "dimulai", "Kata Kerja",
               ("式|しき が 始|はじ まります。", "Upacaranya dimulai.")),
        KOTOBA("k31-2", "続けます", "つづけます", "tsuzukemasu", "melanjutkan", "Kata Kerja",
               ("勉強|べんきょう を 続|つづ けます。", "Melanjutkan belajar.")),
        KOTOBA("k31-3", "見つけます", "みつけます", "mitsukemasu", "menemukan", "Kata Kerja",
               ("かぎ を 見|み つけました。", "Saya menemukan kuncinya.")),
        KOTOBA("k31-4", "受けます", "うけます", "ukemasu", "mengikuti (ujian)", "Kata Kerja",
               ("試験|しけん を 受|う けます。", "Mengikuti ujian.")),
        KOTOBA("k31-5", "入学します", "にゅうがくします", "nyūgaku shimasu", "masuk (sekolah/universitas)", "Kata Kerja",
               ("4月|しがつ に 大学|だいがく に 入学|にゅうがく します。", "Masuk universitas bulan April.")),
        KOTOBA("k31-6", "卒業します", "そつぎょうします", "sotsugyō shimasu", "lulus", "Kata Kerja",
               ("来年|らいねん 卒業|そつぎょう します。", "Tahun depan saya lulus.")),
        KOTOBA("k31-7", "出席します", "しゅっせきします", "shusseki shimasu", "menghadiri", "Kata Kerja",
               ("会議|かいぎ に 出席|しゅっせき します。", "Menghadiri rapat.")),
        KOTOBA("k31-8", "休憩します", "きゅうけいします", "kyūkei shimasu", "beristirahat", "Kata Kerja",
               ("10分|じゅっぷん 休憩|きゅうけい しましょう。", "Mari istirahat 10 menit.")),
        KOTOBA("k31-9", "連休", "れんきゅう", "renkyū", "libur beruntun", "Kata Benda",
               ("連休|れんきゅう に 旅行|りょこう します。", "Berlibur saat libur panjang.")),
        KOTOBA("k31-10", "作文", "さくぶん", "sakubun", "karangan", "Kata Benda",
               ("作文|さくぶん を 書|か きます。", "Menulis karangan.")),
        KOTOBA("k31-11", "展覧会", "てんらんかい", "tenrankai", "pameran", "Kata Benda",
               ("展覧会|てんらんかい を 見|み に 行|い きます。", "Pergi melihat pameran.")),
        KOTOBA("k31-12", "結婚式", "けっこんしき", "kekkonshiki", "upacara pernikahan", "Kata Benda",
               ("結婚式|けっこんしき は 教会|きょうかい で あります。", "Pernikahannya diadakan di gereja.")),
        KOTOBA("k31-13", "本社", "ほんしゃ", "honsha", "kantor pusat", "Kata Benda",
               ("本社|ほんしゃ は 東京|とうきょう に あります。", "Kantor pusatnya ada di Tokyo.")),
        KOTOBA("k31-14", "支店", "してん", "shiten", "kantor cabang", "Kata Benda",
               ("大阪|おおさか の 支店|してん で 働|はたら いて います。", "Bekerja di cabang Osaka.")),
        KOTOBA("k31-15", "大学院", "だいがくいん", "daigakuin", "pascasarjana", "Kata Benda",
               ("大学院|だいがくいん に 進|すす みたい です。", "Saya ingin lanjut ke pascasarjana.")),
        KOTOBA("k31-16", "動物園", "どうぶつえん", "dōbutsuen", "kebun binatang", "Kata Benda",
               ("動物園|どうぶつえん で パンダ を 見|み ました。", "Melihat panda di kebun binatang.")),
        KOTOBA("k31-17", "ずっと", "ずっと", "zutto", "terus-menerus", "Kata Keterangan",
               ("ずっと ここ に います。", "Saya di sini terus.")),
        KOTOBA("k31-18", "残ります", "のこります", "nokorimasu", "tersisa; tinggal", "Kata Kerja",
               ("ケーキ が 少|すこ し 残|のこ って います。", "Kuenya tersisa sedikit.")),
    ],
    kanji=[
        KANJI("j31-1", "始", "シ", "はじ(まる)", "mulai", 8,
              [("始まります", "はじまります", "dimulai"), ("開始", "かいし", "permulaan")]),
        KANJI("j31-2", "続", "ゾク", "つづ(ける)", "lanjut", 13,
              [("続けます", "つづけます", "melanjutkan"), ("連続", "れんぞく", "beruntun")]),
        KANJI("j31-3", "受", "ジュ", "う(ける)", "terima; ikut", 8,
              [("受けます", "うけます", "mengikuti (ujian)"), ("受験", "じゅけん", "ujian masuk")]),
        KANJI("j31-4", "卒", "ソツ", "—", "lulus", 8,
              [("卒業", "そつぎょう", "kelulusan"), ("卒業式", "そつぎょうしき", "upacara wisuda")]),
        KANJI("j31-5", "式", "シキ", "—", "upacara", 6,
              [("結婚式", "けっこんしき", "upacara pernikahan"), ("式", "しき", "upacara")]),
        KANJI("j31-6", "院", "イン", "—", "lembaga", 10,
              [("大学院", "だいがくいん", "pascasarjana"), ("病院", "びょういん", "rumah sakit")]),
    ],
    kaiwa=KAIWA(
        "卒業後の こと — Rencana Setelah Lulus",
        "Miller dan Pak Yamada berbincang tentang rencana Miller setelah menyelesaikan kursusnya.",
        [
            ("山田", "Yamada", "ミラーさん、 日本語学校|にほんごがっこう を 卒業|そつぎょう したら、 どう するん です か。",
             "Pak Miller, setelah lulus dari sekolah bahasa Jepang, apa rencana Anda?"),
            ("ミラー", "Mirā", "大学院|だいがくいん に 進|すす もう と 思|おも って います。",
             "Saya berniat melanjutkan ke pascasarjana."),
            ("山田", "Yamada", "そう です か。 試験|しけん は いつ です か。",
             "Oh begitu. Kapan ujiannya?"),
            ("ミラー", "Mirā", "2月|にがつ の 初|はじ め の 予定|よてい です。 それまで ずっと 勉強|べんきょう を 続|つづ ける つもり です。",
             "Dijadwalkan awal Februari. Sampai saat itu saya berniat terus belajar."),
            ("山田", "Yamada", "大変|たいへん です ね。 合格|ごうかく する と いい です ね。",
             "Berat, ya. Semoga lulus, ya."),
            ("ミラー", "Mirā", "ありがとう ございます。 合格|ごうかく したら、 連絡|れんらく します。",
             "Terima kasih. Kalau lulus, akan saya kabari."),
        ],
    ),
    quiz_bunpo=[
        QB("qb31-1", "あした は 早|はや く 起|お き＿＿。", ["よう", "いよう", "きう", "お"], 0,
           "あした は 早|はや く 起|お きよう。", "起きよう", "Gol II: ます → よう",
           "Golongan II mengganti ます dengan よう: 起きます → 起きよう."),
        QB("qb31-2", "来年|らいねん 国|くに へ 帰|かえ る ＿＿ です。", ["つもり", "はず", "まま", "わけ"], 0,
           "来年|らいねん 国|くに へ 帰|かえ る つもり です。", "つもり", "[Bentuk kamus] つもり です",
           "つもりです menyatakan niat pribadi; bentuknya mengikuti bentuk kamus."),
        QB("qb31-3", "会議|かいぎ は 3時|さんじ に 始|はじ まる ＿＿ です。", ["予定", "つもり", "意向", "ため"], 0,
           "会議|かいぎ は 3時|さんじ に 始|はじ まる 予定|よてい です。", "予定", "〜 予定|よてい です",
           "Jadwal resmi seperti rapat memakai 予定です, bukan つもりです."),
        QB_ID("qb31-4", "“Saya berniat melanjutkan ke pascasarjana.”",
              ["大学院|だいがくいん に 進|すす もう と 思|おも って います。",
               "大学院|だいがくいん に 進|すす みます と 思|おも います。",
               "大学院|だいがくいん に 進|すす む 予定|よてい と 思|おも います。",
               "大学院|だいがくいん に 進|すす んだ と 思|おも って います。"], 0,
              "大学院|だいがくいん に 進|すす もう と 思|おも って います。", "進もうと 思っています",
              "[Bentuk Volitional] と 思|おも って います",
              "Niat yang sudah dipikirkan lama memakai bentuk volitional + と 思っています."),
    ],
    quiz_susun=[
        QS("qs31-1", "Saya berniat melanjutkan ke pascasarjana.",
           "大学院|だいがくいん に 進|すす もうと 思|おも って います", "帰|かえ ろう 会社|かいしゃ"),
        QS("qs31-2", "Besok saya akan bangun pagi.",
           "あした は 早|はや く 起|お きようと 思|おも います", "遅|おそ く 寝|ね よう"),
        QS("qs31-3", "Rapat dijadwalkan mulai jam 3.",
           "会議|かいぎ は 3時|さんじ に 始|はじ まる 予定|よてい です", "終|お わる つもり"),
    ],
)

BAB32 = CHAPTER(
    32, "たぶん あしたは いい 天気に なる でしょう。", "Besok mungkin cuacanya akan bagus.",
    bunpo=[
        BUNPO(
            "b32-1", "〜ほうが いいです — Sebaiknya",
            "[Kata Kerja bentuk た] ほうが いい です ／ [Bentuk ない] ほうが いい です",
            [
                "saran positif: Vた形 + ほうがいいです",
                "saran negatif: Vない形 + ほうがいいです",
                "bentuk 現在 (〜るほうがいい) dipakai untuk nasihat umum",
            ],
            "Pola ini memberi saran. Untuk saran melakukan sesuatu dipakai bentuk た; untuk saran "
            "agar TIDAK melakukan dipakai bentuk ない: 行かない ほうが いいです (sebaiknya jangan pergi).",
            [
                ("かぜ です から、 早|はや く 寝|ね た ほうが いい です よ。",
                 "Karena masuk angin, sebaiknya Anda cepat tidur."),
                ("もっと 運動|うんどう した ほうが いい です。", "Sebaiknya Anda lebih banyak berolahraga."),
                ("無理|むり は しない ほうが いい です。", "Sebaiknya jangan memaksakan diri."),
            ],
        ),
        BUNPO(
            "b32-2", "〜でしょう — Dugaan (Cukup Yakin)",
            "[Bentuk Biasa] でしょう",
            [
                "keyakinan pembicara cukup tinggi (±80%)",
                "sering dipakai bersama たぶん",
                "bentuk pertanyaan 〜でしょう？ untuk meminta persetujuan",
            ],
            "でしょう menyatakan dugaan dengan keyakinan yang cukup tinggi, misalnya ramalan cuaca. "
            "Dengan nada naik (〜でしょう？), polanya meminta persetujuan lawan bicara.",
            [
                ("たぶん あした は いい 天気|てんき に なる でしょう。", "Besok mungkin cuacanya akan bagus."),
                ("あの 人|ひと は たぶん 田中|たなか さん の 弟|おとうと さん でしょう。",
                 "Orang itu mungkin adiknya Pak Tanaka."),
                ("この 本|ほん は おもしろい でしょう。", "Buku ini menarik, kan?"),
            ],
        ),
        BUNPO(
            "b32-3", "〜かもしれません — Kemungkinan (Kurang Yakin)",
            "[Bentuk Biasa] かもしれません",
            [
                "kemungkinan lebih kecil daripada でしょう (±50%)",
                "sering dipakai bersama もしかしたら",
                "bisa untuk hal baik maupun buruk",
            ],
            "かもしれません menyatakan kemungkinan ketika pembicara kurang yakin. Bandingkan: "
            "あした 雨が 降るでしょう (saya cukup yakin) vs 降るかもしれません (mungkin saja).",
            [
                ("もしかしたら、 彼|かれ は 来|こ ない かもしれません。", "Mungkin saja dia tidak datang."),
                ("かぜ を ひいた かもしれません。", "Mungkin saya masuk angin."),
                ("宝|たから くじ が 当|あ たる かもしれません。", "Mungkin saja lotrenya menang."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k32-1", "運動します", "うんどうします", "undō shimasu", "berolahraga", "Kata Kerja",
               ("健康|けんこう の ため に 運動|うんどう します。", "Berolahraga demi kesehatan.")),
        KOTOBA("k32-2", "成功します", "せいこうします", "seikō shimasu", "berhasil", "Kata Kerja",
               ("実験|じっけん が 成功|せいこう しました。", "Eksperimennya berhasil.")),
        KOTOBA("k32-3", "失敗します", "しっぱいします", "shippai shimasu", "gagal", "Kata Kerja",
               ("試験|しけん に 失敗|しっぱい しました。", "Gagal dalam ujian.")),
        KOTOBA("k32-4", "合格します", "ごうかくします", "gōkaku shimasu", "lulus (ujian)", "Kata Kerja",
               ("試験|しけん に 合格|ごうかく しました。", "Lulus ujian.")),
        KOTOBA("k32-5", "戻ります", "もどります", "modorimasu", "kembali", "Kata Kerja",
               ("すぐ 戻|もど ります。", "Saya segera kembali.")),
        KOTOBA("k32-6", "やみます", "やみます", "yamimasu", "berhenti (hujan)", "Kata Kerja",
               ("雨|あめ が やみました。", "Hujannya berhenti.")),
        KOTOBA("k32-7", "晴れます", "はれます", "haremasu", "cerah", "Kata Kerja",
               ("あした は 晴|は れる でしょう。", "Besok mungkin cerah.")),
        KOTOBA("k32-8", "曇ります", "くもります", "kumorimasu", "mendung", "Kata Kerja",
               ("夕方|ゆうがた から 曇|くも る でしょう。", "Sore nanti mungkin mendung.")),
        KOTOBA("k32-9", "吹きます", "ふきます", "fukimasu", "bertiup", "Kata Kerja",
               ("強|つよ い 風|かぜ が 吹|ふ いて います。", "Angin kencang sedang bertiup.")),
        KOTOBA("k32-10", "治ります", "なおります", "naorimasu", "sembuh; terperbaiki", "Kata Kerja",
               ("病気|びょうき が 治|なお りました。", "Sakitnya sudah sembuh.")),
        KOTOBA("k32-11", "ひきます", "ひきます", "hikimasu", "tertular (sakit)", "Kata Kerja",
               ("かぜ を ひきました。", "Saya masuk angin.")),
        KOTOBA("k32-12", "冷やします", "ひやします", "hiyashimasu", "mendinginkan", "Kata Kerja",
               ("熱|ねつ が ある から、 頭|あたま を 冷|ひ やします。", "Karena demam, saya kompres kepalanya.")),
        KOTOBA("k32-13", "心配", "しんぱい", "shinpai", "khawatir", "Kata Sifat-na",
               ("母|はは が 心配|しんぱい して います。", "Ibu khawatir.")),
        KOTOBA("k32-14", "十分", "じゅうぶん", "jūbun", "cukup", "Kata Sifat-na",
               ("睡眠|すいみん は 十分|じゅうぶん です か。", "Apakah tidur Anda cukup?")),
        KOTOBA("k32-15", "おかしい", "おかしい", "okashii", "aneh; lucu", "Kata Sifat-i",
               ("パソコン の 調子|ちょうし が おかしい です。", "Kondisi komputernya aneh.")),
        KOTOBA("k32-16", "うるさい", "うるさい", "urusai", "berisik", "Kata Sifat-i",
               ("隣|となり の 部屋|へや が うるさい です。", "Kamar sebelah berisik.")),
        KOTOBA("k32-17", "けが", "けが", "kega", "luka; cedera", "Kata Benda",
               ("けが を しました。", "Saya terluka.")),
        KOTOBA("k32-18", "今夜", "こんや", "konya", "malam ini", "Kata Keterangan",
               ("今夜|こんや は 寒|さむ く なる でしょう。", "Malam ini mungkin akan dingin.")),
    ],
    kanji=[
        KANJI("j32-1", "晴", "セイ", "は(れる)", "cerah", 12,
              [("晴れます", "はれます", "cerah"), ("晴天", "せいてん", "cuaca cerah")]),
        KANJI("j32-2", "曇", "ドン", "くも(る)", "mendung", 16,
              [("曇ります", "くもります", "mendung"), ("曇天", "どんてん", "langit mendung")]),
        KANJI("j32-3", "吹", "スイ", "ふ(く)", "tiup", 7,
              [("吹きます", "ふきます", "bertiup"), ("吹雪", "ふぶき", "badai salju")]),
        KANJI("j32-4", "治", "ジ", "なお(る)", "sembuh", 8,
              [("治ります", "なおります", "sembuh"), ("治療", "ちりょう", "perawatan medis")]),
        KANJI("j32-5", "星", "セイ", "ほし", "bintang", 9,
              [("星", "ほし", "bintang"), ("星座", "せいざ", "rasi bintang")]),
        KANJI("j32-6", "健", "ケン", "—", "sehat", 11,
              [("健康", "けんこう", "kesehatan"), ("健全", "けんぜん", "sehat; sehat jasmani")]),
    ],
    kaiwa=KAIWA(
        "かぜを ひいた みたい — Sepertinya Masuk Angin",
        "Di kantor, Pak Yamada khawatir melihat wajah Miller yang pucat.",
        [
            ("山田", "Yamada", "ミラーさん、 顔色|かおいろ が 悪|わる い です ね。",
             "Pak Miller, wajah Anda kelihatan kurang sehat."),
            ("ミラー", "Mirā", "昨日|きのう から せき が 出|で るん です。 かぜ を ひいた かもしれません。",
             "Sejak kemarin saya batuk. Mungkin saya masuk angin."),
            ("山田", "Yamada", "それは いけません ね。 病院|びょういん へ 行|い った ほうが いい です よ。",
             "Wah, kasihan. Sebaiknya Anda periksa ke rumah sakit."),
            ("ミラー", "Mirā", "ええ、 午後|ごご 行|い く つもり です。", "Ya, siang ini saya berencana pergi."),
            ("山田", "Yamada", "今夜|こんや は 寒|さむ く なる でしょう。 早|はや く 帰|かえ った ほうが いい です。 お大事|だいじ に ね。",
             "Malam ini mungkin akan dingin. Sebaiknya Anda cepat pulang. Lekas sembuh, ya."),
            ("ミラー", "Mirā", "ありがとう ございます。 そう します。",
             "Terima kasih. Baik, saya pulang sekarang."),
        ],
    ),
    quiz_bunpo=[
        QB("qb32-1", "かぜ を ひきました。 早|はや く 寝|ね た ＿＿ が いい です よ。", ["ほう", "もの", "こと", "わけ"], 0,
           "早|はや く 寝|ね た ほうが いい です よ。", "寝たほうが いい", "[Bentuk た] ほうが いい です",
           "Saran untuk melakukan sesuatu memakai bentuk た + ほうがいいです."),
        QB("qb32-2", "たぶん あした は 雨|あめ が 降|ふ る ＿＿。", ["でしょう", "つもりです", "ままです", "とおりです"], 0,
           "たぶん あした は 雨|あめ が 降|ふ る でしょう。", "降るでしょう", "[Bentuk Biasa] でしょう",
           "でしょう menyatakan dugaan dengan keyakinan cukup tinggi; sering berpasangan dengan たぶん."),
        QB("qb32-3", "もしかしたら、 彼|かれ は 来|こ ない ＿＿。", ["かもしれません", "でしょう", "ほうがいいです", "つもりです"], 0,
           "もしかしたら、 彼|かれ は 来|こ ない かもしれません。", "かもしれません", "[Bentuk Biasa] かもしれません",
           "もしかしたら berpasangan dengan かもしれません untuk kemungkinan yang kurang pasti."),
        QB_ID("qb32-4", "“Sebaiknya Anda tidak minum obat itu.”",
              ["その 薬|くすり は 飲|の まない ほうが いい です。",
               "その 薬|くすり は 飲|の んだ ほうが いい です。",
               "その 薬|くすり は 飲|の む ほうが いい です。",
               "その 薬|くすり は 飲|の んで ほうが いい です。"], 0,
              "その 薬|くすり は 飲|の まない ほうが いい です。", "飲まない ほうが いい",
              "[Bentuk ない] ほうが いい です",
              "Saran agar TIDAK melakukan memakai bentuk ない + ほうがいいです."),
    ],
    quiz_susun=[
        QS("qs32-1", "Sebaiknya Anda lebih banyak berolahraga.",
           "もっと 運動|うんどう した ほうが いい です", "しない たぶん"),
        QS("qs32-2", "Mungkin besok akan turun hujan.",
           "あした は 雨|あめ が 降|ふ る かもしれません", "晴|は れる でしょう"),
        QS("qs32-3", "Besok mungkin cuacanya akan bagus.",
           "たぶん あした は いい 天気|てんき に なる でしょう", "悪|わる い かもしれません"),
    ],
)

BAB33 = CHAPTER(
    33, "あの マークは どういう 意味ですか。", "Apa arti tanda itu?",
    bunpo=[
        BUNPO(
            "b33-1", "Bentuk Perintah (命令形) & Larangan (禁止形)",
            "Gol I: い → え ／ Gol II: ろ ／ Gol III: しろ・来|こ い ／ Larangan: bentuk kamus ＋ な",
            [
                "Golongan I: 書|か け ； 急|いそ げ",
                "Golongan II: 食|た べろ ； 見|み ろ",
                "Golongan III: しろ ； 来|こ い",
                "larangan: 書|か くな ； 入|はい るな",
                "terdengar kasar — dipakai di papan tanda, ujian, olahraga",
            ],
            "Bentuk perintah dan larangan terdengar keras sehingga jarang dipakai dalam percakapan "
            "sehari-hari. Namun bentuk ini sering muncul di papan petunjuk (止まれ), soal ujian "
            "(説明しろ), dan teriakan penyemangat (がんばれ).",
            [
                ("止|と まれ。", "Berhenti."),
                ("早|はや く しろ。", "Cepat lakukan."),
                ("ここ に 入|はい るな。", "Dilarang masuk ke sini."),
            ],
        ),
        BUNPO(
            "b33-2", "〜と 書いて あります ／ 〜と 読みます — Membaca Tanda",
            "[Isi tulisan] と 書|か いて あります ／ 何|なん と 読|よ みます か",
            [
                "dipakai untuk menyebutkan isi papan, tanda, poster",
                "「立入禁止」と 書いてあります = tertulis “dilarang masuk”",
                "この 漢字は 何と 読みますか = bagaimana kanji ini dibaca",
            ],
            "Untuk mengutip tulisan di papan atau dokumen, isinya diikuti と 書いてあります. "
            "Untuk menanyakan cara baca huruf atau kata, pakai 何と 読みますか.",
            [
                ("あの マーク に 「立入|たちいり 禁止|きんし」 と 書|か いて あります。",
                 "Pada tanda itu tertulis “dilarang masuk”."),
                ("この 漢字|かんじ は 何|なん と 読|よ みます か。", "Kanji ini dibaca apa?"),
                ("ドア に 「使用中|しようちゅう」 と 書|か いて あります。", "Di pintu tertulis “sedang dipakai”."),
            ],
        ),
        BUNPO(
            "b33-3", "〜という 意味です ／ 〜と 言っていました — Arti & Pesan",
            "[Kata] と いう 意味|いみ です ／ [Isi pesan] と 言|い って いました",
            [
                "Xは Y という意味です = X berarti Y",
                "どういう 意味ですか = apa artinya",
                "menyampaikan pesan orang lain: 〜と 言っていました",
                "meminta menyampaikan: 〜と 伝えて いただけませんか",
            ],
            "〜という意味です dipakai untuk menjelaskan arti sebuah kata atau tanda. Sedangkan "
            "〜と 言っていました dipakai untuk meneruskan perkataan orang lain (pesan lisan).",
            [
                ("「駐車|ちゅうしゃ 違反|いはん」 は どういう 意味|いみ です か。", "Apa arti “pelanggaran parkir”?"),
                ("「本日|ほんじつ 休業|きゅうぎょう」 は 今日|きょう は 休|やす み だ と いう 意味|いみ です。",
                 "“Tutup hari ini” artinya hari ini libur."),
                ("山田|やまだ さん が 「会議|かいぎ は 4時|よじ から です」 と 言|い って いました。",
                 "Bu Yamada bilang rapatnya mulai jam 4."),
            ],
        ),
        BUNPO(
            "b33-4", "〜って — Bentuk Santai Pengganti と",
            "[Kalimat bentuk biasa] って",
            [
                "bentuk percakapan santai dari と",
                "bisa juga menggantikan という: ～って 意味",
                "hanya untuk situasi tidak formal",
            ],
            "Dalam percakapan santai dengan teman dekat, と sering diganti って untuk mengutip "
            "perkataan atau menyebut nama sesuatu.",
            [
                ("山田|やまだ さん、 あした 休|やす む って。", "Kata Yamada, besok dia libur."),
                ("「禁止|きんし」 って どういう 意味|いみ。", "“Larangan” itu artinya apa?"),
                ("あの 店|みせ、 おいしい って 評判|ひょうばん だ よ。", "Toko itu katanya enak, lho."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k33-1", "逃げます", "にげます", "nigemasu", "kabur; melarikan diri", "Kata Kerja",
               ("猫|ねこ が 逃|に げました。", "Kucingnya kabur.")),
        KOTOBA("k33-2", "騒ぎます", "さわぎます", "sawagimasu", "gaduh; ribut", "Kata Kerja",
               ("夜|よる 騒|さわ がないで ください。", "Tolong jangan gaduh malam-malam.")),
        KOTOBA("k33-3", "あきらめます", "あきらめます", "akiramemasu", "menyerah; pasrah", "Kata Kerja",
               ("夢|ゆめ を あきらめません。", "Saya tidak menyerah pada mimpi.")),
        KOTOBA("k33-4", "投げます", "なげます", "nagemasu", "melempar", "Kata Kerja",
               ("ボール を 投|な げます。", "Melempar bola.")),
        KOTOBA("k33-5", "守ります", "まもります", "mamorimasu", "mematuhi; menjaga", "Kata Kerja",
               ("規則|きそく を 守|まも りましょう。", "Mari patuhi peraturan.")),
        KOTOBA("k33-6", "上げます", "あげます", "agemasu", "menaikkan", "Kata Kerja",
               ("手|て を 上|あ げて ください。", "Silakan angkat tangan.")),
        KOTOBA("k33-7", "下げます", "さげます", "sagemasu", "menurunkan", "Kata Kerja",
               ("値段|ねだん を 下|さ げます。", "Menurunkan harga.")),
        KOTOBA("k33-8", "伝えます", "つたえます", "tsutaemasu", "menyampaikan", "Kata Kerja",
               ("先生|せんせい に 伝|つた えて ください。", "Tolong sampaikan kepada guru.")),
        KOTOBA("k33-9", "注意します", "ちゅういします", "chūi shimasu", "berhati-hati", "Kata Kerja",
               ("車|くるま に 注意|ちゅうい してください。", "Tolong hati-hati terhadap mobil.")),
        KOTOBA("k33-10", "席を外します", "せきをはずします", "seki o hazushimasu", "meninggalkan meja sebentar", "Ungkapan",
               ("今|いま 席|せき を 外|はず して います。", "Beliau sedang tidak di tempat.")),
        KOTOBA("k33-11", "だめ", "だめ", "dame", "tidak boleh; percuma", "Kata Sifat-na",
               ("ここ で 写真|しゃしん を 撮|と っては だめ です。", "Tidak boleh memotret di sini.")),
        KOTOBA("k33-12", "規則", "きそく", "kisoku", "peraturan", "Kata Benda",
               ("学校|がっこう の 規則|きそく が 厳|きび しい です。", "Peraturan sekolahnya ketat.")),
        KOTOBA("k33-13", "使用禁止", "しようきんし", "shiyō kinshi", "dilarang menggunakan", "Kata Benda",
               ("この 機械|きかい は 使用|しよう 禁止|きんし です。", "Mesin ini dilarang digunakan.")),
        KOTOBA("k33-14", "立入禁止", "たちいりきんし", "tachiiri kinshi", "dilarang masuk", "Kata Benda",
               ("ここ は 立入|たちいり 禁止|きんし です。", "Di sini dilarang masuk.")),
        KOTOBA("k33-15", "非常口", "ひじょうぐち", "hijōguchi", "pintu darurat", "Kata Benda",
               ("非常口|ひじょうぐち は あそこ です。", "Pintu daruratnya di sana.")),
        KOTOBA("k33-16", "営業中", "えいぎょうちゅう", "eigyōchū", "sedang buka (toko)", "Kata Benda",
               ("「営業中|えいぎょうちゅう」 と 書|か いて あります。", "Tertulis “sedang buka”.")),
        KOTOBA("k33-17", "罰金", "ばっきん", "bakkin", "denda", "Kata Benda",
               ("罰金|ばっきん を 払|はら いました。", "Saya membayar denda.")),
        KOTOBA("k33-18", "できるだけ", "できるだけ", "dekiru dake", "sebisa mungkin", "Kata Keterangan",
               ("できるだけ 早|はや く 来|き て ください。", "Tolong datang secepat mungkin.")),
    ],
    kanji=[
        KANJI("j33-1", "逃", "トウ", "に(げる)", "kabur", 9,
              [("逃げます", "にげます", "kabur"), ("逃亡", "とうぼう", "pelarian")]),
        KANJI("j33-2", "投", "トウ", "な(げる)", "lempar", 7,
              [("投げます", "なげます", "melempar"), ("投票", "とうひょう", "pemungutan suara")]),
        KANJI("j33-3", "守", "シュ", "まも(る)", "jaga; patuhi", 6,
              [("守ります", "まもります", "mematuhi"), ("守備", "しゅび", "pertahanan")]),
        KANJI("j33-4", "伝", "デン", "つた(える)", "sampaikan", 6,
              [("伝えます", "つたえます", "menyampaikan"), ("伝言", "でんごん", "pesan")]),
        KANJI("j33-5", "注", "チュウ", "—", "perhatian; tuang", 8,
              [("注意", "ちゅうい", "perhatian; hati-hati"), ("注文", "ちゅうもん", "pesanan")]),
        KANJI("j33-6", "禁", "キン", "—", "larang", 13,
              [("禁止", "きんし", "larangan"), ("禁煙", "きんえん", "dilarang merokok")]),
    ],
    kaiwa=KAIWA(
        "マークの 意味 — Arti Tanda",
        "Pon dan Li melihat berbagai papan tanda di gedung olahraga.",
        [
            ("ポン", "Pon", "あの マーク は どういう 意味|いみ です か。", "Apa arti tanda itu?"),
            ("リー", "Rī", "「立入|たちいり 禁止|きんし」 と 書|か いて あります。 中|なか に 入|はい っては いけない と いう 意味|いみ です。",
             "Tertulis “dilarang masuk”. Artinya kita tidak boleh masuk ke dalam."),
            ("ポン", "Pon", "へえ。 こっち の 洗濯機|せんたくき は 「使用|しよう 禁止|きんし」 です ね。",
             "Oh. Mesin cuci yang ini tertulis “dilarang digunakan”, ya."),
            ("リー", "Rī", "ええ、 壊|こわ れて いるん です。 あ、 そうだ。 山田|やまだ さん が 「会議|かいぎ は 4時|よじ から」 と 言|い って いました よ。",
             "Iya, sedang rusak. Ah, iya. Bu Yamada bilang rapatnya mulai jam 4, lho."),
            ("ポン", "Pon", "分|わ かりました。 じゃ、 急|いそ ぎましょう。", "Baik. Kalau begitu, ayo buru-buru."),
        ],
    ),
    quiz_bunpo=[
        QB("qb33-1", "急|いそ ぎます の 命令形|めいれいけい は ＿＿。", ["急げ", "急ご", "急げよ", "急いで"], 0,
           "急|いそ げ。", "急げ", "Gol I: baris い → baris え",
           "Bentuk perintah Golongan I mengubah baris い menjadi え: 急ぎます → 急げ."),
        QB("qb33-2", "ここ に 車|くるま を 止|と める ＿＿。", ["な", "ては", "ず", "なく"], 0,
           "ここ に 車|くるま を 止|と めるな。", "止めるな", "[Bentuk kamus] ＋ な",
           "Bentuk larangan dibentuk dari bentuk kamus + な."),
        QB("qb33-3", "あの マーク に 「立入|たちいり 禁止|きんし」 と ＿＿ あります。", ["書いて", "書きます", "書く", "書いた"], 0,
           "あの マーク に 「立入|たちいり 禁止|きんし」 と 書|か いて あります。", "書いてあります",
           "〜 と 書|か いて あります",
           "Isi tulisan di papan diikuti と 書いてあります."),
        QB_ID("qb33-4", "“Bu Yamada bilang rapatnya mulai jam 4.”",
              ["山田|やまだ さん が 会議|かいぎ は 4時|よじ から だ と 言|い って いました。",
               "山田|やまだ さん が 会議|かいぎ は 4時|よじ から だ と 書|か いて あります。",
               "山田|やまだ さん は 会議|かいぎ が 4時|よじ から 言|い います。",
               "山田|やまだ さん が 会議|かいぎ に 4時|よじ から 言|い いました。"], 0,
              "山田|やまだ さん が 会議|かいぎ は 4時|よじ から だ と 言|い って いました。", "と 言っていました",
              "[Isi pesan] と 言|い って いました",
              "Meneruskan perkataan orang lain memakai 〜と 言っていました."),
    ],
    quiz_susun=[
        QS("qs33-1", "Pada tanda itu tertulis “dilarang menggunakan”.",
           "あの マーク に 使用禁止|しようきんし と 書|か いて あります", "言|い って 営業中|えいぎょうちゅう"),
        QS("qs33-2", "Bu Yamada bilang rapatnya mulai jam 4.",
           "山田|やまだ さん が 会議|かいぎ は 4時|よじ から だと 言|い って いました", "書|か いて 終|お わる"),
        QS("qs33-3", "Apa arti tanda itu?",
           "あの マーク は どういう 意味|いみ です か", "この 読|よ みます"),
    ],
)

BAB34 = CHAPTER(
    34, "説明書の とおりに 組み立てます。", "Merakit sesuai buku petunjuk.",
    bunpo=[
        BUNPO(
            "b34-1", "〜とおりに — Sesuai Dengan",
            "[Kata Benda] の とおり に ／ [Kata Kerja bentuk kamus・た] とおり に",
            [
                "kata benda: 説明書|せつめいしょ の とおり に",
                "kata kerja bentuk kamus: 書|か いて ある とおり に",
                "kata kerja bentuk た: 思|おも った とおり に",
            ],
            "〜とおりに berarti melakukan sesuatu persis mengikuti contoh, instruksi, atau keadaan "
            "yang disebutkan: sesuai buku petunjuk, sesuai yang dibayangkan, sesuai perkataan.",
            [
                ("説明書|せつめいしょ の とおり に 組|く み立|た てます。", "Merakit sesuai buku petunjuk."),
                ("わたし が 言|い った とおり に やって ください。", "Kerjakan sesuai yang saya katakan."),
                ("思|おも った とおり に なりました。", "Hasilnya sesuai yang saya bayangkan."),
            ],
        ),
        BUNPO(
            "b34-2", "〜た あとで — Setelah Melakukan",
            "[Kata Kerja bentuk た] あと で、 〜",
            [
                "urutan: aksi pertama selesai, lalu aksi kedua",
                "berpasangan terbalik dengan 〜まえに (Bab 18)",
                "bisa juga 食事|しょくじ の あと で (kata benda + の)",
            ],
            "〜たあとで menyatakan aksi kedua dilakukan setelah aksi pertama selesai. Ingat: "
            "bentuknya SELALU た, kebalikan dari まえに yang memakai bentuk kamus.",
            [
                ("ごはん を 食|た べた あと で、 歯|は を 磨|みが きます。", "Setelah makan, saya menggosok gigi."),
                ("仕事|しごと が 終|お わった あと で、 飲|の みに 行|い きます。", "Setelah pekerjaan selesai, kami pergi minum."),
                ("授業|じゅぎょう の あと で、 質問|しつもん します。", "Setelah pelajaran, saya bertanya."),
            ],
        ),
        BUNPO(
            "b34-3", "〜ないで — Tanpa Melakukan",
            "[Bentuk ない tanpa ない] ない で、 〜",
            [
                "行|い かない で = tanpa pergi",
                "食|た べない で = tanpa makan",
                "berbeda dengan 〜なくて (sebab-akibat)",
            ],
            "〜ないで menyatakan aksi kedua dilakukan TANPA melakukan aksi pertama. Jangan tertukar "
            "dengan 〜なくて yang menyatakan sebab: 傘を 持たないで 出かけました (pergi tanpa membawa "
            "payung).",
            [
                ("歯|は を 磨|みが かない で、 寝|ね ました。", "Dia tidur tanpa menggosok gigi."),
                ("朝|あさ ごはん を 食|た べない で、 会社|かいしゃ へ 行|い きました。",
                 "Saya pergi ke kantor tanpa sarapan."),
                ("説明書|せつめいしょ を 見|み ない で、 組|く み立|た てました。",
                 "Dia merakit tanpa melihat buku petunjuk."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k34-1", "磨きます", "みがきます", "migakimasu", "menggosok; mengasah", "Kata Kerja",
               ("歯|は を 磨|みが きます。", "Menggosok gigi.")),
        KOTOBA("k34-2", "組み立てます", "くみたてます", "kumitatemasu", "merakit", "Kata Kerja",
               ("家具|かぐ を 組|く み立|た てます。", "Merakit perabot.")),
        KOTOBA("k34-3", "気がつきます", "きがつきます", "ki ga tsukimasu", "menyadari", "Kata Kerja",
               ("忘|わす れ物|もの に 気|き が つきました。", "Saya menyadari ada barang ketinggalan.")),
        KOTOBA("k34-4", "つけます", "つけます", "tsukemasu", "mencelup; membubuh", "Kata Kerja",
               ("しょうゆ を つけて 食|た べます。", "Makan dengan mencelup kecap.")),
        KOTOBA("k34-5", "見つかります", "みつかります", "mitsukarimasu", "ditemukan", "Kata Kerja",
               ("かぎ が 見|み つかりました。", "Kuncinya sudah ditemukan.")),
        KOTOBA("k34-6", "質問します", "しつもんします", "shitsumon shimasu", "bertanya", "Kata Kerja",
               ("先生|せんせい に 質問|しつもん します。", "Bertanya kepada guru.")),
        KOTOBA("k34-7", "細い", "ほそい", "hosoi", "ramping; tipis", "Kata Sifat-i",
               ("線|せん が 細|ほそ い です。", "Garisnya tipis.")),
        KOTOBA("k34-8", "太い", "ふとい", "futoi", "tebal; besar", "Kata Sifat-i",
               ("太|ふと い ロープ を 買|か いました。", "Membeli tali yang besar.")),
        KOTOBA("k34-9", "家具", "かぐ", "kagu", "perabot", "Kata Benda",
               ("新|あたら しい 家具|かぐ を 組|く み立|た てます。", "Merakit perabot baru.")),
        KOTOBA("k34-10", "説明書", "せつめいしょ", "setsumeisho", "buku petunjuk", "Kata Benda",
               ("説明書|せつめいしょ を よく 読|よ んで ください。", "Tolong baca buku petunjuk baik-baik.")),
        KOTOBA("k34-11", "図", "ず", "zu", "gambar; diagram", "Kata Benda",
               ("図|ず を 見|み ながら 説明|せつめい します。", "Menjelaskan sambil melihat diagram.")),
        KOTOBA("k34-12", "線", "せん", "sen", "garis", "Kata Benda",
               ("線|せん の とおり に 切|き って ください。", "Tolong potong sesuai garis.")),
        KOTOBA("k34-13", "矢印", "やじるし", "yajirushi", "tanda panah", "Kata Benda",
               ("矢印|やじるし の ほう へ 進|すす んで ください。", "Silakan maju ke arah tanda panah.")),
        KOTOBA("k34-14", "苦い", "にがい", "nigai", "pahit", "Kata Sifat-i",
               ("この 薬|くすり は 苦|にが い です。", "Obat ini pahit.")),
        KOTOBA("k34-15", "材料", "ざいりょう", "zairyō", "bahan", "Kata Benda",
               ("材料|ざいりょう を 全部|ぜんぶ 切|き って おきます。", "Semua bahan dipotong dulu.")),
        KOTOBA("k34-16", "調味料", "ちょうみりょう", "chōmiryō", "bumbu", "Kata Benda",
               ("調味料|ちょうみりょう を 入|い れます。", "Memasukkan bumbu.")),
        KOTOBA("k34-17", "煮ます", "にます", "nimasu", "merebus; memasak", "Kata Kerja",
               ("野菜|やさい を 煮|に ます。", "Merebus sayuran.")),
        KOTOBA("k34-18", "先に", "さきに", "saki ni", "terlebih dulu", "Kata Keterangan",
               ("先|さき に 手|て を 洗|あら います。", "Cuci tangan terlebih dulu.")),
    ],
    kanji=[
        KANJI("j34-1", "組", "ソ", "く(む)", "rangkai; kelompok", 11,
              [("組み立てます", "くみたてます", "merakit"), ("番組", "ばんぐみ", "acara")]),
        KANJI("j34-2", "質", "シツ", "—", "kualitas; isi", 15,
              [("質問", "しつもん", "pertanyaan"), ("品質", "ひんしつ", "kualitas")]),
        KANJI("j34-3", "細", "サイ", "ほそ(い)", "tipis; halus", 11,
              [("細い", "ほそい", "ramping"), ("細部", "さいぶ", "detail")]),
        KANJI("j34-4", "太", "タイ", "ふと(い)", "tebal; besar", 4,
              [("太い", "ふとい", "tebal"), ("太陽", "たいよう", "matahari")]),
        KANJI("j34-5", "線", "セン", "—", "garis", 15,
              [("線", "せん", "garis"), ("電線", "でんせん", "kabel listrik")]),
        KANJI("j34-6", "図", "ズ", "—", "gambar", 7,
              [("図", "ず", "diagram"), ("地図", "ちず", "peta")]),
    ],
    kaiwa=KAIWA(
        "日曜大工 — Kerja Kayu di Hari Minggu",
        "Wan dan Pak Sato merakit rak buku yang baru dibeli.",
        [
            ("ワン", "Wan", "この 本棚|ほんだな、 組|く み立|た てる の が 難|むずか しい です ね。",
             "Rak buku ini sulit dirakit, ya."),
            ("佐藤", "Satō", "説明書|せつめいしょ の とおり に やれば、 簡単|かんたん です よ。",
             "Kalau dikerjakan sesuai buku petunjuk, mudah, kok."),
            ("ワン", "Wan", "図|ず の 線|せん の とおり に 板|いた を 合|あ わせるん です か。",
             "Papannya disatukan sesuai garis di diagram?"),
            ("佐藤", "Satō", "ええ。 まず 矢印|やじるし の とおり に ネジ を 締|し めて、 それから 組|く み立|た てて ください。",
             "Betul. Pertama kencangkan baut sesuai tanda panah, lalu rakit."),
            ("ワン", "Wan", "あれ？ ネジ が 一本|いっぽん 残|のこ って しまいました…。",
             "Lho? Ada satu baut yang tersisa…"),
            ("佐藤", "Satō", "説明書|せつめいしょ を 見|み ない で やった から です よ。 もう 一度|いちど 確認|かくにん しましょう。",
             "Itu karena Anda merakit tanpa melihat buku petunjuk. Ayo kita periksa sekali lagi."),
        ],
    ),
    quiz_bunpo=[
        QB("qb34-1", "説明書|せつめいしょ の ＿＿ に 組|く み立|た てます。", ["とおり", "まま", "ため", "とき"], 0,
           "説明書|せつめいしょ の とおり に 組|く み立|た てます。", "のとおりに", "[Kata Benda] の とおり に",
           "〜とおりに berarti sesuai dengan; setelah kata benda memakai の."),
        QB("qb34-2", "ごはん を 食|た べた ＿＿、 歯|は を 磨|みが きます。", ["あとで", "まえに", "ながら", "とおり"], 0,
           "ごはん を 食|た べた あと で、 歯|は を 磨|みが きます。", "食べたあとで", "[Bentuk た] あと で",
           "〜たあとで berarti setelah melakukan; selalu memakai bentuk た."),
        QB("qb34-3", "歯|は を 磨|みが か ＿＿、 寝|ね ました。", ["ないで", "なくて", "なければ", "ないから"], 0,
           "歯|は を 磨|みが かない で、 寝|ね ました。", "磨かないで", "[Bentuk ない tanpa ない] ない で",
           "〜ないで berarti tanpa melakukan aksi pertama."),
        QB_ID("qb34-4", "“Kerjakanlah sesuai buku petunjuk.”",
              ["説明書|せつめいしょ の とおり に やって ください。",
               "説明書|せつめいしょ みたい に やって ください。",
               "説明書|せつめいしょ の ため に やって ください。",
               "説明書|せつめいしょ に よって やって ください。"], 0,
              "説明書|せつめいしょ の とおり に やって ください。", "のとおりに", "[Kata Benda] の とおり に",
              "Sesuai buku petunjuk = 説明書のとおりに."),
    ],
    quiz_susun=[
        QS("qs34-1", "Merakit sesuai buku petunjuk.",
           "説明書|せつめいしょ の とおり に 組|く み立|た てます", "見|み ないで 壊|こわ します"),
        QS("qs34-2", "Setelah makan, saya menggosok gigi.",
           "ごはん を 食|た べた あとで 歯|は を 磨|みが きます", "まえに 寝|ね ます"),
        QS("qs34-3", "Saya pergi ke kantor tanpa sarapan.",
           "朝|あさ ごはん を 食|た べないで 会社|かいしゃ へ 行|い きました", "食|た べて 家|うち"),
    ],
)

BAB35 = CHAPTER(
    35, "春に なれば、 桜が 咲きます。", "Kalau musim semi tiba, bunga sakura mekar.",
    bunpo=[
        BUNPO(
            "b35-1", "Bentuk ば — Pengandaian “Kalau/Jika”",
            "Kata kerja: 読|よ めば ／ Sifat-i: 安|やす ければ ／ Sifat-na・benda: 静|しず か なら(ば)",
            [
                "kata kerja: baris え ＋ ば （読む → 読めば）",
                "kata sifat-i: い → ければ （安い → 安ければ）",
                "sifat-na / kata benda: なら(ば) （静かなら）",
            ],
            "Bentuk ば menyatakan syarat: kalau syaratnya terpenuhi, maka akibatnya terjadi. "
            "Bentuk ini sering dipakai untuk kebenaran umum, hukum alam, dan nasihat.",
            [
                ("春|はる に なれば、 桜|さくら が 咲|さ きます。", "Kalau musim semi tiba, bunga sakura mekar."),
                ("安|やす ければ、 買|か います。", "Kalau murah, saya beli."),
                ("静|しず か なら、 よく 勉強|べんきょう できます。", "Kalau tenang, kita bisa belajar dengan baik."),
            ],
        ),
        BUNPO(
            "b35-2", "Kata Tanya ＋ 〜ば いいですか — Meminta Saran Cara",
            "[Kata Tanya] 〜ば いい です か",
            [
                "どう すれば いいですか = bagaimana sebaiknya",
                "どこ へ 行|い けば いいですか = ke mana sebaiknya",
                "jawaban: 〜ば いいです ／ 〜たら いいです",
            ],
            "Sama seperti 〜たらいいですか (Bab 26), pola ini menanyakan cara atau pilihan yang "
            "sebaiknya dilakukan, tetapi dengan bentuk ば.",
            [
                ("京都|きょうと へ は どう 行|い けば いい です か。", "Bagaimana sebaiknya saya pergi ke Kyoto?"),
                ("いくら 払|はら えば いい です か。", "Berapa yang sebaiknya saya bayar?"),
                ("だれ に 聞|き けば いい です か。", "Kepada siapa sebaiknya saya bertanya?"),
            ],
        ),
        BUNPO(
            "b35-3", "〜なら — Kalau Soal… (Topik & Rekomendasi)",
            "[Kata Benda] なら ／ [Kalimat bentuk biasa] なら",
            [
                "mengangkat topik yang disebut lawan bicara",
                "dipakai untuk memberi rekomendasi atau informasi terkait",
                "スキー なら、 北海道|ほっかいどう が いいです",
            ],
            "なら menanggapi topik yang diungkit lawan bicara, lalu memberi saran atau informasi "
            "yang relevan: “kalau (soal) ski, Hokkaido bagus”.",
            [
                ("スキー なら、 北海道|ほっかいどう が いい です よ。", "Kalau soal ski, Hokkaido bagus, lho."),
                ("駅|えき へ 行|い く なら、 バス が 便利|べんり です。", "Kalau mau ke stasiun, bus lebih praktis."),
                ("日本料理|にほんりょうり なら、 この 店|みせ が おいしい です。", "Kalau masakan Jepang, toko ini enak."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k35-1", "咲きます", "さきます", "sakimasu", "mekar", "Kata Kerja",
               ("桜|さくら が 咲|さ きました。", "Sakuranya sudah mekar.")),
        KOTOBA("k35-2", "変わります", "かわります", "kawarimasu", "berubah", "Kata Kerja",
               ("葉|は の 色|いろ が 変|か わります。", "Warna daun berubah.")),
        KOTOBA("k35-3", "付けます", "つけます", "tsukemasu", "membubuhkan tanda", "Kata Kerja",
               ("正|ただ しい 答|こた え に 丸|まる を 付|つ けます。", "Membubuhkan lingkaran pada jawaban benar.")),
        KOTOBA("k35-4", "拾います", "ひろいます", "hiroimasu", "memungut", "Kata Kerja",
               ("財布|さいふ を 拾|ひろ いました。", "Saya memungut dompet.")),
        KOTOBA("k35-5", "楽", "らく", "raku", "nyaman; ringan", "Kata Sifat-na",
               ("この 靴|くつ は 楽|らく です。", "Sepatu ini nyaman.")),
        KOTOBA("k35-6", "正しい", "ただしい", "tadashii", "benar; tepat", "Kata Sifat-i",
               ("答|こた え が 正|ただ しい です。", "Jawabannya benar.")),
        KOTOBA("k35-7", "珍しい", "めずらしい", "mezurashii", "langka", "Kata Sifat-i",
               ("珍|めずら しい 花|はな が 咲|さ いて います。", "Ada bunga langka yang sedang mekar.")),
        KOTOBA("k35-8", "向こう", "むこう", "mukō", "seberang sana", "Kata Benda",
               ("向|む こう に 島|しま が 見|み えます。", "Di seberang sana terlihat pulau.")),
        KOTOBA("k35-9", "島", "しま", "shima", "pulau", "Kata Benda",
               ("小|ちい さい 島|しま に 住|す んで います。", "Dia tinggal di pulau kecil.")),
        KOTOBA("k35-10", "港", "みなと", "minato", "pelabuhan", "Kata Benda",
               ("港|みなと に 船|ふね が 着|つ きました。", "Kapal tiba di pelabuhan.")),
        KOTOBA("k35-11", "近所", "きんじょ", "kinjo", "lingkungan sekitar", "Kata Benda",
               ("近所|きんじょ に 便利|べんり な 店|みせ が あります。", "Di lingkungan sekitar ada toko yang praktis.")),
        KOTOBA("k35-12", "屋上", "おくじょう", "okujō", "atap", "Kata Benda",
               ("屋上|おくじょう で 花火|はなび を 見|み ます。", "Melihat kembang api dari atap.")),
        KOTOBA("k35-13", "海外", "かいがい", "kaigai", "luar negeri", "Kata Benda",
               ("海外|かいがい へ 旅行|りょこう したい です。", "Saya ingin berwisata ke luar negeri.")),
        KOTOBA("k35-14", "山登り", "やまのぼり", "yamanobori", "mendaki gunung", "Kata Benda",
               ("週末|しゅうまつ に 山登|やまのぼ り を します。", "Akhir pekan saya mendaki gunung.")),
        KOTOBA("k35-15", "機会", "きかい", "kikai", "kesempatan", "Kata Benda",
               ("いい 機会|きかい です。", "Ini kesempatan bagus.")),
        KOTOBA("k35-16", "許可", "きょか", "kyoka", "izin", "Kata Benda",
               ("写真|しゃしん の 許可|きょか を もらいました。", "Saya mendapat izin memotret.")),
        KOTOBA("k35-17", "方法", "ほうほう", "hōhō", "cara; metode", "Kata Benda",
               ("いい 方法|ほうほう を 教|おし えて ください。", "Tolong ajari cara yang baik.")),
        KOTOBA("k35-18", "楽しみ", "たのしみ", "tanoshimi", "hal yang dinantikan", "Kata Benda",
               ("旅行|りょこう が 楽|たの しみ です。", "Saya menantikan perjalanannya.")),
    ],
    kanji=[
        KANJI("j35-1", "咲", "ショウ", "さ(く)", "mekar", 9,
              [("咲きます", "さきます", "mekar"), ("開花", "かいか", "mekarnya bunga")]),
        KANJI("j35-2", "変", "ヘン", "か(わる)", "ubah; aneh", 9,
              [("変わります", "かわります", "berubah"), ("大変", "たいへん", "berat; luar biasa")]),
        KANJI("j35-3", "拾", "シュウ", "ひろ(う)", "pungut", 9,
              [("拾います", "ひろいます", "memungut"), ("拾得物", "しゅうとくぶつ", "barang temuan")]),
        KANJI("j35-4", "島", "トウ", "しま", "pulau", 10,
              [("島", "しま", "pulau"), ("半島", "はんとう", "semenanjung")]),
        KANJI("j35-5", "港", "コウ", "みなと", "pelabuhan", 12,
              [("港", "みなと", "pelabuhan"), ("空港", "くうこう", "bandara")]),
        KANJI("j35-6", "楽", "ガク", "たの(しい)", "senang; nyaman", 13,
              [("楽しい", "たのしい", "menyenangkan"), ("音楽", "おんがく", "musik")]),
    ],
    kaiwa=KAIWA(
        "旅行の 相談 — Konsultasi Perjalanan",
        "Di biro perjalanan, seorang pelanggan bertanya tentang wisata ke Hokkaido.",
        [
            ("客", "Kaku", "北海道|ほっかいどう へ 行|い きたいん です が、 いつ が いい です か。",
             "Saya ingin ke Hokkaido, kapan waktu yang bagus?"),
            ("店員", "Tenin", "夏|なつ なら 花|はな が きれい です し、 冬|ふゆ なら スキー が できます よ。",
             "Kalau musim panas bunganya indah, kalau musim dingin bisa main ski."),
            ("客", "Kaku", "安|やす く 行|い く なら、 どう すれば いい です か。",
             "Kalau mau pergi dengan hemat, bagaimana sebaiknya?"),
            ("店員", "Tenin", "夜行|やこう バス を 使|つか えば、 ホテル 代|だい が いりません よ。",
             "Kalau memakai bus malam, Anda tidak perlu biaya hotel."),
            ("客", "Kaku", "いい です ね。 詳|くわ しい パンフレット が あれば、 ください。",
             "Bagus juga. Kalau ada brosur yang lengkap, tolong berikan."),
            ("店員", "Tenin", "はい、 こちら です。 楽|たの しい 旅行|りょこう に なります ように。",
             "Baik, ini dia. Semoga perjalanannya menyenangkan."),
        ],
    ),
    quiz_bunpo=[
        QB("qb35-1", "春|はる に なれ＿＿、 桜|さくら が 咲|さ きます。", ["ば", "が", "のに", "まま"], 0,
           "春|はる に なれば、 桜|さくら が 咲|さ きます。", "なれば", "Kata kerja: baris え ＋ ば",
           "Bentuk ば kata kerja: ubah vokal akhir ke baris え + ば: なる → なれば."),
        QB("qb35-2", "安|やす けれ＿＿、 買|か います。", ["ば", "ら", "て", "く"], 0,
           "安|やす ければ、 買|か います。", "安ければ", "Kata sifat-i: い → ければ",
           "Kata sifat-i membentuk pengandaian dengan い → ければ."),
        QB("qb35-3", "駅|えき へ 行|い く ＿＿、 バス が 便利|べんり です。", ["なら", "ので", "ても", "し"], 0,
           "駅|えき へ 行|い く なら、 バス が 便利|べんり です。", "なら", "〜 なら (rekomendasi)",
           "なら menanggapi topik lalu memberi rekomendasi: kalau ke stasiun, bus lebih praktis."),
        QB_ID("qb35-4", "“Bagaimana sebaiknya saya pergi ke sana?”",
              ["どう 行|い けば いい です か。",
               "どう 行|い く ほう が です か。",
               "どう 行|い け ます か。",
               "どう 行|い き ましょう か。"], 0,
              "どう 行|い けば いい です か。", "行けばいいですか", "[Kata Tanya] 〜ば いい です か",
              "Menanyakan cara terbaik memakai kata tanya + bentuk ば + いいですか."),
    ],
    quiz_susun=[
        QS("qs35-1", "Kalau musim semi tiba, bunga sakura mekar.",
           "春|はる に なれば 桜|さくら が 咲|さ きます", "冬|ふゆ 散|ち ります"),
        QS("qs35-2", "Kalau murah, saya beli.",
           "安|やす ければ 買|か います", "高|たか い 売|う ります"),
        QS("qs35-3", "Kalau ke stasiun, bus lebih praktis.",
           "駅|えき へ 行|い く なら バス が 便利|べんり です", "歩|ある いて 遠|とお い"),
    ],
)

CHAPTERS = [BAB31, BAB32, BAB33, BAB34, BAB35]
