"""Materi Minna no Nihongo 2 — Bab 46 s/d 50 (penutup buku 2)."""

from seed_data.dsl import BUNPO, CHAPTER, KAIWA, KANJI, KOTOBA, QB, QB_ID, QS

BAB46 = CHAPTER(
    46, "ちょうど 今、 出かける ところです。", "Saya pas baru saja akan pergi.",
    bunpo=[
        BUNPO(
            "b46-1", "〜ところです — Tepat Saat…",
            "[Bentuk kamus] ところ です ／ [Bentuk て] いる ところ です ／ [Bentuk た] ところ です",
            [
                "bentuk kamus: 今|いま から 食べる ところです (baru saja akan)",
                "bentuk ている: 食べて いる ところです (sedang tepat)",
                "bentuk た: 食べた ところです (baru saja selesai)",
            ],
            "ところです menyatakan titik waktu yang tepat dari sebuah aksi: baru mau, sedang, "
            "atau baru selesai. Sangat sering dipakai dalam percakapan sehari-hari untuk "
            "menjawab “lagi apa?”.",
            [
                ("ちょうど 今|いま、 出|で かける ところ です。", "Saya pas baru saja akan pergi."),
                ("今|いま、 昼|ひる ごはん を 食|た べて いる ところ です。", "Saya pas sedang makan siang."),
                ("さっき 家|いえ に 着|つ いた ところ です。", "Saya baru saja tiba di rumah."),
            ],
        ),
        BUNPO(
            "b46-2", "〜た ばかりです — Baru Saja (Kesan Waktu)",
            "[Kata Kerja bentuk た] ばかり です",
            [
                "baru saja melakukan (kesan waktu masih dekat)",
                "日本|にほん へ 来|き た ばかり です",
                "〜たところです = benar-benar baru detik ini",
            ],
            "ばかりです juga berarti baru saja, tetapi mengukur dari PERASAAN pembicara: "
            "日本へ 来たばかりです bisa dipakai bahkan setelah beberapa bulan. Sedangkan "
            "〜たところです benar-benar sesaat setelah aksi selesai.",
            [
                ("日本|にほん へ 来|き た ばかり です。", "Saya baru datang ke Jepang."),
                ("さっき 食|た べた ばかり な のに、 もう おなか が すきました。", "Padahal baru saja makan, sudah lapar lagi."),
                ("この 単語|たんご は 習|なら った ばかり です。", "Kata ini baru saja saya pelajari."),
            ],
        ),
        BUNPO(
            "b46-3", "〜はずです — Seharusnya (Harapan Logis)",
            "[Bentuk Biasa] はず です",
            [
                "kesimpulan logis berdasarkan informasi yang ada",
                "彼|かれ は もう 着|つ く はずです (seharusnya sudah tiba)",
                "negatif: 〜はず が ありません (tak mungkin)",
            ],
            "はずです menyatakan sesuatu yang SEHARUSNYA terjadi menurut hitungan logis — jadwal, "
            "informasi, atau kebiasaan. Bukan sekadar tebakan seperti でしょう.",
            [
                ("8時|はちじ の 電車|でんしゃ です から、 もう 着|つ く はず です。",
                 "Karena naik kereta jam 8, seharusnya sudah tiba."),
                ("田中|たなか さん は この こと を 知|し らない はず です。", "Tanaka seharusnya tidak tahu hal ini."),
                ("荷物|にもつ は あした 届|とど く はず です。", "Paketnya seharusnya sampai besok."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k46-1", "焼きます", "やきます", "yakimasu", "memanggang", "Kata Kerja",
               ("パン を 焼|や きます。", "Memanggang roti.")),
        KOTOBA("k46-2", "渡します", "わたします", "watashimasu", "menyerahkan", "Kata Kerja",
               ("先生|せんせい に レポート を 渡|わた します。", "Menyerahkan laporan kepada guru.")),
        KOTOBA("k46-3", "帰って来ます", "かえってきます", "kaette kimasu", "kembali", "Kata Kerja",
               ("今|いま 帰|かえ って 来|き た ところ です。", "Saya baru saja kembali.")),
        KOTOBA("k46-4", "出ます", "でます", "demasu", "berangkat", "Kata Kerja",
               ("バス が 出|で る ところ です。", "Busnya baru saja akan berangkat.")),
        KOTOBA("k46-5", "留守", "るす", "rusu", "sedang tidak di tempat", "Kata Benda",
               ("今|いま 留守|るす です。", "Sekarang beliau sedang tidak ada.")),
        KOTOBA("k46-6", "宅配便", "たくはいびん", "takuhaibin", "jasa antar paket", "Kata Benda",
               ("宅配便|たくはいびん で 送|おく ります。", "Mengirim lewat jasa antar paket.")),
        KOTOBA("k46-7", "原因", "げんいん", "gen'in", "penyebab", "Kata Benda",
               ("事故|じこ の 原因|げんいん を 調|しら べます。", "Menyelidiki penyebab kecelakaan.")),
        KOTOBA("k46-8", "注射", "ちゅうしゃ", "chūsha", "suntik", "Kata Benda",
               ("注射|ちゅうしゃ が 痛|いた い です。", "Suntiknya sakit.")),
        KOTOBA("k46-9", "食欲", "しょくよく", "shokuyoku", "nafsu makan", "Kata Benda",
               ("食欲|しょくよく が ありません。", "Tidak ada nafsu makan.")),
        KOTOBA("k46-10", "パンフレット", "パンフレット", "panfuretto", "brosur", "Kata Benda",
               ("パンフレット を 読|よ んで います。", "Sedang membaca brosur.")),
        KOTOBA("k46-11", "ちょうど", "ちょうど", "chōdo", "pas; tepat", "Kata Keterangan",
               ("ちょうど 今|いま 始|はじ まりました。", "Pas baru saja dimulai.")),
        KOTOBA("k46-12", "たった今", "たったいま", "tatta ima", "baru saja", "Kata Keterangan",
               ("たった今|いま 着|つ きました。", "Baru saja tiba.")),
        KOTOBA("k46-13", "具合", "ぐあい", "guai", "kondisi", "Kata Benda",
               ("機械|きかい の 具合|ぐあい が 悪|わる い です。", "Kondisi mesinnya jelek.")),
        KOTOBA("k46-14", "向かいます", "むかいます", "mukaimasu", "menuju", "Kata Kerja",
               ("駅|えき へ 向|む かって います。", "Sedang menuju stasiun.")),
        KOTOBA("k46-15", "お待たせしました", "おまたせしました", "omatase shimashita", "maaf membuat menunggu", "Ungkapan",
               ("お待|ま たせ しました。 どうぞ。", "Maaf membuat Anda menunggu. Silakan.")),
        KOTOBA("k46-16", "知識", "ちしき", "chishiki", "pengetahuan", "Kata Benda",
               ("専門|せんもん の 知識|ちしき が 必要|ひつよう です。", "Perlu pengetahuan khusus.")),
        KOTOBA("k46-17", "入力します", "にゅうりょくします", "nyūryoku shimasu", "memasukkan (data)", "Kata Kerja",
               ("データ を 入力|にゅうりょく します。", "Memasukkan data.")),
        KOTOBA("k46-18", "秒", "びょう", "byō", "detik", "Kata Benda",
               ("あと 10秒|びょう です。", "10 detik lagi.")),
    ],
    kanji=[
        KANJI("j46-1", "渡", "ト", "わた(す)", "serahkan; seberang", 12,
              [("渡します", "わたします", "menyerahkan"), ("渡航", "とこう", "perjalanan ke luar negeri")]),
        KANJI("j46-2", "射", "シャ", "—", "tembak", 10,
              [("注射", "ちゅうしゃ", "suntikan"), ("発射", "はっしゃ", "peluncuran")]),
        KANJI("j46-3", "向", "コウ", "む(かう)", "arah", 6,
              [("向かいます", "むかいます", "menuju"), ("方向", "ほうこう", "arah")]),
        KANJI("j46-4", "識", "シキ", "—", "tahu; kenal", 19,
              [("知識", "ちしき", "pengetahuan"), ("意識", "いしき", "kesadaran")]),
        KANJI("j46-5", "具", "グ", "—", "alat; perlengkapan", 8,
              [("具合", "ぐあい", "kondisi"), ("道具", "どうぐ", "perkakas")]),
        KANJI("j46-6", "秒", "ビョウ", "—", "detik", 9,
              [("秒", "びょう", "detik"), ("秒針", "びょうしん", "jarum detik")]),
    ],
    kaiwa=KAIWA(
        "電話口で — Di Ujung Telepon",
        "Miller menelepon rumah Pak Yamada; yang mengangkat istrinya.",
        [
            ("山田夫人", "Yamada-fujin", "もしもし、 山田|やまだ です。", "Halo, ini keluarga Yamada."),
            ("ミラー", "Mirā", "ミラー です が、 ご主人|しゅじん は いらっしゃいます か。", "Ini Miller, apakah suami Anda ada?"),
            ("山田夫人", "Yamada-fujin", "すみません、 たった今|いま 出|で かけた ところ です。",
             "Maaf, beliau baru saja pergi."),
            ("ミラー", "Mirā", "そう です か。 何時|なんじ ごろ 帰|かえ って 来|く る はず です か。",
             "Oh begitu. Jam berapa beliau seharusnya kembali?"),
            ("山田夫人", "Yamada-fujin", "5時|ごじ には 帰|かえ る はず です。 伝言|でんごん が あれば、 どうぞ。",
             "Seharusnya pulang jam 5. Kalau ada pesan, silakan."),
            ("ミラー", "Mirā", "じゃ、 また 電話|でんわ します。 ありがとう ございました。",
             "Kalau begitu, nanti saya telepon lagi. Terima kasih."),
        ],
    ),
    quiz_bunpo=[
        QB("qb46-1", "ちょうど 今|いま、 昼|ひる ごはん を 食|た べて ＿＿ ところ です。", ["いる", "いました", "おく", "ある"], 0,
           "ちょうど 今|いま、 昼|ひる ごはん を 食|た べて いる ところ です。", "食べているところ",
           "[Bentuk て] いる ところ です", "Sedang tepat melakukan: 〜ているところです."),
        QB("qb46-2", "さっき 家|いえ に 着|つ いた ＿＿ です。", ["ところ", "まえ", "なか", "うち"], 0,
           "さっき 家|いえ に 着|つ いた ところ です。", "着いたところ", "[Bentuk た] ところ です",
           "Baru saja selesai: bentuk た + ところです."),
        QB("qb46-3", "8時|はちじ の 電車|でんしゃ だ から、 もう 着|つ く ＿＿ です。", ["はず", "そう", "つもり", "わけ"], 0,
           "もう 着|つ く はず です。", "着くはず", "[Bentuk Biasa] はず です",
           "はずです = seharusnya, kesimpulan logis dari informasi yang ada."),
        QB_ID("qb46-4", "“Saya baru datang ke Jepang (kesannya masih baru).”",
              ["日本|にほん へ 来|き た ばかり です。",
               "日本|にほん へ 来|き て いる ところ です。",
               "日本|にほん へ 来|く る ところ です。",
               "日本|にほん へ 来|き たい ところ です。"], 0,
              "日本|にほん へ 来|き た ばかり です。", "来たばかり", "[Bentuk た] ばかり です",
              "ばかりです berarti baru saja menurut perasaan pembicara."),
    ],
    quiz_susun=[
        QS("qs46-1", "Saya pas baru saja akan pergi.",
           "ちょうど 今|いま 出|で かける ところ です", "帰|かえ る たった今|いま"),
        QS("qs46-2", "Saya baru saja tiba di rumah.",
           "さっき 家|いえ に 着|つ いた ところ です", "出|で る 駅|えき"),
        QS("qs46-3", "Seharusnya beliau pulang jam 5.",
           "5時|ごじ に 帰|かえ る はず です", "来|こ ない そう"),
    ],
)

BAB47 = CHAPTER(
    47, "天気予報に よると、 あしたは 雨だ そうです。", "Menurut ramalan cuaca, besok katanya hujan.",
    bunpo=[
        BUNPO(
            "b47-1", "〜そうです (伝聞) — Katanya",
            "[Bentuk Biasa] そう です",
            [
                "menyampaikan kabar dari orang lain / berita",
                "bentuk penuh: 降|ふ るそうです (BUKAN 降りそうです)",
                "jangan tertukar dengan そうです 様子 (Bab 43)",
            ],
            "そうです untuk kabar memakai BENTUK BIASA penuh: あした 雨が 降るそうです = katanya "
            "besok hujan. Bandingkan dengan Bab 43: 降りそうです (kelihatannya akan turun).",
            [
                ("あした は 雨|あめ だ そう です。", "Katanya besok hujan."),
                ("山田|やまだ さん は 来月|らいげつ 結婚|けっこん する そう です。", "Katanya Yamada menikah bulan depan."),
                ("この 店|みせ の ラーメン は おいしい そう です。", "Katanya ramen toko ini enak."),
            ],
        ),
        BUNPO(
            "b47-2", "〜ようです — Sepertinya (Dugaan dari Bukti)",
            "[Bentuk Biasa] よう です",
            [
                "dugaan berdasarkan bukti yang dilihat/dirasakan",
                "誰|だれ か いる ようです (sepertinya ada orang — dari suaranya)",
                "bentuk lain: みたいです (lebih santai)",
            ],
            "ようです menyatakan kesimpulan yang ditarik dari petunjuk pancaindra: dari suara, "
            "bau, keadaan. みたいです adalah versi santainya.",
            [
                ("誰|だれ か いる よう です。 声|こえ が します。", "Sepertinya ada orang. Terdengar suara."),
                ("雨|あめ が 降|ふ った よう です。 道|みち が ぬれて います。",
                 "Sepertinya tadi hujan. Jalannya basah."),
                ("この 部屋|へや は 誰|だれ も 使|つか って いない みたい です。", "Kamar ini sepertinya tidak dipakai siapa-siapa."),
            ],
        ),
        BUNPO(
            "b47-3", "〜に よると — Menurut (Sumber)",
            "[Sumber] に よると、 [Bentuk Biasa] そう です ／ よう です",
            [
                "menyebutkan sumber informasi",
                "天気予報|てんきよほう によると = menurut ramalan cuaca",
                "sering dipasangkan dengan そうです",
            ],
            "によると dipakai untuk menyebutkan sumber kabar: berita, ramalan, atau seseorang. "
            "Biasanya disusul そうです.",
            [
                ("天気予報|てんきよほう に よると、 あした は 雪|ゆき だ そう です。",
                 "Menurut ramalan cuaca, besok katanya turun salju."),
                ("ニュース に よると、 事故|じこ が あった そう です。", "Menurut berita, katanya ada kecelakaan."),
                ("先生|せんせい に よると、 試験|しけん は 来週|らいしゅう だ そう です。",
                 "Menurut guru, ujiannya katanya minggu depan."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k47-1", "集まります", "あつまります", "atsumarimasu", "berkumpul", "Kata Kerja",
               ("広場|ひろば に 人|ひと が 集|あつ まって います。", "Orang-orang berkumpul di alun-alun.")),
        KOTOBA("k47-2", "別れます", "わかれます", "wakaremasu", "berpisah", "Kata Kerja",
               ("駅|えき で 友達|ともだち と 別|わか れました。", "Berpisah dengan teman di stasiun.")),
        KOTOBA("k47-3", "長生きします", "ながいきします", "nagaiki shimasu", "panjang umur", "Kata Kerja",
               ("祖父母|そふぼ は 長生|ながい き して います。", "Kakek-nenek saya panjang umur.")),
        KOTOBA("k47-4", "さします", "さします", "sashimasu", "memasang (payung)", "Kata Kerja",
               ("傘|かさ を さして 歩|ある きます。", "Berjalan dengan payung terpasang.")),
        KOTOBA("k47-5", "ひどい", "ひどい", "hidoi", "parah; kejam", "Kata Sifat-i",
               ("ひどい 雨|あめ です ね。", "Hujannya parah, ya.")),
        KOTOBA("k47-6", "怖い", "こわい", "kowai", "menakutkan", "Kata Sifat-i",
               ("雷|かみなり は 怖|こわ い です。", "Petir itu menakutkan.")),
        KOTOBA("k47-7", "天気予報", "てんきよほう", "tenki yohō", "ramalan cuaca", "Kata Benda",
               ("天気予報|てんきよほう を 見|み ました か。", "Sudah lihat ramalan cuaca?")),
        KOTOBA("k47-8", "発表", "はっぴょう", "happyō", "pengumuman; presentasi", "Kata Benda",
               ("結果|けっか の 発表|はっぴょう は 来週|らいしゅう です。", "Pengumuman hasilnya minggu depan.")),
        KOTOBA("k47-9", "実験", "じっけん", "jikken", "percobaan; eksperimen", "Kata Benda",
               ("科学|かがく の 実験|じっけん を します。", "Melakukan eksperimen sains.")),
        KOTOBA("k47-10", "人口", "じんこう", "jinkō", "populasi", "Kata Benda",
               ("人口|じんこう が 減|へ って いる そう です。", "Katanya populasinya sedang berkurang.")),
        KOTOBA("k47-11", "科学", "かがく", "kagaku", "ilmu pengetahuan", "Kata Benda",
               ("科学|かがく が 進|すす んで います。", "Ilmu pengetahuan terus maju.")),
        KOTOBA("k47-12", "医学", "いがく", "igaku", "ilmu kedokteran", "Kata Benda",
               ("医学|いがく を 勉強|べんきょう して います。", "Saya belajar ilmu kedokteran.")),
        KOTOBA("k47-13", "文学", "ぶんがく", "bungaku", "sastra", "Kata Benda",
               ("日本|にほん 文学|ぶんがく に 興味|きょうみ が あります。", "Saya berminat pada sastra Jepang.")),
        KOTOBA("k47-14", "救急車", "きゅうきゅうしゃ", "kyūkyūsha", "ambulans", "Kata Benda",
               ("救急車|きゅうきゅうしゃ の 音|おと が します。", "Terdengar suara ambulans.")),
        KOTOBA("k47-15", "賛成", "さんせい", "sansei", "setuju", "Kata Benda",
               ("わたし は 賛成|さんせい です。", "Saya setuju.")),
        KOTOBA("k47-16", "反対", "はんたい", "hantai", "menentang; berlawanan", "Kata Benda",
               ("彼|かれ は 反対|はんたい の よう です。", "Sepertinya dia menentang.")),
        KOTOBA("k47-17", "によると", "によると", "ni yoru to", "menurut", "Kata Keterangan",
               ("新聞|しんぶん に よると、 事故|じこ だそう です。", "Menurut koran, katanya kecelakaan.")),
        KOTOBA("k47-18", "婚約します", "こんやくします", "kon'yaku shimasu", "bertunangan", "Kata Kerja",
               ("二人|ふたり は 婚約|こんやく した そう です。", "Katanya mereka berdua sudah bertunangan.")),
    ],
    kanji=[
        KANJI("j47-1", "集", "シュウ", "あつ(まる)", "kumpul", 12,
              [("集まります", "あつまります", "berkumpul"), ("集中", "しゅうちゅう", "konsentrasi")]),
        KANJI("j47-2", "別", "ベツ", "わか(れる)", "pisah; lain", 7,
              [("別れます", "わかれます", "berpisah"), ("別々", "べつべつ", "terpisah-pisah")]),
        KANJI("j47-3", "科", "カ", "—", "bidang ilmu", 9,
              [("科学", "かがく", "ilmu pengetahuan"), ("教科書", "きょうかしょ", "buku pelajaran")]),
        KANJI("j47-4", "医", "イ", "—", "kedokteran", 7,
              [("医学", "いがく", "ilmu kedokteran"), ("医者", "いしゃ", "dokter")]),
        KANJI("j47-5", "対", "タイ", "—", "lawan; hadap", 7,
              [("反対", "はんたい", "menentang"), ("対象", "たいしょう", "sasaran")]),
        KANJI("j47-6", "婚", "コン", "—", "nikah", 11,
              [("婚約", "こんやく", "pertunangan"), ("結婚", "けっこん", "pernikahan")]),
    ],
    kaiwa=KAIWA(
        "うわさ話 — Gosip di Kantor",
        "Dua rekan kantor membicarakan kabar terbaru tentang teman-teman mereka.",
        [
            ("佐藤", "Satō", "聞|き きました か。 田中|たなか さん、 婚約|こんやく した そう です よ。",
             "Sudah dengar? Katanya Tanaka sudah bertunangan, lho."),
            ("ワン", "Wan", "えっ、 本当|ほんとう です か。 誰|だれ と です か。", "Hah, benarkah? Dengan siapa?"),
            ("佐藤", "Satō", "大学|だいがく の 時|とき の 友達|ともだち だそう です。 来月|らいげつ 発表|はっぴょう する そう です。",
             "Katanya teman kuliah dulu. Katanya akan diumumkan bulan depan."),
            ("ワン", "Wan", "いい です ね。 あ、 雨|あめ が 降|ふ って きた よう です。",
             "Bagus sekali. Ah, sepertinya mulai turun hujan."),
            ("佐藤", "Satō", "天気予報|てんきよほう に よると、 夕方|ゆうがた から ひどく なる そう です よ。",
             "Menurut ramalan cuaca, katanya sore ini akan semakin deras, lho."),
            ("ワン", "Wan", "傘|かさ を 持|も って いないん です。 早|はや く 帰|かえ りましょう。",
             "Saya tidak bawa payung. Ayo cepat pulang."),
        ],
    ),
    quiz_bunpo=[
        QB("qb47-1", "あした は 雨|あめ が 降|ふ る ＿＿ です。", ["そう", "よう", "はず", "ところ"], 0,
           "あした は 雨|あめ が 降|ふ る そう です。", "降るそう", "[Bentuk Biasa] そう です (kabar)",
           "Kabar dari orang lain memakai bentuk biasa penuh + そうです: 降るそうです."),
        QB("qb47-2", "道|みち が ぬれて います。 雨|あめ が 降|ふ った ＿＿ です。", ["よう", "そうな", "はずの", "ばかり"], 0,
           "雨|あめ が 降|ふ った よう です。", "降ったよう", "[Bentuk Biasa] よう です",
           "ようです = dugaan dari bukti yang terlihat (jalan basah → tadi hujan)."),
        QB("qb47-3", "天気予報|てんきよほう ＿＿、 あした は 雪|ゆき だ そう です。", ["によると", "について", "にとって", "にかけて"], 0,
           "天気予報|てんきよほう によると、 あした は 雪|ゆき だ そう です。", "によると", "[Sumber] に よると",
           "Sumber kabar ditandai によると."),
        QB_ID("qb47-4", "“Katanya ramen toko ini enak.” (kabar dari orang lain)",
              ["この 店|みせ の ラーメン は おいしい そう です。",
               "この 店|みせ の ラーメン は おいしそう です。",
               "この 店|みせ の ラーメン は おいしい はず です か。",
               "この 店|みせ の ラーメン は おいしい ところ です。"], 0,
              "この 店|みせ の ラーメン は おいしい そう です。", "おいしいそう", "[Bentuk Biasa] そう です (kabar)",
              "おいしいそうです = katanya enak (kabar); おいしそうです = kelihatan enak (kesan)."),
    ],
    quiz_susun=[
        QS("qs47-1", "Menurut ramalan cuaca, besok katanya hujan.",
           "天気予報|てんきよほう によると あした は 雨|あめ だそう です", "雪|ゆき 晴|は れ"),
        QS("qs47-2", "Katanya Yamada menikah bulan depan.",
           "山田|やまだ さん は 来月|らいげつ 結婚|けっこん する そう です", "婚約|こんやく 去年|きょねん"),
        QS("qs47-3", "Sepertinya tadi hujan. Jalannya basah.",
           "雨|あめ が 降|ふ った よう です 道|みち が ぬれて います", "雪|ゆき 乾|かわ いて"),
    ],
)

BAB48 = CHAPTER(
    48, "子どもに 薬を 飲ませました。", "Saya menyuruh anak minum obat.",
    bunpo=[
        BUNPO(
            "b48-1", "Bentuk Kausatif (使役) — Menyuruh / Membiarkan",
            "Gol I: あ段 ＋ せます ／ Gol II: させます ／ Gol III: させます・来|こ させます",
            [
                "Golongan I: 書|か きます → 書かせます",
                "Golongan II: 食|た べます → 食べさせます",
                "Golongan III: します → させます ； 来|き ます → 来|こ させます",
                "makna: menyuruh ATAU membiarkan — lihat konteks",
            ],
            "Bentuk kausatif dipakai saat seseorang membuat orang lain melakukan sesuatu "
            "(menyuruh) atau mengizinkannya (membiarkan). Contoh: 先生は 生徒に 作文を 書かせます "
            "(guru menyuruh murid menulis karangan).",
            [
                ("母|はは は 子|こ ども に 野菜|やさい を 食|た べさせました。", "Ibu menyuruh anaknya makan sayur."),
                ("子|こ ども に 薬|くすり を 飲|の ませました。", "Saya menyuruh anak minum obat."),
                ("子|こ ども を 一人|ひとり で 遊|あそ ばせます。", "Membiarkan anak bermain sendiri."),
            ],
        ),
        BUNPO(
            "b48-2", "Partikel dalam Kausatif — を vs に",
            "Intransitif: [Orang] を V(さ)せます ／ Transitif: [Orang] に [Benda] を V(さ)せます",
            [
                "kata kerja intransitif: 子|こ ども を 行|い かせます",
                "kata kerja transitif: 子|こ ども に 本|ほん を 読|よ ませます",
                "yang disuruh: を (intransitif), に (transitif)",
            ],
            "Partikel untuk pihak yang disuruh berbeda: を untuk kata kerja intransitif "
            "(行く, 休む), に untuk kata kerja transitif yang sudah punya を (読む, 作る).",
            [
                ("子|こ ども を 塾|じゅく へ 行|い かせます。", "Menyuruh anak pergi ke bimbel."),
                ("生徒|せいと に 漢字|かんじ を 書|か かせます。", "Menyuruh murid menulis kanji."),
                ("部下|ぶか に 書類|しょるい を 作|つく らせます。", "Menyuruh bawahan membuat dokumen."),
            ],
        ),
        BUNPO(
            "b48-3", "使役 ＋ ていただけませんか — Meminta Izin Sopan",
            "[Bentuk kausatif て] いただけません か",
            [
                "休|やす ませて いただけませんか = bolehkah saya diizinkan istirahat",
                "tingkat kesopanan tinggi — untuk atasan/resmi",
                "lebih halus daripada 〜ても いいですか",
            ],
            "Kausatif digabung ていただけませんか menjadi cara paling sopan untuk meminta izin "
            "melakukan sesuatu: secara harfiah “tidak bisakah saya menerima (izin) untuk "
            "dibiarkan melakukan…”.",
            [
                ("あした 休|やす ませて いただけません か。", "Bolehkah saya izin tidak masuk besok?"),
                ("この 資料|しりょう を 使|つか わせて いただけません か。", "Bolehkah saya diizinkan memakai bahan ini?"),
                ("意見|いけん を 言|い わせて いただけません か。", "Bolehkah saya menyampaikan pendapat?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k48-1", "下ろします", "おろします", "oroshimasu", "menurunkan", "Kata Kerja",
               ("荷物|にもつ を 下|お ろします。", "Menurunkan barang.")),
        KOTOBA("k48-2", "届けます", "とどけます", "todokemasu", "mengantarkan; melaporkan", "Kata Kerja",
               ("書類|しょるい を 届|とど けます。", "Mengantarkan dokumen.")),
        KOTOBA("k48-3", "世話をします", "せわをします", "sewa o shimasu", "mengurus", "Ungkapan",
               ("子|こ ども の 世話|せわ を します。", "Mengurus anak.")),
        KOTOBA("k48-4", "嫌", "いや", "iya", "enggan; tidak suka", "Kata Sifat-na",
               ("子|こ ども は 勉強|べんきょう を 嫌|いや がります。", "Anaknya enggan belajar.")),
        KOTOBA("k48-5", "厳しい", "きびしい", "kibishii", "tegas; keras", "Kata Sifat-i",
               ("厳|きび しい 先生|せんせい です。", "Guru yang tegas.")),
        KOTOBA("k48-6", "塾", "じゅく", "juku", "bimbingan belajar", "Kata Benda",
               ("塾|じゅく に 通|かよ って います。", "Berangkat ke bimbel.")),
        KOTOBA("k48-7", "スケジュール", "スケジュール", "sukejūru", "jadwal", "Kata Benda",
               ("スケジュール を 確認|かくにん します。", "Mengecek jadwal.")),
        KOTOBA("k48-8", "生徒", "せいと", "seito", "murid", "Kata Benda",
               ("生徒|せいと に 作文|さくぶん を 書|か かせます。", "Menyuruh murid menulis karangan.")),
        KOTOBA("k48-9", "者", "もの", "mono", "orang (bawahan sendiri)", "Kata Benda",
               ("私|わたくし の 者|もの が 伺|うかが います。", "Orang saya yang akan datang.")),
        KOTOBA("k48-10", "入管", "にゅうかん", "nyūkan", "kantor imigrasi", "Kata Benda",
               ("入管|にゅうかん で 手続|てつづ き を します。", "Mengurus di kantor imigrasi.")),
        KOTOBA("k48-11", "再入国ビザ", "さいにゅうこくビザ", "sainyūkoku biza", "visa masuk kembali", "Kata Benda",
               ("再入国|さいにゅうこく ビザ が 必要|ひつよう です。", "Perlu visa masuk kembali.")),
        KOTOBA("k48-12", "久しぶり", "ひさしぶり", "hisashiburi", "setelah lama tak jumpa", "Kata Benda",
               ("久|ひさ しぶり です ね。", "Lama tak jumpa, ya.")),
        KOTOBA("k48-13", "営業", "えいぎょう", "eigyō", "penjualan; bisnis", "Kata Benda",
               ("営業|えいぎょう の 仕事|しごと を して います。", "Bekerja di bagian penjualan.")),
        KOTOBA("k48-14", "それまでに", "それまでに", "sore made ni", "sebelum waktu itu", "Kata Keterangan",
               ("それまで に 終|お わらせます。", "Akan saya selesaikan sebelum itu.")),
        KOTOBA("k48-15", "かまいません", "かまいません", "kamaimasen", "tidak apa-apa", "Ungkapan",
               ("あした で かまいません。", "Besok pun tidak apa-apa.")),
        KOTOBA("k48-16", "競走します", "きょうそうします", "kyōsō shimasu", "berlomba lari", "Kata Kerja",
               ("馬|うま が 競走|きょうそう します。", "Kudanya berlomba.")),
        KOTOBA("k48-17", "姿", "すがた", "sugata", "sosok; penampilan", "Kata Benda",
               ("美|うつく しい 姿|すがた です。", "Sosok yang indah.")),
        KOTOBA("k48-18", "心", "こころ", "kokoro", "hati; batin", "Kata Benda",
               ("心|こころ に 残|のこ ります。", "Membekas di hati.")),
    ],
    kanji=[
        KANJI("j48-1", "厳", "ゲン", "きび(しい)", "tegas", 17,
              [("厳しい", "きびしい", "tegas"), ("厳重", "げんじゅう", "ketat (penjagaan)")]),
        KANJI("j48-2", "塾", "ジュク", "—", "bimbel", 14,
              [("塾", "じゅく", "bimbingan belajar"), ("学習塾", "がくしゅうじゅく", "bimbel")]),
        KANJI("j48-3", "競", "キョウ", "きそ(う)", "lomba", 20,
              [("競走", "きょうそう", "lomba lari"), ("競争", "きょうそう", "persaingan")]),
        KANJI("j48-4", "姿", "シ", "すがた", "sosok", 9,
              [("姿", "すがた", "sosok"), ("姿勢", "しせい", "postur")]),
        KANJI("j48-5", "心", "シン", "こころ", "hati", 4,
              [("心", "こころ", "hati"), ("心配", "しんぱい", "khawatir")]),
        KANJI("j48-6", "営", "エイ", "—", "usaha", 12,
              [("営業", "えいぎょう", "penjualan"), ("経営", "けいえい", "manajemen")]),
    ],
    kaiwa=KAIWA(
        "厳しい お母さん — Ibu yang Tegas",
        "Dua ibu berbincang tentang cara mendidik anak masing-masing.",
        [
            ("田中", "Tanaka", "お宅|たく の お子|こ さん、 塾|じゅく に 通|かよ って いる そう です ね。",
             "Anak Anda kabarnya berangkat bimbel, ya."),
            ("鈴木", "Suzuki", "ええ。 うち は 子|こ ども を 塾|じゅく へ 行|い かせて います。",
             "Iya. Kami menyuruh anak pergi ke bimbel."),
            ("田中", "Tanaka", "お子|こ さん は 嫌|いや がりません か。", "Anaknya tidak keberatan?"),
            ("鈴木", "Suzuki", "最初|さいしょ は 嫌|いや がりました が、 毎日|まいにち 一時間|いちじかん 勉強|べんきょう させて います。",
             "Awalnya enggan, tapi kami menyuruhnya belajar satu jam setiap hari."),
            ("田中", "Tanaka", "少|すこ し 厳|きび しすぎません か。 遊|あそ ぶ 時間|じかん も 大切|たいせつ です よ。",
             "Bukankah itu agak terlalu keras? Waktu bermain juga penting, lho."),
            ("鈴木", "Suzuki", "そう です ね。 日曜日|にちようび は 自由|じゆう に 遊|あそ ばせて います。",
             "Betul juga. Hari Minggu kami biarkan dia bebas bermain."),
        ],
    ),
    quiz_bunpo=[
        QB("qb48-1", "母|はは は 子|こ ども に 野菜|やさい を 食|た べ＿＿ました。", ["させ", "られ", "てもらい", "ていただき"], 0,
           "母|はは は 子|こ ども に 野菜|やさい を 食|た べさせました。", "食べさせました",
           "Gol II: ます → させます", "Kausatif Golongan II: 食べます → 食べさせます."),
        QB("qb48-2", "子|こ ども ＿＿ 塾|じゅく へ 行|い かせます。", ["を", "に", "が", "へ"], 0,
           "子|こ ども を 塾|じゅく へ 行|い かせます。", "子どもを", "Intransitif: [Orang] を Vさせます",
           "Kata kerja intransitif (行く) dalam kausatif: yang disuruh ditandai を."),
        QB("qb48-3", "あした 休|やす ませて ＿＿ません か。", ["いただけ", "くれ", "あげ", "もらい"], 0,
           "あした 休|やす ませて いただけません か。", "休ませていただけませんか",
           "Kausatif ＋ て いただけません か",
           "Cara paling sopan meminta izin: kausatif + ていただけませんか."),
        QB_ID("qb48-4", "“Guru menyuruh murid menulis karangan.”",
              ["先生|せんせい は 生徒|せいと に 作文|さくぶん を 書|か かせます。",
               "先生|せんせい は 生徒|せいと を 作文|さくぶん を 書|か かせます。",
               "先生|せんせい は 生徒|せいと に 作文|さくぶん を 書|か かれます。",
               "先生|せんせい は 生徒|せいと に 作文|さくぶん を 書|か いて あげます。"], 0,
              "先生|せんせい は 生徒|せいと に 作文|さくぶん を 書|か かせます。", "生徒に作文を 書かせます",
              "Transitif: [Orang] に [Benda] を Vさせます",
              "Karena 書く punya objek を, pihak yang disuruh ditandai に."),
    ],
    quiz_susun=[
        QS("qs48-1", "Saya menyuruh anak minum obat.",
           "子|こ ども に 薬|くすり を 飲|の ませました", "食|た べさせ 犬|いぬ"),
        QS("qs48-2", "Menyuruh anak pergi ke bimbel.",
           "子|こ ども を 塾|じゅく へ 行|い かせます", "帰|かえ らせ 家|うち"),
        QS("qs48-3", "Bolehkah saya izin tidak masuk besok?",
           "あした 休|やす ませて いただけません か", "休|やす んでも です"),
    ],
)

BAB49 = CHAPTER(
    49, "先生は もう お帰りに なりました。", "Guru sudah pulang (bahasa hormat).",
    bunpo=[
        BUNPO(
            "b49-1", "Bahasa Hormat (尊敬語) — Untuk Orang yang Dihormati",
            "お ＋ [bentuk ます tanpa ます] ＋ に なります ／ kata kerja khusus",
            [
                "お帰|かえ りに なります, お読|よ みに なります",
                "kata khusus: いらっしゃいます (ada/pergi/datang)",
                "おっしゃいます (berkata), ご覧|らん に なります (melihat)",
                "なさいます (melakukan), 召|め し上|あ がります (makan/minum)",
            ],
            "Untuk menghormati orang yang berbicara dengan kita atau yang dibicarakan (atasan, "
            "tamu, orang tua orang lain), kata kerjanya diubah ke bentuk hormat: pola お〜に "
            "なります atau kata kerja khusus.",
            [
                ("先生|せんせい は もう お帰|かえ りに なりました。", "Guru sudah pulang."),
                ("部長|ぶちょう が そう おっしゃいました。", "Kepala bagian berkata begitu."),
                ("社長|しゃちょう は 新聞|しんぶん を ご覧|らん に なって います。", "Direktur sedang membaca koran."),
            ],
        ),
        BUNPO(
            "b49-2", "Bentuk Pasif sebagai Bahasa Hormat",
            "[Bentuk pasif] (ら)れます",
            [
                "読|よ まれます = membaca (hormat)",
                "来|こ られます = datang (hormat)",
                "lebih ringan daripada お〜になります",
            ],
            "Bentuk pasif (Bab 37) juga bisa dipakai sebagai bahasa hormat tingkat ringan. "
            "Perhatikan: 来られます sebagai hormat berbeda dari bentuk kemungkinan 来られる "
            "(bisa datang) — lihat konteksnya.",
            [
                ("先生|せんせい は 何時|なんじ に 来|こ られます か。", "Jam berapa guru akan datang?"),
                ("社長|しゃちょう が 挨拶|あいさつ されました。", "Direktur memberi sambutan."),
                ("どちら に 泊|と まられます か。", "Anda menginap di mana?"),
            ],
        ),
        BUNPO(
            "b49-3", "Ungkapan Hormat Lainnya",
            "ご存|ぞん じ です ／ お持|も ち です ／ 〜で いらっしゃいます",
            [
                "知っています → ご存じです",
                "持っています → お持ちです",
                "〜です → 〜でいらっしゃいます",
                "ペンを お持ちですか = apakah Anda membawa pulpen",
            ],
            "Beberapa ungkapan hormat tidak mengikuti pola umum dan perlu dihafal: ご存じです, "
            "お持ちです, dan 〜でいらっしゃいます.",
            [
                ("この 方|かた を ご存|ぞん じ です か。", "Apakah Anda mengenal beliau ini?"),
                ("ペン を お持|も ち です か。", "Apakah Anda membawa pulpen?"),
                ("お元気|げんき で いらっしゃいます か。", "Apakah Anda sehat?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k49-1", "いらっしゃいます", "いらっしゃいます", "irasshaimasu", "ada/pergi/datang (hormat)", "Kata Kerja",
               ("先生|せんせい は もう いらっしゃいます か。", "Apakah guru sudah datang?")),
        KOTOBA("k49-2", "召し上がります", "めしあがります", "meshiagarimasu", "makan/minum (hormat)", "Kata Kerja",
               ("どうぞ 召|め し上|あ がって ください。", "Silakan makan.")),
        KOTOBA("k49-3", "おっしゃいます", "おっしゃいます", "osshaimasu", "berkata (hormat)", "Kata Kerja",
               ("何|なん と おっしゃいました か。", "Apa yang beliau katakan?")),
        KOTOBA("k49-4", "なさいます", "なさいます", "nasaimasu", "melakukan (hormat)", "Kata Kerja",
               ("週末|しゅうまつ は 何|なに を なさいます か。", "Akhir pekan Anda melakukan apa?")),
        KOTOBA("k49-5", "ご覧になります", "ごらんになります", "goran ni narimasu", "melihat (hormat)", "Kata Kerja",
               ("この 写真|しゃしん を ご覧|らん に なりました か。", "Apakah Anda sudah melihat foto ini?")),
        KOTOBA("k49-6", "ご存じです", "ごぞんじです", "gozonji desu", "mengetahui (hormat)", "Kata Kerja",
               ("田中|たなか さん を ご存|ぞん じ です か。", "Apakah Anda kenal Tanaka?")),
        KOTOBA("k49-7", "勤めます", "つとめます", "tsutomemasu", "bekerja (di)", "Kata Kerja",
               ("銀行|ぎんこう に 勤|つと めて います。", "Bekerja di bank.")),
        KOTOBA("k49-8", "過ごします", "すごします", "sugoshimasu", "melewatkan (waktu)", "Kata Kerja",
               ("週末|しゅうまつ を 家|いえ で 過|す ごします。", "Melewatkan akhir pekan di rumah.")),
        KOTOBA("k49-9", "寄ります", "よります", "yorimasu", "mampir", "Kata Kerja",
               ("帰|かえ り に 本屋|ほんや に 寄|よ ります。", "Mampir ke toko buku dalam perjalanan pulang.")),
        KOTOBA("k49-10", "あいさつ", "あいさつ", "aisatsu", "salam; sambutan", "Kata Benda",
               ("社長|しゃちょう の あいさつ です。", "Sambutan dari direktur.")),
        KOTOBA("k49-11", "旅館", "りょかん", "ryokan", "penginapan Jepang", "Kata Benda",
               ("旅館|りょかん に 泊|と まります。", "Menginap di penginapan Jepang.")),
        KOTOBA("k49-12", "会場", "かいじょう", "kaijō", "tempat acara", "Kata Benda",
               ("会場|かいじょう は こちら です。", "Tempat acaranya di sini.")),
        KOTOBA("k49-13", "貿易", "ぼうえき", "bōeki", "perdagangan", "Kata Benda",
               ("貿易|ぼうえき 会社|がいしゃ で 働|はたら いて います。", "Bekerja di perusahaan dagang.")),
        KOTOBA("k49-14", "遠慮なく", "えんりょなく", "enryo naku", "jangan sungkan", "Kata Keterangan",
               ("ご遠慮|えんりょ なく 召|め し上|あ がって ください。", "Jangan sungkan, silakan makan.")),
        KOTOBA("k49-15", "ちっとも", "ちっとも", "chittomo", "sama sekali (tidak)", "Kata Keterangan",
               ("ちっとも 分|わ かりません。", "Sama sekali tidak mengerti.")),
        KOTOBA("k49-16", "失礼いたします", "しつれいいたします", "shitsurei itashimasu", "permisi (sopan)", "Ungkapan",
               ("では、 失礼|しつれい いたします。", "Kalau begitu, saya permisi.")),
        KOTOBA("k49-17", "講師", "こうし", "kōshi", "dosen; pembicara", "Kata Benda",
               ("講師|こうし の 先生|せんせい が お見|み えに なりました。", "Bapak pembicara sudah datang.")),
        KOTOBA("k49-18", "作品", "さくひん", "sakuhin", "karya", "Kata Benda",
               ("有名|ゆうめい な 作家|さっか の 作品|さくひん です。", "Karya penulis terkenal.")),
    ],
    kanji=[
        KANJI("j49-1", "勤", "キン", "つと(める)", "bekerja", 12,
              [("勤めます", "つとめます", "bekerja"), ("通勤", "つうきん", "pergi ke kantor")]),
        KANJI("j49-2", "寄", "キ", "よ(る)", "mampir; dekat", 11,
              [("寄ります", "よります", "mampir"), ("寄付", "きふ", "sumbangan")]),
        KANJI("j49-3", "覧", "ラン", "—", "lihat", 17,
              [("ご覧になります", "ごらんになります", "melihat (hormat)"), ("観覧", "かんらん", "menonton")]),
        KANJI("j49-4", "存", "ゾン", "—", "ada; tahu (hormat)", 6,
              [("ご存じです", "ごぞんじです", "mengetahui (hormat)"), ("存在", "そんざい", "keberadaan")]),
        KANJI("j49-5", "貿", "ボウ", "—", "dagang", 12,
              [("貿易", "ぼうえき", "perdagangan"), ("貿易会社", "ぼうえきがいしゃ", "perusahaan dagang")]),
        KANJI("j49-6", "講", "コウ", "—", "ceramah", 17,
              [("講師", "こうし", "pembicara"), ("講義", "こうぎ", "kuliah")]),
    ],
    kaiwa=KAIWA(
        "会社の 応接室で — Di Ruang Tamu Perusahaan",
        "Resepsionis menerima tamu penting dengan bahasa hormat.",
        [
            ("受付", "Uketsuke", "いらっしゃいませ。 どちら 様|さま で いらっしゃいます か。",
             "Selamat datang. Dengan siapa, ya?"),
            ("客", "Kaku", "山田商事|しょうじ の 田中|たなか と 申|もう します。 佐藤|さとう 部長|ぶちょう に お会|あ いしたいん です が。",
             "Saya Tanaka dari Yamada Shoji. Saya ingin bertemu Kepala Bagian Sato."),
            ("受付", "Uketsuke", "申|もう し訳|わけ ございません。 部長|ぶちょう は ただいま 会議中|かいぎちゅう で いらっしゃいます。",
             "Mohon maaf. Beliau sedang rapat."),
            ("客", "Kaku", "何時|なんじ ごろ お終|お わりに なります か。", "Kira-kira jam berapa selesai?"),
            ("受付", "Uketsuke", "3時|さんじ に 終|お わる 予定|よてい で ございます。 こちら で お待|ま ち くださいます か。",
             "Dijadwalkan selesai jam 3. Bersediakah Anda menunggu di sini?"),
            ("客", "Kaku", "はい、 お願|ねが いします。", "Baik, terima kasih."),
        ],
    ),
    quiz_bunpo=[
        QB("qb49-1", "先生|せんせい は もう お帰|かえ りに ＿＿ました。", ["なり", "しまい", "い", "あい"], 0,
           "先生|せんせい は もう お帰|かえ りに なりました。", "お帰りに なりました", "お ＋ batang ＋ に なります",
           "Bahasa hormat umum: お + bentuk ます tanpa ます + になります."),
        QB("qb49-2", "部長|ぶちょう が そう ＿＿ました。", ["おっしゃい", "おいいになり", "おいわれ", "もうしあげ"], 0,
           "部長|ぶちょう が そう おっしゃいました。", "おっしゃいました", "言います → おっしゃいます",
           "Berkata (hormat) memakai kata khusus おっしゃいます."),
        QB("qb49-3", "先生|せんせい は 何時|なんじ に ＿＿ます か。", ["来|こ られ", "来|き させ", "来|き まれ", "来|き まし"], 0,
           "先生|せんせい は 何時|なんじ に 来|こ られます か。", "来られます", "Bentuk pasif sebagai hormat",
           "Bentuk (ら)れます bisa dipakai sebagai bahasa hormat tingkat ringan."),
        QB_ID("qb49-4", "“Apakah Anda membawa pulpen?” (kepada tamu, hormat)",
              ["ペン を お持|も ち です か。",
               "ペン を 持|も って いらっしゃいます か ね。",
               "ペン を 持|も ちます か。",
               "ペン を お持|も たせ に なります か。"], 0,
              "ペン を お持|も ち です か。", "お持ちです", "持っています → お持ちです",
              "お持ちです adalah bentuk hormat khusus dari 持っています."),
    ],
    quiz_susun=[
        QS("qs49-1", "Guru sudah pulang (hormat).",
           "先生|せんせい は もう お帰|かえ りに なりました", "帰|かえ りました 学生|がくせい"),
        QS("qs49-2", "Silakan makan (hormat).",
           "どうぞ 召|め し上|あ がって ください", "食|た べて 飲|の んで"),
        QS("qs49-3", "Direktur sedang membaca koran (hormat).",
           "社長|しゃちょう は 新聞|しんぶん を ご覧|らん に なって います", "読|よ んで 部長|ぶちょう"),
    ],
)

BAB50 = CHAPTER(
    50, "私が ご案内 いたします。", "Saya yang akan mengantar Anda (bahasa rendah hati).",
    bunpo=[
        BUNPO(
            "b50-1", "Bahasa Rendah Hati (謙譲語) — Untuk Aksi Sendiri",
            "お ＋ [bentuk ます tanpa ます] ＋ します ／ ご ＋ [kata suru] ＋ します",
            [
                "お持|も ち します, お送|おく り します",
                "ご案内|あんない します, ご説明|せつめい します (kata kanji: ご〜)",
                "merendahkan aksi SENDIRI di hadapan lawan bicara",
            ],
            "Kebalikan dari Bab 49: untuk menghormati lawan bicara, aksi sendiri direndahkan "
            "dengan お〜します (kata kerja asli Jepang) atau ご〜します (kata kerja serapan kanji "
            "seperti 案内, 説明).",
            [
                ("私|わたし が ご案内|あんない いたします。", "Saya yang akan mengantar Anda."),
                ("荷物|にもつ を お持|も ち しましょう か。", "Bolehkah saya bawakan barang Anda?"),
                ("詳|くわ しく ご説明|せつめい いたします。", "Saya akan menjelaskannya dengan rinci."),
            ],
        ),
        BUNPO(
            "b50-2", "Kata Kerja Rendah Hati Khusus",
            "まいります ／ おります ／ 申|もう します ／ いたします ／ 拝見|はいけん します ／ 伺|うかが います",
            [
                "行きます・来ます → まいります",
                "います → おります ； 言います → 申します",
                "します → いたします ； 見ます → 拝見します",
                "聞きます・訪ねます → 伺います ； 会います → お目|め に かかります",
            ],
            "Seperti halnya bahasa hormat, bahasa rendah hati punya kata kerja khusus yang harus "
            "dihafal. Ini wajib di dunia kerja dan pelayanan pelanggan.",
            [
                ("私|わたくし は 田中|たなか と 申|もう します。", "Saya bernama Tanaka."),
                ("明日|あした そちら へ 伺|うかが います。", "Besok saya akan berkunjung ke sana."),
                ("お写真|しゃしん を 拝見|はいけん しました。", "Saya telah melihat foto Anda."),
            ],
        ),
        BUNPO(
            "b50-3", "Bahasa Sopan Ekstra (丁重語)",
            "あります → ございます ； です → で ございます",
            [
                "ございます = bentuk sopan ekstra dari あります",
                "でございます = bentuk sopan ekstra dari です",
                "sering terdengar di toko, hotel, dan pengumuman",
            ],
            "丁重語 meningkatkan kesopanan kalimat tanpa mengubah siapa yang dihormati. Umum di "
            "pelayanan: こちらが 会場で ございます (inilah tempat acaranya).",
            [
                ("会場|かいじょう は 2階|かい で ございます。", "Tempat acaranya di lantai 2."),
                ("こちら が お部屋|へや で ございます。", "Inilah kamar Anda."),
                ("本日|ほんじつ は 誠|まこと に ありがとう ございます。", "Terima kasih banyak atas kehadirannya hari ini."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k50-1", "参ります", "まいります", "mairimasu", "pergi/datang (rendah hati)", "Kata Kerja",
               ("すぐ 参|まい ります。", "Saya segera ke sana.")),
        KOTOBA("k50-2", "おります", "おります", "orimasu", "ada (rendah hati)", "Kata Kerja",
               ("田中|たなか は 只今|ただいま 外出|がいしゅつ して おります。", "Tanaka sedang keluar.")),
        KOTOBA("k50-3", "申します", "もうします", "mōshimasu", "berkata (rendah hati)", "Kata Kerja",
               ("ワン と 申|もう します。", "Saya bernama Wang.")),
        KOTOBA("k50-4", "いたします", "いたします", "itashimasu", "melakukan (rendah hati)", "Kata Kerja",
               ("わたし が いたします。", "Saya yang akan melakukannya.")),
        KOTOBA("k50-5", "拝見します", "はいけんします", "haiken shimasu", "melihat (rendah hati)", "Kata Kerja",
               ("資料|しりょう を 拝見|はいけん しました。", "Saya sudah melihat bahannya.")),
        KOTOBA("k50-6", "存じます", "ぞんじます", "zonjimasu", "mengetahui (rendah hati)", "Kata Kerja",
               ("その 方|かた は 存|ぞん じて おります。", "Saya mengenal beliau.")),
        KOTOBA("k50-7", "伺います", "うかがいます", "ukagaimasu", "bertanya/berkunjung (rendah hati)", "Kata Kerja",
               ("一|ひと つ 伺|うかが っても よろしい です か。", "Bolehkah saya bertanya satu hal?")),
        KOTOBA("k50-8", "お目にかかります", "おめにかかります", "ome ni kakarimasu", "bertemu (rendah hati)", "Kata Kerja",
               ("お目|め に かかれて 光栄|こうえい です。", "Senang bisa bertemu Anda.")),
        KOTOBA("k50-9", "ございます", "ございます", "gozaimasu", "ada (sopan ekstra)", "Kata Kerja",
               ("受付|うけつけ は あちら で ございます。", "Resepsionisnya di sebelah sana.")),
        KOTOBA("k50-10", "私", "わたくし", "watakushi", "saya (sopan)", "Kata Benda",
               ("私|わたくし が 担当|たんとう いたします。", "Saya yang bertanggung jawab.")),
        KOTOBA("k50-11", "お宅", "おたく", "otaku", "rumah (orang lain, hormat)", "Kata Benda",
               ("お宅|たく へ 伺|うかが います。", "Saya berkunjung ke rumah Anda.")),
        KOTOBA("k50-12", "郊外", "こうがい", "kōgai", "pinggiran kota", "Kata Benda",
               ("郊外|こうがい に 住|す んで います。", "Tinggal di pinggiran kota.")),
        KOTOBA("k50-13", "アルバム", "アルバム", "arubamu", "album", "Kata Benda",
               ("アルバム を 拝見|はいけん しても いい です か。", "Bolehkah saya melihat albumnya?")),
        KOTOBA("k50-14", "半年", "はんとし", "hantoshi", "setengah tahun", "Kata Benda",
               ("日本|にほん に 来|き て 半年|はんとし に なります。", "Sudah setengah tahun saya di Jepang.")),
        KOTOBA("k50-15", "緊張します", "きんちょうします", "kinchō shimasu", "gugup", "Kata Kerja",
               ("少|すこ し 緊張|きんちょう して おります。", "Saya sedikit gugup.")),
        KOTOBA("k50-16", "協力します", "きょうりょくします", "kyōryoku shimasu", "bekerja sama", "Kata Kerja",
               ("ご協力|きょうりょく を お願|ねが いいたします。", "Mohon kerja samanya.")),
        KOTOBA("k50-17", "心から", "こころから", "kokoro kara", "dari hati", "Kata Keterangan",
               ("心|こころ から 感謝|かんしゃ いたします。", "Saya berterima kasih dari hati.")),
        KOTOBA("k50-18", "感謝します", "かんしゃします", "kansha shimasu", "berterima kasih", "Kata Kerja",
               ("皆|みな さま に 感謝|かんしゃ して おります。", "Saya berterima kasih kepada semuanya.")),
    ],
    kanji=[
        KANJI("j50-1", "参", "サン", "まい(る)", "pergi (rendah hati)", 8,
              [("参ります", "まいります", "pergi (rendah hati)"), ("参加", "さんか", "partisipasi")]),
        KANJI("j50-2", "拝", "ハイ", "—", "sembah; hormat", 8,
              [("拝見します", "はいけんします", "melihat (rendah hati)"), ("拝啓", "はいけい", "salam pembuka surat")]),
        KANJI("j50-3", "宅", "タク", "—", "rumah", 6,
              [("お宅", "おたく", "rumah Anda (hormat)"), ("住宅", "じゅうたく", "perumahan")]),
        KANJI("j50-4", "郊", "コウ", "—", "pinggiran", 10,
              [("郊外", "こうがい", "pinggiran kota"), ("近郊", "きんこう", "sekitar kota")]),
        KANJI("j50-5", "緊", "キン", "—", "tegang", 15,
              [("緊張", "きんちょう", "ketegangan; gugup"), ("緊急", "きんきゅう", "darurat")]),
        KANJI("j50-6", "感", "カン", "—", "rasa", 13,
              [("感謝", "かんしゃ", "terima kasih"), ("感動", "かんどう", "terharu")]),
    ],
    kaiwa=KAIWA(
        "スピーチ — Pidato Perpisahan",
        "Miller memberi pidato perpisahan di hari terakhir kerja magangnya dengan bahasa sopan.",
        [
            ("ミラー", "Mirā", "皆|みな さま、 本日|ほんじつ は ありがとう ございます。 私|わたくし、 ミラー と 申|もう します。",
             "Semuanya, terima kasih untuk hari ini. Saya bernama Miller."),
            ("ミラー", "Mirā", "この 半年間|はんとしかん、 大変|たいへん お世話|せわ に なりました。",
             "Selama setengah tahun ini, saya banyak dibantu oleh semuanya."),
            ("ミラー", "Mirā", "皆|みな さま の ご親切|しんせつ を 心|こころ から 感謝|かんしゃ いたします。",
             "Saya berterima kasih dari hati atas kebaikan semuanya."),
            ("ミラー", "Mirā", "少|すこ し 緊張|きんちょう して おります が、 日本|にほん で 学|まな んだ こと を 国|くに で 生|い かしたい と 思|おも います。",
             "Meskipun sedikit gugup, saya ingin menerapkan apa yang saya pelajari di Jepang di negara saya."),
            ("ミラー", "Mirā", "また いつか お目|め に かかれる 日|ひ を 楽|たの しみ に して おります。",
             "Saya menantikan hari ketika kita bisa bertemu lagi."),
            ("ミラー", "Mirā", "本当|ほんとう に ありがとう ございました。", "Terima kasih banyak atas semuanya."),
        ],
    ),
    quiz_bunpo=[
        QB("qb50-1", "私|わたし が ご案内|あんない ＿＿します。", ["いた", "なり", "さ", "あり"], 0,
           "私|わたし が ご案内|あんない いたします。", "ご案内いたします", "ご ＋ kata suru ＋ します/いたします",
           "Bahasa rendah hati untuk kata serapan kanji: ご案内します; いたします lebih sopan dari します."),
        QB("qb50-2", "私|わたくし は 田中|たなか と ＿＿ します。", ["申|もう し", "おっしゃり", "言|い い", "なさい"], 0,
           "私|わたくし は 田中|たなか と 申|もう します。", "申します", "言います → 申します",
           "Menyebut nama sendiri dengan rendah hati memakai 申します."),
        QB("qb50-3", "受付|うけつけ は あちら で ＿＿。", ["ございます", "いらっしゃいます", "おります", "まいります"], 0,
           "受付|うけつけ は あちら で ございます。", "でございます", "です → で ございます",
           "でございます adalah bentuk sopan ekstra dari です, umum di pelayanan."),
        QB_ID("qb50-4", "“Besok saya akan berkunjung ke sana.” (rendah hati)",
              ["明日|あした そちら へ 伺|うかが います。",
               "明日|あした そちら へ いらっしゃいます。",
               "明日|あした そちら へ おいで に なります。",
               "明日|あした そちら へ ご覧|らん に なります。"], 0,
              "明日|あした そちら へ 伺|うかが います。", "伺います", "行きます・来ます → 伺います/まいります",
              "Aksi sendiri direndahkan dengan 伺います atau まいります; いらっしゃいます untuk pihak yang dihormati."),
    ],
    quiz_susun=[
        QS("qs50-1", "Saya yang akan mengantar Anda.",
           "私|わたし が ご案内|あんない いたします", "説明|せつめい 彼|かれ"),
        QS("qs50-2", "Saya bernama Wang.",
           "私|わたくし は ワン と 申|もう します", "言|い います 田中|たなか"),
        QS("qs50-3", "Tempat acaranya di lantai 2.",
           "会場|かいじょう は 2階|かい で ございます", "3階|かい あります"),
    ],
)

CHAPTERS = [BAB46, BAB47, BAB48, BAB49, BAB50]
