"""Materi Minna no Nihongo 2 — Bab 41 s/d 45."""

from seed_data.dsl import BUNPO, CHAPTER, KAIWA, KANJI, KOTOBA, QB, QB_ID, QS

BAB41 = CHAPTER(
    41, "誕生日に プレゼントを いただきました。", "Saya menerima hadiah pada hari ulang tahun.",
    bunpo=[
        BUNPO(
            "b41-1", "あげます・くれます・もらいます ＋ Tingkat Kesopanan",
            "やります ／ あげます ／ さしあげます ； くれます ／ くださいます ； もらいます ／ いただきます",
            [
                "memberi ke bawah (adik, hewan): やります",
                "memberi sejajar: あげます ； ke atas: さしあげます",
                "menerima dari orang yang lebih tinggi: いただきます",
                "orang (lebih tinggi) memberi kita: くださいます",
            ],
            "Pola memberi-menerima dari Bab 7 punya pasangan sopan: kepada orang yang lebih tua "
            "atau dihormati, あげます menjadi さしあげます, もらいます menjadi いただきます, dan "
            "くれます menjadi くださいます.",
            [
                ("先生|せんせい に お土産|みやげ を さしあげました。", "Saya memberi oleh-oleh kepada guru."),
                ("誕生日|たんじょうび に プレゼント を いただきました。", "Saya menerima hadiah pada hari ulang tahun."),
                ("課長|かちょう が 書類|しょるい を くださいました。", "Kepala seksi memberikan dokumennya kepada saya."),
            ],
        ),
        BUNPO(
            "b41-2", "〜て あげます・やります — Memberi Jasa",
            "[Kata Kerja bentuk て] あげます ／ さしあげます ／ やります",
            [
                "melakukan sesuatu UNTUK orang lain",
                "kepada yang dihormati: 〜て さしあげます",
                "kepada adik/hewan: 〜て やります",
            ],
            "Seperti pada Bab 24, bentuk て＋あげます menyatakan memberi jasa. Tingkat kesopanannya "
            "mengikuti pola di atas: 先生に 写真を 撮って さしあげました.",
            [
                ("先生|せんせい に 写真|しゃしん を 撮|と って さしあげました。", "Saya memotretkan untuk guru."),
                ("弟|おとうと に 絵本|えほん を 読|よ んで やります。", "Saya membacakan buku bergambar untuk adik."),
                ("犬|いぬ に えさ を やります。", "Saya memberi makan anjing."),
            ],
        ),
        BUNPO(
            "b41-3", "〜て くれます・くださいます ／ 〜て もらいます・いただきます",
            "[Kata Kerja bentuk て] くれます ／ くださいます ／ もらいます ／ いただきます",
            [
                "〜て くれます: orang lain melakukan untuk kita",
                "〜て くださいます: dari orang yang dihormati",
                "〜て もらいます / いただきます: kita menerima jasa",
                "permintaan sopan: 〜て くださいませんか",
            ],
            "Dua sudut pandang: 先生が 教えて くださいました (guru yang mengajari saya) dan "
            "先生に 教えて いただきました (saya diajari oleh guru). Untuk meminta dengan sopan: "
            "〜て くださいませんか.",
            [
                ("先生|せんせい が 文法|ぶんぽう を 教|おし えて くださいました。", "Guru mengajari saya tata bahasa."),
                ("先生|せんせい に 文法|ぶんぽう を 教|おし えて いただきました。", "Saya diajari tata bahasa oleh guru."),
                ("ちょっと 手伝|てつだ って くださいません か。", "Bisakah Anda membantu saya sebentar?"),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k41-1", "いただきます", "いただきます", "itadakimasu", "menerima (sopan)", "Kata Kerja",
               ("先生|せんせい に 本|ほん を いただきました。", "Saya menerima buku dari guru.")),
        KOTOBA("k41-2", "くださいます", "くださいます", "kudasaimasu", "memberikan (kepada saya, hormat)", "Kata Kerja",
               ("課長|かちょう が これ を くださいました。", "Kepala seksi memberikan ini kepada saya.")),
        KOTOBA("k41-3", "呼びます", "よびます", "yobimasu", "memanggil", "Kata Kerja",
               ("子|こ ども を 呼|よ んで ください。", "Tolong panggilkan anaknya.")),
        KOTOBA("k41-4", "取り替えます", "とりかえます", "torikaemasu", "menukar; mengganti", "Kata Kerja",
               ("切符|きっぷ を 取|と り替|か えました。", "Saya menukar tiketnya.")),
        KOTOBA("k41-5", "親切にします", "しんせつにします", "shinsetsu ni shimasu", "berbuat baik kepada", "Ungkapan",
               ("みんな が 親切|しんせつ に して くれます。", "Semua orang berbuat baik kepada saya.")),
        KOTOBA("k41-6", "可愛い", "かわいい", "kawaii", "lucu; imut", "Kata Sifat-i",
               ("可愛|かわい い 犬|いぬ です ね。", "Anjingnya lucu, ya.")),
        KOTOBA("k41-7", "お祝い", "おいわい", "oiwai", "hadiah perayaan", "Kata Benda",
               ("結婚|けっこん の お祝|いわ い を 贈|おく ります。", "Mengirim hadiah pernikahan.")),
        KOTOBA("k41-8", "お年玉", "おとしだま", "otoshidama", "angpau tahun baru", "Kata Benda",
               ("子|こ ども に お年玉|としだま を あげます。", "Memberi angpau kepada anak-anak.")),
        KOTOBA("k41-9", "お見舞い", "おみまい", "omimai", "buah tangan jenguk", "Kata Benda",
               ("病院|びょういん へ お見舞|みま い に 行|い きます。", "Pergi menjenguk ke rumah sakit.")),
        KOTOBA("k41-10", "興味", "きょうみ", "kyōmi", "minat", "Kata Benda",
               ("日本|にほん の 歴史|れきし に 興味|きょうみ が あります。", "Saya berminat pada sejarah Jepang.")),
        KOTOBA("k41-11", "情報", "じょうほう", "jōhō", "informasi", "Kata Benda",
               ("インターネット で 情報|じょうほう を 集|あつ めます。", "Mengumpulkan informasi di internet.")),
        KOTOBA("k41-12", "文法", "ぶんぽう", "bunpō", "tata bahasa", "Kata Benda",
               ("文法|ぶんぽう の 質問|しつもん が あります。", "Saya ada pertanyaan tata bahasa.")),
        KOTOBA("k41-13", "発音", "はつおん", "hatsuon", "pengucapan", "Kata Benda",
               ("発音|はつおん が きれい です ね。", "Pengucapan Anda bagus, ya.")),
        KOTOBA("k41-14", "手袋", "てぶくろ", "tebukuro", "sarung tangan", "Kata Benda",
               ("祖母|そぼ が 手袋|てぶくろ を 編|あ んで くれました。", "Nenek merajutkan sarung tangan untuk saya.")),
        KOTOBA("k41-15", "指輪", "ゆびわ", "yubiwa", "cincin", "Kata Benda",
               ("母|はは に 指輪|ゆびわ を もらいました。", "Saya mendapat cincin dari ibu.")),
        KOTOBA("k41-16", "祖父", "そふ", "sofu", "kakek (sendiri)", "Kata Benda",
               ("祖父|そふ は 80歳|はちじゅっさい です。", "Kakek saya berumur 80 tahun.")),
        KOTOBA("k41-17", "孫", "まご", "mago", "cucu", "Kata Benda",
               ("孫|まご に おもちゃ を 買|か って あげました。", "Saya membelikan mainan untuk cucu.")),
        KOTOBA("k41-18", "昔話", "むかしばなし", "mukashibanashi", "cerita rakyat", "Kata Benda",
               ("祖母|そぼ が 昔話|むかしばなし を して くれます。", "Nenek menceritakan dongeng untuk saya.")),
    ],
    kanji=[
        KANJI("j41-1", "贈", "ゾウ", "おく(る)", "hadiahkan", 18,
              [("贈り物", "おくりもの", "hadiah"), ("贈呈", "ぞうてい", "penyerahan hadiah")]),
        KANJI("j41-2", "預", "ヨ", "あず(かる)", "titip", 13,
              [("預かります", "あずかります", "menyimpan titipan"), ("預金", "よきん", "simpanan bank")]),
        KANJI("j41-3", "助", "ジョ", "たす(ける)", "tolong", 7,
              [("助けます", "たすけます", "menolong"), ("助かります", "たすかります", "tertolong")]),
        KANJI("j41-4", "興", "キョウ", "—", "minat; bangkit", 16,
              [("興味", "きょうみ", "minat"), ("興奮", "こうふん", "terkesan; gembira")]),
        KANJI("j41-5", "孫", "ソン", "まご", "cucu", 10,
              [("孫", "まご", "cucu"), ("子孫", "しそん", "keturunan")]),
        KANJI("j41-6", "城", "ジョウ", "しろ", "kastil", 9,
              [("城", "しろ", "kastil"), ("城下町", "じょうかまち", "kota kastil")]),
    ],
    kaiwa=KAIWA(
        "お祝いの 季節 — Musim Perayaan",
        "Karina bercerita tentang hadiah-hadiah yang ia terima dan berikan di akhir tahun.",
        [
            ("山田", "Yamada", "カリナさん、 その 手袋|てぶくろ、 可愛|かわい い です ね。",
             "Karina, sarung tanganmu lucu, ya."),
            ("カリナ", "Karina", "ありがとう ございます。 祖母|そぼ が 編|あ んで くれたん です。",
             "Terima kasih. Nenek saya yang merajutkannya."),
            ("山田", "Yamada", "いい です ね。 誕生日|たんじょうび に いただいたん です か。",
             "Bagus sekali. Anda terima saat ulang tahun?"),
            ("カリナ", "Karina", "ええ。 先生|せんせい にも 絵|え はがき を いただきました。 わたし は 先生|せんせい に 写真|しゃしん を 撮|と って さしあげました。",
             "Ya. Saya juga menerima kartu bergambar dari guru. Saya memotretkan foto untuk beliau."),
            ("山田", "Yamada", "お正月|しょうがつ に は 子|こ どもたち に お年玉|としだま を やります か。",
             "Saat tahun baru, apakah Anda memberi angpau kepada anak-anak?"),
            ("カリナ", "Karina", "ええ、 少|すこ し ずつ。 喜|よろこ んで もらえる と うれしい です ね。",
             "Ya, sedikit-sedikit. Senang rasanya kalau mereka gembira menerimanya."),
        ],
    ),
    quiz_bunpo=[
        QB("qb41-1", "先生|せんせい に お土産|みやげ を ＿＿ました。", ["さしあげ", "いただき", "ください", "やり"], 0,
           "先生|せんせい に お土産|みやげ を さしあげました。", "さしあげました", "kepala yang dihormati: さしあげます",
           "Memberi kepada orang yang dihormati memakai さしあげます, bukan あげます."),
        QB("qb41-2", "課長|かちょう が 書類|しょるい を ＿＿ました。", ["ください", "いただき", "さしあげ", "やり"], 0,
           "課長|かちょう が 書類|しょるい を くださいました。", "くださいました", "orang (lebih tinggi) → saya: くださいます",
           "Ketika orang yang lebih tinggi memberi kita, kata kerjanya くださいます."),
        QB("qb41-3", "先生|せんせい に 文法|ぶんぽう を 教|おし えて ＿＿ました。", ["いただき", "さしあげ", "くれ", "やり"], 0,
           "先生|せんせい に 文法|ぶんぽう を 教|おし えて いただきました。", "教えていただきました",
           "Vて いただきます (menerima jasa)",
           "Kita menerima jasa dari orang yang dihormati: 〜ていただきます."),
        QB_ID("qb41-4", "“Bisakah Anda membantu saya sebentar?” (sopan)",
              ["ちょっと 手伝|てつだ って くださいません か。",
               "ちょっと 手伝|てつだ って さしあげません か。",
               "ちょっと 手伝|てつだ って いただきます か。",
               "ちょっと 手伝|てつだ い て くれます か。"], 0,
              "ちょっと 手伝|てつだ って くださいません か。", "てくださいませんか", "Vて くださいません か",
              "Permintaan sopan kepada orang lain memakai 〜てくださいませんか."),
    ],
    quiz_susun=[
        QS("qs41-1", "Saya memberi oleh-oleh kepada guru.",
           "先生|せんせい に お土産|みやげ を さしあげました", "もらいました 弟|おとうと"),
        QS("qs41-2", "Guru mengajari saya tata bahasa.",
           "先生|せんせい が 文法|ぶんぽう を 教|おし えて くださいました", "やりました 読|よ んで"),
        QS("qs41-3", "Saya membacakan buku bergambar untuk adik.",
           "弟|おとうと に 絵本|えほん を 読|よ んで やります", "犬|いぬ 書|か いて"),
    ],
)

BAB42 = CHAPTER(
    42, "留学の ために 貯金して います。", "Saya menabung demi belajar ke luar negeri.",
    bunpo=[
        BUNPO(
            "b42-1", "〜ために — Demi / Untuk (Tujuan)",
            "[Kata Kerja bentuk kamus] ために ／ [Kata Benda] の ために",
            [
                "kata kerja: 留学|りゅうがく する ために (tujuan aksi)",
                "kata benda: 家族|かぞく の ために (demi seseorang/sesuatu)",
                "bandingkan 〜ように (Bab 36): untuk hal non-kehendak",
            ],
            "ために menyatakan tujuan suatu aksi yang disengaja, atau pihak yang diuntungkan. "
            "Karena aksi di bagian belakang harus bisa dikendalikan, kata kerja non-kehendak "
            "memakai ように, bukan ために.",
            [
                ("留学|りゅうがく の ために、 貯金|ちょきん して います。", "Saya menabung demi belajar ke luar negeri."),
                ("家族|かぞく の ために、 一生懸命|いっしょうけんめい 働|はたら きます。", "Saya bekerja keras demi keluarga."),
                ("健康|けんこう の ために、 野菜|やさい を たくさん 食|た べます。", "Demi kesehatan, saya makan banyak sayur."),
            ],
        ),
        BUNPO(
            "b42-2", "〜のに ／ 〜に — Dipakai Untuk",
            "[Kata Kerja bentuk kamus] のに 使|つか います ／ 便利|べんり です ／ 時間|じかん が かかります",
            [
                "alat: この はさみ は 紙|かみ を 切るのに 使います",
                "penilaian: 漢字|かんじ を 覚えるのに 便利です",
                "biaya/waktu: 書|か くのに 時間が かかります",
            ],
            "Untuk menyatakan kegunaan suatu alat atau biaya/waktu yang diperlukan suatu kegiatan, "
            "kata kerjanya dinominalkan dengan のに. Setelah kata benda langsung pakai に: "
            "この かばんは 旅行に 便利です.",
            [
                ("栓抜|せんぬ き は 瓶|びん の ふた を 開|あ ける のに 使|つか います。",
                 "Pembuka tutup dipakai untuk membuka tutup botol."),
                ("この アプリ は 漢字|かんじ を 覚|おぼ える のに 便利|べんり です。",
                 "Aplikasi ini praktis untuk menghafal kanji."),
                ("作文|さくぶん を 書|か く のに 2時間|にじかん かかりました。",
                 "Menulis karangan memakan waktu 2 jam."),
            ],
        ),
        BUNPO(
            "b42-3", "数量詞 は ／ 数量詞 も — Sedikitnya / Sampai-sampai",
            "[Kata Jumlah] は 〜 ／ [Kata Jumlah] も 〜",
            [
                "は: menegaskan jumlah minimal (setidaknya)",
                "も: menegaskan jumlah yang mengejutkan besarnya",
                "1時間|いちじかん も かかりました = sampai 1 jam",
            ],
            "は setelah kata jumlah berarti “setidaknya segitu”; も menyatakan jumlah yang "
            "dirasakan besar atau banyak sekali.",
            [
                ("この 本|ほん を 読|よ む のに 1週間|いっしゅうかん は かかります。",
                 "Membaca buku ini setidaknya butuh seminggu."),
                ("きのう は 8時間|はちじかん も 寝|ね ました。", "Kemarin saya tidur sampai 8 jam."),
                ("100人|ひゃくにん も 集|あつ まりました。", "Sampai 100 orang berkumpul."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k42-1", "包みます", "つつみます", "tsutsumimasu", "membungkus", "Kata Kerja",
               ("プレゼント を 包|つつ みます。", "Membungkus hadiah.")),
        KOTOBA("k42-2", "沸かします", "わかします", "wakashimasu", "merebus (air)", "Kata Kerja",
               ("やかん で お湯|ゆ を 沸|わ かします。", "Merebus air dengan ketel.")),
        KOTOBA("k42-3", "混ぜます", "まぜます", "mazemasu", "mencampur", "Kata Kerja",
               ("材料|ざいりょう を よく 混|ま ぜます。", "Mencampur bahan sampai rata.")),
        KOTOBA("k42-4", "計算します", "けいさんします", "keisan shimasu", "menghitung", "Kata Kerja",
               ("そろばん で 計算|けいさん します。", "Menghitung dengan sempoa.")),
        KOTOBA("k42-5", "厚い", "あつい", "atsui", "tebal", "Kata Sifat-i",
               ("厚|あつ い 本|ほん です ね。", "Bukunya tebal, ya.")),
        KOTOBA("k42-6", "薄い", "うすい", "usui", "tipis", "Kata Sifat-i",
               ("この 紙|かみ は 薄|うす い です。", "Kertas ini tipis.")),
        KOTOBA("k42-7", "弁護士", "べんごし", "bengoshi", "pengacara", "Kata Benda",
               ("弁護士|べんごし に なりたい です。", "Saya ingin menjadi pengacara.")),
        KOTOBA("k42-8", "音楽家", "おんがくか", "ongakuka", "musisi", "Kata Benda",
               ("ベートーベン は 有名|ゆうめい な 音楽家|おんがくか です。", "Beethoven adalah musisi terkenal.")),
        KOTOBA("k42-9", "教育", "きょういく", "kyōiku", "pendidikan", "Kata Benda",
               ("教育|きょういく の ために 引|ひ っ越|こ しました。", "Pindah demi pendidikan.")),
        KOTOBA("k42-10", "文化", "ぶんか", "bunka", "budaya", "Kata Benda",
               ("日本|にほん の 文化|ぶんか を 勉強|べんきょう します。", "Mempelajari budaya Jepang.")),
        KOTOBA("k42-11", "社会", "しゃかい", "shakai", "masyarakat", "Kata Benda",
               ("社会|しゃかい の 問題|もんだい に 興味|きょうみ が あります。", "Saya berminat pada masalah masyarakat.")),
        KOTOBA("k42-12", "法律", "ほうりつ", "hōritsu", "hukum", "Kata Benda",
               ("法律|ほうりつ を 守|まも りましょう。", "Mari patuhi hukum.")),
        KOTOBA("k42-13", "平和", "へいわ", "heiwa", "perdamaian", "Kata Benda",
               ("世界|せかい の 平和|へいわ を 願|ねが います。", "Mendoakan perdamaian dunia.")),
        KOTOBA("k42-14", "目的", "もくてき", "mokuteki", "tujuan", "Kata Benda",
               ("旅行|りょこう の 目的|もくてき は 何|なん です か。", "Apa tujuan perjalanannya?")),
        KOTOBA("k42-15", "論文", "ろんぶん", "ronbun", "skripsi; makalah", "Kata Benda",
               ("論文|ろんぶん を 書|か く のに 1年|いちねん かかりました。", "Menulis skripsi memakan waktu setahun.")),
        KOTOBA("k42-16", "缶詰", "かんづめ", "kanzume", "makanan kaleng", "Kata Benda",
               ("缶詰|かんづめ は 保存|ほぞん に 便利|べんり です。", "Makanan kaleng praktis untuk disimpan.")),
        KOTOBA("k42-17", "体温計", "たいおんけい", "taionkei", "termometer", "Kata Benda",
               ("体温計|たいおんけい で 熱|ねつ を 測|はか ります。", "Mengukur demam dengan termometer.")),
        KOTOBA("k42-18", "一生懸命", "いっしょうけんめい", "isshōkenmei", "sekuat tenaga", "Kata Keterangan",
               ("夢|ゆめ の ために 一生懸命|いっしょうけんめい 頑張|がんば ります。", "Saya berusaha sekuat tenaga demi mimpi.")),
    ],
    kanji=[
        KANJI("j42-1", "包", "ホウ", "つつ(む)", "bungkus", 5,
              [("包みます", "つつみます", "membungkus"), ("包装", "ほうそう", "kemasan")]),
        KANJI("j42-2", "沸", "フツ", "わ(かす)", "didihkan", 8,
              [("沸かします", "わかします", "merebus air"), ("沸騰", "ふっとう", "mendidih")]),
        KANJI("j42-3", "混", "コン", "ま(ぜる)", "campur", 11,
              [("混ぜます", "まぜます", "mencampur"), ("混雑", "こんざつ", "kepadatan")]),
        KANJI("j42-4", "計", "ケイ", "はか(る)", "hitung; rencana", 9,
              [("計算", "けいさん", "perhitungan"), ("計画", "けいかく", "rencana")]),
        KANJI("j42-5", "厚", "コウ", "あつ(い)", "tebal", 9,
              [("厚い", "あつい", "tebal"), ("厚生", "こうせい", "kesejahteraan")]),
        KANJI("j42-6", "薄", "ハク", "うす(い)", "tipis", 16,
              [("薄い", "うすい", "tipis"), ("薄暗い", "うすぐらい", "remang-remang")]),
    ],
    kaiwa=KAIWA(
        "ローンの 相談 — Konsultasi Pinjaman",
        "Wang berkonsultasi dengan Pak Sato tentang menabung untuk kuliah ke luar negeri.",
        [
            ("ワン", "Wan", "佐藤|さとう さん、 留学|りゅうがく の ために 貯金|ちょきん したいん です が…。",
             "Pak Sato, saya ingin menabung demi kuliah ke luar negeri…"),
            ("佐藤", "Satō", "いい です ね。 いくら 必要|ひつよう なん です か。", "Bagus sekali. Berapa yang diperlukan?"),
            ("ワン", "Wan", "100万円|ひゃくまんえん は 必要|ひつよう です。 今|いま 半分|はんぶん しか ありません。",
             "Setidaknya satu juta yen. Sekarang baru ada setengahnya."),
            ("佐藤", "Satō", "毎月|まいつき いくら ずつ 貯|た めて いるん です か。", "Berapa yang Anda tabung setiap bulan?"),
            ("ワン", "Wan", "5万円|ごまんえん ずつ です。 あと 10か月|じゅっかげつ も かかります。",
             "Lima puluh ribu yen. Masih butuh sampai 10 bulan lagi."),
            ("佐藤", "Satō", "頑張|がんば って ください。 夢|ゆめ の ため です から ね。",
             "Semangat, ya. Ini demi mimpi Anda, kan."),
        ],
    ),
    quiz_bunpo=[
        QB("qb42-1", "留学|りゅうがく する ＿＿、 貯金|ちょきん して います。", ["ために", "ように", "のに", "ところ"], 0,
           "留学|りゅうがく する ために、 貯金|ちょきん して います。", "ために", "[Bentuk kamus] ために",
           "Tujuan aksi yang disengaja memakai ために."),
        QB("qb42-2", "この はさみ は 紙|かみ を 切|き る ＿＿ 使|つか います。", ["のに", "ために", "ように", "から"], 0,
           "この はさみ は 紙|かみ を 切|き る のに 使|つか います。", "切るのに", "[Bentuk kamus] のに 使います",
           "Kegunaan alat dinyatakan dengan 〜のに 使います."),
        QB("qb42-3", "きのう の パーティー に 100人|ひゃくにん ＿＿ 来|き ました。", ["も", "は", "だけ", "しか"], 0,
           "きのう の パーティー に 100人|ひゃくにん も 来|き ました。", "も", "[Kata Jumlah] も",
           "も setelah kata jumlah berarti sampai-sampai (jumlah yang mengejutkan)."),
        QB_ID("qb42-4", "“Saya bekerja keras demi keluarga.”",
              ["家族|かぞく の ために、 一生懸命|いっしょうけんめい 働|はたら きます。",
               "家族|かぞく の ように、 一生懸命|いっしょうけんめい 働|はたら きます。",
               "家族|かぞく の のに、 一生懸命|いっしょうけんめい 働|はたら きます。",
               "家族|かぞく に よって、 一生懸命|いっしょうけんめい 働|はたら きます。"], 0,
              "家族|かぞく の ために、 一生懸命|いっしょうけんめい 働|はたら きます。", "のために",
              "[Kata Benda] の ために",
              "Setelah kata benda, tujuan memakai のために."),
    ],
    quiz_susun=[
        QS("qs42-1", "Saya menabung demi belajar ke luar negeri.",
           "留学|りゅうがく の ために 貯金|ちょきん して います", "旅行|りょこう 使|つか います"),
        QS("qs42-2", "Pembuka tutup dipakai untuk membuka tutup botol.",
           "栓抜|せんぬ き は ふた を 開|あ ける のに 使|つか います", "缶詰|かんづめ 切|き ります"),
        QS("qs42-3", "Menulis skripsi memakan waktu setahun.",
           "論文|ろんぶん を 書|か く のに 1年|いちねん かかりました", "読|よ む 半分|はんぶん"),
    ],
)

BAB43 = CHAPTER(
    43, "雨が 降りそうです。", "Sepertinya akan turun hujan.",
    bunpo=[
        BUNPO(
            "b43-1", "〜そうです (様子) — Kelihatannya",
            "Kata kerja: [bentuk ます tanpa ます] そう です ／ Sifat-i: buang い ／ Sifat-na: ＋ そう です",
            [
                "kata kerja: 降|ふ りそうです (sepertinya akan turun)",
                "kata sifat-i: おいしそうです (kelihatan enak)",
                "kata sifat-na: 元気|げんき そうです (kelihatan sehat)",
                "pengecualian: いい → よさそう ； ない → なさそう",
            ],
            "〜そうです di sini menyatakan KESAN dari apa yang terlihat: sesuatu yang sebentar lagi "
            "terjadi atau keadaan yang tampak dari luar. Ini berbeda dengan そうです untuk kabar "
            "(Bab 47).",
            [
                ("空|そら が 暗|くら い です ね。 雨|あめ が 降|ふ りそう です。", "Langitnya gelap, ya. Sepertinya akan hujan."),
                ("この ケーキ は おいしそう です。", "Kue ini kelihatan enak."),
                ("彼|かれ は 元気|げんき そう です。", "Dia kelihatan sehat."),
            ],
        ),
        BUNPO(
            "b43-2", "〜そうな ＋ Kata Benda ／ 〜そうに ＋ Kata Kerja",
            "[Batang kata] そう な [Kata Benda] ／ そう に [Kata Kerja]",
            [
                "そうな ＋ kata benda: おいしそうな ケーキ",
                "そうに ＋ kata kerja: 楽|たの しそうに 遊|あそ んで います",
                "bentuk な / に mengikuti pola kata sifat-na",
            ],
            "そうです berubah bentuk seperti kata sifat-na ketika menerangkan kata lain: そうな "
            "di depan kata benda, そうに di depan kata kerja.",
            [
                ("おいしそう な 料理|りょうり が 並|なら んで います。", "Masakan yang kelihatan enak berjajar."),
                ("子|こ どもたち が 楽|たの しそう に 遊|あそ んで います。", "Anak-anak bermain dengan riang."),
                ("かばん が 今|いま にも 落|お ちそう です。", "Tasnya sepertinya sebentar lagi jatuh."),
            ],
        ),
        BUNPO(
            "b43-3", "〜て きます — Pergi Melakukan Lalu Kembali",
            "[Kata Kerja bentuk て] きます",
            [
                "買|か って きます = pergi membeli lalu kembali",
                "bisa juga perubahan yang berlanjut: 増|ふ えて きました",
                "bandingkan 〜て いきます (berlanjut ke depan)",
            ],
            "Makna paling umum 〜てきます adalah “melakukan sesuatu di tempat lain lalu kembali”. "
            "Makna kedua: perubahan yang mulai terjadi sampai sekarang, misalnya 増えてきました "
            "(mulai bertambah).",
            [
                ("ちょっと ジュース を 買|か って きます。", "Saya beli jus dulu sebentar."),
                ("手袋|てぶくろ を 忘|わす れた ので、 取|と って きます。", "Karena sarung tangan ketinggalan, saya ambil dulu."),
                ("最近|さいきん、 輸入|ゆにゅう が 増|ふ えて きました。", "Akhir-akhir ini impornya mulai bertambah."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k43-1", "増えます", "ふえます", "fuemasu", "bertambah", "Kata Kerja",
               ("人口|じんこう が 増|ふ えます。", "Penduduknya bertambah.")),
        KOTOBA("k43-2", "減ります", "へります", "herimasu", "berkurang", "Kata Kerja",
               ("ガソリン が 減|へ って きました。", "Bensinnya mulai berkurang.")),
        KOTOBA("k43-3", "上がります", "あがります", "agarimasu", "naik", "Kata Kerja",
               ("値段|ねだん が 上|あ がりました。", "Harganya naik.")),
        KOTOBA("k43-4", "下がります", "さがります", "sagarimasu", "turun", "Kata Kerja",
               ("熱|ねつ が 下|さ がりました。", "Demamnya turun.")),
        KOTOBA("k43-5", "切れます", "きれます", "kiremasu", "putus", "Kata Kerja",
               ("ひも が 切|き れそう です。", "Talinya sepertinya akan putus.")),
        KOTOBA("k43-6", "とれます", "とれます", "toremasu", "terlepas", "Kata Kerja",
               ("ボタン が とれました。", "Kancingnya lepas.")),
        KOTOBA("k43-7", "落ちます", "おちます", "ochimasu", "jatuh", "Kata Kerja",
               ("荷物|にもつ が 落|お ちました。", "Barangnya jatuh.")),
        KOTOBA("k43-8", "丈夫", "じょうぶ", "jōbu", "kuat; kokoh", "Kata Sifat-na",
               ("この かばん は 丈夫|じょうぶ です。", "Tas ini kuat.")),
        KOTOBA("k43-9", "変", "へん", "hen", "aneh", "Kata Sifat-na",
               ("変|へん な 音|おと が します。", "Terdengar bunyi aneh.")),
        KOTOBA("k43-10", "幸せ", "しあわせ", "shiawase", "bahagia", "Kata Sifat-na",
               ("幸|しあわ せそう な 家族|かぞく です ね。", "Keluarga yang kelihatan bahagia, ya.")),
        KOTOBA("k43-11", "うまい", "うまい", "umai", "enak; jago", "Kata Sifat-i",
               ("この 店|みせ の ラーメン は うまい です。", "Ramen toko ini enak.")),
        KOTOBA("k43-12", "まずい", "まずい", "mazui", "tidak enak", "Kata Sifat-i",
               ("この 料理|りょうり は まずい です。", "Masakan ini tidak enak.")),
        KOTOBA("k43-13", "つまらない", "つまらない", "tsumaranai", "membosankan", "Kata Sifat-i",
               ("つまらない 映画|えいが でした。", "Filmnya membosankan.")),
        KOTOBA("k43-14", "ガソリン", "ガソリン", "gasorin", "bensin", "Kata Benda",
               ("ガソリン が なくなりそう です。", "Bensinnya sepertinya akan habis.")),
        KOTOBA("k43-15", "暖房", "だんぼう", "danbō", "pemanas ruangan", "Kata Benda",
               ("暖房|だんぼう を つけます。", "Menyalakan pemanas.")),
        KOTOBA("k43-16", "冷房", "れいぼう", "reibō", "pendingin ruangan", "Kata Benda",
               ("冷房|れいぼう が 効|き いて います。", "AC-nya berfungsi.")),
        KOTOBA("k43-17", "今にも", "いまにも", "ima ni mo", "sebentar lagi (seolah)", "Kata Keterangan",
               ("今|いま にも 泣|な きそう です。", "Sepertinya sebentar lagi menangis.")),
        KOTOBA("k43-18", "ぴったり", "ぴったり", "pittari", "pas sekali", "Kata Keterangan",
               ("この 靴|くつ は ぴったり です。", "Sepatu ini pas sekali.")),
    ],
    kanji=[
        KANJI("j43-1", "増", "ゾウ", "ふ(える)", "tambah", 14,
              [("増えます", "ふえます", "bertambah"), ("増加", "ぞうか", "pertambahan")]),
        KANJI("j43-2", "減", "ゲン", "へ(る)", "kurang", 12,
              [("減ります", "へります", "berkurang"), ("減少", "げんしょう", "pengurangan")]),
        KANJI("j43-3", "丈", "ジョウ", "—", "panjang; kuat", 3,
              [("丈夫", "じょうぶ", "kuat; kokoh"), ("大丈夫", "だいじょうぶ", "tidak apa-apa")]),
        KANJI("j43-4", "幸", "コウ", "しあわ(せ)", "bahagia", 8,
              [("幸せ", "しあわせ", "kebahagiaan"), ("幸福", "こうふく", "bahagia")]),
        KANJI("j43-5", "暖", "ダン", "あたた(かい)", "hangat", 13,
              [("暖房", "だんぼう", "pemanas ruangan"), ("暖かい", "あたたかい", "hangat")]),
        KANJI("j43-6", "冷", "レイ", "つめ(たい)", "dingin", 7,
              [("冷房", "れいぼう", "pendingin ruangan"), ("冷たい", "つめたい", "dingin")]),
    ],
    kaiwa=KAIWA(
        "天気の 話 — Bicara soal Cuaca",
        "Sari dan Rina bersiap keluar rumah sambil melihat langit.",
        [
            ("サリ", "Sari", "あ、 空|そら が 暗|くら く なって きました ね。", "Ah, langitnya mulai gelap, ya."),
            ("リナ", "Rina", "雨|あめ が 降|ふ りそう です ね。 傘|かさ を 持|も って いきましょう。",
             "Sepertinya akan hujan. Ayo bawa payung."),
            ("サリ", "Sari", "そう です ね。 あ、 その かばん、 荷物|にもつ が 今|いま にも 落|お ちそう です よ。",
             "Betul. Eh, tas itu barangnya sepertinya sebentar lagi jatuh, lho."),
            ("リナ", "Rina", "ほんとう だ。 ファスナー が 壊|こわ れそう に なって います ね。",
             "Benar juga. Ritsletingnya sepertinya mau rusak."),
            ("サリ", "Sari", "じゃ、 新|あたら しい の を 買|か いません か。 駅前|えきまえ の 店|みせ が 安|やす く なって います よ。",
             "Kalau begitu, beli yang baru, tidak? Toko depan stasiun sedang diskon, lho."),
            ("リナ", "Rina", "いい です ね。 帰|かえ り に 寄|よ って きます。", "Bagus. Nanti saya mampir dalam perjalanan pulang."),
        ],
    ),
    quiz_bunpo=[
        QB("qb43-1", "雨|あめ が 降|ふ り ＿＿ です。", ["そう", "よう", "らしい", "はず"], 0,
           "雨|あめ が 降|ふ りそう です。", "降りそう", "[Bentuk ます tanpa ます] そう です",
           "Kesan akan terjadi: batang kata kerja + そうです."),
        QB("qb43-2", "この ケーキ は おいし＿＿ です。", ["そう", "そうなん", "いそう", "さそう"], 0,
           "この ケーキ は おいしそう です。", "おいしそう", "Kata sifat-i: buang い ＋ そう",
           "Kata sifat-i membuang い lalu ditambah そう: おいしい → おいしそう."),
        QB("qb43-3", "ちょっと ジュース を 買|か って ＿＿。", ["きます", "いきます", "あります", "みます"], 0,
           "ちょっと ジュース を 買|か って きます。", "買ってきます", "Vて きます",
           "〜てきます berarti melakukan di tempat lain lalu kembali."),
        QB_ID("qb43-4", "“Tasnya sepertinya sebentar lagi jatuh.”",
              ["かばん が 今|いま にも 落|お ちそう です。",
               "かばん が 今|いま にも 落|お ちる そう です。",
               "かばん が 今|いま にも 落|お ちた そう です。",
               "かばん が 今|いま にも 落|お ちて います。"], 0,
              "かばん が 今|いま にも 落|お ちそう です。", "落ちそう", "[Bentuk ます tanpa ます] そう です",
              "Sesuatu yang sebentar lagi terjadi: 落ちます → 落ちそうです. 落ちるそうです adalah kabar dari orang lain."),
    ],
    quiz_susun=[
        QS("qs43-1", "Sepertinya akan turun hujan.",
           "雨|あめ が 降|ふ りそう です", "雪|ゆき 止|や みます"),
        QS("qs43-2", "Saya pergi membeli jus dulu sebentar.",
           "ちょっと ジュース を 買|か って きます", "飲|の んで いきます"),
        QS("qs43-3", "Anak-anak bermain dengan riang.",
           "子|こ どもたち が 楽|たの しそうに 遊|あそ んで います", "泣|な いて 悲|かな しい"),
    ],
)

BAB44 = CHAPTER(
    44, "この 本は 読みやすいです。", "Buku ini mudah dibaca.",
    bunpo=[
        BUNPO(
            "b44-1", "〜すぎます — Terlalu / Ke-…-an",
            "[Bentuk ます tanpa ます / batang kata sifat] すぎます",
            [
                "kata kerja: 食|た べすぎました (kebanyakan makan)",
                "kata sifat-i: 高|たか すぎます (terlalu mahal)",
                "kata sifat-na: 静|しず か すぎます (terlalu sepi)",
            ],
            "すぎます menyatakan sesuatu MELEBIHI batas yang wajar, dengan kesan negatif. "
            "Bentuknya mengikuti kata kerja (buang ます), kata sifat-i (buang い), dan kata sifat-na.",
            [
                ("ゆうべ 飲|の みすぎました。", "Semalam saya kebanyakan minum."),
                ("この かばん は 高|たか すぎます。", "Tas ini terlalu mahal."),
                ("部屋|へや が 静|しず か すぎて、 寂|さび しい です。", "Kamarnya terlalu sepi, jadi terasa sepi."),
            ],
        ),
        BUNPO(
            "b44-2", "〜やすいです ／ 〜にくいです — Mudah / Sulit",
            "[Bentuk ます tanpa ます] やすい です ／ にくい です",
            [
                "読|よ みやすい = mudah dibaca",
                "使|つか いにくい = sulit dipakai",
                "berfungsi sebagai kata sifat-i",
            ],
            "Untuk menilai apakah sesuatu mudah atau sulit dilakukan, batang kata kerja diikuti "
            "やすい atau にくい: この ペンは 書きやすいです (pulpen ini enak dipakai menulis).",
            [
                ("この 本|ほん は 読|よ みやすい です。", "Buku ini mudah dibaca."),
                ("この 辞書|じしょ は 使|つか いやすい です。", "Kamus ini mudah dipakai."),
                ("この 道|みち は 歩|ある きにくい です。", "Jalan ini sulit dilewati."),
            ],
        ),
        BUNPO(
            "b44-3", "〜く します ／ 〜に します — Mengubah Keadaan",
            "[Kata Sifat-i → く] します ／ [Kata Sifat-na / Kata Benda → に] します",
            [
                "部屋|へや を 明|あか るく します = menerangkan kamar",
                "静|しず か に してください = tolong tenang",
                "Nに します juga = memilih: これ に します",
            ],
            "します di sini berarti mengubah keadaan menjadi tertentu: kata sifat-i berubah い→く, "
            "kata sifat-na dan kata benda memakai に. Pola Nにします juga dipakai saat memilih "
            "di toko atau restoran.",
            [
                ("部屋|へや を 明|あか るく します。", "Saya menerangkan kamar."),
                ("音|おと を 小|ちい さく してください。", "Tolong kecilkan suaranya."),
                ("飲|の み物|もの は コーヒー に します。", "Minumannya saya pilih kopi."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k44-1", "泣きます", "なきます", "nakimasu", "menangis", "Kata Kerja",
               ("子|こ ども が 泣|な いて います。", "Anaknya sedang menangis.")),
        KOTOBA("k44-2", "笑います", "わらいます", "waraimasu", "tertawa", "Kata Kerja",
               ("みんな で 笑|わら いました。", "Kami tertawa bersama.")),
        KOTOBA("k44-3", "乾きます", "かわきます", "kawakimasu", "kering", "Kata Kerja",
               ("洗濯物|せんたくもの が 乾|かわ きました。", "Cuciannya sudah kering.")),
        KOTOBA("k44-4", "濡れます", "ぬれます", "nuremasu", "basah", "Kata Kerja",
               ("雨|あめ で 濡|ぬ れました。", "Basah karena hujan.")),
        KOTOBA("k44-5", "滑ります", "すべります", "suberimasu", "tergelincir", "Kata Kerja",
               ("道|みち が 凍|こお って 滑|すべ ります。", "Jalannya beku dan licin.")),
        KOTOBA("k44-6", "起きます", "おきます", "okimasu", "terjadi", "Kata Kerja",
               ("事故|じこ が 起|お きました。", "Terjadi kecelakaan.")),
        KOTOBA("k44-7", "調節します", "ちょうせつします", "chōsetsu shimasu", "menyetel", "Kata Kerja",
               ("温度|おんど を 調節|ちょうせつ します。", "Menyetel suhu.")),
        KOTOBA("k44-8", "丁寧", "ていねい", "teinei", "sopan; teliti", "Kata Sifat-na",
               ("丁寧|ていねい に 説明|せつめい します。", "Menjelaskan dengan teliti.")),
        KOTOBA("k44-9", "細かい", "こまかい", "komakai", "kecil-kecil; rinci", "Kata Sifat-i",
               ("細|こま かい お金|かね が ありません。", "Tidak punya uang kecil.")),
        KOTOBA("k44-10", "濃い", "こい", "koi", "kental; pekat", "Kata Sifat-i",
               ("味|あじ が 濃|こ い です。", "Rasanya kental.")),
        KOTOBA("k44-11", "空気", "くうき", "kūki", "udara", "Kata Benda",
               ("山|やま の 空気|くうき は おいしい です。", "Udara gunung segar.")),
        KOTOBA("k44-12", "涙", "なみだ", "namida", "air mata", "Kata Benda",
               ("涙|なみだ が 出|で ました。", "Air matanya keluar.")),
        KOTOBA("k44-13", "和食", "わしょく", "washoku", "masakan Jepang", "Kata Benda",
               ("和食|わしょく が 好|す き です。", "Saya suka masakan Jepang.")),
        KOTOBA("k44-14", "洋食", "ようしょく", "yōshoku", "masakan Barat", "Kata Benda",
               ("昼|ひる は 洋食|ようしょく に します。", "Siang ini saya pilih masakan Barat.")),
        KOTOBA("k44-15", "おかず", "おかず", "okazu", "lauk", "Kata Benda",
               ("おかず を 作|つく ります。", "Membuat lauk.")),
        KOTOBA("k44-16", "半分", "はんぶん", "hanbun", "setengah", "Kata Benda",
               ("半分|はんぶん 食|た べました。", "Saya makan setengahnya.")),
        KOTOBA("k44-17", "理由", "りゆう", "riyū", "alasan", "Kata Benda",
               ("遅|おく れた 理由|りゆう を 説明|せつめい してください。", "Tolong jelaskan alasan terlambatnya.")),
        KOTOBA("k44-18", "順序", "じゅんじょ", "junjo", "urutan", "Kata Benda",
               ("順序|じゅんじょ が 違|ちが います。", "Urutannya salah.")),
    ],
    kanji=[
        KANJI("j44-1", "泣", "キュウ", "な(く)", "tangis", 8,
              [("泣きます", "なきます", "menangis"), ("号泣", "ごうきゅう", "menangis keras")]),
        KANJI("j44-2", "笑", "ショウ", "わら(う)", "tawa", 10,
              [("笑います", "わらいます", "tertawa"), ("笑顔", "えがお", "senyum")]),
        KANJI("j44-3", "乾", "カン", "かわ(く)", "kering", 11,
              [("乾きます", "かわきます", "kering"), ("乾燥", "かんそう", "kekeringan")]),
        KANJI("j44-4", "濡", "ジュ", "ぬ(れる)", "basah", 17,
              [("濡れます", "ぬれます", "basah"), ("濡れ衣", "ぬれぎぬ", "tuduhan palsu")]),
        KANJI("j44-5", "滑", "カツ", "すべ(る)", "licin", 13,
              [("滑ります", "すべります", "tergelincir"), ("滑走", "かっそう", "meluncur")]),
        KANJI("j44-6", "調", "チョウ", "—", "selidik; setel", 15,
              [("調節", "ちょうせつ", "penyetelan"), ("調査", "ちょうさ", "penyelidikan")]),
    ],
    kaiwa=KAIWA(
        "美容院で — Di Salon",
        "Karina memotong rambut di salon dan berbicara dengan penata rambut.",
        [
            ("美容師", "Biyōshi", "いらっしゃいませ。 今日|きょう は どう なさいます か。",
             "Selamat datang. Mau diapakan hari ini?"),
            ("カリナ", "Karina", "カット を お願|ねが いします。 もう 少|すこ し 短|みじか く したいん です。",
             "Potong rambut, ya. Saya ingin sedikit lebih pendek."),
            ("美容師", "Biyōshi", "この くらい で いかが です か。", "Kira-kira sepanjang ini bagaimana?"),
            ("カリナ", "Karina", "うーん、 短|みじか すぎます。 もう 少|すこ し 長|なが め に して ください。",
             "Hmm, itu terlalu pendek. Tolong dibuat agak lebih panjang."),
            ("美容師", "Biyōshi", "かしこまりました。 この 髪|かみ は 扱|あつか いやすい です ね。",
             "Baik. Rambut Anda mudah ditata, ya."),
            ("カリナ", "Karina", "ありがとう ございます。 セット しやすい ように して ください。",
             "Terima kasih. Tolong dibuat supaya mudah ditata."),
        ],
    ),
    quiz_bunpo=[
        QB("qb44-1", "ゆうべ 飲|の み ＿＿ました。", ["すぎ", "やすい", "にくい", "ながら"], 0,
           "ゆうべ 飲|の みすぎました。", "飲みすぎました", "〜 すぎます",
           "すぎます menyatakan berlebihan; kata kerja membuang ます."),
        QB("qb44-2", "この 本|ほん は 読|よ み ＿＿ です。", ["やすい", "にくいな", "すぎるな", "ながら"], 0,
           "この 本|ほん は 読|よ みやすい です。", "読みやすい", "〜 やすい です",
           "Mudah dilakukan: batang kata kerja + やすいです."),
        QB("qb44-3", "音|おと を 小|ちい さ＿＿ して ください。", ["く", "に", "い", "さ"], 0,
           "音|おと を 小|ちい さく して ください。", "小さくして", "Kata sifat-i: い → く ＋ します",
           "Mengubah keadaan dengan kata sifat-i: い berubah menjadi く + します."),
        QB_ID("qb44-4", "“Kamus ini sulit dipakai.”",
              ["この 辞書|じしょ は 使|つか いにくい です。",
               "この 辞書|じしょ は 使|つか いやすい です。",
               "この 辞書|じしょ は 使|つか いすぎます。",
               "この 辞書|じしょ は 使|つか えにくい です か。"], 0,
              "この 辞書|じしょ は 使|つか いにくい です。", "使いにくい", "〜 にくい です",
              "Sulit dilakukan: batang kata kerja + にくいです."),
    ],
    quiz_susun=[
        QS("qs44-1", "Buku ini mudah dibaca.",
           "この 本|ほん は 読|よ みやすい です", "書|か きにくい 難|むずか しい"),
        QS("qs44-2", "Semalam saya kebanyakan minum.",
           "ゆうべ 飲|の みすぎました", "食|た べすぎ 今朝|けさ"),
        QS("qs44-3", "Tolong kecilkan suaranya.",
           "音|おと を 小|ちい さく して ください", "大|おお きく 消|け して"),
    ],
)

BAB45 = CHAPTER(
    45, "雨の 場合は、 中止です。", "Kalau hujan, acaranya dibatalkan.",
    bunpo=[
        BUNPO(
            "b45-1", "〜場合は — Dalam Hal / Jika Terjadi",
            "[Bentuk Biasa / Kata Benda の] 場合|ばあい は",
            [
                "kata kerja: 雨|あめ が 降|ふ る 場合は",
                "kata benda: 雨|あめ の 場合は",
                "lebih formal daripada 〜たら — umum di aturan & pengumuman",
            ],
            "〜場合は dipakai untuk menyebut kondisi yang mungkin terjadi beserta tindakan yang "
            "harus dilakukan. Pola ini sering muncul di peraturan, pengumuman, dan instruksi "
            "darurat.",
            [
                ("雨|あめ の 場合|ばあい は、 試合|しあい は 中止|ちゅうし です。", "Kalau hujan, pertandingan dibatalkan."),
                ("遅|おく れる 場合|ばあい は、 連絡|れんらく して ください。", "Jika akan terlambat, tolong hubungi kami."),
                ("火事|かじ の 場合|ばあい は、 エレベーター を 使|つか わないで ください。",
                 "Dalam hal kebakaran, jangan gunakan lift."),
            ],
        ),
        BUNPO(
            "b45-2", "〜のに — Padahal (Kontras)",
            "[Bentuk Biasa / Kata Benda な] のに",
            [
                "menyatakan hasil yang tak terduga / kekecewaan",
                "kata sifat-na & kata benda: なのに （元気|げんき なのに）",
                "berbeda dengan のに untuk kegunaan (Bab 42)",
            ],
            "〜のに menyatakan kontras: kenyataan di bagian belakang bertentangan dengan yang "
            "diharapkan. Sering mengandung nada kecewa atau heran: 勉強したのに、 落ちました.",
            [
                ("たくさん 勉強|べんきょう した のに、 試験|しけん に 落|お ちました。",
                 "Padahal sudah belajar banyak, saya tidak lulus ujian."),
                ("約束|やくそく した のに、 彼|かれ は 来|き ません でした。", "Padahal sudah berjanji, dia tidak datang."),
                ("日曜日|にちようび なのに、 仕事|しごと が あります。", "Padahal hari Minggu, saya ada kerjaan."),
            ],
        ),
    ],
    kotoba=[
        KOTOBA("k45-1", "謝ります", "あやまります", "ayamarimasu", "meminta maaf", "Kata Kerja",
               ("遅|おく れた こと を 謝|あやま ります。", "Meminta maaf karena terlambat.")),
        KOTOBA("k45-2", "信じます", "しんじます", "shinjimasu", "percaya", "Kata Kerja",
               ("彼|かれ の 話|はなし を 信|しん じます。", "Saya percaya ceritanya.")),
        KOTOBA("k45-3", "用意します", "よういします", "yōi shimasu", "menyiapkan", "Kata Kerja",
               ("会議|かいぎ の 資料|しりょう を 用意|ようい します。", "Menyiapkan bahan rapat.")),
        KOTOBA("k45-4", "キャンセルします", "キャンセルします", "kyanseru shimasu", "membatalkan", "Kata Kerja",
               ("予約|よやく を キャンセル しました。", "Saya membatalkan reservasi.")),
        KOTOBA("k45-5", "うまくいきます", "うまくいきます", "umaku ikimasu", "berjalan lancar", "Ungkapan",
               ("計画|けいかく は うまく いきました。", "Rencananya berjalan lancar.")),
        KOTOBA("k45-6", "保証書", "ほしょうしょ", "hoshōsho", "kartu garansi", "Kata Benda",
               ("保証書|ほしょうしょ を なくさないで ください。", "Jangan sampai kartu garansinya hilang.")),
        KOTOBA("k45-7", "領収書", "りょうしゅうしょ", "ryōshūsho", "kuitansi", "Kata Benda",
               ("領収書|りょうしゅうしょ を ください。", "Tolong kuitansinya.")),
        KOTOBA("k45-8", "贈り物", "おくりもの", "okurimono", "hadiah", "Kata Benda",
               ("贈|おく り物|もの を 用意|ようい します。", "Menyiapkan hadiah.")),
        KOTOBA("k45-9", "間違い電話", "まちがいでんわ", "machigai denwa", "salah sambung", "Kata Benda",
               ("間違|まちが い電話|でんわ でした。 失礼|しつれい しました。", "Salah sambung. Maaf, ya.")),
        KOTOBA("k45-10", "キャンプ", "キャンプ", "kyanpu", "kemah", "Kata Benda",
               ("週末|しゅうまつ は キャンプ に 行|い きます。", "Akhir pekan pergi berkemah.")),
        KOTOBA("k45-11", "係", "かかり", "kakari", "petugas; penanggung jawab", "Kata Benda",
               ("会場|かいじょう の 係|かかり に 聞|き いて ください。", "Tolong tanya petugas tempat acara.")),
        KOTOBA("k45-12", "中止", "ちゅうし", "chūshi", "pembatalan", "Kata Benda",
               ("雨|あめ の 場合|ばあい は 中止|ちゅうし です。", "Kalau hujan, dibatalkan.")),
        KOTOBA("k45-13", "ちゃんと", "ちゃんと", "chanto", "dengan benar", "Kata Keterangan",
               ("ちゃんと 説明|せつめい して ください。", "Tolong jelaskan dengan benar.")),
        KOTOBA("k45-14", "急に", "きゅうに", "kyū ni", "tiba-tiba", "Kata Keterangan",
               ("急|きゅう に 雨|あめ が 降|ふ りました。", "Tiba-tiba turun hujan.")),
        KOTOBA("k45-15", "優勝します", "ゆうしょうします", "yūshō shimasu", "menjadi juara", "Kata Kerja",
               ("チーム が 優勝|ゆうしょう しました。", "Timnya menjadi juara.")),
        KOTOBA("k45-16", "悩み", "なやみ", "nayami", "kegelisahan", "Kata Benda",
               ("悩|なや み が あります。", "Saya punya kegelisahan.")),
        KOTOBA("k45-17", "鳴ります", "なります", "narimasu", "berbunyi", "Kata Kerja",
               ("目覚|めざ まし が 鳴|な りました。", "Alarmnya berbunyi.")),
        KOTOBA("k45-18", "それでも", "それでも", "sore demo", "namun demikian", "Kata Keterangan",
               ("それでも、 あきらめません。", "Namun demikian, saya tidak menyerah.")),
    ],
    kanji=[
        KANJI("j45-1", "謝", "シャ", "あやま(る)", "maaf", 17,
              [("謝ります", "あやまります", "meminta maaf"), ("感謝", "かんしゃ", "terima kasih")]),
        KANJI("j45-2", "信", "シン", "—", "percaya", 9,
              [("信じます", "しんじます", "percaya"), ("信用", "しんよう", "kepercayaan")]),
        KANJI("j45-3", "領", "リョウ", "—", "wilayah; terima", 14,
              [("領収書", "りょうしゅうしょ", "kuitansi"), ("領土", "りょうど", "wilayah")]),
        KANJI("j45-4", "悩", "ノウ", "なや(む)", "gelisah", 10,
              [("悩み", "なやみ", "kegelisahan"), ("苦悩", "くのう", "kesusahan")]),
        KANJI("j45-5", "優", "ユウ", "やさ(しい)", "unggul; lembut", 17,
              [("優勝", "ゆうしょう", "juara"), ("優しい", "やさしい", "baik hati")]),
        KANJI("j45-6", "勝", "ショウ", "か(つ)", "menang", 12,
              [("勝ちます", "かちます", "menang"), ("勝敗", "しょうはい", "menang-kalah")]),
    ],
    kaiwa=KAIWA(
        "マラソン大会 — Lomba Maraton",
        "Panitia menjelaskan aturan lomba maraton kepada peserta.",
        [
            ("係員", "Kakariin", "明日|あした の マラソン 大会|たいかい です が、 雨|あめ の 場合|ばあい は 中止|ちゅうし です。",
             "Untuk lomba maraton besok: kalau hujan, dibatalkan."),
            ("参加者", "Sankasha", "小雨|こさめ の 場合|ばあい も 中止|ちゅうし です か。", "Kalau hujan gerimis juga dibatalkan?"),
            ("係員", "Kakariin", "いいえ、 小雨|こさめ なら 行|おこな います。 スタート は 8時|はちじ です。",
             "Tidak, kalau gerimis tetap diadakan. Start jam 8."),
            ("参加者", "Sankasha", "遅|おく れる 場合|ばあい は どう すれば いい です か。", "Kalau terlambat bagaimana?"),
            ("係員", "Kakariin", "8時半|はちじはん まで に 受付|うけつけ を 済|す ませて ください。 それ 以降|いこう は 参加|さんか できません。",
             "Selesaikan pendaftaran sebelum jam setengah sembilan. Lewat itu tidak bisa ikut."),
            ("参加者", "Sankasha", "分|わ かりました。 練習|れんしゅう した のに、 雨|あめ だと 残念|ざんねん です ね。",
             "Baik. Padahal sudah berlatih, sayang sekali kalau hujan, ya."),
        ],
    ),
    quiz_bunpo=[
        QB("qb45-1", "雨|あめ の ＿＿ は、 試合|しあい は 中止|ちゅうし です。", ["場合", "のに", "ところ", "ほう"], 0,
           "雨|あめ の 場合|ばあい は、 試合|しあい は 中止|ちゅうし です。", "場合は", "[Kata Benda の] 場合は",
           "〜場合は menyatakan kondisi beserta tindakannya; umum di peraturan."),
        QB("qb45-2", "たくさん 勉強|べんきょう した ＿＿、 落|お ちました。", ["のに", "ので", "から", "ため"], 0,
           "たくさん 勉強|べんきょう した のに、 落|お ちました。", "したのに", "[Bentuk Biasa] のに (kontras)",
           "〜のに di sini menyatakan kontras (padahal), bukan kegunaan."),
        QB("qb45-3", "日曜日|にちようび ＿＿ のに、 仕事|しごと が あります。", ["な", "だ", "の", "で"], 0,
           "日曜日|にちようび なのに、 仕事|しごと が あります。", "なのに", "[Kata Benda] な のに",
           "Setelah kata benda dan kata sifat-na, kontrasnya menjadi なのに."),
        QB_ID("qb45-4", "“Jika akan terlambat, tolong hubungi kami.”",
              ["遅|おく れる 場合|ばあい は、 連絡|れんらく して ください。",
               "遅|おく れる のに、 連絡|れんらく して ください。",
               "遅|おく れた のに、 連絡|れんらく して ください。",
               "遅|おく れれば、 連絡|れんらく して あります。"], 0,
              "遅|おく れる 場合|ばあい は、 連絡|れんらく して ください。", "場合は", "[Bentuk kamus] 場合は",
              "Kondisi yang belum terjadi memakai bentuk kamus + 場合は."),
    ],
    quiz_susun=[
        QS("qs45-1", "Kalau hujan, pertandingan dibatalkan.",
           "雨|あめ の 場合|ばあい は 試合|しあい は 中止|ちゅうし です", "晴|は れ 行|おこな います"),
        QS("qs45-2", "Padahal sudah berjanji, dia tidak datang.",
           "約束|やくそく した のに 彼|かれ は 来|き ません でした", "来|く る から 喜|よろこ びました"),
        QS("qs45-3", "Dalam hal kebakaran, jangan gunakan lift.",
           "火事|かじ の 場合|ばあい は エレベーター を 使|つか わないで ください", "地震|じしん 乗|の って"),
    ],
)

CHAPTERS = [BAB41, BAB42, BAB43, BAB44, BAB45]
